
	.align 2
	.global DirectSoundData_086B176C
DirectSoundData_086B176C:
	.incbin "sound/direct_sound_samples/086B176C.bin"

	.align 2
	.global DirectSoundData_086B3480
DirectSoundData_086B3480:
	.incbin "sound/direct_sound_samples/086B3480.bin"

	.align 2
	.global DirectSoundData_086B468C
DirectSoundData_086B468C:
	.incbin "sound/direct_sound_samples/086B468C.bin"

	.align 2
	.global DirectSoundData_086B4F34
DirectSoundData_086B4F34:
	.incbin "sound/direct_sound_samples/086B4F34.bin"

	.align 2
	.global DirectSoundData_086B5DFC
DirectSoundData_086B5DFC:
	.incbin "sound/direct_sound_samples/086B5DFC.bin"

	.align 2
	.global DirectSoundData_086B6830
DirectSoundData_086B6830:
	.incbin "sound/direct_sound_samples/086B6830.bin"

	.align 2
	.global DirectSoundData_086B81DC
DirectSoundData_086B81DC:
	.incbin "sound/direct_sound_samples/086B81DC.bin"

	.align 2
	.global DirectSoundData_086B9A7C
DirectSoundData_086B9A7C:
	.incbin "sound/direct_sound_samples/086B9A7C.bin"

	.align 2
	.global DirectSoundData_086BA7D0
DirectSoundData_086BA7D0:
	.incbin "sound/direct_sound_samples/086BA7D0.bin"

	.align 2
	.global DirectSoundData_086BC858
DirectSoundData_086BC858:
	.incbin "sound/direct_sound_samples/086BC858.bin"

	.align 2
	.global DirectSoundData_086BD574
DirectSoundData_086BD574:
	.incbin "sound/direct_sound_samples/086BD574.bin"

	.align 2
	.global DirectSoundData_086BE04C
DirectSoundData_086BE04C:
	.incbin "sound/direct_sound_samples/086BE04C.bin"

	.align 2
	.global DirectSoundData_086BEF54
DirectSoundData_086BEF54:
	.incbin "sound/direct_sound_samples/086BEF54.bin"

	.align 2
	.global DirectSoundData_086BFA4C
DirectSoundData_086BFA4C:
	.incbin "sound/direct_sound_samples/086BFA4C.bin"

	.align 2
	.global DirectSoundData_086C0984
DirectSoundData_086C0984:
	.incbin "sound/direct_sound_samples/086C0984.bin"

	.align 2
	.global DirectSoundData_086C1BDC
DirectSoundData_086C1BDC:
	.incbin "sound/direct_sound_samples/086C1BDC.bin"

	.align 2
	.global DirectSoundData_086C2E88
DirectSoundData_086C2E88:
	.incbin "sound/direct_sound_samples/086C2E88.bin"

	.align 2
	.global DirectSoundData_086C3E8C
DirectSoundData_086C3E8C:
	.incbin "sound/direct_sound_samples/086C3E8C.bin"

	.align 2
	.global DirectSoundData_086C4698
DirectSoundData_086C4698:
	.incbin "sound/direct_sound_samples/086C4698.bin"

	.align 2
	.global DirectSoundData_086C4B94
DirectSoundData_086C4B94:
	.incbin "sound/direct_sound_samples/086C4B94.bin"

	.align 2
	.global DirectSoundData_086C4BEC
DirectSoundData_086C4BEC:
	.incbin "sound/direct_sound_samples/086C4BEC.bin"

	.align 2
	.global DirectSoundData_086C50B4
DirectSoundData_086C50B4:
	.incbin "sound/direct_sound_samples/086C50B4.bin"

	.align 2
	.global DirectSoundData_086C52CC
DirectSoundData_086C52CC:
	.incbin "sound/direct_sound_samples/086C52CC.bin"

	.align 2
	.global DirectSoundData_086C56F8
DirectSoundData_086C56F8:
	.incbin "sound/direct_sound_samples/086C56F8.bin"

	.align 2
	.global DirectSoundData_086C5AE8
DirectSoundData_086C5AE8:
	.incbin "sound/direct_sound_samples/086C5AE8.bin"

	.align 2
	.global DirectSoundData_086C5DA4
DirectSoundData_086C5DA4:
	.incbin "sound/direct_sound_samples/086C5DA4.bin"

	.align 2
	.global DirectSoundData_086C6828
DirectSoundData_086C6828:
	.incbin "sound/direct_sound_samples/086C6828.bin"

	.align 2
	.global DirectSoundData_086C8114
DirectSoundData_086C8114:
	.incbin "sound/direct_sound_samples/086C8114.bin"

	.align 2
	.global DirectSoundData_086C93DC
DirectSoundData_086C93DC:
	.incbin "sound/direct_sound_samples/086C93DC.bin"

	.align 2
	.global DirectSoundData_086CA8D0
DirectSoundData_086CA8D0:
	.incbin "sound/direct_sound_samples/086CA8D0.bin"

	.align 2
	.global DirectSoundData_086CBE78
DirectSoundData_086CBE78:
	.incbin "sound/direct_sound_samples/086CBE78.bin"

	.align 2
	.global DirectSoundData_086CC7E0
DirectSoundData_086CC7E0:
	.incbin "sound/direct_sound_samples/086CC7E0.bin"

	.align 2
	.global DirectSoundData_086CCC8C
DirectSoundData_086CCC8C:
	.incbin "sound/direct_sound_samples/086CCC8C.bin"

	.align 2
	.global DirectSoundData_086CD72C
DirectSoundData_086CD72C:
	.incbin "sound/direct_sound_samples/086CD72C.bin"

	.align 2
	.global DirectSoundData_086CE77C
DirectSoundData_086CE77C:
	.incbin "sound/direct_sound_samples/086CE77C.bin"

	.align 2
	.global DirectSoundData_086D1998
DirectSoundData_086D1998:
	.incbin "sound/direct_sound_samples/086D1998.bin"

	.align 2
	.global DirectSoundData_086D28EC
DirectSoundData_086D28EC:
	.incbin "sound/direct_sound_samples/086D28EC.bin"

	.align 2
	.global DirectSoundData_086D2A78
DirectSoundData_086D2A78:
	.incbin "sound/direct_sound_samples/086D2A78.bin"

	.align 2
	.global DirectSoundData_086D2D84
DirectSoundData_086D2D84:
	.incbin "sound/direct_sound_samples/086D2D84.bin"

	.align 2
	.global DirectSoundData_086D4C68
DirectSoundData_086D4C68:
	.incbin "sound/direct_sound_samples/086D4C68.bin"

	.align 2
	.global DirectSoundData_086D5490
DirectSoundData_086D5490:
	.incbin "sound/direct_sound_samples/086D5490.bin"

	.align 2
	.global DirectSoundData_086D565C
DirectSoundData_086D565C:
	.incbin "sound/direct_sound_samples/086D565C.bin"

	.align 2
	.global DirectSoundData_086D63E0
DirectSoundData_086D63E0:
	.incbin "sound/direct_sound_samples/086D63E0.bin"

	.align 2
	.global DirectSoundData_086D6604
DirectSoundData_086D6604:
	.incbin "sound/direct_sound_samples/086D6604.bin"

	.align 2
	.global DirectSoundData_086D6870
DirectSoundData_086D6870:
	.incbin "sound/direct_sound_samples/086D6870.bin"

	.align 2
	.global DirectSoundData_086D7128
DirectSoundData_086D7128:
	.incbin "sound/direct_sound_samples/086D7128.bin"

	.align 2
	.global DirectSoundData_086D7CCC
DirectSoundData_086D7CCC:
	.incbin "sound/direct_sound_samples/086D7CCC.bin"

	.align 2
	.global DirectSoundData_086D8020
DirectSoundData_086D8020:
	.incbin "sound/direct_sound_samples/086D8020.bin"

	.align 2
	.global DirectSoundData_086D85D4
DirectSoundData_086D85D4:
	.incbin "sound/direct_sound_samples/086D85D4.bin"

	.align 2
	.global DirectSoundData_086D8750
DirectSoundData_086D8750:
	.incbin "sound/direct_sound_samples/086D8750.bin"

	.align 2
	.global DirectSoundData_086D8984
DirectSoundData_086D8984:
	.incbin "sound/direct_sound_samples/086D8984.bin"

	.align 2
	.global DirectSoundData_086D8C94
DirectSoundData_086D8C94:
	.incbin "sound/direct_sound_samples/086D8C94.bin"

	.align 2
	.global DirectSoundData_086DA624
DirectSoundData_086DA624:
	.incbin "sound/direct_sound_samples/086DA624.bin"

	.align 2
	.global DirectSoundData_086DB964
DirectSoundData_086DB964:
	.incbin "sound/direct_sound_samples/086DB964.bin"

	.align 2
	.global DirectSoundData_086DBAA4
DirectSoundData_086DBAA4:
	.incbin "sound/direct_sound_samples/086DBAA4.bin"

	.align 2
	.global DirectSoundData_086DBE4C
DirectSoundData_086DBE4C:
	.incbin "sound/direct_sound_samples/086DBE4C.bin"

	.align 2
	.global DirectSoundData_086DCD9C
DirectSoundData_086DCD9C:
	.incbin "sound/direct_sound_samples/086DCD9C.bin"

	.align 2
	.global DirectSoundData_086DEAB0
DirectSoundData_086DEAB0:
	.incbin "sound/direct_sound_samples/086DEAB0.bin"

	.align 2
	.global DirectSoundData_086DF964
DirectSoundData_086DF964:
	.incbin "sound/direct_sound_samples/086DF964.bin"

	.align 2
	.global DirectSoundData_086DFDE8
DirectSoundData_086DFDE8:
	.incbin "sound/direct_sound_samples/086DFDE8.bin"

	.align 2
	.global DirectSoundData_086E05B4
DirectSoundData_086E05B4:
	.incbin "sound/direct_sound_samples/086E05B4.bin"

	.align 2
	.global DirectSoundData_086E1B38
DirectSoundData_086E1B38:
	.incbin "sound/direct_sound_samples/086E1B38.bin"

	.align 2
	.global DirectSoundData_086E2250
DirectSoundData_086E2250:
	.incbin "sound/direct_sound_samples/086E2250.bin"

	.align 2
	.global DirectSoundData_086E26BC
DirectSoundData_086E26BC:
	.incbin "sound/direct_sound_samples/086E26BC.bin"

	.align 2
	.global DirectSoundData_086E4588
DirectSoundData_086E4588:
	.incbin "sound/direct_sound_samples/086E4588.bin"

	.align 2
	.global DirectSoundData_086E9120
DirectSoundData_086E9120:
	.incbin "sound/direct_sound_samples/086E9120.bin"

	.align 2
	.global DirectSoundData_086EA8B4
DirectSoundData_086EA8B4:
	.incbin "sound/direct_sound_samples/086EA8B4.bin"

	.align 2
	.global DirectSoundData_086EAFCC
DirectSoundData_086EAFCC:
	.incbin "sound/direct_sound_samples/086EAFCC.bin"

	.align 2
	.global DirectSoundData_086EBBCC
DirectSoundData_086EBBCC:
	.incbin "sound/direct_sound_samples/086EBBCC.bin"

	.align 2
	.global DirectSoundData_086EED40
DirectSoundData_086EED40:
	.incbin "sound/direct_sound_samples/086EED40.bin"

	.align 2
	.global DirectSoundData_086F1C50
DirectSoundData_086F1C50:
	.incbin "sound/direct_sound_samples/086F1C50.bin"

	.align 2
	.global DirectSoundData_086F297C
DirectSoundData_086F297C:
	.incbin "sound/direct_sound_samples/086F297C.bin"

	.align 2
	.global DirectSoundData_086F3E4C
DirectSoundData_086F3E4C:
	.incbin "sound/direct_sound_samples/086F3E4C.bin"

	.align 2
	.global DirectSoundData_086F6920
DirectSoundData_086F6920:
	.incbin "sound/direct_sound_samples/086F6920.bin"

	.align 2
	.global DirectSoundData_086F98B4
DirectSoundData_086F98B4:
	.incbin "sound/direct_sound_samples/086F98B4.bin"

	.align 2
	.global DirectSoundData_086FCCB8
DirectSoundData_086FCCB8:
	.incbin "sound/direct_sound_samples/086FCCB8.bin"

	.align 2
	.global DirectSoundData_086FF568
DirectSoundData_086FF568:
	.incbin "sound/direct_sound_samples/086FF568.bin"

	.align 2
	.global DirectSoundData_08702890
DirectSoundData_08702890:
	.incbin "sound/direct_sound_samples/08702890.bin"

	.align 2
	.global DirectSoundData_08704598
DirectSoundData_08704598:
	.incbin "sound/direct_sound_samples/08704598.bin"

	.align 2
	.global DirectSoundData_0870818C
DirectSoundData_0870818C:
	.incbin "sound/direct_sound_samples/0870818C.bin"

	.align 2
	.global DirectSoundData_087081A0
DirectSoundData_087081A0:
	.incbin "sound/direct_sound_samples/087081A0.bin"

	.align 2
	.global DirectSoundData_08708810
DirectSoundData_08708810:
	.incbin "sound/direct_sound_samples/08708810.bin"

	.align 2
	.global DirectSoundData_08709FF0
DirectSoundData_08709FF0:
	.incbin "sound/direct_sound_samples/08709FF0.bin"

	.align 2
	.global DirectSoundData_0870A5C8
DirectSoundData_0870A5C8:
	.incbin "sound/direct_sound_samples/0870A5C8.bin"

	.align 2
	.global DirectSoundData_0870CC50
DirectSoundData_0870CC50:
	.incbin "sound/direct_sound_samples/0870CC50.bin"

	.align 2
	.global DirectSoundData_0870CC64
DirectSoundData_0870CC64:
	.incbin "sound/direct_sound_samples/0870CC64.bin"

	.align 2
	.global DirectSoundData_0870F888
DirectSoundData_0870F888:
	.incbin "sound/direct_sound_samples/0870F888.bin"

	.align 2
	.global DirectSoundData_0870F89C
DirectSoundData_0870F89C:
	.incbin "sound/direct_sound_samples/0870F89C.bin"

	.align 2
	.global DirectSoundData_087114D0
DirectSoundData_087114D0:
	.incbin "sound/direct_sound_samples/087114D0.bin"

	.align 2
	.global DirectSoundData_087136CC
DirectSoundData_087136CC:
	.incbin "sound/direct_sound_samples/087136CC.bin"

	.align 2
	.global DirectSoundData_087136E0
DirectSoundData_087136E0:
	.incbin "sound/direct_sound_samples/087136E0.bin"

	.align 2
	.global DirectSoundData_087136F4
DirectSoundData_087136F4:
	.incbin "sound/direct_sound_samples/087136F4.bin"

	.align 2
	.global DirectSoundData_08718F04
DirectSoundData_08718F04:
	.incbin "sound/direct_sound_samples/08718F04.bin"

	.align 2
	.global DirectSoundData_0871A97C
DirectSoundData_0871A97C:
	.incbin "sound/direct_sound_samples/0871A97C.bin"

	.align 2
	.global DirectSoundData_0871CC08
DirectSoundData_0871CC08:
	.incbin "sound/direct_sound_samples/0871CC08.bin"

	.align 2
	.global DirectSoundData_0871DB28
DirectSoundData_0871DB28:
	.incbin "sound/direct_sound_samples/0871DB28.bin"

	.align 2
	.global DirectSoundData_0871F380
DirectSoundData_0871F380:
	.incbin "sound/direct_sound_samples/0871F380.bin"

	.align 2
	.global DirectSoundData_0871F394
DirectSoundData_0871F394:
	.incbin "sound/direct_sound_samples/0871F394.bin"

	.align 2
	.global DirectSoundData_0871F3A8
DirectSoundData_0871F3A8:
	.incbin "sound/direct_sound_samples/0871F3A8.bin"

	.align 2
	.global DirectSoundData_0871F3BC
DirectSoundData_0871F3BC:
	.incbin "sound/direct_sound_samples/0871F3BC.bin"

	.align 2
	.global DirectSoundData_0871F3D0
DirectSoundData_0871F3D0:
	.incbin "sound/direct_sound_samples/0871F3D0.bin"

	.align 2
	.global DirectSoundData_0871FA68
DirectSoundData_0871FA68:
	.incbin "sound/direct_sound_samples/0871FA68.bin"

	.align 2
	.global DirectSoundData_0871FA7C
DirectSoundData_0871FA7C:
	.incbin "sound/direct_sound_samples/0871FA7C.bin"

	.align 2
	.global DirectSoundData_0872052C
DirectSoundData_0872052C:
	.incbin "sound/direct_sound_samples/0872052C.bin"

	.align 2
	.global DirectSoundData_08721120
DirectSoundData_08721120:
	.incbin "sound/direct_sound_samples/08721120.bin"

	.align 2
	.global DirectSoundData_08721910
DirectSoundData_08721910:
	.incbin "sound/direct_sound_samples/08721910.bin"

	.align 2
	.global DirectSoundData_087225A4
DirectSoundData_087225A4:
	.incbin "sound/direct_sound_samples/087225A4.bin"

	.align 2
	.global DirectSoundData_08722D44
DirectSoundData_08722D44:
	.incbin "sound/direct_sound_samples/08722D44.bin"

	.align 2
	.global DirectSoundData_08722D58
DirectSoundData_08722D58:
	.incbin "sound/direct_sound_samples/08722D58.bin"

	.align 2
	.global DirectSoundData_08723488
DirectSoundData_08723488:
	.incbin "sound/direct_sound_samples/08723488.bin"

	.align 2
	.global DirectSoundData_0872349C
DirectSoundData_0872349C:
	.incbin "sound/direct_sound_samples/0872349C.bin"

	.align 2
	.global DirectSoundData_08723A18
DirectSoundData_08723A18:
	.incbin "sound/direct_sound_samples/08723A18.bin"

	.align 2
	.global DirectSoundData_08723A2C
DirectSoundData_08723A2C:
	.incbin "sound/direct_sound_samples/08723A2C.bin"

	.align 2
	.global DirectSoundData_08723A40
DirectSoundData_08723A40:
	.incbin "sound/direct_sound_samples/08723A40.bin"

	.align 2
	.global DirectSoundData_087277A4
DirectSoundData_087277A4:
	.incbin "sound/direct_sound_samples/087277A4.bin"

	.align 2
	.global DirectSoundData_087277B8
DirectSoundData_087277B8:
	.incbin "sound/direct_sound_samples/087277B8.bin"

	.align 2
	.global DirectSoundData_087277CC
DirectSoundData_087277CC:
	.incbin "sound/direct_sound_samples/087277CC.bin"

	.align 2
	.global DirectSoundData_087277E0
DirectSoundData_087277E0:
	.incbin "sound/direct_sound_samples/087277E0.bin"

	.align 2
	.global DirectSoundData_087277F4
DirectSoundData_087277F4:
	.incbin "sound/direct_sound_samples/087277F4.bin"

	.align 2
	.global DirectSoundData_08727DCC
DirectSoundData_08727DCC:
	.incbin "sound/direct_sound_samples/08727DCC.bin"

	.align 2
	.global DirectSoundData_08727DE0
DirectSoundData_08727DE0:
	.incbin "sound/direct_sound_samples/08727DE0.bin"

	.align 2
	.global DirectSoundData_08727DF4
DirectSoundData_08727DF4:
	.incbin "sound/direct_sound_samples/08727DF4.bin"

	.align 2
	.global DirectSoundData_08727E08
DirectSoundData_08727E08:
	.incbin "sound/direct_sound_samples/08727E08.bin"

	.align 2
	.global DirectSoundData_08728258
DirectSoundData_08728258:
	.incbin "sound/direct_sound_samples/08728258.bin"

	.align 2
	.global DirectSoundData_0872826C
DirectSoundData_0872826C:
	.incbin "sound/direct_sound_samples/0872826C.bin"

	.align 2
	.global DirectSoundData_08728280
DirectSoundData_08728280:
	.incbin "sound/direct_sound_samples/08728280.bin"

	.align 2
	.global DirectSoundData_08729DB4
DirectSoundData_08729DB4:
	.incbin "sound/direct_sound_samples/08729DB4.bin"

	.align 2
	.global DirectSoundData_08729DC8
DirectSoundData_08729DC8:
	.incbin "sound/direct_sound_samples/08729DC8.bin"

	.align 2
	.global DirectSoundData_0872DFA4
DirectSoundData_0872DFA4:
	.incbin "sound/direct_sound_samples/0872DFA4.bin"

	.align 2
	.global DirectSoundData_0872F01C
DirectSoundData_0872F01C:
	.incbin "sound/direct_sound_samples/0872F01C.bin"

	.align 2
	.global DirectSoundData_08731FE0
DirectSoundData_08731FE0:
	.incbin "sound/direct_sound_samples/08731FE0.bin"

	.align 2
	.global DirectSoundData_0873525C
DirectSoundData_0873525C:
	.incbin "sound/direct_sound_samples/0873525C.bin"

	.align 2
	.global DirectSoundData_08737A78
DirectSoundData_08737A78:
	.incbin "sound/direct_sound_samples/08737A78.bin"

	.align 2
	.global DirectSoundData_0873804C
DirectSoundData_0873804C:
	.incbin "sound/direct_sound_samples/0873804C.bin"

	.align 2
	.global DirectSoundData_08738060
DirectSoundData_08738060:
	.incbin "sound/direct_sound_samples/08738060.bin"

	.align 2
	.global DirectSoundData_08738074
DirectSoundData_08738074:
	.incbin "sound/direct_sound_samples/08738074.bin"

	.align 2
	.global DirectSoundData_0873B050
DirectSoundData_0873B050:
	.incbin "sound/direct_sound_samples/0873B050.bin"

	.align 2
	.global DirectSoundData_0873CCA0
DirectSoundData_0873CCA0:
	.incbin "sound/direct_sound_samples/0873CCA0.bin"

	.align 2
	.global DirectSoundData_0873CCB4
DirectSoundData_0873CCB4:
	.incbin "sound/direct_sound_samples/0873CCB4.bin"

	.align 2
	.global DirectSoundData_0873CCC8
DirectSoundData_0873CCC8:
	.incbin "sound/direct_sound_samples/0873CCC8.bin"

	.align 2
	.global DirectSoundData_08742228
DirectSoundData_08742228:
	.incbin "sound/direct_sound_samples/08742228.bin"

	.align 2
	.global DirectSoundData_08746238
DirectSoundData_08746238:
	.incbin "sound/direct_sound_samples/08746238.bin"

	.align 2
	.global DirectSoundData_0874624C
DirectSoundData_0874624C:
	.incbin "sound/direct_sound_samples/0874624C.bin"

	.align 2
	.global DirectSoundData_08746BD8
DirectSoundData_08746BD8:
	.incbin "sound/direct_sound_samples/08746BD8.bin"

	.align 2
	.global DirectSoundData_08747170
DirectSoundData_08747170:
	.incbin "sound/direct_sound_samples/08747170.bin"

	.align 2
	.global DirectSoundData_087492F0
DirectSoundData_087492F0:
	.incbin "sound/direct_sound_samples/087492F0.bin"

	.align 2
	.global DirectSoundData_08749304
DirectSoundData_08749304:
	.incbin "sound/direct_sound_samples/08749304.bin"

	.align 2
	.global DirectSoundData_08749318
DirectSoundData_08749318:
	.incbin "sound/direct_sound_samples/08749318.bin"

	.align 2
	.global DirectSoundData_0874932C
DirectSoundData_0874932C:
	.incbin "sound/direct_sound_samples/0874932C.bin"

	.align 2
	.global DirectSoundData_08749340
DirectSoundData_08749340:
	.incbin "sound/direct_sound_samples/08749340.bin"

	.align 2
	.global DirectSoundData_08749354
DirectSoundData_08749354:
	.incbin "sound/direct_sound_samples/08749354.bin"

	.align 2
	.global DirectSoundData_08749368
DirectSoundData_08749368:
	.incbin "sound/direct_sound_samples/08749368.bin"

	.align 2
	.global DirectSoundData_0874937C
DirectSoundData_0874937C:
	.incbin "sound/direct_sound_samples/0874937C.bin"

	.align 2
	.global DirectSoundData_08749390
DirectSoundData_08749390:
	.incbin "sound/direct_sound_samples/08749390.bin"

	.align 2
	.global DirectSoundData_0874C580
DirectSoundData_0874C580:
	.incbin "sound/direct_sound_samples/0874C580.bin"

	.align 2
	.global DirectSoundData_0874F3A0
DirectSoundData_0874F3A0:
	.incbin "sound/direct_sound_samples/0874F3A0.bin"

	.align 2
	.global DirectSoundData_0874F3B4
DirectSoundData_0874F3B4:
	.incbin "sound/direct_sound_samples/0874F3B4.bin"

	.align 2
	.global DirectSoundData_0874F3C8
DirectSoundData_0874F3C8:
	.incbin "sound/direct_sound_samples/0874F3C8.bin"

	.align 2
	.global DirectSoundData_08752D10
DirectSoundData_08752D10:
	.incbin "sound/direct_sound_samples/08752D10.bin"

	.align 2
	.global DirectSoundData_08752D24
DirectSoundData_08752D24:
	.incbin "sound/direct_sound_samples/08752D24.bin"

	.align 2
	.global DirectSoundData_08754188
DirectSoundData_08754188:
	.incbin "sound/direct_sound_samples/08754188.bin"

	.align 2
	.global DirectSoundData_08754E1C
DirectSoundData_08754E1C:
	.incbin "sound/direct_sound_samples/08754E1C.bin"

	.align 2
	.global DirectSoundData_08754E30
DirectSoundData_08754E30:
	.incbin "sound/direct_sound_samples/08754E30.bin"

	.align 2
	.global DirectSoundData_08754E44
DirectSoundData_08754E44:
	.incbin "sound/direct_sound_samples/08754E44.bin"

	.align 2
	.global DirectSoundData_08754E58
DirectSoundData_08754E58:
	.incbin "sound/direct_sound_samples/08754E58.bin"

	.align 2
	.global DirectSoundData_08754E6C
DirectSoundData_08754E6C:
	.incbin "sound/direct_sound_samples/08754E6C.bin"

	.align 2
	.global DirectSoundData_08754E80
DirectSoundData_08754E80:
	.incbin "sound/direct_sound_samples/08754E80.bin"

	.align 2
	.global DirectSoundData_08754E94
DirectSoundData_08754E94:
	.incbin "sound/direct_sound_samples/08754E94.bin"

	.align 2
	.global DirectSoundData_08754EA8
DirectSoundData_08754EA8:
	.incbin "sound/direct_sound_samples/08754EA8.bin"

	.align 2
	.global DirectSoundData_08754EBC
DirectSoundData_08754EBC:
	.incbin "sound/direct_sound_samples/08754EBC.bin"

	.align 2
	.global DirectSoundData_08754ED0
DirectSoundData_08754ED0:
	.incbin "sound/direct_sound_samples/08754ED0.bin"

	.align 2
	.global DirectSoundData_08759B14
DirectSoundData_08759B14:
	.incbin "sound/direct_sound_samples/08759B14.bin"

	.align 2
	.global DirectSoundData_08759B28
DirectSoundData_08759B28:
	.incbin "sound/direct_sound_samples/08759B28.bin"

	.align 2
	.global DirectSoundData_08759B3C
DirectSoundData_08759B3C:
	.incbin "sound/direct_sound_samples/08759B3C.bin"

	.align 2
	.global DirectSoundData_0875E860
DirectSoundData_0875E860:
	.incbin "sound/direct_sound_samples/0875E860.bin"

	.align 2
	.global DirectSoundData_0875E874
DirectSoundData_0875E874:
	.incbin "sound/direct_sound_samples/0875E874.bin"

	.align 2
	.global DirectSoundData_0875E888
DirectSoundData_0875E888:
	.incbin "sound/direct_sound_samples/0875E888.bin"

	.align 2
	.global DirectSoundData_0875E89C
DirectSoundData_0875E89C:
	.incbin "sound/direct_sound_samples/0875E89C.bin"

	.align 2
	.global DirectSoundData_0875E8B0
DirectSoundData_0875E8B0:
	.incbin "sound/direct_sound_samples/0875E8B0.bin"

	.align 2
	.global DirectSoundData_0875E8C4
DirectSoundData_0875E8C4:
	.incbin "sound/direct_sound_samples/0875E8C4.bin"

	.align 2
	.global DirectSoundData_0875E8D8
DirectSoundData_0875E8D8:
	.incbin "sound/direct_sound_samples/0875E8D8.bin"

	.align 2
	.global DirectSoundData_0875E8EC
DirectSoundData_0875E8EC:
	.incbin "sound/direct_sound_samples/0875E8EC.bin"

	.align 2
	.global DirectSoundData_0875FA70
DirectSoundData_0875FA70:
	.incbin "sound/direct_sound_samples/0875FA70.bin"

	.align 2
	.global DirectSoundData_0876188C
DirectSoundData_0876188C:
	.incbin "sound/direct_sound_samples/0876188C.bin"

	.align 2
	.global DirectSoundData_08762C04
DirectSoundData_08762C04:
	.incbin "sound/direct_sound_samples/08762C04.bin"

	.align 2
	.global DirectSoundData_087636B8
DirectSoundData_087636B8:
	.incbin "sound/direct_sound_samples/087636B8.bin"

	.align 2
	.global DirectSoundData_087636CC
DirectSoundData_087636CC:
	.incbin "sound/direct_sound_samples/087636CC.bin"

	.align 2
	.global DirectSoundData_087636E0
DirectSoundData_087636E0:
	.incbin "sound/direct_sound_samples/087636E0.bin"

	.align 2
	.global DirectSoundData_08765ABC
DirectSoundData_08765ABC:
	.incbin "sound/direct_sound_samples/08765ABC.bin"

	.align 2
	.global DirectSoundData_08765AD0
DirectSoundData_08765AD0:
	.incbin "sound/direct_sound_samples/08765AD0.bin"

	.align 2
	.global DirectSoundData_08767EE0
DirectSoundData_08767EE0:
	.incbin "sound/direct_sound_samples/08767EE0.bin"

	.align 2
	.global DirectSoundData_08767EF4
DirectSoundData_08767EF4:
	.incbin "sound/direct_sound_samples/08767EF4.bin"

	.align 2
	.global DirectSoundData_08767F08
DirectSoundData_08767F08:
	.incbin "sound/direct_sound_samples/08767F08.bin"

	.align 2
	.global DirectSoundData_08767F1C
DirectSoundData_08767F1C:
	.incbin "sound/direct_sound_samples/08767F1C.bin"

	.align 2
	.global DirectSoundData_08771CD0
DirectSoundData_08771CD0:
	.incbin "sound/direct_sound_samples/08771CD0.bin"

	.align 2
	.global DirectSoundData_08771CE4
DirectSoundData_08771CE4:
	.incbin "sound/direct_sound_samples/08771CE4.bin"

	.align 2
	.global DirectSoundData_08771CF8
DirectSoundData_08771CF8:
	.incbin "sound/direct_sound_samples/08771CF8.bin"

	.align 2
	.global DirectSoundData_08771D0C
DirectSoundData_08771D0C:
	.incbin "sound/direct_sound_samples/08771D0C.bin"

	.align 2
	.global DirectSoundData_087739DC
DirectSoundData_087739DC:
	.incbin "sound/direct_sound_samples/087739DC.bin"

	.align 2
	.global DirectSoundData_0877984C
DirectSoundData_0877984C:
	.incbin "sound/direct_sound_samples/0877984C.bin"

	.align 2
	.global DirectSoundData_08779860
DirectSoundData_08779860:
	.incbin "sound/direct_sound_samples/08779860.bin"

	.align 2
	.global DirectSoundData_0877E0B4
DirectSoundData_0877E0B4:
	.incbin "sound/direct_sound_samples/0877E0B4.bin"

	.align 2
	.global DirectSoundData_0877FB50
DirectSoundData_0877FB50:
	.incbin "sound/direct_sound_samples/0877FB50.bin"

	.align 2
	.global DirectSoundData_0878237C
DirectSoundData_0878237C:
	.incbin "sound/direct_sound_samples/0878237C.bin"

	.align 2
	.global DirectSoundData_08782390
DirectSoundData_08782390:
	.incbin "sound/direct_sound_samples/08782390.bin"

	.align 2
	.global DirectSoundData_087823A4
DirectSoundData_087823A4:
	.incbin "sound/direct_sound_samples/087823A4.bin"

	.align 2
	.global DirectSoundData_087823B8
DirectSoundData_087823B8:
	.incbin "sound/direct_sound_samples/087823B8.bin"

	.align 2
	.global DirectSoundData_087823CC
DirectSoundData_087823CC:
	.incbin "sound/direct_sound_samples/087823CC.bin"

	.align 2
	.global DirectSoundData_087823E0
DirectSoundData_087823E0:
	.incbin "sound/direct_sound_samples/087823E0.bin"

	.align 2
	.global DirectSoundData_087823F4
DirectSoundData_087823F4:
	.incbin "sound/direct_sound_samples/087823F4.bin"

	.align 2
	.global DirectSoundData_08782408
DirectSoundData_08782408:
	.incbin "sound/direct_sound_samples/08782408.bin"

	.align 2
	.global DirectSoundData_0878241C
DirectSoundData_0878241C:
	.incbin "sound/direct_sound_samples/0878241C.bin"

	.align 2
	.global DirectSoundData_08786F48
DirectSoundData_08786F48:
	.incbin "sound/direct_sound_samples/08786F48.bin"

	.align 2
	.global DirectSoundData_0878B5EC
DirectSoundData_0878B5EC:
	.incbin "sound/direct_sound_samples/0878B5EC.bin"

	.align 2
	.global DirectSoundData_0878C4EC
DirectSoundData_0878C4EC:
	.incbin "sound/direct_sound_samples/0878C4EC.bin"

	.align 2
	.global DirectSoundData_0878D250
DirectSoundData_0878D250:
	.incbin "sound/direct_sound_samples/0878D250.bin"

	.align 2
	.global DirectSoundData_08790CEC
DirectSoundData_08790CEC:
	.incbin "sound/direct_sound_samples/08790CEC.bin"

	.align 2
	.global DirectSoundData_08791A38
DirectSoundData_08791A38:
	.incbin "sound/direct_sound_samples/08791A38.bin"

	.align 2
	.global DirectSoundData_08793F80
DirectSoundData_08793F80:
	.incbin "sound/direct_sound_samples/08793F80.bin"

	.align 2
	.global DirectSoundData_08795320
DirectSoundData_08795320:
	.incbin "sound/direct_sound_samples/08795320.bin"

	.align 2
	.global DirectSoundData_08795334
DirectSoundData_08795334:
	.incbin "sound/direct_sound_samples/08795334.bin"

	.align 2
	.global DirectSoundData_08795348
DirectSoundData_08795348:
	.incbin "sound/direct_sound_samples/08795348.bin"

	.align 2
	.global DirectSoundData_08796EB0
DirectSoundData_08796EB0:
	.incbin "sound/direct_sound_samples/08796EB0.bin"

	.align 2
	.global DirectSoundData_08799E38
DirectSoundData_08799E38:
	.incbin "sound/direct_sound_samples/08799E38.bin"

	.align 2
	.global DirectSoundData_0879B948
DirectSoundData_0879B948:
	.incbin "sound/direct_sound_samples/0879B948.bin"

	.align 2
	.global DirectSoundData_0879B95C
DirectSoundData_0879B95C:
	.incbin "sound/direct_sound_samples/0879B95C.bin"

	.align 2
	.global DirectSoundData_0879FDA0
DirectSoundData_0879FDA0:
	.incbin "sound/direct_sound_samples/0879FDA0.bin"

	.align 2
	.global DirectSoundData_087A4448
DirectSoundData_087A4448:
	.incbin "sound/direct_sound_samples/087A4448.bin"

	.align 2
	.global DirectSoundData_087A8FC4
DirectSoundData_087A8FC4:
	.incbin "sound/direct_sound_samples/087A8FC4.bin"

	.align 2
	.global DirectSoundData_087A8FD8
DirectSoundData_087A8FD8:
	.incbin "sound/direct_sound_samples/087A8FD8.bin"

	.align 2
	.global DirectSoundData_087AB264
DirectSoundData_087AB264:
	.incbin "sound/direct_sound_samples/087AB264.bin"

	.align 2
	.global DirectSoundData_087AEDD0
DirectSoundData_087AEDD0:
	.incbin "sound/direct_sound_samples/087AEDD0.bin"

	.align 2
	.global DirectSoundData_087AEDE4
DirectSoundData_087AEDE4:
	.incbin "sound/direct_sound_samples/087AEDE4.bin"

	.align 2
	.global DirectSoundData_087AEDF8
DirectSoundData_087AEDF8:
	.incbin "sound/direct_sound_samples/087AEDF8.bin"

	.align 2
	.global DirectSoundData_087B2964
DirectSoundData_087B2964:
	.incbin "sound/direct_sound_samples/087B2964.bin"

	.align 2
	.global DirectSoundData_087B42D8
DirectSoundData_087B42D8:
	.incbin "sound/direct_sound_samples/087B42D8.bin"

	.align 2
	.global DirectSoundData_087B42EC
DirectSoundData_087B42EC:
	.incbin "sound/direct_sound_samples/087B42EC.bin"

	.align 2
	.global DirectSoundData_087B4300
DirectSoundData_087B4300:
	.incbin "sound/direct_sound_samples/087B4300.bin"

	.align 2
	.global DirectSoundData_087B4314
DirectSoundData_087B4314:
	.incbin "sound/direct_sound_samples/087B4314.bin"

	.align 2
	.global DirectSoundData_087B4328
DirectSoundData_087B4328:
	.incbin "sound/direct_sound_samples/087B4328.bin"

	.align 2
	.global DirectSoundData_087B433C
DirectSoundData_087B433C:
	.incbin "sound/direct_sound_samples/087B433C.bin"

	.align 2
	.global DirectSoundData_087B4350
DirectSoundData_087B4350:
	.incbin "sound/direct_sound_samples/087B4350.bin"

	.align 2
	.global DirectSoundData_087B4364
DirectSoundData_087B4364:
	.incbin "sound/direct_sound_samples/087B4364.bin"

	.align 2
	.global DirectSoundData_087B4378
DirectSoundData_087B4378:
	.incbin "sound/direct_sound_samples/087B4378.bin"

	.align 2
	.global DirectSoundData_087B438C
DirectSoundData_087B438C:
	.incbin "sound/direct_sound_samples/087B438C.bin"

	.align 2
	.global DirectSoundData_087B43A0
DirectSoundData_087B43A0:
	.incbin "sound/direct_sound_samples/087B43A0.bin"

	.align 2
	.global DirectSoundData_087B43B4
DirectSoundData_087B43B4:
	.incbin "sound/direct_sound_samples/087B43B4.bin"

	.align 2
	.global DirectSoundData_087B43C8
DirectSoundData_087B43C8:
	.incbin "sound/direct_sound_samples/087B43C8.bin"

	.align 2
	.global DirectSoundData_087B43DC
DirectSoundData_087B43DC:
	.incbin "sound/direct_sound_samples/087B43DC.bin"

	.align 2
	.global DirectSoundData_087B43F0
DirectSoundData_087B43F0:
	.incbin "sound/direct_sound_samples/087B43F0.bin"

	.align 2
	.global DirectSoundData_087B4404
DirectSoundData_087B4404:
	.incbin "sound/direct_sound_samples/087B4404.bin"

	.align 2
	.global DirectSoundData_087B4418
DirectSoundData_087B4418:
	.incbin "sound/direct_sound_samples/087B4418.bin"

	.align 2
	.global DirectSoundData_087B442C
DirectSoundData_087B442C:
	.incbin "sound/direct_sound_samples/087B442C.bin"

	.align 2
	.global DirectSoundData_087B4440
DirectSoundData_087B4440:
	.incbin "sound/direct_sound_samples/087B4440.bin"

	.align 2
	.global DirectSoundData_087B4454
DirectSoundData_087B4454:
	.incbin "sound/direct_sound_samples/087B4454.bin"

	.align 2
	.global DirectSoundData_087B4468
DirectSoundData_087B4468:
	.incbin "sound/direct_sound_samples/087B4468.bin"

	.align 2
	.global DirectSoundData_087B447C
DirectSoundData_087B447C:
	.incbin "sound/direct_sound_samples/087B447C.bin"

	.align 2
	.global DirectSoundData_087B4490
DirectSoundData_087B4490:
	.incbin "sound/direct_sound_samples/087B4490.bin"

	.align 2
	.global DirectSoundData_087B44A4
DirectSoundData_087B44A4:
	.incbin "sound/direct_sound_samples/087B44A4.bin"

	.align 2
	.global DirectSoundData_087B44B8
DirectSoundData_087B44B8:
	.incbin "sound/direct_sound_samples/087B44B8.bin"

	.align 2
	.global DirectSoundData_087B44CC
DirectSoundData_087B44CC:
	.incbin "sound/direct_sound_samples/087B44CC.bin"

	.align 2
	.global DirectSoundData_087B44E0
DirectSoundData_087B44E0:
	.incbin "sound/direct_sound_samples/087B44E0.bin"

	.align 2
	.global DirectSoundData_087B44F4
DirectSoundData_087B44F4:
	.incbin "sound/direct_sound_samples/087B44F4.bin"

	.align 2
	.global DirectSoundData_087B4508
DirectSoundData_087B4508:
	.incbin "sound/direct_sound_samples/087B4508.bin"

	.align 2
	.global DirectSoundData_087B451C
DirectSoundData_087B451C:
	.incbin "sound/direct_sound_samples/087B451C.bin"

	.align 2
	.global DirectSoundData_087C5DBC
DirectSoundData_087C5DBC:
	.incbin "sound/direct_sound_samples/087C5DBC.bin"

	.align 2
	.global DirectSoundData_087C7904
DirectSoundData_087C7904:
	.incbin "sound/direct_sound_samples/087C7904.bin"

	.align 2
	.global DirectSoundData_087C8B64
DirectSoundData_087C8B64:
	.incbin "sound/direct_sound_samples/087C8B64.bin"

	.align 2
	.global DirectSoundData_087C9590
DirectSoundData_087C9590:
	.incbin "sound/direct_sound_samples/087C9590.bin"

	.align 2
	.global DirectSoundData_087CA344
DirectSoundData_087CA344:
	.incbin "sound/direct_sound_samples/087CA344.bin"

	.align 2
	.global DirectSoundData_087CAF48
DirectSoundData_087CAF48:
	.incbin "sound/direct_sound_samples/087CAF48.bin"

	.align 2
	.global DirectSoundData_087CC77C
DirectSoundData_087CC77C:
	.incbin "sound/direct_sound_samples/087CC77C.bin"

	.align 2
	.global DirectSoundData_087CCB78
DirectSoundData_087CCB78:
	.incbin "sound/direct_sound_samples/087CCB78.bin"
