	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0029_1
song_0029_1:	@ 0x087DB4F4
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 78
	.byte	W12
	.byte		N13	, An4, v127
	.byte	W12
	.byte		N10	, Gn4
	.byte	W12
	.byte		TIE	, Fn4
	.byte	W12
song_0029_1_1:
	.byte	W96
	.byte	W36
	.byte	W03
	.byte		EOT	, Fn4
	.byte	W21
	.byte		N12	, An4, v127
	.byte	W12
	.byte		N09	, Gn4
	.byte	W12
	.byte		TIE	, Fn4
	.byte	W12
	.byte	W96
	.byte	W32
	.byte	W02
	.byte		EOT	
	.byte	W24
	.byte	W02
	.byte		N05	, Dn4
	.byte	W12
	.byte		N13	, Fn4
	.byte	W12
	.byte		N06	, Dn4
	.byte	W12
	.byte		N32	, An4
	.byte	W36
	.byte			Gn4
	.byte	W36
	.byte		TIE	, Fn4
	.byte		N02	, Gn4
	.byte	W24
	.byte	W96
	.byte	W21
	.byte		EOT	, Fn4
	.byte	W36
	.byte	W03
	.byte		N14	, An3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte		TIE	, Fn3
	.byte	W12
	.byte	W96
	.byte	W21
	.byte		EOT	
	.byte	W15
	.byte		N04	, Cn3
	.byte	W12
	.byte		N13	, Fn3
	.byte	W12
	.byte		N05	, An3
	.byte	W12
	.byte		N15	, Dn4
	.byte	W12
	.byte		TIE	, Cn4
	.byte	W12
	.byte	W96
	.byte	W24
	.byte	W03
	.byte		EOT	
	.byte	W21
	.byte		N14	, An3
	.byte	W12
	.byte		N28	, Cn4
	.byte	W36
	.byte		N36	, Fn4
	.byte	W48
	.byte		N44	, En4
	.byte	W48
	.byte		N40	, Dn4
	.byte	W48
	.byte		N11	
	.byte	W12
	.byte		N07	, An3
	.byte	W12
	.byte		N06	, As3
	.byte	W12
	.byte		TIE	, Gn3
	.byte	W12
	.byte	W96
	.byte	W32
	.byte	W02
	.byte		EOT	
	.byte	W24
	.byte	W02
	.byte		N14	, As3
	.byte	W12
	.byte		N11	, An3
	.byte	W12
	.byte		TIE	, Gn3
	.byte	W12
	.byte	W96
	.byte	W22
	.byte		EOT	
	.byte	W24
	.byte	W02
	.byte		N11	
	.byte	W12
	.byte		N12	, An3
	.byte	W12
	.byte		N06	, As3
	.byte	W12
	.byte		N42	, Cn4
	.byte	W12
	.byte	W48
	.byte		N23	
	.byte	W24
	.byte		N06	, An3
	.byte	W12
	.byte		N60	, Fn4
	.byte	W12
	.byte	W60
	.byte		N04	, Fn3
	.byte	W12
	.byte		N24	, Gn3
	.byte	W24
	.byte		N05	, An3
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N08	, Dn4
	.byte	W36
	.byte		N05	, An3
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N08	, Dn4
	.byte	W24
	.byte		N03	, Fn3
	.byte	W12
	.byte		N13	, An3
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N20	
	.byte	W24
	.byte		N08	, As3
	.byte	W12
	.byte		TIE	, Gn3
	.byte	W12
	.byte	W92
	.byte		EOT	
	.byte	W04
	.byte	W24
	.byte		N13	, Dn4
	.byte	W24
	.byte		N11	, Fn4
	.byte	W12
	.byte		N16	, En4
	.byte	W24
	.byte		N19	, An4
	.byte	W12
	.byte	W12
	.byte		N05	, Gn4
	.byte	W12
	.byte		N09	, Fn4
	.byte	W12
	.byte			En4
	.byte	W24
	.byte		N10	
	.byte		N02	, Fn4
	.byte	W12
	.byte		N09	
	.byte	W12
	.byte		N06	, Gn4
	.byte	W12
	.byte		N21	, Fn4
	.byte	W24
	.byte		N15	, En4
	.byte	W12
	.byte		TIE	, Dn4
	.byte	W60
	.byte	W44
	.byte	W03
	.byte		EOT	
	.byte	W13
	.byte		N17	, An3
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte		N17	, Cn4
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte		N17	
	.byte	W48
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N07	, En4
	.byte	W12
	.byte		N11	, Fn4
	.byte	W12
	.byte		N15	, Dn4
	.byte	W24
	.byte		N21	, An4
	.byte	W12
	.byte	W24
	.byte		N15	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N06	, Gn4
	.byte	W12
	.byte		N10	, Fn4
	.byte	W12
	.byte		N06	, Dn4
	.byte	W12
	.byte		N07	, Fn4
	.byte	W12
	.byte		N14	, Gn4
	.byte	W24
	.byte		N17	
	.byte	W24
	.byte		N09	, Fn4
	.byte	W12
	.byte		N16	, Dn4
	.byte	W24
	.byte	W24
	.byte		N11	
	.byte	W12
	.byte		N08	, En4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte		N19	, Dn4
	.byte	W24
	.byte		N03	, En4
	.byte		N24	, Fn4
	.byte	W12
	.byte	W12
	.byte		N09	, En4
	.byte	W12
	.byte		N06	, Fn4
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N13	, En4
	.byte	W12
	.byte		N10	, Dn4
	.byte	W12
	.byte		N12	, En4
	.byte	W12
	.byte		N18	, Dn4
	.byte	W24
	.byte		N15	, Cn4
	.byte	W24
	.byte		N22	
	.byte	W24
	.byte		N09	, An3
	.byte	W12
	.byte		N72	, An4
	.byte	W12
	.byte	W60
	.byte		N13	, Gn4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte		N09	, En4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte		N44	, Dn4
	.byte	W60
	.byte		N08	
	.byte	W12
	.byte		N06	, En4
	.byte	W12
	.byte		N13	, Fn4
	.byte	W12
	.byte		N36	, Dn4
	.byte	W48
	.byte		N15	
	.byte	W12
	.byte		N09	, En4
	.byte	W12
	.byte		N06	, Fn4
	.byte	W12
	.byte		N15	, An4
	.byte	W24
	.byte		N11	
	.byte	W24
	.byte		N14	
	.byte	W12
	.byte		N07	, As4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte		TIE	, Gn4
	.byte	W12
	.byte	W96
	.byte		EOT	
	.byte	W24
	.byte		N12	, Cn4
	.byte	W24
	.byte		N13	, An4
	.byte	W24
	.byte		N14	, As4
	.byte	W24
	.byte		N60	, An4
	.byte	W60
	.byte		N09	, Fn4
	.byte	W12
	.byte		N07	, Gn4
	.byte	W12
	.byte		N28	, An4
	.byte	W12
	.byte	W24
	.byte		N17	
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte		N09	, Gn4
	.byte	W12
	.byte		N08	, Fn4
	.byte	W12
	.byte		N17	, En4
	.byte	W12
	.byte	W12
	.byte		N09	
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte		N24	, Gn4
	.byte	W24
	.byte		N13	, Fn4
	.byte	W12
	.byte		N09	, En4
	.byte	W12
	.byte		N15	, Dn4
	.byte	W12
	.byte	W24
	.byte		N14	
	.byte	W12
	.byte		N10	, En4
	.byte	W12
	.byte		N13	, Fn4
	.byte	W12
	.byte		N08	, Dn4
	.byte	W24
	.byte		N22	
	.byte	W12
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N13	
	.byte	W12
	.byte		N11	, En4
	.byte	W12
	.byte		N13	, Fn4
	.byte	W12
	.byte		N18	, Dn4
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N15	, Cn4
	.byte	W24
	.byte		N16	, Dn4
	.byte	W24
	.byte		N17	, En4
	.byte	W24
	.byte		N08	, Fn4
	.byte	W12
	.byte		N16	, Gn4
	.byte	W12
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N07	, An4
	.byte	W12
	.byte		N13	, As4
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte		N19	, Cn5
	.byte	W24
	.byte		N15	, An4
	.byte	W24
	.byte		N15	
	.byte	W24
	.byte		N15	
	.byte	W12
	.byte		N09	, Gn4
	.byte	W12
	.byte		N05	, Fn4
	.byte	W12
	.byte		N16	, Cn4
	.byte	W12
	.byte	W12
	.byte		N12	, An4
	.byte	W24
	.byte		N07	
	.byte	W12
	.byte		N13	
	.byte	W12
	.byte		N08	, Gn4
	.byte	W12
	.byte		N11	, Fn4
	.byte	W12
	.byte		N07	, Cn4
	.byte	W12
	.byte		N12	, En4
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N15	
	.byte	W12
	.byte		N08	, Fn4
	.byte	W12
	.byte		N05	, Gn4
	.byte	W12
	.byte		N21	, Cn5
	.byte	W12
	.byte	W12
	.byte		N06	, As4
	.byte	W12
	.byte		N09	
	.byte	W12
	.byte		N36	, An4
	.byte	W36
	.byte		N11	, Fn4
	.byte	W12
	.byte		N07	, Gn4
	.byte	W12
	.byte		N84	, An4
	.byte	W84
	.byte		N05	, Dn4
	.byte	W12
	.byte		N36	, An4
	.byte	W48
	.byte		N14	
	.byte	W12
	.byte		N12	, Gn4
	.byte	W12
	.byte		N06	, Fn4
	.byte	W12
	.byte		N19	
	.byte	W12
	.byte	W24
	.byte		N11	
	.byte	W24
	.byte		N12	, Dn4
	.byte	W12
	.byte		N11	, Cn4
	.byte	W24
	.byte		N16	, Fn3
	.byte	W12
	.byte	W60
	.byte		N13	, An4
	.byte	W12
	.byte		N10	, Gn4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte	GOTO	
		.word	song_0029_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0029_2
song_0029_2:	@ 0x087DB779
	.byte	KEYSH	, 0
	.byte	VOICE	, 8
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
song_0029_2_3:
	.byte	W48
	.byte	W01
	.byte		N07	, Dn5, v127
	.byte	W13
	.byte		N05	, Cn5
	.byte	W11
	.byte			As4
	.byte	W12
	.byte		N07	, An4
	.byte	W11
	.byte	W12
	.byte		N05	, Fn4
	.byte	W12
	.byte		N06	, Fn5
	.byte	W72
	.byte	W48
	.byte		N07	, Dn5
	.byte	W12
	.byte		N05	, Cn5
	.byte	W12
	.byte			As4
	.byte	W12
	.byte		N06	, An4
	.byte	W12
	.byte	W12
	.byte		N05	, Fn4
	.byte	W12
	.byte			Fn5
	.byte	W72
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W12
	.byte		N12	, Cn5
	.byte	W12
	.byte			Fn5
	.byte	W12
	.byte		N60	, Cn6
	.byte	W60
	.byte	W96
	.byte	W12
	.byte		N12	, Cn5
	.byte	W12
	.byte			En5
	.byte	W12
	.byte		N60	, Cn6
	.byte	W60
	.byte	W96
song_0029_2_1:
	.byte	W12
	.byte		N12	, Dn5, v127
	.byte	W12
	.byte			Fn5
	.byte	W12
	.byte		N60	, Dn6
	.byte	W60
	.byte	PEND
	.byte	W96
	.byte	PATT	
		.word	song_0029_2_1
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0029_2_2:
	.byte	W48
	.byte		N12	, An4, v127
	.byte	W12
	.byte			Dn5
	.byte	W36
	.byte	PEND
	.byte	PATT	
		.word	song_0029_2_2
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W72
	.byte		N06	, Gn4, v127
	.byte	W24
	.byte		N07	, Dn5
	.byte	W36
	.byte		N06	, Gn5
	.byte	W60
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	VOICE	, 5
	.byte	W12
	.byte		N03	, Dn3, v100
	.byte	W12
	.byte		N08	, Fn3
	.byte	W12
	.byte		N05	, Dn3
	.byte	W12
	.byte		N08	, As3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W12
	.byte		N09	, Fn3
	.byte	W12
	.byte		N06	, Dn3
	.byte	W12
	.byte	W12
	.byte		N05	, Cn3
	.byte	W12
	.byte		N09	, En3
	.byte	W12
	.byte		N03	, Cn3
	.byte	W12
	.byte		N09	, Gn3
	.byte	W12
	.byte		N03	, Cn3
	.byte	W12
	.byte		N10	, En3
	.byte	W12
	.byte		N05	, Cn3
	.byte	W12
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N09	, En3
	.byte	W12
	.byte		N03	, Cn3
	.byte	W12
	.byte		N09	, Cn4
	.byte	W12
	.byte		N03	, Cn3
	.byte	W12
	.byte		N10	, En3
	.byte	W12
	.byte		N05	, Cn3
	.byte	W12
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N10	, Fn3
	.byte	W12
	.byte		N05	, Dn3
	.byte	W12
	.byte		N09	, An3
	.byte	W12
	.byte		N03	, Dn3
	.byte	W12
	.byte		N10	, Fn3
	.byte	W12
	.byte		N05	, Dn3
	.byte	W12
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N09	, Fn3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W12
	.byte		N08	, Bn3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W12
	.byte		N10	, Fn3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W12
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N08	, Fn3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W12
	.byte		N08	, Bn3
	.byte	W12
	.byte		N05	, Dn3
	.byte	W12
	.byte		N11	, Fn3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W12
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N09	, Fn3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W12
	.byte		N08	, An3
	.byte	W12
	.byte		N03	, Dn3
	.byte	W12
	.byte		N06	, Fn3
	.byte	W12
	.byte		N09	, Cn4
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	VOICE	, 8
	.byte	W24
	.byte		N06	, Fn5, v127
	.byte	W24
	.byte			Dn5
	.byte	W12
	.byte			Cn5
	.byte	W24
	.byte		N08	, Fn4
	.byte	W12
	.byte	W96
	.byte	GOTO	
		.word	song_0029_2_3
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0029_3
song_0029_3:	@ 0x087DB8B3
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
song_0029_3_1:
	.byte	VOICE	, 5
	.byte	W12
	.byte		N04	, Dn3, v127
	.byte	W12
	.byte		N11	, Fn3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W12
	.byte		N13	, As3
	.byte	W12
	.byte		N10	, Cn4
	.byte	W12
	.byte		N06	, Dn4
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte	W12
	.byte		N05	, An3
	.byte	W12
	.byte		N09	
	.byte	W72
	.byte	W12
	.byte		N05	, Dn3
	.byte	W12
	.byte		N11	, Fn3
	.byte	W12
	.byte		N06	, Dn3
	.byte	W12
	.byte		N09	, As3
	.byte	W12
	.byte		N12	, Cn4
	.byte	W12
	.byte		N07	, Dn4
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte	W12
	.byte		N06	, An3
	.byte	W12
	.byte		N08	
	.byte	W72
	.byte		N36	, Fn3
	.byte	W36
	.byte			En3
	.byte	W36
	.byte		TIE	, Dn3
	.byte	W24
	.byte	W96
	.byte	W32
	.byte	W01
	.byte		EOT	
	.byte	W15
	.byte		N06	
	.byte	W12
	.byte		N10	
	.byte	W36
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W72
	.byte	VOICE	, 0
	.byte	W24
	.byte		N48	, As3
	.byte	W48
	.byte			An3
	.byte	W48
	.byte		N96	, Gn3
	.byte	W96
	.byte		N48	, An3
	.byte	W48
	.byte		N36	, Gn3
	.byte	W36
	.byte		TIE	, Fn3
	.byte	W12
	.byte	W96
	.byte		EOT	
	.byte		TIE	, Fn4
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		N16	
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N78	, En4
	.byte	W12
	.byte	W66
	.byte		N06	, Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		TIE	, An4
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		N36	, Bn4
	.byte	W36
	.byte		N60	, Gn4
	.byte	W60
	.byte		N36	, Dn4
	.byte	W36
	.byte			Bn3
	.byte	W36
	.byte		N24	, An3
	.byte	W24
	.byte		TIE	
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		N24	, Dn3
	.byte	W24
	.byte			Gn3
	.byte	W24
	.byte			Bn3
	.byte	W24
	.byte		N23	, Dn4
	.byte	W24
	.byte		N12	, Fn4
	.byte	W12
	.byte			Gn4
	.byte	W48
	.byte		N36	, En3
	.byte	W36
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		N06	, Gn3
	.byte	W06
	.byte			Fs3
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte			An3
	.byte	W06
	.byte			As3
	.byte	W06
	.byte			An3
	.byte	W06
	.byte			As3
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Dn4
	.byte	W04
	.byte			En4
	.byte	W04
	.byte			Fn4
	.byte	W04
	.byte			Gn4
	.byte	W04
	.byte			An4
	.byte	W04
	.byte			As4
	.byte	W04
	.byte		TIE	, Cn5
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		N96	, Cs5
	.byte	W96
	.byte			Dn5
	.byte	W96
	.byte		N12	, As3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte		N72	, Dn4
	.byte	W72
	.byte		N12	, Gn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte		N72	, As3
	.byte	W72
	.byte		N16	, En3
	.byte	W24
	.byte			Fn3
	.byte	W24
	.byte			Gn3
	.byte	W24
	.byte		N12	, An3
	.byte	W12
	.byte		N16	, As3
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N04	, Cn4
	.byte	W12
	.byte		N16	, Dn4
	.byte	W24
	.byte		N04	
	.byte	W12
	.byte		N24	, En4
	.byte	W24
	.byte		TIE	, Cn5
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		N96	, Cs5
	.byte	W96
	.byte			Dn5
	.byte	W96
	.byte	W36
	.byte		N60	, Fn3
	.byte	W60
	.byte	W36
	.byte			En3
	.byte	W60
	.byte		N12	, Fn3
	.byte	W24
	.byte			Fn4
	.byte	W24
	.byte			Dn4
	.byte	W12
	.byte			Cn4
	.byte	W24
	.byte			Fn3
	.byte	W12
	.byte	W96
	.byte	GOTO	
		.word	song_0029_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0029_4
song_0029_4:	@ 0x087DB9E7
	.byte	KEYSH	, 0
	.byte	VOICE	, 2
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
song_0029_4_1:
	.byte	W24
	.byte		N12	, As1, v127
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N24	, Fn1
	.byte	W12
	.byte	PEND
song_0029_4_2:
	.byte	W12
	.byte		N12	, Fn1, v127
	.byte	W12
	.byte		N12	
	.byte	W72
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_1
	.byte	PATT	
		.word	song_0029_4_2
	.byte		N36	, Gn2, v127
	.byte	W36
	.byte			Fn2
	.byte	W36
	.byte		TIE	, Ds2
	.byte	W24
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W36
song_0029_4_3:
	.byte		N12	, Fn1, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_3
song_0029_4_4:
	.byte		N12	, An1, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_4
song_0029_4_5:
	.byte		N12	, Dn2, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_5
song_0029_4_6:
	.byte		N12	, Gn1, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_6
	.byte	PATT	
		.word	song_0029_4_6
	.byte		N12	, Cn2, v127
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte			As1
	.byte	W12
	.byte		N24	, An1
	.byte	W12
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	, Dn2
	.byte	W12
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte			As1
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PATT	
		.word	song_0029_4_6
	.byte		N12	, Cn2, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N24	
	.byte	W12
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte			Cs2
	.byte	W12
song_0029_4_7:
	.byte		N12	, Dn2, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte			An1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_7
song_0029_4_8:
	.byte		N12	, Gn1, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte			Dn2
	.byte	W12
	.byte	PEND
	.byte			Gn1
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte			An1
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte	PATT	
		.word	song_0029_4_7
	.byte	PATT	
		.word	song_0029_4_7
	.byte	PATT	
		.word	song_0029_4_8
	.byte		N12	, Gn1, v127
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte		N36	, An1
	.byte	W36
	.byte		N12	, As1
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte			Cn2
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte			As1
	.byte	W12
song_0029_4_10:
	.byte		N12	, An1, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_7
	.byte	PATT	
		.word	song_0029_4_8
song_0029_4_11:
	.byte		N12	, Gn1, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte	PEND
	.byte			Cn2
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte			Gn1
	.byte	W12
	.byte		N24	, Cn2
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
song_0029_4_9:
	.byte		N12	, Fn1, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte			Cn2
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_9
	.byte	PATT	
		.word	song_0029_4_10
song_0029_4_12:
	.byte		N12	, Dn2, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0029_4_8
	.byte	PATT	
		.word	song_0029_4_11
	.byte		N12	, Cn2, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte			Gn1
	.byte	W12
	.byte			Cn2
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	PATT	
		.word	song_0029_4_9
	.byte	PATT	
		.word	song_0029_4_9
	.byte	PATT	
		.word	song_0029_4_10
	.byte	PATT	
		.word	song_0029_4_12
	.byte	PATT	
		.word	song_0029_4_8
	.byte		N12	, Cn2, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte			Fn1
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte			Dn2
	.byte	W12
	.byte			Cn2
	.byte	W24
	.byte		N24	, Fn1
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	GOTO	
		.word	song_0029_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0029_5
song_0029_5:	@ 0x087DBB76
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W12
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Fn1
	.byte	W12
song_0029_5_3:
	.byte		N12	, Cn1, v127
	.byte		N23	, Cs2
	.byte	W24
	.byte		N12	, Dn1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte			Cn1
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			Cn1
	.byte		N22	, An2
	.byte	W24
	.byte		N12	, Dn1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte		N23	, Cs2
	.byte	W24
	.byte	W96
	.byte	W48
	.byte		N12	, Dn1
	.byte	W12
	.byte		N12	
	.byte	W36
	.byte			Cn1
	.byte		N23	, An2
	.byte	W24
	.byte		N12	, Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			Dn1
	.byte	W24
song_0029_5_1:
	.byte		N12	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte		N12	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte		N21	, Cs2
	.byte	W12
	.byte	W12
	.byte		N12	, Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	, Dn1
	.byte	W06
	.byte		N12	
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N05	
	.byte	W06
song_0029_5_2:
	.byte		N12	, An1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Fn1
	.byte	W24
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0029_5_2
	.byte	PATT	
		.word	song_0029_5_2
	.byte	PATT	
		.word	song_0029_5_2
	.byte	PATT	
		.word	song_0029_5_2
	.byte	PATT	
		.word	song_0029_5_2
	.byte	PATT	
		.word	song_0029_5_2
	.byte		N12	, An1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte		N24	, Cs2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N12	, Cn1
	.byte		N22	, An2
	.byte	W24
	.byte		N12	, Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte		N12	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte			Cn1
	.byte		N21	, Cs2
	.byte	W24
	.byte		N12	, Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte	PATT	
		.word	song_0029_5_1
	.byte		N12	, Dn1, v127
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte	GOTO	
		.word	song_0029_5_3
	.byte	FINE

	.align 2
	.global song_0029
song_0029:	@ 0x087DBD40
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0029_1		@ track
	.word	song_0029_2		@ track
	.word	song_0029_3		@ track
	.word	song_0029_4		@ track
	.word	song_0029_5		@ track
