	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0011_1
song_0011_1:	@ 0x087D5C60
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 56
	.byte		N24	, Gn4, v127
	.byte	W24
	.byte		N22	, Gs4
	.byte	W24
song_0011_1_2:
	.byte		N15	, As4, v127
	.byte	W36
	.byte		N11	, Ds4
	.byte	W12
	.byte		N13	, Fn4
	.byte	W12
	.byte		N11	, Gn4
	.byte	W12
	.byte		N12	, Gs4
	.byte	W12
	.byte		N56	, As4
	.byte	W12
	.byte	PEND
	.byte	W84
	.byte		N12	, Gn4
	.byte	W12
song_0011_1_1:
	.byte		N24	, Dn5, v127
	.byte	W24
	.byte			Cn5
	.byte	W24
	.byte		N23	, As4
	.byte	W36
	.byte		N04	, Gn4
	.byte	W12
	.byte	PEND
song_0011_1_3:
	.byte		N10	, As4, v127
	.byte	W12
	.byte		N05	, Gs4
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N04	, Gn4
	.byte	W12
	.byte		N40	, Gs4
	.byte	W54
	.byte	PEND
song_0011_1_4:
	.byte		N28	, Fn4, v127
	.byte	W36
	.byte		N04	
	.byte	W12
	.byte		N24	, Cn5
	.byte	W24
	.byte		N21	, Dn5
	.byte	W24
	.byte	PEND
song_0011_1_5:
	.byte		N06	, Cn5, v127
	.byte	W12
	.byte			As4
	.byte	W12
	.byte		N05	, An4
	.byte	W06
	.byte		N06	, As4
	.byte	W12
	.byte		N21	, Ds5
	.byte	W30
	.byte		N05	, Ds4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte	PEND
song_0011_1_6:
	.byte		N11	, Gn4, v127
	.byte	W12
	.byte		N05	, Gs4
	.byte	W06
	.byte			Gn4
	.byte	W30
	.byte		N09	
	.byte	W12
	.byte		N04	, Cn5
	.byte	W06
	.byte		N04	
	.byte	W18
	.byte		N03	, Ds4
	.byte	W12
	.byte	PEND
song_0011_1_7:
	.byte		N32	, Fn4, v127
	.byte	W48
	.byte		N23	, Gn4
	.byte	W24
	.byte		N24	, Gs4
	.byte	W24
	.byte	PEND
	.byte			As4
	.byte	W36
	.byte		N05	, Ds4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte		N11	, Gn4
	.byte	W12
	.byte		N12	, Gs4
	.byte	W12
	.byte		N13	, Cn5
	.byte	W12
	.byte		N48	, As4
	.byte	W84
	.byte		N04	, Gn4
	.byte	W12
	.byte	PATT	
		.word	song_0011_1_1
	.byte		N10	, As4, v127
	.byte	W12
	.byte		N04	, Gs4
	.byte	W12
	.byte		N07	
	.byte	W06
	.byte		N04	, Gn4
	.byte	W12
	.byte		N36	, Gs4
	.byte	W54
	.byte		N44	, Fn4
	.byte	W60
	.byte		N13	
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte		N12	, Gs4
	.byte	W12
	.byte		N24	, As4
	.byte	W24
	.byte		N22	, Gn4
	.byte	W24
	.byte		N36	, Cn5
	.byte	W36
	.byte		N07	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N05	, Ds5
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte			Fn4
	.byte	W06
	.byte		N07	, Gn4
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte		N24	, Gn4
	.byte	W24
	.byte		N13	, Fn4
	.byte	W18
	.byte		N12	, Ds4
	.byte	W06
	.byte	W84
	.byte			As3
	.byte	W12
	.byte		N07	, Gn4
	.byte	W48
	.byte		N10	, Fn4
	.byte	W36
	.byte		N05	, Dn4
	.byte	W12
	.byte		N06	, Ds4
	.byte	W12
	.byte		N05	, Dn4
	.byte	W06
	.byte			Ds4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte		N36	, Cn4
	.byte	W54
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N13	, Dn4
	.byte	W12
	.byte		N14	, Ds4
	.byte	W12
	.byte		N12	, Dn4
	.byte	W12
	.byte			Ds4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte			As4
	.byte	W12
	.byte		N20	, Gs4
	.byte	W18
	.byte		N05	, Gn4
	.byte	W18
	.byte		N11	
	.byte	W30
	.byte		N06	
	.byte	W06
	.byte		N05	, Gs4
	.byte	W12
	.byte		N06	, As4
	.byte	W12
	.byte		N15	, Cn5
	.byte	W36
	.byte		N06	
	.byte	W12
	.byte		N23	, Dn5
	.byte	W24
	.byte		N24	, Ds5
	.byte	W24
	.byte		N36	, As4
	.byte	W60
	.byte		N04	, Gn4
	.byte	W12
	.byte		N12	, Gs4
	.byte	W12
	.byte		N13	, Gn4
	.byte	W12
	.byte		N05	, Cn5
	.byte	W12
	.byte		N04	, Gn4
	.byte	W06
	.byte		N28	
	.byte	W42
	.byte		N10	, Ds4
	.byte	W12
	.byte		N13	, Fn4
	.byte	W12
	.byte		N12	, Gn4
	.byte	W12
	.byte		N20	, Fn4
	.byte	W48
	.byte		N36	, As4
	.byte	W36
	.byte		N12	, Gs4
	.byte	W12
	.byte		N11	, Gn4
	.byte	W48
	.byte		N12	, Fn4
	.byte	W36
	.byte		N05	, Dn4
	.byte	W12
	.byte		N10	, Ds4
	.byte	W12
	.byte		N04	, Dn4
	.byte	W06
	.byte			Ds4
	.byte	W12
	.byte		N05	, Gn4
	.byte	W12
	.byte		N40	, Cn4
	.byte	W54
	.byte	W12
	.byte		N14	
	.byte	W12
	.byte		N12	, Dn4
	.byte	W12
	.byte		N14	, Ds4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N13	, Ds4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte		N13	, As4
	.byte	W12
	.byte		N16	, Gs4
	.byte	W18
	.byte		N05	, Gn4
	.byte	W18
	.byte		N20	
	.byte	W30
	.byte		N06	
	.byte	W06
	.byte		N05	, Gs4
	.byte	W12
	.byte		N07	, As4
	.byte	W12
	.byte		N24	, Cn5
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	, Dn5
	.byte	W24
	.byte			Ds5
	.byte	W24
	.byte		N36	, As4
	.byte	W36
	.byte		N12	, Gn4
	.byte	W12
	.byte		N30	, Cn5
	.byte	W48
	.byte		N07	, Gs4
	.byte	W06
	.byte		N05	, Gn4
	.byte	W12
	.byte		N17	, Fn4
	.byte	W18
	.byte		N08	, Ds4
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte		N07	, Cn4
	.byte	W06
	.byte		N05	, Dn4
	.byte	W12
	.byte		N15	, Ds4
	.byte	W18
	.byte		N14	, Cn4
	.byte	W12
	.byte		N32	, Cn5
	.byte	W48
	.byte		N09	, As3
	.byte	W12
	.byte		N06	, Cn4
	.byte	W06
	.byte		N04	, Dn4
	.byte	W12
	.byte			As3
	.byte	W12
	.byte		N32	, As4
	.byte	W54
	.byte		N10	, Gs3
	.byte	W12
	.byte		N07	, As3
	.byte	W06
	.byte		N04	, Cn4
	.byte	W12
	.byte		N05	, Gs3
	.byte	W12
	.byte		N30	, Gs4
	.byte	W30
	.byte		N24	, As4
	.byte	W24
	.byte		N09	, Gs4
	.byte	W12
	.byte		N04	, Gn4
	.byte	W06
	.byte		N48	
	.byte	W78
	.byte		N12	, Cn4
	.byte	W12
	.byte		N07	, Dn4
	.byte	W06
	.byte		N04	, Ds4
	.byte	W12
	.byte		N05	, Cn4
	.byte	W12
	.byte		N36	, Cn5
	.byte	W54
	.byte		N10	, As3
	.byte	W12
	.byte		N08	, Cn4
	.byte	W06
	.byte		N05	, Dn4
	.byte	W12
	.byte			As3
	.byte	W12
	.byte		N40	, As4
	.byte	W54
	.byte		N09	, Cn4
	.byte	W12
	.byte		N07	, Dn4
	.byte	W06
	.byte		N04	, Ds4
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte		N28	, Cn5
	.byte	W30
	.byte		N24	, Dn5
	.byte	W24
	.byte		N08	, As4
	.byte	W36
	.byte		N04	, Fn4
	.byte	W12
	.byte		N24	, Gn4
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte	PATT	
		.word	song_0011_1_2
	.byte	W84
	.byte		N12	, Gn4, v127
	.byte	W12
	.byte	PATT	
		.word	song_0011_1_1
	.byte	PATT	
		.word	song_0011_1_3
	.byte	PATT	
		.word	song_0011_1_4
	.byte	PATT	
		.word	song_0011_1_5
	.byte	PATT	
		.word	song_0011_1_6
	.byte	PATT	
		.word	song_0011_1_7
	.byte	GOTO	
		.word	song_0011_1_2
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0011_2
song_0011_2:	@ 0x087D5EAA
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		N24	, Gn3, v127
	.byte	W24
	.byte			Gs3
	.byte	W24
song_0011_2_6:
	.byte		N16	, Ds4, v127
	.byte	W96
song_0011_2_1:
	.byte	W54
	.byte		N03	, As3, v127
	.byte	W18
	.byte		N03	
	.byte	W24
	.byte	PEND
	.byte	W96
song_0011_2_2:
	.byte	W42
	.byte		N04	, Fn4, v127
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			Ds4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte	PEND
song_0011_2_3:
	.byte		N40	, As3, v127
	.byte	W48
	.byte			Gs3
	.byte	W48
	.byte	PEND
song_0011_2_4:
	.byte		N40	, Gn3, v127
	.byte	W44
	.byte	W03
	.byte			Cn4
	.byte	W48
	.byte	W01
	.byte	PEND
	.byte	W30
	.byte		N12	, Cn5
	.byte	W66
song_0011_2_5:
	.byte	W48
	.byte		N24	, Gn3, v127
	.byte	W24
	.byte			Gs3
	.byte	W24
	.byte	PEND
	.byte		N16	, Ds4
	.byte	W96
	.byte	PATT	
		.word	song_0011_2_1
	.byte	W96
	.byte	PATT	
		.word	song_0011_2_2
	.byte	PATT	
		.word	song_0011_2_3
	.byte	PATT	
		.word	song_0011_2_4
	.byte	W30
	.byte		N10	, Cn5, v127
	.byte	W18
	.byte		N06	, As3
	.byte	W24
	.byte		N18	
	.byte	W18
	.byte		N06	, Ds4
	.byte	W06
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W18
	.byte		N06	
	.byte	W48
	.byte			As3
	.byte	W30
	.byte	W54
	.byte		N04	, Cn4
	.byte	W18
	.byte		N04	
	.byte	W24
	.byte	W96
	.byte		N18	, Gs3
	.byte	W18
	.byte		N04	, Gn3
	.byte	W18
	.byte		N32	
	.byte	W32
	.byte	W03
	.byte		N24	, Cs4
	.byte	W24
	.byte	W01
	.byte		N96	, Cn4
	.byte	W96
	.byte		N48	, As3
	.byte	W48
	.byte		N36	, Cn4
	.byte	W48
	.byte		N06	, Gs4
	.byte	W06
	.byte		N04	, Gn4
	.byte	W12
	.byte		N18	, Fn4
	.byte	W18
	.byte		N04	, Ds4
	.byte	W12
	.byte		N20	
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte		N08	, Ds4
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W54
	.byte		N06	, Gn3
	.byte	W06
	.byte			As3
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	, Gn4
	.byte	W06
	.byte		N06	, Fn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N08	, Cn4
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT	
		.word	song_0011_2_5
	.byte		N16	, Ds4, v127
	.byte	W96
	.byte	PATT	
		.word	song_0011_2_1
	.byte	W96
	.byte	PATT	
		.word	song_0011_2_2
	.byte	PATT	
		.word	song_0011_2_3
	.byte	PATT	
		.word	song_0011_2_4
	.byte	W30
	.byte		N08	, Cn5, v127
	.byte	W66
	.byte	PATT	
		.word	song_0011_2_5
	.byte	GOTO	
		.word	song_0011_2_6
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0011_3
song_0011_3:	@ 0x087D5F9A
	.byte	KEYSH	, 0
	.byte	VOICE	, 1
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	BEND	, c_v
	.byte	W24
	.byte	W48
song_0011_3_1:
	.byte		N12	, Ds2, v127
	.byte	W12
	.byte			As2
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte		N60	, Gn3
	.byte	W60
	.byte	PEND
song_0011_3_2:
	.byte		N12	, Dn2, v127
	.byte	W12
	.byte			As2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N60	, Fn3
	.byte	W60
	.byte	PEND
song_0011_3_3:
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte		N60	, Gn3
	.byte	W60
	.byte	PEND
song_0011_3_4:
	.byte		N12	, Fn2, v127
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte		N60	, Fn3
	.byte	W60
	.byte	PEND
song_0011_3_5:
	.byte		N12	, As2, v127
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N24	, Fn3
	.byte	W24
	.byte		N12	, Gs2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N24	, Fn3
	.byte	W24
	.byte	PEND
song_0011_3_6:
	.byte		N12	, Gn2, v127
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N24	, Fn3
	.byte	W24
	.byte		N12	, Gn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte		N24	, Gn3
	.byte	W24
	.byte	PEND
song_0011_3_9:
	.byte		N12	, Fn2, v127
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte		N60	, Gn3
	.byte	W60
	.byte	PEND
song_0011_3_10:
	.byte		N12	, Fn2, v127
	.byte	W12
	.byte			As2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N60	, Fn3
	.byte	W60
	.byte	PEND
	.byte	PATT	
		.word	song_0011_3_1
	.byte	PATT	
		.word	song_0011_3_2
	.byte	PATT	
		.word	song_0011_3_3
	.byte	PATT	
		.word	song_0011_3_4
	.byte	PATT	
		.word	song_0011_3_5
	.byte	PATT	
		.word	song_0011_3_6
	.byte		N12	, Fn2, v127
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte		N24	, Fn3
	.byte	W24
	.byte		N12	, Fn2
	.byte	W12
	.byte			As2
	.byte	W12
	.byte		N18	, Fn3
	.byte	W24
	.byte	W18
	.byte		N06	, As1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			Gn1
	.byte	W12
	.byte		N18	, Fn1
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte			As1
	.byte	W12
	.byte		N11	, Ds2
	.byte	W12
	.byte		N05	, As2
	.byte	W06
	.byte		N18	, Ds3
	.byte	W18
	.byte		N10	, Ds2
	.byte	W12
	.byte			As1
	.byte	W12
	.byte		N05	, Fn2
	.byte	W06
	.byte		N17	, Dn3
	.byte	W18
	.byte		N12	, As1
	.byte	W12
	.byte		N10	, Cn2
	.byte	W12
	.byte		N04	, Gn2
	.byte	W06
	.byte		N16	, Gn3
	.byte	W18
	.byte		N11	, Cn2
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte		N06	, Gn2
	.byte	W06
	.byte		N18	, Ds3
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte		N09	, Fn1
	.byte	W12
	.byte		N05	, Fn2
	.byte	W06
	.byte		N16	, Cn3
	.byte	W18
	.byte		N10	, Fn1
	.byte	W12
	.byte			As1
	.byte	W12
	.byte		N05	, Fn2
	.byte	W06
	.byte		N16	, Dn3
	.byte	W18
	.byte		N12	, As1
	.byte	W12
	.byte		N15	, Ds3
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N32	
	.byte	W36
	.byte		N19	, Cs3
	.byte	W24
	.byte		N08	, Gs1
	.byte	W12
	.byte		N05	, Gs2
	.byte	W06
	.byte		N16	, Cn3
	.byte	W18
	.byte		N12	, Ds2
	.byte	W12
	.byte		N11	, Gs1
	.byte	W12
	.byte		N06	, Gs2
	.byte	W06
	.byte		N16	, Cn3
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
	.byte		N10	, Gn1
	.byte	W12
	.byte		N06	, Gn2
	.byte	W06
	.byte		N18	, As2
	.byte	W18
	.byte		N10	, Dn2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte		N05	, Gn2
	.byte	W06
	.byte		N18	, As2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte		N11	, Fn1
	.byte	W12
	.byte		N05	, Fn2
	.byte	W06
	.byte		N17	, Cn3
	.byte	W18
	.byte		N11	, Cn2
	.byte	W12
	.byte		N10	, Fn1
	.byte	W12
	.byte		N05	, Fn2
	.byte	W06
	.byte		N16	, Cn3
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte		N11	, As1
	.byte	W12
	.byte		N06	, As2
	.byte	W06
	.byte		N17	, Dn3
	.byte	W18
	.byte		N12	, Fn2
	.byte	W12
	.byte			Fn3
	.byte	W24
	.byte		N24	, Dn3
	.byte	W24
	.byte		N11	, Ds2
	.byte	W12
	.byte		N05	, As2
	.byte	W06
	.byte		N16	, Ds3
	.byte	W18
	.byte		N12	, Ds2
	.byte	W12
	.byte		N11	, As1
	.byte	W12
	.byte		N05	, Fn2
	.byte	W06
	.byte		N17	, Dn3
	.byte	W18
	.byte		N12	, As1
	.byte	W12
	.byte		N09	, Cn2
	.byte	W12
	.byte		N05	, Gn2
	.byte	W06
	.byte		N18	, Ds3
	.byte	W18
	.byte		N12	, Cn2
	.byte	W12
	.byte		N11	, Gs1
	.byte	W12
	.byte		N06	, Gn2
	.byte	W06
	.byte		N18	, Ds3
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte		N10	, Fn1
	.byte	W12
	.byte		N05	, Fn2
	.byte	W06
	.byte		N18	, Cn3
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte		N10	, As1
	.byte	W12
	.byte		N05	, Fn2
	.byte	W06
	.byte		N18	, Dn3
	.byte	W18
	.byte		N12	, As1
	.byte	W12
	.byte		N15	, Ds3
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N32	
	.byte	W36
	.byte		N23	, Cs3
	.byte	W24
	.byte		N10	, Gs1
	.byte	W12
	.byte		N05	, Gs2
	.byte	W06
	.byte		N18	, Ds3
	.byte	W18
	.byte		N12	, Ds2
	.byte	W12
	.byte		N10	, Gs1
	.byte	W12
	.byte		N06	, Gs2
	.byte	W06
	.byte		N18	, Ds3
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
	.byte		N10	, Gn1
	.byte	W12
	.byte		N05	, Gn2
	.byte	W06
	.byte		N18	, Dn3
	.byte	W18
	.byte		N12	, Dn2
	.byte	W12
	.byte		N11	, Cn2
	.byte	W12
	.byte		N06	, Gn2
	.byte	W06
	.byte		N18	, En3
	.byte	W18
	.byte		N12	, Cn2
	.byte	W12
	.byte	W96
song_0011_3_7:
	.byte	W06
	.byte		N06	, Ds3, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-35
	.byte		N12	, Gs2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W12
	.byte		N06	, Ds3
	.byte	W12
	.byte			Gs3
	.byte	W12
	.byte			Ds3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N12	, Gs2
	.byte	W12
	.byte	PEND
song_0011_3_8:
	.byte	W06
	.byte		N06	, Dn3, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Gn2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W12
	.byte		N06	, Dn3
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			Dn3
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Cn3
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N12	, Gn2
	.byte	W12
	.byte	PEND
	.byte	W06
	.byte		N06	, Ds3
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Gn2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W12
	.byte		N06	, Ds3
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Cn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, As2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N06	, Dn3
	.byte	W06
	.byte	W06
	.byte			Gn3
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte	W06
	.byte		c_v
	.byte		N06	, Ds3
	.byte	W06
	.byte		N04	, Gn2
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, As2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W12
	.byte		N06	, Ds2
	.byte	W06
	.byte		N12	, Ds3
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte	PATT	
		.word	song_0011_3_7
	.byte	PATT	
		.word	song_0011_3_8
	.byte	W06
	.byte		N06	, Ds3, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, An2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W12
	.byte		N06	, Ds3
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Cn3
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Dn3
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N06	, Ds3
	.byte	W06
	.byte	W06
	.byte			Dn3
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Cn3
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N06	, Dn3
	.byte	W60
	.byte	PATT	
		.word	song_0011_3_1
	.byte	PATT	
		.word	song_0011_3_2
	.byte	PATT	
		.word	song_0011_3_3
	.byte	PATT	
		.word	song_0011_3_4
	.byte	PATT	
		.word	song_0011_3_5
	.byte	PATT	
		.word	song_0011_3_6
	.byte	PATT	
		.word	song_0011_3_9
	.byte	PATT	
		.word	song_0011_3_10
	.byte	GOTO	
		.word	song_0011_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0011_4
song_0011_4:	@ 0x087D626B
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
song_0011_4_1:
	.byte		N08	, Ds2, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N06	, As1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Ds2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N18	, As1
	.byte	W18
	.byte		N06	, Cn2
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte	PEND
song_0011_4_2:
	.byte		N08	, Dn2, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N06	, As1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Dn2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Fn2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Dn2
	.byte	W06
	.byte		N12	, As1
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte	PEND
song_0011_4_3:
	.byte		N08	, Cn2, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N06	, Gn1
	.byte	W06
	.byte			As1
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Cn2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Gn2
	.byte	W06
	.byte		N01	, Cn2
	.byte	W06
	.byte		N18	, Gn1
	.byte	W18
	.byte		N06	, As1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte	PEND
song_0011_4_4:
	.byte		N08	, Fn1, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N06	, Gs1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte		N01	, Fn2
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	, Ds2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte	PEND
song_0011_4_5:
	.byte		N24	, As1, v127
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	, Gs1
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	PEND
song_0011_4_6:
	.byte		N24	, Gn1, v127
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	, Cn2
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	PEND
song_0011_4_13:
	.byte		N08	, Fn1, v127
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	, Cn2
	.byte	W06
	.byte		N18	
	.byte	W18
	.byte			Fn2
	.byte	W18
	.byte			Cn2
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte	PEND
song_0011_4_14:
	.byte		N24	, As1, v127
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N06	, Fn1
	.byte	W06
	.byte			Gn1
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N12	, Gs1
	.byte	W12
	.byte		N06	, An1
	.byte	W06
	.byte		N12	, As1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0011_4_1
	.byte	PATT	
		.word	song_0011_4_2
	.byte	PATT	
		.word	song_0011_4_3
	.byte	PATT	
		.word	song_0011_4_4
	.byte	PATT	
		.word	song_0011_4_5
	.byte	PATT	
		.word	song_0011_4_6
	.byte		N24	, Fn1, v127
	.byte	W24
	.byte		N01	, Cn2
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	, As1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N12	, Ds2
	.byte	W06
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	, As1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			Gn1
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N18	, Fn1
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte			As1
	.byte	W12
song_0011_4_7:
	.byte		N30	, Ds2, v127
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N30	, As1
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0011_4_8:
	.byte		N30	, Cn2, v127
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N18	, Gs1
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte	PEND
song_0011_4_9:
	.byte		N30	, Fn1, v127
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N30	, As1
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0011_4_10:
	.byte		N12	, Ds2, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N36	
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N12	, Gn1
	.byte	W12
	.byte	PEND
song_0011_4_11:
	.byte		N30	, Gs1, v127
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N30	
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte	PEND
	.byte		N30	, Gn1
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N18	
	.byte	W18
	.byte			Dn2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte		N30	, Fn1
	.byte	W36
	.byte		N08	, Cn2
	.byte	W12
	.byte		N30	, Fn1
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N30	, As1
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte	PATT	
		.word	song_0011_4_7
	.byte	PATT	
		.word	song_0011_4_8
	.byte	PATT	
		.word	song_0011_4_9
	.byte	PATT	
		.word	song_0011_4_10
	.byte	PATT	
		.word	song_0011_4_11
	.byte		N30	, Gn1, v127
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N30	, Cn2
	.byte	W36
	.byte		N08	, En1
	.byte	W12
	.byte		N06	, Fn1
	.byte	W06
	.byte			Gn1
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N18	, Gs1
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte		N06	, As1
	.byte	W06
	.byte			As2
	.byte	W06
	.byte		N01	, As1
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N18	, Gs1
	.byte	W18
	.byte			Ds2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	, Ds2
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
song_0011_4_12:
	.byte		N18	, Gn1, v127
	.byte	W18
	.byte			Dn2
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	, Dn2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte	PEND
	.byte		N18	, Fn1
	.byte	W18
	.byte			Cn2
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte			As1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	, Fn1
	.byte	W18
	.byte		N12	, As1
	.byte	W12
	.byte		N18	, Ds2
	.byte	W18
	.byte			As1
	.byte	W18
	.byte		N12	, Ds2
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N01	, Ds2
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte		N18	, Gs1
	.byte	W18
	.byte			Ds2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	, Ds2
	.byte	W18
	.byte		N06	, As1
	.byte	W06
	.byte			Gs1
	.byte	W06
	.byte	PATT	
		.word	song_0011_4_12
	.byte		N18	, Fn1, v127
	.byte	W18
	.byte			Cn2
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	, Cn2
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte		N18	, As1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte		N18	, Fn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte		N12	, As1
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte	PATT	
		.word	song_0011_4_1
	.byte	PATT	
		.word	song_0011_4_2
	.byte	PATT	
		.word	song_0011_4_3
	.byte	PATT	
		.word	song_0011_4_4
	.byte	PATT	
		.word	song_0011_4_5
	.byte	PATT	
		.word	song_0011_4_6
	.byte	PATT	
		.word	song_0011_4_13
	.byte	PATT	
		.word	song_0011_4_14
	.byte	GOTO	
		.word	song_0011_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0011_5
song_0011_5:	@ 0x087D64DA
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		N06	, Dn1, v127
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Dn1
	.byte	W12
song_0011_5_9:
	.byte		N06	, Cn1, v127
	.byte		N18	, Cs2, v100
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
song_0011_5_1:
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0011_5_1
	.byte	PATT	
		.word	song_0011_5_1
song_0011_5_2:
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0011_5_2
song_0011_5_7:
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0011_5_8:
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte		N03	, Dn1
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W12
	.byte	PEND
	.byte			Cn1
	.byte		N18	, An2, v100
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
song_0011_5_3:
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0011_5_3
	.byte	PATT	
		.word	song_0011_5_3
	.byte	PATT	
		.word	song_0011_5_3
	.byte	PATT	
		.word	song_0011_5_3
	.byte		N06	, Cn1, v127
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			An1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Cn2
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			An1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W12
	.byte			Cn1
	.byte		N22	, Cs2, v100
	.byte	W24
	.byte		N06	, Dn1, v127
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
song_0011_5_4:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0011_5_5:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte	PEND
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte		N20	, An2, v100
	.byte	W24
	.byte		N06	, Dn1, v127
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte	PATT	
		.word	song_0011_5_4
	.byte	PATT	
		.word	song_0011_5_4
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W23
	.byte		N01	
	.byte	W01
	.byte		N06	
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			Fn1
	.byte	W12
	.byte			Cn1
	.byte		N17	, Cs2, v100
	.byte	W18
	.byte		N06	, Dn1, v127
	.byte	W18
	.byte			Fn1
	.byte	W12
	.byte			Cn1
	.byte	W18
	.byte			Dn1
	.byte		N11	, An2, v100
	.byte	W12
	.byte		N06	, An1, v127
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte		N06	, An1
	.byte	W12
	.byte			Cn1
	.byte		N20	, Cs2, v100
	.byte	W24
	.byte		N06	, Dn1, v127
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W05
	.byte		N24	, An2, v100
	.byte	W01
	.byte	PATT	
		.word	song_0011_5_5
	.byte	PATT	
		.word	song_0011_5_4
	.byte		N06	, Dn1, v127
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte		N21	, Cs2, v100
	.byte	W18
	.byte		N06	, Cn1, v127
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
song_0011_5_6:
	.byte		N06	, Cn1, v127
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0011_5_6
	.byte	PATT	
		.word	song_0011_5_6
	.byte		N06	, Cn1, v127
	.byte		N19	, An2, v100
	.byte	W18
	.byte		N06	, Cn1, v127
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0011_5_6
	.byte	PATT	
		.word	song_0011_5_6
	.byte		N06	, Cn1, v127
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W05
	.byte		N01	, Dn1
	.byte	W01
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte			Cn2
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte		N21	, Cs2, v100
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0011_5_1
	.byte	PATT	
		.word	song_0011_5_1
	.byte	PATT	
		.word	song_0011_5_1
	.byte	PATT	
		.word	song_0011_5_2
	.byte	PATT	
		.word	song_0011_5_2
	.byte	PATT	
		.word	song_0011_5_7
	.byte	PATT	
		.word	song_0011_5_8
	.byte	GOTO	
		.word	song_0011_5_9
	.byte	FINE

	.align 2
	.global song_0011
song_0011:	@ 0x087D6754
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0011_1		@ track
	.word	song_0011_2		@ track
	.word	song_0011_3		@ track
	.word	song_0011_4		@ track
	.word	song_0011_5		@ track
