	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0033_1
song_0033_1:	@ 0x087DCC84
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 82
	.byte		N24	, Fs4, v127
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte			An4
	.byte	W24
song_0033_1_1:
	.byte		N12	, Bn4, v127
	.byte	W36
	.byte		N11	, Gs4
	.byte	W12
	.byte		N14	, Fs4
	.byte	W12
	.byte		N10	, En4
	.byte	W24
	.byte		N08	, Cn5
	.byte	W12
	.byte	W12
	.byte		N10	
	.byte	W24
	.byte		N09	, Gs4
	.byte	W12
	.byte		N13	, Fs4
	.byte	W12
	.byte		N09	, En4
	.byte	W36
	.byte		N12	, An4
	.byte	W24
	.byte		N17	, Gs4
	.byte	W24
	.byte		N14	, An4
	.byte	W12
	.byte		N08	, Gs4
	.byte	W12
	.byte		N15	, An4
	.byte	W12
	.byte		N08	, Gs4
	.byte	W12
	.byte	W12
	.byte		N14	, Fs4
	.byte	W36
	.byte		N13	
	.byte	W12
	.byte		N11	, Gs4
	.byte	W12
	.byte		N16	, An4
	.byte	W24
	.byte		N11	, Bn4
	.byte	W36
	.byte		N12	, Gs4
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte		N16	, En4
	.byte	W24
	.byte		N08	, Cn5
	.byte	W12
	.byte	W12
	.byte		N14	
	.byte	W24
	.byte		N10	, Gs4
	.byte	W12
	.byte		N15	, Fs4
	.byte	W12
	.byte		N13	, En4
	.byte	W36
	.byte		N16	, Gs4
	.byte	W24
	.byte		N22	, Fs4
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte		N08	, An4
	.byte	W12
	.byte		N36	
	.byte	W12
	.byte	W24
	.byte		N24	, Gs4
	.byte	W24
	.byte		N14	, En4
	.byte	W12
	.byte		N32	, Fs4
	.byte	W36
	.byte		TIE	, En4
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		N16	, Gs4
	.byte	W24
	.byte		N12	, Gn4
	.byte	W12
	.byte			Gs4
	.byte	W24
	.byte		N24	, Cn5
	.byte	W12
	.byte	W12
	.byte		N12	, Gs4
	.byte	W12
	.byte		N24	, Gs5
	.byte	W24
	.byte			Ds5
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N12	, Gn4
	.byte	W12
	.byte			Gs4
	.byte	W24
	.byte		N24	, Cs5
	.byte	W12
	.byte	W12
	.byte		N12	, Gs4
	.byte	W12
	.byte		N24	, Gs5
	.byte	W24
	.byte			En5
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte	W24
	.byte		N16	, An4
	.byte	W24
	.byte		N12	, Gs4
	.byte	W12
	.byte			An4
	.byte	W24
	.byte		N24	, Cs5
	.byte	W12
	.byte	W12
	.byte		N12	, An4
	.byte	W12
	.byte		N24	, An5
	.byte	W24
	.byte			Gs4
	.byte		N24	, En5
	.byte	W24
	.byte			An4
	.byte	W24
	.byte		N12	, Gs4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Gs4
	.byte	W12
	.byte		N84	, Fs4
	.byte	W60
	.byte	W24
	.byte		N24	, Bn5
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte		N48	, En4
	.byte	W48
	.byte		N36	, Cs5
	.byte	W36
	.byte		N60	
	.byte	W12
	.byte	W84
	.byte		N12	
	.byte	W12
	.byte		N16	, Bn4
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte		N60	, Gs4
	.byte	W12
	.byte	W84
	.byte		N12	
	.byte	W12
	.byte		N16	, An4
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte		N24	, Cs5
	.byte	W24
	.byte		N96	, Bn4
	.byte	W96
	.byte	W24
	.byte		N24	, Fs4
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte	GOTO	
		.word	song_0033_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0033_2
song_0033_2:	@ 0x087DCDA5
	.byte	KEYSH	, 0
	.byte	VOICE	, 14
	.byte	VOL	, v056
	.byte	PAN	, c_v
	.byte	W24
	.byte		N24	, Fs2, v127
	.byte	W24
	.byte			Gs2
	.byte	W24
	.byte			An2
	.byte	W24
song_0033_2_3:
	.byte		N10	, En1, v127
	.byte	W12
	.byte		N06	, Gs2
	.byte		N08	, Bn2
	.byte	W24
	.byte		N11	, En1
	.byte	W12
	.byte		N22	, Gs2
	.byte		N22	, Bn2
	.byte	W24
	.byte		N10	, En1
	.byte	W12
	.byte		N68	, Gs2
	.byte		N68	, Cn3
	.byte	W12
	.byte	W60
	.byte		N10	, En1
	.byte	W12
	.byte		N11	, Gs2
	.byte		N11	, Cn3
	.byte	W12
	.byte		N08	, En1
	.byte	W12
	.byte		N13	, An2
	.byte		N12	, Cs3
	.byte	W24
	.byte		N18	, An2
	.byte		N16	, Cs3
	.byte	W24
	.byte		N09	, Fs1
	.byte	W12
	.byte		N11	, An2
	.byte		N10	, Cs3
	.byte	W12
	.byte		N09	, Fs1
	.byte	W12
	.byte		N22	, An2
	.byte		N21	, Cs3
	.byte	W12
	.byte	W12
	.byte		N12	, Bn0
	.byte		N09	, An2
	.byte		N09	, Cs3
	.byte	W24
	.byte		N13	, Bn0
	.byte	W12
	.byte		N11	, An2
	.byte		N10	, Ds3
	.byte	W24
	.byte		N18	, An2
	.byte		N17	, Ds3
	.byte	W24
	.byte		N10	, Bn2
	.byte		N10	, En3
	.byte	W24
	.byte		N21	, Gs2
	.byte		N22	, Bn2
	.byte	W24
	.byte		N11	, En1
	.byte	W12
	.byte		N10	, Gs2
	.byte		N10	, Bn2
	.byte	W12
	.byte			En1
	.byte	W12
	.byte		N68	, Gs2
	.byte		N68	, Cn3
	.byte	W12
	.byte	W60
	.byte		N11	, En1
	.byte	W12
	.byte			Gs2
	.byte		N11	, Cn3
	.byte	W12
	.byte			En1
	.byte	W12
	.byte		N44	, An2
	.byte		N44	, Cs3
	.byte	W48
	.byte		N10	, Fs1
	.byte	W12
	.byte		N11	, An2
	.byte		N10	, Cs3
	.byte	W12
	.byte		N11	, Fs1
	.byte	W12
	.byte		N60	, An2
	.byte		N56	, Cs3
	.byte	W12
	.byte	W24
	.byte		N10	, Bn0
	.byte	W24
	.byte		N48	
	.byte	W12
	.byte		N24	, An2
	.byte		N24	, Ds3
	.byte	W36
	.byte		N44	, Bn2
	.byte		N44	, En3
	.byte	W48
	.byte		N09	, En1
	.byte	W12
	.byte		N11	, Bn2
	.byte		N12	, En3
	.byte	W12
	.byte		N11	, En1
	.byte	W12
	.byte		N32	, Cs2
	.byte		N02	, Cn3
	.byte	W02
	.byte		N32	, Cs3
	.byte	W10
	.byte	W24
	.byte		N23	, Bn1
	.byte		N24	, Bn2
	.byte	W24
	.byte		N23	, Gs1
	.byte		N22	, Gs2
	.byte	W24
	.byte			Bn1
	.byte		N24	, Bn2
	.byte	W24
	.byte		N22	, En1
	.byte	W24
	.byte		N24	, Gs2
	.byte		N23	, Bn2
	.byte	W24
	.byte		N11	, En1
	.byte	W12
	.byte		N16	, Gs2
	.byte		N17	, Bn2
	.byte	W24
	.byte		N36	
	.byte		N36	, En3
	.byte	W12
	.byte	W24
	.byte		N22	, Gs2
	.byte		N22	, Bn2
	.byte	W24
	.byte		N11	, En1
	.byte	W12
	.byte		N24	, Gs2
	.byte		N24	, Bn2
	.byte	W24
	.byte		N12	, Gs2
	.byte		N12	, Bn2
	.byte	W12
song_0033_2_1:
	.byte		N12	, Ds3, v127
	.byte		N12	, Fs3
	.byte	W72
	.byte			Ds3
	.byte		N12	, Fs3
	.byte	W12
	.byte			Ds3
	.byte		N12	, Fs3
	.byte	W12
	.byte	PEND
song_0033_2_2:
	.byte	W36
	.byte		N12	, Ds3, v127
	.byte		N12	, Fs3
	.byte	W24
	.byte			Ds3
	.byte		N12	, Fs3
	.byte	W24
	.byte			Ds3
	.byte		N12	, Fs3
	.byte	W12
	.byte	PEND
	.byte			Bn2
	.byte		N12	, En3
	.byte	W72
	.byte			Bn2
	.byte		N12	, En3
	.byte	W12
	.byte			Bn2
	.byte		N12	, En3
	.byte	W12
	.byte	W36
	.byte			Bn2
	.byte		N12	, En3
	.byte	W24
	.byte			Bn2
	.byte		N12	, En3
	.byte	W24
	.byte			Bn2
	.byte		N12	, En3
	.byte	W12
	.byte			Cs3
	.byte		N12	, En3
	.byte	W72
	.byte			Cs3
	.byte		N12	, En3
	.byte	W12
	.byte			Cs3
	.byte		N12	, En3
	.byte	W12
	.byte	W36
	.byte			Cs3
	.byte		N12	, En3
	.byte	W24
	.byte			Cs3
	.byte		N12	, En3
	.byte	W24
	.byte			Cs3
	.byte		N12	, En3
	.byte	W12
	.byte	PATT	
		.word	song_0033_2_1
	.byte	PATT	
		.word	song_0033_2_2
	.byte		N72	, Cs3, v127
	.byte		N72	, En3
	.byte	W84
	.byte		N60	, Ds3
	.byte		N60	, Fs3
	.byte	W12
	.byte	W48
	.byte		N08	, Ds3
	.byte		N08	, Fs3
	.byte	W24
	.byte		N24	, Ds3
	.byte		N24	, Fs3
	.byte	W24
	.byte		N72	, Ds3
	.byte		N72	, Fs3
	.byte	W84
	.byte		N60	, Cs3
	.byte		N60	, Fn3
	.byte	W12
	.byte	W48
	.byte		N08	, Cs3
	.byte		N08	, Fn3
	.byte	W24
	.byte		N24	, Cs3
	.byte		N24	, Fn3
	.byte	W24
	.byte		N72	, Cs3
	.byte		N72	, En3
	.byte	W84
	.byte		TIE	, Cs3
	.byte		TIE	, En3
	.byte	W12
	.byte	W96
	.byte		EOT	, Cs3
	.byte			En3
	.byte		N24	, Cs3
	.byte		N24	, En3
	.byte	W24
	.byte			Cs3
	.byte		N24	, En3
	.byte	W24
	.byte		N12	, Bn1
	.byte	W12
	.byte			Cs3
	.byte		N12	, En3
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte		TIE	, Ds3
	.byte		TIE	, Fs3
	.byte	W12
	.byte	W24
	.byte		N24	, Fs2
	.byte	W24
	.byte			Gs2
	.byte	W24
	.byte			An2
	.byte	W24
	.byte		EOT	, Ds3
	.byte			Fs3
	.byte	GOTO	
		.word	song_0033_2_3
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0033_3
song_0033_3:	@ 0x087DCF57
	.byte	KEYSH	, 0
	.byte	VOICE	, 2
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
	.byte		N24	, Bn1, v127
	.byte	W24
song_0033_3_1:
	.byte		N24	, En2, v127
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N24	, Bn1
	.byte	W36
	.byte		N08	, En2
	.byte	W12
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N08	, Gs1
	.byte	W12
	.byte		N24	, Fs1
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N08	, Fs2
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N16	, Cs2
	.byte	W12
	.byte		N08	, Bn1
	.byte	W12
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N16	
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte			En2
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N24	, Bn1
	.byte	W36
	.byte		N12	, En2
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N08	, Gs1
	.byte	W12
	.byte		N24	, Fs1
	.byte	W36
	.byte		N12	, Cs2
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N16	, Fs1
	.byte	W12
	.byte		N12	, Bn1
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte			En2
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	, Bn1
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N36	, Cs2
	.byte	W12
	.byte	W24
	.byte		N24	, Bn1
	.byte	W24
	.byte			Gs1
	.byte	W24
	.byte			Bn1
	.byte	W24
	.byte			En2
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	, Bn1
	.byte	W36
	.byte		N12	, En1
	.byte	W12
	.byte	W12
	.byte			En2
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	, Bn1
	.byte	W24
	.byte			En1
	.byte	W24
	.byte			Gs1
	.byte	W72
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	, Cs2
	.byte	W72
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	, An1
	.byte	W72
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	, Bn1
	.byte	W72
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	, An1
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N12	, Bn1
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte			An1
	.byte	W24
	.byte			Gs1
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N12	, Cs2
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte			Gs1
	.byte	W24
	.byte			An1
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N12	, Fs1
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Cs2
	.byte	W12
	.byte			Fs1
	.byte	W12
	.byte		N24	, Bn1
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N12	, Fs1
	.byte	W12
	.byte	W12
	.byte			Bn1
	.byte	W60
	.byte		N24	
	.byte	W24
	.byte	GOTO	
		.word	song_0033_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0033_4
song_0033_4:	@ 0x087DD072
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v069
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
	.byte		N08	, Bn4, v127
	.byte	W08
	.byte		N04	, Cn5
	.byte	W04
	.byte			Cs5
	.byte	W04
	.byte			Dn5
	.byte	W04
	.byte			Ds5
	.byte	W04
song_0033_4_1:
	.byte		TIE	, En5, v127
	.byte	W96
	.byte	W96
	.byte	W32
	.byte	W03
	.byte		EOT	
	.byte	W13
	.byte		N10	, An4
	.byte	W12
	.byte		N08	, Gs4
	.byte	W12
	.byte		N11	, An4
	.byte	W12
	.byte		N15	, Gs4
	.byte	W12
	.byte	W12
	.byte		N14	, Fs4
	.byte	W60
	.byte		N08	, Bn4
	.byte	W08
	.byte		N04	, Cn5
	.byte	W04
	.byte			Cs5
	.byte	W04
	.byte			Dn5
	.byte	W04
	.byte			Ds5
	.byte	W04
	.byte		TIE	, En5
	.byte	W96
	.byte	W84
	.byte	W01
	.byte		EOT	
	.byte	W11
	.byte		N16	, Gs4
	.byte	W24
	.byte		N22	, Fs4
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte		N08	, An4
	.byte	W12
	.byte		N32	, Cs5
	.byte	W12
	.byte	W24
	.byte		N24	, Bn4
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N32	
	.byte	W36
	.byte		TIE	, En5
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W48
	.byte		N24	, Gs4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte		N72	, En4
	.byte	W84
	.byte		TIE	, Ds4
	.byte	W12
	.byte	W96
	.byte		EOT	
	.byte		N72	, Fs4
	.byte	W84
	.byte		TIE	, Fn4
	.byte	W12
	.byte	W96
	.byte		EOT	
	.byte		N72	, En4
	.byte	W84
	.byte		N60	, Cs4
	.byte	W12
	.byte	W48
	.byte		N48	, En4
	.byte	W48
	.byte		N72	
	.byte	W84
	.byte		N84	, Fs4
	.byte	W12
	.byte	W72
	.byte		N08	, Bn4
	.byte	W08
	.byte		N04	, Cn5
	.byte	W04
	.byte			Cs5
	.byte	W04
	.byte			Dn5
	.byte	W04
	.byte			Ds5
	.byte	W04
	.byte	GOTO	
		.word	song_0033_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0033_5
song_0033_5:	@ 0x087DD112
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
	.byte		N06	, Cn1, v127
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
song_0033_5_7:
	.byte		N06	, Cn1, v127
	.byte		N19	, Cs2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
song_0033_5_1:
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte	PEND
song_0033_5_2:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0033_5_1
	.byte	PATT	
		.word	song_0033_5_2
	.byte	PATT	
		.word	song_0033_5_1
	.byte	PATT	
		.word	song_0033_5_2
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte		N21	, Cs2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte		N20	, Cs2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0033_5_1
	.byte	PATT	
		.word	song_0033_5_2
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
song_0033_5_3:
	.byte		N06	, Dn1, v127
	.byte	W72
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte	PEND
song_0033_5_4:
	.byte	W36
	.byte		N06	, Dn1, v127
	.byte	W24
	.byte		N06	
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0033_5_3
	.byte	PATT	
		.word	song_0033_5_4
	.byte	PATT	
		.word	song_0033_5_3
	.byte	PATT	
		.word	song_0033_5_4
	.byte	PATT	
		.word	song_0033_5_3
	.byte	PATT	
		.word	song_0033_5_4
song_0033_5_5:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0033_5_6:
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0033_5_5
	.byte	PATT	
		.word	song_0033_5_6
	.byte	PATT	
		.word	song_0033_5_5
	.byte	PATT	
		.word	song_0033_5_6
	.byte	PATT	
		.word	song_0033_5_5
	.byte	PATT	
		.word	song_0033_5_6
	.byte	GOTO	
		.word	song_0033_5_7
	.byte	FINE

	.align 2
	.global song_0033
song_0033:	@ 0x087DD214
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0033_1		@ track
	.word	song_0033_2		@ track
	.word	song_0033_3		@ track
	.word	song_0033_4		@ track
	.word	song_0033_5		@ track
