	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0015_1
song_0015_1:	@ 0x087D7A24
	.byte	KEYSH	, 0
	.byte	TEMPO	, 30
	.byte	VOICE	, 3
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
song_0015_1_1:
	.byte	W72
	.byte		N12	, Gn4, v127
	.byte	W12
	.byte		N09	, Dn5
	.byte	W12
	.byte		TIE	
	.byte	W96
	.byte	W03
	.byte		EOT	
	.byte	W44
	.byte	W01
	.byte		N17	, An4
	.byte	W15
	.byte			As4
	.byte	W18
	.byte		N14	, Cn5
	.byte	W15
	.byte		N72	, An4
	.byte	W72
	.byte		N22	, Fn4
	.byte	W24
	.byte	W48
	.byte		N16	, Gn4
	.byte	W16
	.byte			An4
	.byte	W16
	.byte		N15	, As4
	.byte	W16
	.byte		N60	
	.byte	W72
	.byte		N13	, Cn5
	.byte	W12
	.byte		N07	, As4
	.byte	W06
	.byte		N17	, Dn5
	.byte	W06
	.byte	W12
	.byte		N06	, Cn5
	.byte	W06
	.byte		TIE	, Dn5
	.byte	W78
	.byte	W44
	.byte		EOT	
	.byte	W52
	.byte	W72
	.byte		N11	, Gn4
	.byte	W12
	.byte		N08	, Dn5
	.byte	W12
	.byte		TIE	
	.byte	W96
	.byte	W03
	.byte		EOT	
	.byte	W44
	.byte	W01
	.byte		N16	, An4
	.byte	W15
	.byte			As4
	.byte	W18
	.byte		N14	, Cn5
	.byte	W15
	.byte		N76	, Fn5
	.byte	W78
	.byte		N08	, Dn5
	.byte	W12
	.byte		N07	, Cn5
	.byte	W06
	.byte		N05	, Dn5
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte		N92	, Dn5
	.byte	W84
	.byte	W36
	.byte		N04	, An4
	.byte	W03
	.byte		N06	, As4
	.byte	W06
	.byte		N28	, Gn4
	.byte	W24
	.byte	W03
	.byte		N14	, An4
	.byte	W12
	.byte		N13	, As4
	.byte	W12
	.byte		TIE	, An4
	.byte	W96
	.byte	W56
	.byte		EOT	
	.byte	W40
	.byte	GOTO	
		.word	song_0015_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0015_2
song_0015_2:	@ 0x087D7AAC
	.byte	KEYSH	, 0
	.byte	VOICE	, 6
	.byte	VOL	, v069
	.byte	PAN	, c_v
	.byte	W06
song_0015_2_1:
	.byte		N05	, Dn5, v100
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W12
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	GOTO	
		.word	song_0015_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0015_3
song_0015_3:	@ 0x087D7CBB
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v050
	.byte	PAN	, c_v
	.byte	W06
song_0015_3_1:
	.byte		TIE	, Dn4, v127
	.byte		TIE	, As4
	.byte	W96
	.byte	PEND
	.byte	W76
	.byte		EOT	, Dn4
	.byte			As4
	.byte	W20
song_0015_3_2:
	.byte		TIE	, Cn4, v127
	.byte		TIE	, An4
	.byte	W96
	.byte	PEND
	.byte	W72
	.byte	W03
	.byte		EOT	, Cn4
	.byte			An4
	.byte	W21
	.byte		TIE	, Ds4
	.byte		TIE	, As4
	.byte	W96
	.byte	W72
	.byte	W01
	.byte		EOT	, Ds4
	.byte			As4
	.byte	W23
	.byte		N96	, Dn4
	.byte		N96	, An4
	.byte	W96
	.byte		N24	, An3
	.byte	W24
	.byte		N22	, As3
	.byte	W24
	.byte			Cn4
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte	PATT	
		.word	song_0015_3_1
	.byte	W72
	.byte	W01
	.byte		EOT	, As4
	.byte	W01
	.byte			Dn4
	.byte	W22
	.byte	PATT	
		.word	song_0015_3_2
	.byte	W36
	.byte	W01
	.byte		EOT	, An4
	.byte	W11
	.byte		N30	, Fn4, v127
	.byte	W30
	.byte	W01
	.byte		EOT	, Cn4
	.byte	W17
	.byte		TIE	, Ds4
	.byte		N92	, As4
	.byte	W96
	.byte		N68	, Dn5
	.byte	W68
	.byte	W01
	.byte		EOT	, Ds4
	.byte	W24
	.byte	W03
	.byte		TIE	, Fn4
	.byte		TIE	, Cn5
	.byte	W96
	.byte	W44
	.byte	W02
	.byte		EOT	
	.byte	W02
	.byte		N22	, Dn5
	.byte	W21
	.byte		EOT	, Fn4
	.byte	W24
	.byte	W03
	.byte	GOTO	
		.word	song_0015_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0015_4
song_0015_4:	@ 0x087D7D38
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
song_0015_4_1:
	.byte		TIE	, Ds2, v127
	.byte	W96
	.byte	W76
	.byte	W01
	.byte		EOT	
	.byte	W19
	.byte		TIE	, Dn2
	.byte	W96
	.byte	W72
	.byte	W03
	.byte		EOT	
	.byte	W21
	.byte		TIE	, Cn2
	.byte	W96
	.byte	W72
	.byte		EOT	
	.byte	W24
	.byte		TIE	, As1
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		EOT	
	.byte	W01
	.byte		TIE	, Ds2
	.byte	W96
	.byte	W72
	.byte	W03
	.byte		EOT	
	.byte	W21
	.byte		TIE	, Dn2
	.byte	W96
	.byte	W66
	.byte	W01
	.byte		EOT	
	.byte	W28
	.byte	W01
	.byte		TIE	, Cn2
	.byte	W96
	.byte	W66
	.byte		EOT	
	.byte	W30
	.byte		TIE	, As1
	.byte	W96
	.byte	W66
	.byte		EOT	
	.byte	W30
	.byte	GOTO	
		.word	song_0015_4_1
	.byte	FINE

	.align 2
	.global song_0015
song_0015:	@ 0x087D7D80
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	188		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0015_1		@ track
	.word	song_0015_2		@ track
	.word	song_0015_3		@ track
	.word	song_0015_4		@ track
