	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0005_1
song_0005_1:	@ 0x087D3398
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
	.byte	TEMPO	, 66
	.byte		N48	, Fs4, v127
	.byte	W48
	.byte			Gs4
	.byte	W48
	.byte			An4
	.byte	W48
song_0005_1_1:
	.byte		N12	, Bn4, v127
	.byte	W40
	.byte		N11	, Gs4
	.byte	W08
	.byte		N14	, Fs4
	.byte	W16
	.byte		N10	, En4
	.byte	W24
	.byte		N08	, Cn5
	.byte	W08
	.byte	W16
	.byte		N10	
	.byte	W24
	.byte		N09	, Gs4
	.byte	W08
	.byte		N13	, Fs4
	.byte	W16
	.byte		N09	, En4
	.byte	W32
	.byte		N12	, An4
	.byte	W24
	.byte		N17	, Gs4
	.byte	W24
	.byte		N14	, An4
	.byte	W16
	.byte		N08	, Gs4
	.byte	W08
	.byte		N15	, An4
	.byte	W16
	.byte		N11	, Gs4
	.byte	W08
	.byte	W16
	.byte		N14	, Fs4
	.byte	W32
	.byte		N13	
	.byte	W16
	.byte		N11	, Gs4
	.byte	W08
	.byte		N16	, An4
	.byte	W24
	.byte		N11	, Bn4
	.byte	W40
	.byte		N12	, Gs4
	.byte	W08
	.byte			Fs4
	.byte	W16
	.byte		N16	, En4
	.byte	W24
	.byte		N13	, Cn5
	.byte	W08
	.byte	W16
	.byte		N14	
	.byte	W24
	.byte		N10	, Gs4
	.byte	W08
	.byte		N15	, Fs4
	.byte	W16
	.byte		N13	, En4
	.byte	W32
	.byte		N16	, Gs4
	.byte	W24
	.byte		N22	, Fs4
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte		N08	, An4
	.byte	W16
	.byte		N32	
	.byte	W08
	.byte	W24
	.byte		N24	, Gs4
	.byte	W24
	.byte		N14	, En4
	.byte	W16
	.byte		N32	, Fs4
	.byte	W32
	.byte		TIE	, En4
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W48
	.byte	W96
	.byte	W48
	.byte		N17	
	.byte	W16
	.byte		N10	, Fs4
	.byte	W08
	.byte			Gs4
	.byte	W16
	.byte		N28	
	.byte	W08
	.byte	W72
	.byte		N15	, En4
	.byte	W16
	.byte		N17	, An4
	.byte	W08
	.byte	W16
	.byte		N10	
	.byte	W08
	.byte		N24	, Gs4
	.byte	W24
	.byte		N13	, Fs4
	.byte	W16
	.byte		N32	, Gs4
	.byte	W32
	.byte		N23	, Fs4
	.byte	W24
	.byte		N14	, Gs4
	.byte	W16
	.byte		N54	, En4
	.byte	W56
	.byte	W24
	.byte		N20	
	.byte	W24
	.byte		N24	, Fs4
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte		N22	, Bn4
	.byte	W24
	.byte		N24	, An4
	.byte	W48
	.byte		N13	, Gs4
	.byte	W16
	.byte		N17	, An4
	.byte	W08
	.byte	W16
	.byte		N10	
	.byte	W08
	.byte		N24	, Gs4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte		N07	, Gs4
	.byte	W16
	.byte		N21	
	.byte	W08
	.byte	W16
	.byte		N10	, En4
	.byte	W08
	.byte		N18	, Gs4
	.byte	W16
	.byte		N40	, Fs4
	.byte	W56
	.byte	W48
	.byte		N16	, Gs4
	.byte	W24
	.byte		N20	, An4
	.byte	W24
	.byte		N10	, Bn4
	.byte	W24
	.byte		N14	
	.byte	W24
	.byte		N15	
	.byte	W24
	.byte		N13	
	.byte	W16
	.byte		N15	, Dn5
	.byte	W08
	.byte	W16
	.byte		N10	
	.byte	W08
	.byte		N16	, Cs5
	.byte	W24
	.byte		N24	, Bn4
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte		N23	, Bn4
	.byte	W24
	.byte		N13	, An4
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte		N15	, Gs4
	.byte	W16
	.byte		N24	, Bn4
	.byte	W08
	.byte	W16
	.byte		N06	, An4
	.byte	W08
	.byte		N22	
	.byte	W64
	.byte		N08	
	.byte	W08
	.byte		N12	, Gs4
	.byte	W48
	.byte		N13	, An4
	.byte	W48
	.byte		N11	, Fs4
	.byte	W24
	.byte		N13	, En4
	.byte	W24
	.byte		N15	, Ds4
	.byte	W16
	.byte		N32	, Fs4
	.byte	W32
	.byte		N96	, En4
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0005_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0005_2
song_0005_2:	@ 0x087D34C0
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte	W48
	.byte	W24
	.byte		N24	, Bn2, v127
	.byte	W24
	.byte			Bn3
	.byte	W24
	.byte			An3
	.byte	W24
song_0005_2_1:
	.byte		N72	, Gs3, v127
	.byte	W72
	.byte		N16	, Fs3
	.byte	W16
	.byte		N80	, En3
	.byte	W08
	.byte	PEND
	.byte	W72
	.byte		N24	, Ds3
	.byte	W24
	.byte		N60	, Cs3
	.byte	W72
	.byte		N16	
	.byte	W16
	.byte		N08	, Bn2
	.byte	W08
	.byte	W16
	.byte		N24	
	.byte	W32
	.byte		N16	, Bn3
	.byte	W24
	.byte			An3
	.byte	W24
	.byte	PATT	
		.word	song_0005_2_1
	.byte	W72
	.byte		N24	, Ds3, v127
	.byte	W24
	.byte		N60	, Cs3
	.byte	W96
	.byte	W96
	.byte	W88
	.byte		N32	
	.byte	W08
	.byte	W24
	.byte		N24	, Bn2
	.byte	W24
	.byte			Gs2
	.byte	W24
	.byte			Bn2
	.byte	W24
	.byte		N72	, Gs2
	.byte		N72	, En3
	.byte	W88
	.byte		TIE	, Gs2
	.byte		TIE	, Dn3
	.byte	W08
	.byte	W96
	.byte		EOT	, Gs2
	.byte			Dn3
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		N24	, Gs2
	.byte	W24
	.byte			Cs3
	.byte	W24
	.byte		N16	, En3
	.byte	W16
	.byte		N08	, Gs3
	.byte	W08
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N24	, Fs3
	.byte	W24
	.byte			En3
	.byte	W24
	.byte			Ds3
	.byte	W24
	.byte		N72	, Cs3
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		N24	, An2
	.byte	W24
	.byte			Cs3
	.byte	W24
	.byte		N16	, En3
	.byte	W16
	.byte		N48	, Ds3
	.byte	W08
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N16	
	.byte	W48
	.byte			Cs3
	.byte	W48
	.byte		N16	
	.byte	W24
	.byte			En3
	.byte	W24
	.byte		N12	, Ds3
	.byte	W16
	.byte		N32	, An3
	.byte	W32
	.byte		N96	, Gs3
	.byte	W96
	.byte	W64
	.byte		N08	, Bn2
	.byte	W08
	.byte		N16	, Bn3
	.byte	W16
	.byte		N08	, An3
	.byte	W08
	.byte	GOTO	
		.word	song_0005_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0005_3
song_0005_3:	@ 0x087D3567
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W06
	.byte	W48
	.byte	W72
	.byte		N24	, Bn1, v127
	.byte	W24
song_0005_3_1:
	.byte		N24	, En2, v127
	.byte	W40
	.byte		N08	
	.byte	W08
	.byte		N24	, Bn1
	.byte	W40
	.byte		N13	, En2
	.byte	W08
	.byte	PEND
song_0005_3_2:
	.byte	W16
	.byte		N13	, En2, v127
	.byte	W24
	.byte		N08	
	.byte	W08
	.byte		N24	
	.byte	W40
	.byte		N08	, Gs1
	.byte	W08
	.byte	PEND
	.byte		N24	, Fs1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, Fs2
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N16	, Cs2
	.byte	W16
	.byte		N13	, Bn1
	.byte	W08
	.byte	W16
	.byte		N13	
	.byte	W24
	.byte		N08	
	.byte	W08
	.byte		N16	
	.byte	W16
	.byte		N01	, Cs2
	.byte	W08
	.byte		N24	, Bn1
	.byte	W24
	.byte	PATT	
		.word	song_0005_3_1
	.byte	PATT	
		.word	song_0005_3_2
	.byte		N24	, Fs1, v127
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, Cs2
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N16	, Fs1
	.byte	W16
	.byte		N13	, Bn1
	.byte	W08
	.byte	W16
	.byte		N13	
	.byte	W24
	.byte		N08	
	.byte	W08
	.byte		N16	
	.byte	W16
	.byte		N32	
	.byte	W32
	.byte		N24	, En2
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N24	, Bn1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N32	, Cs2
	.byte	W08
	.byte	W24
	.byte		N24	, Bn1
	.byte	W24
	.byte			Gs1
	.byte	W24
	.byte			Bn1
	.byte	W24
	.byte			En2
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N24	, Bn1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N32	, En2
	.byte	W08
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte			Gs1
	.byte	W24
	.byte			An1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, En2
	.byte	W08
	.byte		N16	
	.byte	W16
	.byte		N08	, An1
	.byte	W08
	.byte		N16	, Gs1
	.byte	W16
	.byte		N08	, Fs1
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N16	, Gs1
	.byte	W16
	.byte		N24	, Gs2
	.byte	W24
	.byte		N08	, Gs1
	.byte	W08
	.byte		N24	, Cs2
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, Gs1
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N01	, Cs2
	.byte	W16
	.byte		N24	, Bn1
	.byte	W08
	.byte	W16
	.byte		N08	, Gs1
	.byte	W08
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N24	, Bn1
	.byte	W24
	.byte			An1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, En2
	.byte	W08
	.byte		N16	
	.byte	W16
	.byte		N08	, An1
	.byte	W08
	.byte		N16	, Gs1
	.byte	W16
	.byte		N32	, Fs1
	.byte	W08
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, Cs2
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, Fs1
	.byte	W08
	.byte		N24	, Bn1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, Fs1
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N24	, Bn1
	.byte	W08
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte			An1
	.byte	W24
	.byte			Gs1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, Ds2
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N16	, Gs1
	.byte	W16
	.byte		N24	, Cs2
	.byte	W08
	.byte	W16
	.byte		N08	, Gs1
	.byte	W08
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N24	, Cs2
	.byte	W24
	.byte			Fs1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	, Cs2
	.byte	W08
	.byte		N16	
	.byte	W16
	.byte		N08	, Fs1
	.byte	W08
	.byte		N16	, Gs1
	.byte	W16
	.byte		N24	, An1
	.byte	W08
	.byte	W16
	.byte		N08	, En2
	.byte	W08
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N24	, An1
	.byte	W24
	.byte		N16	, Gs1
	.byte	W16
	.byte		N01	
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N16	, Cs2
	.byte	W16
	.byte		N01	
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N16	, Fs1
	.byte	W16
	.byte		N01	
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte		N16	, Bn1
	.byte	W16
	.byte		N01	
	.byte	W08
	.byte		N24	
	.byte	W24
	.byte			En2
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N24	, Bn1
	.byte	W24
	.byte		N01	
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte		N16	, En2
	.byte	W16
	.byte		N01	
	.byte	W08
	.byte		N12	, Bn1
	.byte	W24
	.byte			Cs2
	.byte	W24
	.byte			Ds2
	.byte	W24
	.byte	GOTO	
		.word	song_0005_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0005_4
song_0005_4:	@ 0x087D36F0
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v-64
	.byte	W06
	.byte	W48
	.byte	W96
song_0005_4_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W88
	.byte		N32	, Cs5, v127
	.byte	W08
	.byte	W24
	.byte		N24	, Bn4
	.byte	W24
	.byte		N08	
	.byte	W16
	.byte		N32	
	.byte	W32
	.byte		N96	, En5
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W48
	.byte		N16	, Ds4
	.byte	W24
	.byte			Cs4
	.byte	W24
	.byte		N40	, Bn3
	.byte	W48
	.byte		N24	, Bn4
	.byte	W24
	.byte		N12	, An4
	.byte	W16
	.byte		N68	, Gs4
	.byte	W08
	.byte	W72
	.byte		N24	, Gs3
	.byte	W24
	.byte		N40	, An3
	.byte	W48
	.byte		N24	, An4
	.byte	W24
	.byte		N12	, Gs4
	.byte	W16
	.byte		TIE	, Fs4
	.byte	W08
	.byte	W96
	.byte		EOT	
	.byte	W24
	.byte		N24	, Bn3
	.byte	W40
	.byte		N32	, Cs4
	.byte	W32
	.byte	W24
	.byte		N13	
	.byte	W40
	.byte		N32	, Ds4
	.byte	W32
	.byte		N96	, En4
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0005_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0005_5
song_0005_5:	@ 0x087D3756
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte	W48
	.byte	W40
	.byte		N08	, Cn1, v127
	.byte	W08
	.byte		N07	
	.byte	W08
	.byte		N08	, Dn1
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte		N08	
	.byte	W08
song_0005_5_3:
	.byte		N08	, Cn1, v127
	.byte		N20	, Cs2
	.byte	W24
	.byte		N08	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W16
	.byte			Cn1
	.byte	W08
song_0005_5_1:
	.byte	W16
	.byte		N08	, Cn1, v127
	.byte	W08
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W16
	.byte		N08	
	.byte	W08
	.byte			Dn1
	.byte	W24
	.byte	PEND
song_0005_5_2:
	.byte		N08	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W16
	.byte			Cn1
	.byte	W08
	.byte	PEND
	.byte	PATT	
		.word	song_0005_5_1
	.byte	PATT	
		.word	song_0005_5_2
	.byte	PATT	
		.word	song_0005_5_1
	.byte	PATT	
		.word	song_0005_5_2
	.byte	W16
	.byte		N08	, Cn1, v127
	.byte	W08
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W16
	.byte		N08	
	.byte		N15	, Cs2
	.byte	W16
	.byte		N08	, Dn1
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte			Cn1
	.byte		N24	, An2
	.byte	W24
	.byte		N08	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W16
	.byte			Cn1
	.byte	W08
	.byte	PATT	
		.word	song_0005_5_1
	.byte		N08	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W16
	.byte			Cn1
	.byte		N22	, Cs2
	.byte	W08
	.byte	W16
	.byte		N08	, Cn1
	.byte	W08
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte		N08	, Cn2
	.byte	W16
	.byte			Cn1
	.byte	W08
	.byte			Fn1
	.byte	W24
	.byte			Cn1
	.byte		N22	, An2
	.byte	W24
	.byte		N08	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W16
	.byte			Cn1
	.byte	W08
	.byte	PATT	
		.word	song_0005_5_1
	.byte	PATT	
		.word	song_0005_5_2
	.byte	PATT	
		.word	song_0005_5_1
	.byte	PATT	
		.word	song_0005_5_2
	.byte	PATT	
		.word	song_0005_5_1
	.byte	PATT	
		.word	song_0005_5_2
	.byte	PATT	
		.word	song_0005_5_1
	.byte	PATT	
		.word	song_0005_5_2
	.byte	PATT	
		.word	song_0005_5_1
	.byte	PATT	
		.word	song_0005_5_2
	.byte	PATT	
		.word	song_0005_5_1
	.byte	PATT	
		.word	song_0005_5_2
	.byte	PATT	
		.word	song_0005_5_2
	.byte	PATT	
		.word	song_0005_5_2
	.byte		N08	, Dn1, v127
	.byte	W16
	.byte			Cn1
	.byte	W08
	.byte			An1
	.byte	W16
	.byte			Cn1
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte			Dn1
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte	GOTO	
		.word	song_0005_5_3
	.byte	FINE

	.align 2
	.global song_0005
song_0005:	@ 0x087D3860
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0005_1		@ track
	.word	song_0005_2		@ track
	.word	song_0005_3		@ track
	.word	song_0005_4		@ track
	.word	song_0005_5		@ track
