	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0044_1
song_0044_1:	@ 0x087E0454
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 98
	.byte		N06	, An5, v127
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte	TEMPO	, 86
	.byte		N06	
	.byte	W24
	.byte			Gs5
	.byte	W24
	.byte	TEMPO	, 98
	.byte			Gn5
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte	TEMPO	, 86
	.byte		N06	
	.byte	W24
	.byte			Fs5
	.byte	W24
	.byte			En5
	.byte	W72
song_0044_1_6:
	.byte	TEMPO	, 80
	.byte	W24
	.byte	TEMPO	, 65
	.byte	W24
	.byte	TEMPO	, 36
	.byte	W24
	.byte	PEND
song_0044_1_7:
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
song_0044_1_1:
	.byte	TEMPO	, 98
	.byte		N08	, En4, v127
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte	TEMPO	, 86
	.byte			Bn4
	.byte	W12
	.byte			En5
	.byte	W12
	.byte			Gn5
	.byte	W24
	.byte	PEND
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
song_0044_1_2:
	.byte		N08	, En4, v127
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Cs5
	.byte	W12
	.byte			En5
	.byte	W12
	.byte			An5
	.byte	W24
	.byte	PEND
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
song_0044_1_3:
	.byte		N12	, Gn5, v127
	.byte	W12
	.byte			An5
	.byte	W12
	.byte			Bn5
	.byte	W24
	.byte			Gn5
	.byte	W24
	.byte	PEND
song_0044_1_4:
	.byte		N12	, En5, v127
	.byte	W12
	.byte			Fs5
	.byte	W12
	.byte			Gn5
	.byte	W24
	.byte			An5
	.byte	W24
	.byte	PEND
song_0044_1_5:
	.byte		N16	, Dn6, v127
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N16	
	.byte	W24
	.byte	PEND
	.byte	TEMPO	, 80
	.byte	W24
	.byte	TEMPO	, 76
	.byte	W24
	.byte	TEMPO	, 59
	.byte	W24
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	PATT	
		.word	song_0044_1_1
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	PATT	
		.word	song_0044_1_2
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	TEMPO	, 98
	.byte	W24
	.byte	TEMPO	, 86
	.byte	W48
	.byte	PATT	
		.word	song_0044_1_3
	.byte	PATT	
		.word	song_0044_1_4
	.byte	PATT	
		.word	song_0044_1_5
	.byte	PATT	
		.word	song_0044_1_6
	.byte	GOTO	
		.word	song_0044_1_7
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0044_2
song_0044_2:	@ 0x087E0567
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		N16	, En3, v127
	.byte	W72
	.byte		N16	
	.byte	W72
	.byte		N16	
	.byte	W72
	.byte	W72
song_0044_2_3:
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		N72	, Dn3, v127
	.byte	W72
	.byte			En3
	.byte	W72
	.byte			Gn3
	.byte	W72
song_0044_2_1:
	.byte		N36	, An3, v127
	.byte	W36
	.byte		N12	, Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte	PEND
	.byte		N16	, Fs3
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		N48	, Gn3
	.byte	W72
	.byte			An3
	.byte	W72
song_0044_2_2:
	.byte		N16	, Dn4, v127
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N16	
	.byte	W24
	.byte	PEND
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		N72	, Dn3
	.byte	W72
	.byte			En3
	.byte	W72
	.byte			Gn3
	.byte	W72
	.byte	PATT	
		.word	song_0044_2_1
	.byte		N16	, Fs3, v127
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		N48	, Gn3
	.byte	W72
	.byte			An3
	.byte	W72
	.byte	PATT	
		.word	song_0044_2_2
	.byte	W72
	.byte	GOTO	
		.word	song_0044_2_3
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0044_3
song_0044_3:	@ 0x087E05CE
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		N04	, An4, v127
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte		N04	, Gn4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte		N12	, En4
	.byte	W72
	.byte	W72
song_0044_3_1:
	.byte		N24	, Fs4, v127
	.byte	W60
	.byte		N12	, Fn4
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0044_3_1
song_0044_3_3:
	.byte		N24	, Fs4, v127
	.byte	W48
	.byte			Bn4
	.byte	W24
	.byte	PEND
song_0044_3_4:
	.byte		N48	, An4, v127
	.byte	W48
	.byte		N24	, Fs4
	.byte	W24
	.byte	PEND
song_0044_3_2:
	.byte		N24	, Fs4, v127
	.byte	W24
	.byte			En4
	.byte	W36
	.byte		N12	, Bn3
	.byte	W12
	.byte	PEND
	.byte		N72	, En4
	.byte	W72
	.byte	PATT	
		.word	song_0044_3_2
	.byte		N72	, En4, v127
	.byte	W72
	.byte	PATT	
		.word	song_0044_3_1
	.byte	PATT	
		.word	song_0044_3_1
song_0044_3_5:
	.byte		N24	, Fs4, v127
	.byte	W48
	.byte			Dn5
	.byte	W24
	.byte	PEND
song_0044_3_6:
	.byte		N24	, Cs5, v127
	.byte	W24
	.byte			Bn4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte	PEND
song_0044_3_7:
	.byte		N12	, Gn4, v127
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Bn4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte	PEND
song_0044_3_8:
	.byte		N12	, En4, v127
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte			Gn4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte	PEND
song_0044_3_9:
	.byte		N24	, Dn4, v127
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte	PEND
	.byte	W72
	.byte	PATT	
		.word	song_0044_3_1
	.byte	PATT	
		.word	song_0044_3_1
	.byte	PATT	
		.word	song_0044_3_3
	.byte	PATT	
		.word	song_0044_3_4
	.byte	PATT	
		.word	song_0044_3_2
	.byte		N72	, En4, v127
	.byte	W72
	.byte	PATT	
		.word	song_0044_3_2
	.byte		N72	, En4, v127
	.byte	W72
	.byte	PATT	
		.word	song_0044_3_1
	.byte	PATT	
		.word	song_0044_3_1
	.byte	PATT	
		.word	song_0044_3_5
	.byte	PATT	
		.word	song_0044_3_6
	.byte	PATT	
		.word	song_0044_3_7
	.byte	PATT	
		.word	song_0044_3_8
	.byte	PATT	
		.word	song_0044_3_9
	.byte	W72
	.byte	GOTO	
		.word	song_0044_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0044_4
song_0044_4:	@ 0x087E06AA
	.byte	KEYSH	, 0
	.byte	VOICE	, 19
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		N24	, An1, v127
	.byte	W72
	.byte		N24	
	.byte	W72
	.byte		N12	, En2
	.byte	W24
	.byte			Cs2
	.byte	W24
	.byte			Bn1
	.byte	W24
song_0044_4_8:
	.byte		N12	, An1, v127
	.byte	W24
	.byte			Bn1
	.byte	W24
	.byte			Cs2
	.byte	W24
	.byte	PEND
song_0044_4_1:
	.byte		N24	, Dn2, v127
	.byte	W24
	.byte		N04	, An2
	.byte		N04	, Dn3
	.byte	W24
	.byte			An2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0044_4_1
	.byte	PATT	
		.word	song_0044_4_1
	.byte	PATT	
		.word	song_0044_4_1
song_0044_4_2:
	.byte		N24	, En2, v127
	.byte	W24
	.byte		N04	, Bn2
	.byte		N04	, En3
	.byte	W24
	.byte			Bn2
	.byte		N04	, En3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0044_4_2
song_0044_4_3:
	.byte		N24	, An1, v127
	.byte	W24
	.byte		N04	, An2
	.byte		N04	, Dn3
	.byte	W24
	.byte			An2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
song_0044_4_4:
	.byte		N24	, An1, v127
	.byte	W24
	.byte			Bn1
	.byte		N04	, An2
	.byte		N04	, Cs3
	.byte	W24
	.byte		N24	, Cs2
	.byte		N04	, An2
	.byte		N04	, Cs3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0044_4_1
song_0044_4_5:
	.byte		N24	, Cn2, v127
	.byte	W24
	.byte		N04	, An2
	.byte		N04	, Dn3
	.byte	W24
	.byte			An2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
song_0044_4_6:
	.byte		N24	, Bn1, v127
	.byte	W24
	.byte		N04	, An2
	.byte		N04	, Dn3
	.byte	W24
	.byte			An2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0044_4_3
	.byte		N24	, Gn1, v127
	.byte	W72
	.byte			An1
	.byte	W72
song_0044_4_7:
	.byte		N36	, Dn2, v127
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte	PEND
	.byte			An1
	.byte	W24
	.byte			Bn1
	.byte	W24
	.byte			Cs2
	.byte	W24
	.byte	PATT	
		.word	song_0044_4_1
	.byte	PATT	
		.word	song_0044_4_1
	.byte	PATT	
		.word	song_0044_4_1
	.byte	PATT	
		.word	song_0044_4_1
	.byte	PATT	
		.word	song_0044_4_2
	.byte	PATT	
		.word	song_0044_4_2
	.byte	PATT	
		.word	song_0044_4_3
	.byte	PATT	
		.word	song_0044_4_4
	.byte	PATT	
		.word	song_0044_4_1
	.byte	PATT	
		.word	song_0044_4_5
	.byte	PATT	
		.word	song_0044_4_6
	.byte	PATT	
		.word	song_0044_4_3
	.byte	W72
	.byte	W72
	.byte	PATT	
		.word	song_0044_4_7
	.byte	PATT	
		.word	song_0044_4_8
	.byte	GOTO	
		.word	song_0044_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0044_5
song_0044_5:	@ 0x087E07A2
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v069
	.byte	PAN	, c_v
	.byte	W24
	.byte		N12	, Cn5, v127
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte		N16	
	.byte	W24
	.byte		N18	
	.byte	W24
	.byte		N12	, Cn5
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte		N14	
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N18	
	.byte	W72
	.byte	W72
song_0044_5_2:
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		N20	, Dn5, v127
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N15	
	.byte	W24
	.byte	W72
song_0044_5_1:
	.byte		N24	, Cn5, v127
	.byte	W24
	.byte			Dn5
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte	PATT	
		.word	song_0044_5_1
	.byte		N24	, Bn2, v127
	.byte	W72
	.byte		N24	
	.byte	W72
	.byte		N32	
	.byte	W36
	.byte		N12	, Dn5
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte	W72
	.byte	GOTO	
		.word	song_0044_5_2
	.byte	FINE

	.align 2
	.global song_0044
song_0044:	@ 0x087E082C
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0044_1		@ track
	.word	song_0044_2		@ track
	.word	song_0044_3		@ track
	.word	song_0044_4		@ track
	.word	song_0044_5		@ track
