	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0052_1
song_0052_1:	@ 0x087E2998
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 1
	.byte	VOL	, v120
	.byte	PAN	, c_v
	.byte	W24
song_0052_1_1:
	.byte	TEMPO	, 45
	.byte		N11	, En2, v127
	.byte		N11	, Bn2
	.byte		N12	, Dn3
	.byte		N11	, En3
	.byte	W14
	.byte		N10	, Bn2
	.byte	W11
	.byte			Dn3
	.byte	W11
	.byte		N11	, En3
	.byte	W12
	.byte			Bn3
	.byte	W13
	.byte			En2
	.byte	W13
	.byte		N12	, Dn2
	.byte	W01
	.byte		N10	, Dn3
	.byte		N10	, Fs3
	.byte		N10	, Bn3
	.byte	W13
	.byte		N13	, Dn3
	.byte	W08
	.byte	W06
	.byte			Fs3
	.byte	W13
	.byte		N16	, Bn2
	.byte	W16
	.byte		N32	, Bn3
	.byte	W36
	.byte	W02
	.byte		N10	, Cn2
	.byte		N11	, Cn3
	.byte		N12	, Fs3
	.byte	W12
	.byte		N11	, An2
	.byte	W11
	.byte	W01
	.byte			Cn3
	.byte	W12
	.byte		N08	, Gn3
	.byte	W13
	.byte		N10	, An3
	.byte	W13
	.byte			Cn2
	.byte	W16
	.byte			Bn1
	.byte		N11	, Bn2
	.byte		N12	, Dn3
	.byte		N12	, Fs3
	.byte	W12
	.byte		N11	, Fs2
	.byte	W12
	.byte		N12	, An2
	.byte	W13
	.byte		N14	, Bn2
	.byte	W04
	.byte	W12
	.byte		N16	, Dn3
	.byte	W16
	.byte			Fs3
	.byte	W21
	.byte		N10	, An1
	.byte	W01
	.byte		N09	, Gn2
	.byte		N10	, Cn3
	.byte		N10	, En3
	.byte	W11
	.byte		N13	, Gn2
	.byte	W12
	.byte		N08	, Fs3
	.byte	W11
	.byte		N09	, Gn2
	.byte	W12
	.byte		N10	, Gn3
	.byte	W12
	.byte		N12	, An1
	.byte	W14
	.byte		N10	, Dn2
	.byte	W01
	.byte		N09	, Cn3
	.byte		N10	, Fs3
	.byte		N10	, An3
	.byte	W13
	.byte		N11	, Cn3
	.byte	W13
	.byte			Dn3
	.byte	W12
	.byte		N08	, Fs3
	.byte	W14
	.byte		N13	, Cn3
	.byte		N12	, Dn3
	.byte		N13	, Fs3
	.byte		N13	, An3
	.byte	W14
	.byte		N14	, Dn2
	.byte	W03
	.byte	W11
	.byte		N13	, Bn3
	.byte	W01
	.byte		N12	, Gn2
	.byte		N12	, Dn3
	.byte		N12	, Fs3
	.byte	W13
	.byte		N10	, Gn1
	.byte	W13
	.byte		N11	, Dn2
	.byte	W13
	.byte			Dn3
	.byte		N11	, Fs3
	.byte		N13	, An3
	.byte	W01
	.byte		N10	, Gn2
	.byte	W13
	.byte			Gn3
	.byte	W13
	.byte		N12	, An3
	.byte	W14
	.byte			Bn1
	.byte		N12	, En3
	.byte		N12	, Fs3
	.byte		N12	, Bn3
	.byte	W04
	.byte	W10
	.byte		N14	, Fs2
	.byte	W16
	.byte		N13	, Bn2
	.byte	W16
	.byte		N15	, En3
	.byte	W21
	.byte		N52	, Ds3
	.byte		N52	, Fs3
	.byte	W32
	.byte	W01
	.byte	W24
	.byte	W03
	.byte		N12	, En2
	.byte		N11	, Gn2
	.byte		N12	, Bn2
	.byte		N12	, Dn3
	.byte		N13	, En3
	.byte	W14
	.byte		N10	, Gn2
	.byte	W12
	.byte		N11	, Dn3
	.byte	W12
	.byte			En3
	.byte	W13
	.byte		N18	, Bn3
	.byte	W14
	.byte		N11	, En2
	.byte	W04
	.byte	W09
	.byte		N13	, Dn2
	.byte		N12	, Dn3
	.byte		N12	, Fs3
	.byte		N13	, Bn3
	.byte	W14
	.byte		N11	, Dn3
	.byte	W13
	.byte		N10	, Fs3
	.byte	W11
	.byte		N12	, Dn3
	.byte	W14
	.byte		N15	, An3
	.byte	W17
	.byte		N14	, Bn3
	.byte	W18
	.byte	W03
	.byte		N11	, Cn2
	.byte		N11	, Cn3
	.byte	W01
	.byte		N10	, An2
	.byte		N11	, Fs3
	.byte	W12
	.byte		N10	, An2
	.byte	W12
	.byte		N09	, Cn3
	.byte	W12
	.byte		N10	, Gn3
	.byte	W12
	.byte		N09	, An3
	.byte	W11
	.byte		N11	, Cn2
	.byte	W14
	.byte			Bn1
	.byte		N12	, Bn2
	.byte		N12	, Dn3
	.byte		N12	, Fs3
	.byte	W14
	.byte		N11	, An2
	.byte	W05
	.byte	W08
	.byte		N13	, Bn2
	.byte	W13
	.byte			Dn3
	.byte	W15
	.byte		N12	, Fs3
	.byte	W17
	.byte		N10	, Dn3
	.byte	W16
	.byte		N09	, An1
	.byte		N09	, Gn2
	.byte		N09	, En3
	.byte	W01
	.byte			Cn3
	.byte	W11
	.byte		N11	, Gn2
	.byte	W12
	.byte		N09	, Fs3
	.byte	W03
	.byte	W09
	.byte			Gn2
	.byte	W12
	.byte		N10	, Gn3
	.byte	W13
	.byte		N13	, An1
	.byte	W15
	.byte		N11	, Bn1
	.byte		N11	, An2
	.byte		N11	, Dn3
	.byte		N11	, Fs3
	.byte	W13
	.byte		N10	, An2
	.byte	W14
	.byte		N21	
	.byte		N22	, En3
	.byte	W20
	.byte	W05
	.byte		N14	, An2
	.byte		N13	, Dn3
	.byte	W14
	.byte		N16	, Bn1
	.byte	W18
	.byte		N11	, Cn2
	.byte		N11	, Gn2
	.byte		N11	, Cn3
	.byte		N11	, Dn3
	.byte		N11	, En3
	.byte	W14
	.byte		N10	, Gn2
	.byte	W12
	.byte		N09	, Cn3
	.byte	W11
	.byte		N10	, En3
	.byte	W12
	.byte		N11	, Bn3
	.byte	W10
	.byte	W02
	.byte			Cn2
	.byte	W12
	.byte		N10	, Dn2
	.byte		N09	, Dn3
	.byte		N09	, Fs3
	.byte		N10	, Bn3
	.byte	W12
	.byte		N11	, Dn3
	.byte	W11
	.byte			Fs3
	.byte	W12
	.byte			Dn3
	.byte	W13
	.byte		N10	, Bn3
	.byte	W10
	.byte		N14	, Dn2
	.byte	W16
	.byte		N09	, Ds2
	.byte		N09	, Bn2
	.byte		N10	, Ds3
	.byte		N09	, Fs3
	.byte	W08
	.byte	W04
	.byte		N10	, Bn2
	.byte	W12
	.byte		N06	, Fs3
	.byte	W12
	.byte			Bn2
	.byte		N06	, Gn3
	.byte	W13
	.byte		N09	, Bn2
	.byte		N09	, An3
	.byte	W10
	.byte		N12	, Ds2
	.byte	W13
	.byte		N09	, En2
	.byte	W01
	.byte			Bn2
	.byte		N08	, En3
	.byte		N08	, Gn3
	.byte	W11
	.byte		N09	, Bn2
	.byte	W13
	.byte		N09	
	.byte		N09	, Fs3
	.byte	W07
	.byte	W05
	.byte			Bn2
	.byte	W13
	.byte		N10	, Dn2
	.byte		N09	, Bn2
	.byte		N09	, En3
	.byte		N10	, Gn3
	.byte	W12
	.byte		N08	, Bn2
	.byte	W13
	.byte		N09	, Cn2
	.byte		N09	, Cn3
	.byte		N09	, En3
	.byte		N09	, Gn3
	.byte		N09	, Bn3
	.byte	W11
	.byte		N11	, Cn3
	.byte	W13
	.byte			En3
	.byte	W11
	.byte		N10	, Gn3
	.byte	W15
	.byte		N11	
	.byte		N11	, Bn3
	.byte		N12	, En4
	.byte	W03
	.byte	W10
	.byte		N11	, Gn3
	.byte	W13
	.byte		N10	, Fs3
	.byte	W01
	.byte		N09	, Bn1
	.byte		N09	, An3
	.byte		N09	, Bn3
	.byte		N10	, Dn4
	.byte	W11
	.byte		N11	, Fs2
	.byte	W13
	.byte		N10	, Bn2
	.byte	W11
	.byte		N11	, Dn3
	.byte	W13
	.byte		N12	, Fs3
	.byte	W13
	.byte		N10	, Bn3
	.byte	W11
	.byte	W03
	.byte			En3
	.byte	W01
	.byte			An1
	.byte		N10	, Cn3
	.byte		N10	, Gn3
	.byte		N10	, Bn3
	.byte	W12
	.byte		N13	, Cn3
	.byte	W14
	.byte		N11	, En3
	.byte		N12	, An3
	.byte	W12
	.byte		N11	, Cn3
	.byte	W13
	.byte		N12	
	.byte		N12	, En3
	.byte		N12	, Gn3
	.byte	W14
	.byte		N14	, An1
	.byte	W14
	.byte		N11	, Bn1
	.byte		N10	, En3
	.byte		N11	, Fs3
	.byte		N12	, An3
	.byte		N11	, Bn3
	.byte	W13
	.byte		N12	, En3
	.byte	W14
	.byte		N10	, Fs3
	.byte	W12
	.byte		N12	, An3
	.byte	W15
	.byte			Bn3
	.byte	W14
	.byte		N11	, En3
	.byte	W20
	.byte		N92	, Bn1
	.byte		TIE	, Ds3
	.byte		TIE	, Fs3
	.byte		TIE	, Bn3
	.byte	W21
	.byte	W72
	.byte	W02
	.byte		N76	, Bn2
	.byte	W22
	.byte	W54
	.byte		EOT	, Ds3
	.byte			Fs3
	.byte			Bn3
	.byte	W18
	.byte	GOTO	
		.word	song_0052_1_1
	.byte	FINE

	.align 2
	.global song_0052
song_0052:	@ 0x087E2BF8
	.byte	1		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0052_1		@ track
