	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0025_1
song_0025_1:	@ 0x087DA6F8
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 4
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 64
	.byte	W12
	.byte		N14	, An3, v116
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N12	, En4
	.byte	W12
song_0025_1_1:
	.byte		N05	, Dn4, v116
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N24	, Cs4
	.byte	W24
	.byte		N06	, Dn4
	.byte	W12
	.byte		N24	, En4
	.byte	W12
	.byte	W12
	.byte		N14	, Dn4
	.byte	W12
	.byte		N12	, Cs4
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte		N40	, Cs4
	.byte	W48
	.byte		N16	
	.byte	W15
	.byte		N07	, Dn4
	.byte	W06
	.byte		N03	, Cs4
	.byte	W03
	.byte		N10	, Bn3
	.byte	W12
	.byte		N84	
	.byte	W12
	.byte	W96
	.byte		N05	, Dn4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N24	, Cs4
	.byte	W24
	.byte		N04	, Dn4
	.byte	W12
	.byte		N24	, En4
	.byte	W12
	.byte	W12
	.byte		N13	, Dn4
	.byte	W12
	.byte		N11	, Cs4
	.byte	W24
	.byte		N22	
	.byte	W24
	.byte		N21	, Dn4
	.byte	W24
	.byte		N32	, En4
	.byte	W48
	.byte		N14	, Cs4
	.byte	W12
	.byte		N11	, Dn4
	.byte	W12
	.byte		N04	, En4
	.byte	W12
	.byte		N60	, Fs4
	.byte	W12
	.byte	W84
	.byte		N12	, Bn3
	.byte	W12
	.byte		N03	, Fs4
	.byte	W12
	.byte		N03	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N04	, En4
	.byte	W10
	.byte		N02	, Fs4
	.byte	W02
	.byte		N36	, Gn4
	.byte	W12
	.byte	W24
	.byte		N24	, Fs4
	.byte	W24
	.byte			En4
	.byte	W24
	.byte		N22	, Fs4
	.byte	W24
	.byte		N04	, En4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N03	
	.byte	W12
	.byte		N22	
	.byte	W24
	.byte		N07	, Dn4
	.byte	W10
	.byte		N04	, Fn4
	.byte	W02
	.byte		N32	, Fs4
	.byte	W12
	.byte	W24
	.byte		N28	, En4
	.byte	W24
	.byte		N23	, Dn4
	.byte	W24
	.byte		N20	, En4
	.byte	W24
	.byte		N32	, Dn4
	.byte	W36
	.byte		N23	, Bn3
	.byte	W24
	.byte		N13	, Cs4
	.byte	W12
	.byte		N04	, Dn4
	.byte	W12
	.byte		N40	, An3
	.byte	W12
	.byte	W24
	.byte		N09	, En4
	.byte	W12
	.byte		N36	, Dn4
	.byte	W36
	.byte			Cs4
	.byte	W24
	.byte	W12
	.byte		N68	, Bn3
	.byte	W68
	.byte	W02
	.byte		N02	, Cs4
	.byte	W02
	.byte		N20	, Dn4
	.byte	W12
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N10	
	.byte	W24
	.byte		N24	, Cs4
	.byte	W24
	.byte		N18	, Dn4
	.byte	W24
	.byte		TIE	
	.byte	W96
	.byte	W68
	.byte	W01
	.byte		EOT	
	.byte		N06	, As3
	.byte	W06
	.byte		N13	, Bn3
	.byte	W09
	.byte		N92	, An3
	.byte	W12
	.byte	W84
	.byte		N36	, Gn3
	.byte	W12
	.byte	W96
	.byte	W24
	.byte		N20	, An3
	.byte	W24
	.byte		N07	
	.byte	W12
	.byte		N13	
	.byte	W24
	.byte		N36	, As3
	.byte	W12
	.byte	W36
	.byte		N28	
	.byte	W24
	.byte		N14	, Bn3
	.byte	W12
	.byte		N11	, Cs4
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte		N12	, Bn3
	.byte	W12
	.byte		TIE	, Dn4
	.byte	W60
	.byte	W44
	.byte	W01
	.byte		EOT	
	.byte	W48
	.byte	W03
	.byte		N24	, Bn3
	.byte	W24
	.byte		N15	, Cs4
	.byte	W12
	.byte		N11	, Dn4
	.byte	W24
	.byte		N24	, Bn3
	.byte	W24
	.byte		N48	, An3
	.byte	W12
	.byte	W36
	.byte		N40	, Fs3
	.byte	W60
	.byte		N24	, Bn3
	.byte	W24
	.byte		N13	, Cs4
	.byte	W12
	.byte		N17	, Dn4
	.byte	W24
	.byte		N24	, Bn3
	.byte	W21
	.byte		N03	, Fn4
	.byte	W03
	.byte		N23	, Fs4
	.byte	W12
	.byte	W12
	.byte		N14	, En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N12	, En4
	.byte	W24
	.byte		N13	, Cs4
	.byte	W12
	.byte		N12	, Bn3
	.byte	W12
	.byte		N13	, Cs4
	.byte	W12
	.byte		N30	, An3
	.byte	W36
	.byte		N30	
	.byte	W36
	.byte		N14	
	.byte	W12
	.byte		N36	, As3
	.byte	W12
	.byte	W36
	.byte		N28	
	.byte	W24
	.byte		N13	, Bn3
	.byte	W12
	.byte		N18	, Cs4
	.byte	W24
	.byte		N16	
	.byte	W18
	.byte		N07	, Dn4
	.byte	W03
	.byte		N05	, Cs4
	.byte	W06
	.byte		N13	, Bn3
	.byte	W09
	.byte		TIE	, Dn4
	.byte	W60
	.byte	W68
	.byte	W02
	.byte		EOT	
	.byte	W24
	.byte	W02
	.byte		N24	, Bn3
	.byte	W24
	.byte		N04	, Fs4
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N15	, En4
	.byte	W12
	.byte		N06	, Dn4
	.byte	W12
	.byte		N24	, Cs4
	.byte	W12
	.byte	W12
	.byte		N12	, Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		N24	, Dn4
	.byte	W24
	.byte		N07	, En4
	.byte	W06
	.byte		N05	, Dn4
	.byte	W03
	.byte		N30	, Cs4
	.byte	W24
	.byte	W03
	.byte	W12
	.byte		N13	, Bn3
	.byte	W12
	.byte		N11	, Dn4
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte		N12	, Cs4
	.byte	W12
	.byte		N05	, Dn4
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N14	, An3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N13	, Dn4
	.byte	W12
	.byte		N11	, En4
	.byte	W12
	.byte	GOTO	
		.word	song_0025_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0025_2
song_0025_2:	@ 0x087DA8B5
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v100
	.byte	PAN	, c_v
	.byte	W24
	.byte	W72
song_0025_2_1:
	.byte		N24	, Gn1, v127
	.byte	W36
	.byte		N08	, Dn2
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N08	, Gn1
	.byte	W12
	.byte	PEND
song_0025_2_2:
	.byte	W12
	.byte		N12	, Gn1, v127
	.byte	W24
	.byte		N08	, Dn2
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte			Gn1
	.byte	W24
	.byte	PEND
song_0025_2_3:
	.byte		N24	, Fs1, v127
	.byte	W36
	.byte		N08	, Cs2
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N12	, Fs1
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte	PEND
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Cs2
	.byte	W12
	.byte			Ds2
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	, Bn1
	.byte	W12
	.byte		N24	, An1
	.byte	W24
	.byte	PATT	
		.word	song_0025_2_1
	.byte	PATT	
		.word	song_0025_2_2
	.byte	PATT	
		.word	song_0025_2_3
	.byte	W12
	.byte		N12	, Bn1, v127
	.byte	W12
	.byte			Cs2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	, Bn1
	.byte	W12
	.byte		N24	, An1
	.byte	W24
	.byte	PATT	
		.word	song_0025_2_1
	.byte	PATT	
		.word	song_0025_2_2
	.byte	PATT	
		.word	song_0025_2_3
	.byte	W12
	.byte		N12	, Bn1, v127
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	, An1
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte			Gn1
	.byte	W36
	.byte		N08	, Dn2
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N12	, Gn1
	.byte	W12
	.byte		N20	, Fs1
	.byte	W12
	.byte	W12
	.byte		N12	, Cs2
	.byte	W12
	.byte			Fs1
	.byte	W12
	.byte			Bn1
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	, An1
	.byte	W24
	.byte			Gn1
	.byte	W36
	.byte		N08	, Dn2
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N12	, Gn1
	.byte	W12
	.byte		N20	, An1
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N48	
	.byte	W48
song_0025_2_4:
	.byte		N24	, Dn2, v127
	.byte	W36
	.byte		N08	, An1
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N12	, Dn2
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte	PEND
song_0025_2_5:
	.byte	W12
	.byte		N12	, Dn2, v127
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte			An1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0025_2_4
	.byte	PATT	
		.word	song_0025_2_5
song_0025_2_6:
	.byte		N24	, Dn2, v127
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			An1
	.byte	W24
	.byte		N36	, Fs1
	.byte	W12
	.byte	PEND
song_0025_2_7:
	.byte	W24
	.byte		N01	, Fs1, v127
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	, Cs2
	.byte	W24
	.byte		N22	, Fs1
	.byte	W24
	.byte	PEND
song_0025_2_8:
	.byte		N24	, Bn1, v127
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N11	, Fs2
	.byte	W12
	.byte		N12	, Bn1
	.byte	W24
	.byte		N36	, Dn2
	.byte	W12
	.byte	PEND
song_0025_2_9:
	.byte	W24
	.byte		N01	, Dn2, v127
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	, An1
	.byte	W24
	.byte		N22	, Fs1
	.byte	W24
	.byte	PEND
	.byte		N24	, Gn1
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N11	, Bn1
	.byte	W12
	.byte		N12	, Dn2
	.byte	W24
	.byte		N36	, Fs1
	.byte	W12
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N22	, Cs2
	.byte	W24
	.byte			Fs1
	.byte	W24
	.byte		N24	, En2
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N01	, An1
	.byte	W12
	.byte		N24	
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte	PATT	
		.word	song_0025_2_6
	.byte	PATT	
		.word	song_0025_2_7
	.byte	PATT	
		.word	song_0025_2_8
	.byte	PATT	
		.word	song_0025_2_9
	.byte		N24	, Gn1, v127
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N36	, An1
	.byte	W36
	.byte		N12	, Gn1
	.byte	W12
	.byte		N36	, Fs1
	.byte	W12
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N36	, Bn1
	.byte	W36
	.byte		N24	
	.byte	W24
	.byte			En2
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	, An1
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N24	, Dn2
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N12	, An1
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Cs2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte		N11	, En2
	.byte	W12
	.byte	GOTO	
		.word	song_0025_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0025_3
song_0025_3:	@ 0x087DAA45
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
	.byte	W72
song_0025_3_1:
	.byte	W12
	.byte		N04	, Bn3, v116
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte			Cs4
	.byte	W12
	.byte	PEND
song_0025_3_2:
	.byte	W48
	.byte		N24	, Cs3, v116
	.byte	W24
	.byte			Dn3
	.byte	W24
	.byte	PEND
song_0025_3_3:
	.byte	W12
	.byte		N04	, An3, v116
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte			Bn3
	.byte	W12
	.byte	PEND
	.byte	W96
	.byte	PATT	
		.word	song_0025_3_1
	.byte	PATT	
		.word	song_0025_3_2
	.byte	PATT	
		.word	song_0025_3_3
	.byte	W96
	.byte	W12
	.byte		N04	, Bn3, v116
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte			Dn4
	.byte	W12
	.byte	W96
	.byte	PATT	
		.word	song_0025_3_3
	.byte	W96
	.byte	PATT	
		.word	song_0025_3_1
	.byte	W12
	.byte		N04	, Cs4, v116
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N04	, Bn3
	.byte	W12
	.byte		N12	
	.byte	W36
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N48	
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W60
	.byte		N12	, Cs4
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N72	, An3
	.byte	W84
	.byte		N54	, As3
	.byte	W12
	.byte	W42
	.byte		N02	, Bn3
	.byte	W02
	.byte			Cs4
	.byte	W02
	.byte			Dn4
	.byte	W02
	.byte		N48	, En4
	.byte	W48
	.byte		N24	
	.byte	W24
	.byte		N12	, Dn4
	.byte	W12
	.byte		TIE	, Fs4
	.byte	W60
	.byte	W48
	.byte		EOT	
	.byte		N12	, An4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte		N36	, Bn4
	.byte	W36
	.byte		N24	, Fs4
	.byte	W24
	.byte		N12	, En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		N60	, Fs4
	.byte	W60
	.byte		N48	, Gn4
	.byte	W48
	.byte		N24	, An4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N36	, Fs4
	.byte	W36
	.byte		N12	, An3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N11	, En4
	.byte	W12
	.byte	GOTO	
		.word	song_0025_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0025_4
song_0025_4:	@ 0x087DAB25
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
	.byte		N06	, An1, v127
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W12
song_0025_4_1:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0025_4_2:
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0025_4_1
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte	PATT	
		.word	song_0025_4_1
	.byte	PATT	
		.word	song_0025_4_2
	.byte	PATT	
		.word	song_0025_4_1
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0025_4_1
	.byte	PATT	
		.word	song_0025_4_2
	.byte	PATT	
		.word	song_0025_4_1
	.byte	PATT	
		.word	song_0025_4_2
	.byte	PATT	
		.word	song_0025_4_1
	.byte	PATT	
		.word	song_0025_4_2
	.byte	PATT	
		.word	song_0025_4_1
	.byte	W12
	.byte		N06	, Dn1, v127
	.byte	W12
	.byte			Cn1
	.byte		N06	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W48
song_0025_4_3:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0025_4_4:
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0025_4_3
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N12	, An1
	.byte	W12
	.byte		N06	, Dn1
	.byte	W12
	.byte		N12	, Fn1
	.byte	W12
	.byte	PATT	
		.word	song_0025_4_3
	.byte	PATT	
		.word	song_0025_4_4
	.byte	PATT	
		.word	song_0025_4_3
	.byte	PATT	
		.word	song_0025_4_4
	.byte	PATT	
		.word	song_0025_4_3
	.byte	PATT	
		.word	song_0025_4_4
	.byte	PATT	
		.word	song_0025_4_3
	.byte	PATT	
		.word	song_0025_4_4
	.byte	PATT	
		.word	song_0025_4_3
	.byte	PATT	
		.word	song_0025_4_4
	.byte	PATT	
		.word	song_0025_4_3
	.byte	W12
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte		N06	, Cn1
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte		N06	, An1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N11	, Fn1
	.byte	W12
	.byte	GOTO	
		.word	song_0025_4_1
	.byte	FINE

	.align 2
	.global song_0025
song_0025:	@ 0x087DAC6C
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0025_1		@ track
	.word	song_0025_2		@ track
	.word	song_0025_3		@ track
	.word	song_0025_4		@ track
