	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0045_1
song_0045_1:	@ 0x087E0848
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
song_0045_1_1:
	.byte	TEMPO	, 41
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W90
	.byte		N06	, An3, v112
	.byte	W06
	.byte		N76	, En4
	.byte	W84
	.byte		N07	, Dn4
	.byte	W06
	.byte		N02	, Cs4
	.byte	W05
	.byte	BEND	, c_v-19
	.byte	W01
	.byte		c_v-26
	.byte		N13	, En4
	.byte	W01
	.byte	BEND	, c_v-24
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N01	, Dn4
	.byte	W02
	.byte			Cn4
	.byte	W02
	.byte			An3
	.byte	W02
	.byte			Gn3
	.byte	W72
	.byte	W01
	.byte	BEND	, c_v-9
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-22
	.byte		N42	, En4
	.byte	W01
	.byte	BEND	, c_v-13
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W42
	.byte		c_v-9
	.byte	W01
	.byte		c_v-20
	.byte	W02
	.byte		c_v-16
	.byte		N06	
	.byte	W01
	.byte	BEND	, c_v-5
	.byte	W01
	.byte		c_v
	.byte	W04
	.byte		N03	, An4
	.byte	W08
	.byte	BEND	, c_v-5
	.byte	W01
	.byte		c_v-12
	.byte	W02
	.byte		c_v-12
	.byte	W01
	.byte		c_v-5
	.byte		N05	, Gn4
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte		N06	, En4
	.byte	W06
	.byte		N03	, Dn4
	.byte	W06
	.byte		N13	, En4
	.byte	W06
	.byte	W03
	.byte		N03	, Dn4
	.byte	W03
	.byte		N02	, Cn4
	.byte	W02
	.byte		N03	, Bn3
	.byte	W02
	.byte		N02	, An3
	.byte	W02
	.byte			Gn3
	.byte	W84
	.byte	W12
	.byte		N05	, An3
	.byte	W06
	.byte		N02	, Cn4
	.byte	W06
	.byte		N07	
	.byte	W06
	.byte		N03	, An3
	.byte	W10
	.byte	BEND	, c_v-6
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-19
	.byte		N14	, En4
	.byte	W02
	.byte	BEND	, c_v-16
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-3
	.byte	W01
	.byte		c_v
	.byte	W13
	.byte		N07	, Dn4
	.byte	W06
	.byte		N03	, Cn4
	.byte	W06
	.byte		N06	, Dn4
	.byte	W06
	.byte		N08	, En4
	.byte	W13
	.byte	BEND	, c_v-4
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		N06	, An4
	.byte	W01
	.byte	BEND	, c_v-39
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-17
	.byte	W01
	.byte		c_v-3
	.byte	W01
	.byte		c_v
	.byte		N04	, Gn4
	.byte	W12
	.byte		N36	, En4
	.byte	W66
	.byte		N07	, Bn3
	.byte	W06
	.byte		N06	, Cn4
	.byte	W06
	.byte		N16	, An3
	.byte	W18
	.byte		N32	, En4
	.byte	W42
	.byte		N04	, Dn4
	.byte	W12
	.byte		N12	, Cn4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N48	, An3
	.byte	W90
	.byte		N05	
	.byte	W06
	.byte		N80	, En4
	.byte	W84
	.byte		N07	, Dn4
	.byte	W06
	.byte		N03	, Cs4
	.byte	W06
	.byte		N12	, En4
	.byte	W12
	.byte		N03	, Dn4
	.byte	W02
	.byte			Cn4
	.byte	W02
	.byte		N02	, Bn3
	.byte	W02
	.byte			An3
	.byte	W03
	.byte		N01	, Gn3
	.byte	W03
	.byte			En3
	.byte	W66
	.byte		N02	, An3
	.byte	W06
	.byte		N32	, En4
	.byte	W48
	.byte		N07	
	.byte	W06
	.byte		N05	, An4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte		N06	, En4
	.byte	W06
	.byte		N04	, Dn4
	.byte	W06
	.byte		N15	, En4
	.byte	W06
	.byte	W06
	.byte		N03	, Dn4
	.byte	W03
	.byte		N02	, Cn4
	.byte	W03
	.byte			Bn3
	.byte	W02
	.byte		N01	, An3
	.byte	W02
	.byte			Gn3
	.byte	W80
	.byte	W12
	.byte		N06	, An3
	.byte	W06
	.byte		N03	, Cn4
	.byte	W06
	.byte		N07	
	.byte	W06
	.byte		N04	, An3
	.byte	W12
	.byte		N17	, En4
	.byte	W18
	.byte		N07	, Dn4
	.byte	W06
	.byte		N04	, Cn4
	.byte	W06
	.byte		N07	, Dn4
	.byte	W06
	.byte			En4
	.byte	W14
	.byte	BEND	, c_v-9
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-33
	.byte	W02
	.byte		c_v-30
	.byte		N08	, An4
	.byte	W01
	.byte	BEND	, c_v-21
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N05	, Gn4
	.byte	W12
	.byte		N32	, En4
	.byte	W66
	.byte		N07	, Bn3
	.byte	W06
	.byte		N06	, Cn4
	.byte	W06
	.byte		N08	, Dn4
	.byte	W06
	.byte		N07	, Cn4
	.byte	W06
	.byte			Bn3
	.byte	W06
	.byte		N14	, An3
	.byte	W18
	.byte		N22	, En4
	.byte	W24
	.byte		N07	, Dn4
	.byte	W12
	.byte		N13	, Cn4
	.byte	W12
	.byte		N11	, Dn4
	.byte	W12
	.byte		N44	, An3
	.byte	W96
	.byte		N30	, Gn4
	.byte	W36
	.byte		N04	, Fn4
	.byte	W06
	.byte		N04	
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N18	, En4
	.byte	W06
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N07	, An3
	.byte	W06
	.byte		N24	, En4
	.byte	W56
	.byte	W01
	.byte	BEND	, c_v-8
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-14
	.byte		N02	, Fs4
	.byte		N32	, Gn4
	.byte	W01
	.byte	BEND	, c_v-10
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W32
	.byte	W01
	.byte		N07	, An4
	.byte	W06
	.byte		N05	, Gn4
	.byte	W12
	.byte		N04	, Fn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N12	, En4
	.byte	W06
	.byte	W06
	.byte		N05	, An3
	.byte	W06
	.byte		N09	
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N12	, En4
	.byte	W36
	.byte		N04	, An3
	.byte	W06
	.byte		N06	, Cn4
	.byte	W06
	.byte		N03	, An3
	.byte	W06
	.byte			Cs4
	.byte		N10	, Dn4
	.byte	W06
	.byte		N01	, En4
	.byte	W06
	.byte		N05	, Cn4
	.byte	W12
	.byte		N11	, Dn4
	.byte	W12
	.byte		N03	, Cn4
	.byte	W06
	.byte		N11	, Dn4
	.byte	W12
	.byte		N03	, Cn4
	.byte	W06
	.byte		N07	, Dn4
	.byte	W06
	.byte		N03	, Cn4
	.byte	W06
	.byte		N06	, Dn4
	.byte	W06
	.byte		N02	, Cn4
	.byte	W06
	.byte		N07	, Dn4
	.byte	W06
	.byte		N02	, Cn4
	.byte	W06
	.byte		N08	, En4
	.byte	W12
	.byte		N06	, An3
	.byte	W12
	.byte		N07	, Cn4
	.byte	W06
	.byte		N02	, An3
	.byte	W14
	.byte		N04	, Dn4
	.byte	W02
	.byte		N02	, Ds4
	.byte	W02
	.byte		N06	, En4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N04	, Dn4
	.byte	W06
	.byte		N03	, Cn4
	.byte	W06
	.byte		N05	, Dn4
	.byte	W06
	.byte		N07	, En4
	.byte	W09
	.byte	BEND	, c_v-5
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		N18	, An4
	.byte	W02
	.byte	BEND	, c_v-16
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte	W12
	.byte		N08	, Gn4
	.byte	W06
	.byte		N36	, An4
	.byte	W42
	.byte		N07	, Gn4
	.byte	W12
	.byte		N11	, Cn5
	.byte	W12
	.byte		N06	, Bn4
	.byte	W06
	.byte		N60	, An4
	.byte	W06
	.byte	W54
	.byte		N02	, Gn4
	.byte	W02
	.byte			Fn4
	.byte	W02
	.byte		N01	, En4
	.byte	W02
	.byte			Dn4
	.byte	W01
	.byte			Cn4
	.byte	W02
	.byte			Bn3
	.byte	W01
	.byte			An3
	.byte	W02
	.byte			Gn3
	.byte	W30
	.byte	GOTO	
		.word	song_0045_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0045_2
song_0045_2:	@ 0x087E0AA1
	.byte	KEYSH	, 0
	.byte	VOICE	, 1
	.byte	VOL	, v070
	.byte	PAN	, c_v
	.byte	W24
song_0045_2_1:
	.byte		N12	, Cn3, v112
	.byte		N12	, En3
	.byte	W12
	.byte		N01	, Cn3
	.byte		N01	, En3
	.byte	W12
	.byte		N06	, Cn3
	.byte		N06	, En3
	.byte	W06
	.byte			Cn3
	.byte		N06	, En3
	.byte	W06
	.byte		N01	, Cn3
	.byte		N01	, En3
	.byte	W12
	.byte		N12	, Dn3
	.byte		N12	, En3
	.byte	W12
	.byte		N01	, Dn3
	.byte		N01	, En3
	.byte	W12
	.byte		N06	, Dn3
	.byte		N06	, En3
	.byte	W06
	.byte			Dn3
	.byte		N06	, En3
	.byte	W06
	.byte		N01	, Dn3
	.byte		N01	, En3
	.byte	W12
	.byte	PEND
song_0045_2_2:
	.byte		N12	, Cs3, v112
	.byte		N12	, En3
	.byte	W12
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, En3
	.byte	W06
	.byte			Cs3
	.byte		N06	, En3
	.byte	W06
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N12	, Cs3
	.byte		N12	, En3
	.byte	W12
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, En3
	.byte	W06
	.byte			Cs3
	.byte		N06	, En3
	.byte	W06
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0045_2_1
	.byte		N12	, Cs3, v112
	.byte		N12	, En3
	.byte	W12
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, En3
	.byte	W06
	.byte			Cs3
	.byte		N06	, En3
	.byte	W06
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N12	, Cs3
	.byte		N12	, En3
	.byte	W12
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, En3
	.byte	W06
	.byte		N12	, Dn3
	.byte		N12	, En3
	.byte	W18
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte	PATT	
		.word	song_0045_2_2
	.byte	PATT	
		.word	song_0045_2_1
	.byte		N12	, Cs3, v112
	.byte		N12	, En3
	.byte	W12
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, En3
	.byte	W06
	.byte			Cs3
	.byte		N06	, En3
	.byte	W06
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N12	, Cs3
	.byte		N12	, En3
	.byte	W12
	.byte		N01	, Cs3
	.byte		N01	, En3
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, En3
	.byte	W06
	.byte		N13	, Dn3
	.byte		N14	, En3
	.byte	W18
	.byte	GOTO	
		.word	song_0045_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0045_3
song_0045_3:	@ 0x087E0BE6
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
song_0045_3_4:
	.byte	W96
	.byte	W48
	.byte		N01	, Cn3, v112
	.byte	W06
	.byte		N06	, An0
	.byte	W06
	.byte			Cs1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			En1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cs1
	.byte	W06
	.byte			An0
	.byte	W06
song_0045_3_1:
	.byte		N18	, Fn0, v112
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte			Fn0
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N18	, Gn0
	.byte	W18
	.byte		N06	, Dn1
	.byte	W06
	.byte			Gn1
	.byte	W06
	.byte			Gn0
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
song_0045_3_3:
	.byte		N18	, An0, v112
	.byte	W18
	.byte		N06	, En1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			An0
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cs1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			An0
	.byte	W06
	.byte		N18	, Gn0
	.byte	W18
	.byte	PEND
	.byte	PATT	
		.word	song_0045_3_1
song_0045_3_2:
	.byte		N18	, An0, v112
	.byte	W18
	.byte		N06	, En1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			An0
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cs1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			En1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cs1
	.byte	W06
	.byte			An0
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_2
	.byte	PATT	
		.word	song_0045_3_1
	.byte	PATT	
		.word	song_0045_3_3
	.byte	GOTO	
		.word	song_0045_3_4
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0045_4
song_0045_4:	@ 0x087E0CD8
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
song_0045_4_3:
	.byte	W96
	.byte	W72
	.byte		N06	, Cn2, v112
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte		N15	, An2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N11	, An2
	.byte	W18
	.byte		N06	, Cn1
	.byte		N17	, Cs2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W24
song_0045_4_1:
	.byte		N06	, Cn1, v112
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
song_0045_4_2:
	.byte		N06	, Cn1, v112
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte	PEND
	.byte		N06	
	.byte		N24	, Cs2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W24
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_2
	.byte		N06	, Cn1, v112
	.byte		N20	, Cs2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W24
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte	PATT	
		.word	song_0045_4_1
	.byte		N06	, Cn1, v112
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte		N16	, An2
	.byte	W18
	.byte	GOTO	
		.word	song_0045_4_3
	.byte	FINE

	.align 2
	.global song_0045
song_0045:	@ 0x087E0DE4
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0045_1		@ track
	.word	song_0045_2		@ track
	.word	song_0045_3		@ track
	.word	song_0045_4		@ track
