	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0053_1
song_0053_1:	@ 0x087E2C04
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
song_0053_1_2:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		TIE	, Fs4, v127
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		TIE	, En4
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte		N24	, Cs4
	.byte	W24
	.byte		N12	, Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		TIE	, Fs4
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		N96	, En4
	.byte	W96
song_0053_1_1:
	.byte		N48	, Fs4, v127
	.byte	W48
	.byte		N40	, An4
	.byte	W48
	.byte	PEND
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W02
	.byte		TIE	, Fs4
	.byte	W92
	.byte	W02
	.byte	W96
	.byte	W01
	.byte			En4
	.byte	W01
	.byte		EOT	, Fs4
	.byte	W92
	.byte	W02
	.byte	W48
	.byte	W01
	.byte			En4
	.byte	W01
	.byte		N24	, Cs4
	.byte	W24
	.byte		N12	, Dn4
	.byte	W12
	.byte			En4
	.byte	W10
	.byte	W01
	.byte		TIE	, Fs4
	.byte	W92
	.byte	W03
	.byte	W96
	.byte	W01
	.byte		EOT	
	.byte		N96	, En4
	.byte	W92
	.byte	W03
	.byte	PATT	
		.word	song_0053_1_1
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		TIE	, Gn4, v127
	.byte	W96
	.byte	W96
	.byte	W90
	.byte		EOT	
	.byte	W06
	.byte		N96	, Fn4
	.byte	W96
	.byte		TIE	, Gn4
	.byte	W96
	.byte	W96
	.byte	W90
	.byte		EOT	
	.byte	W06
	.byte		N48	
	.byte	W48
	.byte			Fn4
	.byte	W48
	.byte	GOTO	
		.word	song_0053_1_2
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0053_2
song_0053_2:	@ 0x087E2CA8
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
song_0053_2_5:
	.byte		N08	, Bn3, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_2_6:
	.byte		N08	, Dn4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_2_7:
	.byte		N08	, Cs4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_2_8:
	.byte		N08	, An3, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_2_1:
	.byte		N08	, Bn4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_2_2:
	.byte		N08	, Dn5, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_2_3:
	.byte		N08	, Cs5, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_2_4:
	.byte		N08	, An4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0053_2_1
	.byte	PATT	
		.word	song_0053_2_2
	.byte	PATT	
		.word	song_0053_2_3
	.byte	PATT	
		.word	song_0053_2_4
	.byte	PATT	
		.word	song_0053_2_1
	.byte	PATT	
		.word	song_0053_2_2
	.byte	PATT	
		.word	song_0053_2_3
	.byte	PATT	
		.word	song_0053_2_4
	.byte	W96
	.byte		N96	, Bn3, v127
	.byte		N96	, Dn4
	.byte	W96
	.byte			An3
	.byte		N96	, Cs4
	.byte	W96
	.byte		N48	, Fs3
	.byte		N48	, An3
	.byte	W48
	.byte		N44	, Dn3
	.byte		N44	, Fs3
	.byte	W48
	.byte		N90	, En3
	.byte		N90	, Gn3
	.byte	W96
	.byte		N96	, Dn4
	.byte		N96	, Fs4
	.byte	W96
	.byte			Cs4
	.byte		N96	, En4
	.byte	W96
	.byte		N48	, An3
	.byte		N48	, Cs4
	.byte	W48
	.byte		N44	, An3
	.byte		N44	, Dn4
	.byte	W48
	.byte		N96	, Bn2
	.byte	W96
song_0053_2_9:
	.byte		N24	, Bn2, v127
	.byte	W24
	.byte			Cs3
	.byte	W24
	.byte			Dn3
	.byte	W24
	.byte			En3
	.byte	W24
	.byte	PEND
song_0053_2_10:
	.byte		N72	, Fs3, v127
	.byte	W72
	.byte		N24	, En3
	.byte	W24
	.byte	PEND
song_0053_2_11:
	.byte		N24	, En3, v127
	.byte	W24
	.byte		N48	, Dn3
	.byte	W48
	.byte		N24	, Cs3
	.byte	W24
	.byte	PEND
	.byte		N96	, Dn3
	.byte	W96
	.byte			Bn2
	.byte	W96
	.byte			Cs3
	.byte	W96
	.byte		N92	, Fs3
	.byte	W96
	.byte	PATT	
		.word	song_0053_2_5
	.byte	PATT	
		.word	song_0053_2_6
	.byte	PATT	
		.word	song_0053_2_7
	.byte	PATT	
		.word	song_0053_2_8
	.byte	PATT	
		.word	song_0053_2_5
	.byte	PATT	
		.word	song_0053_2_6
	.byte	PATT	
		.word	song_0053_2_7
	.byte	PATT	
		.word	song_0053_2_8
	.byte	PATT	
		.word	song_0053_2_5
	.byte	PATT	
		.word	song_0053_2_6
	.byte	PATT	
		.word	song_0053_2_7
	.byte	PATT	
		.word	song_0053_2_8
	.byte	PATT	
		.word	song_0053_2_5
	.byte	PATT	
		.word	song_0053_2_6
	.byte	PATT	
		.word	song_0053_2_7
	.byte	PATT	
		.word	song_0053_2_8
	.byte		N96	, Fs3, v127
	.byte	W96
	.byte	PATT	
		.word	song_0053_2_9
	.byte	PATT	
		.word	song_0053_2_10
	.byte	PATT	
		.word	song_0053_2_11
	.byte		N96	, Dn3, v127
	.byte	W96
	.byte			Bn2
	.byte	W96
	.byte			Cs3
	.byte	W96
	.byte			Fs3
	.byte	W96
	.byte		N68	, Dn2
	.byte		N68	, Gn2
	.byte	W96
	.byte		N96	, Dn3
	.byte		N96	, Fn3
	.byte	W96
	.byte			Cn3
	.byte		N96	, En3
	.byte	W96
song_0053_2_12:
	.byte		N44	, An2, v127
	.byte		N44	, Cn3
	.byte	W48
	.byte		N48	, Cn2
	.byte		N48	, Fn2
	.byte	W48
	.byte	PEND
	.byte		N96	, Dn2
	.byte		N96	, Gn2
	.byte	W96
	.byte			Dn3
	.byte		N96	, Fn3
	.byte	W96
	.byte			Cn3
	.byte		N96	, En3
	.byte	W96
	.byte	PATT	
		.word	song_0053_2_12
	.byte		N96	, Dn2, v127
	.byte		N96	, Gn2
	.byte	W96
	.byte			Dn3
	.byte		N96	, Fn3
	.byte	W96
	.byte			Cn3
	.byte		N96	, En3
	.byte	W96
	.byte	PATT	
		.word	song_0053_2_12
	.byte		N96	, Dn2, v127
	.byte		N96	, Gn2
	.byte	W96
	.byte			Dn3
	.byte		N96	, Fn3
	.byte	W96
	.byte			Cn3
	.byte		N96	, En3
	.byte	W96
	.byte		N44	, Fn2
	.byte		N44	, Cn3
	.byte	W48
	.byte		N48	, Fn2
	.byte		N48	, Fn3
	.byte	W48
	.byte	GOTO	
		.word	song_0053_2_5
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0053_3
song_0053_3:	@ 0x087E2E77
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
song_0053_3_9:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0053_3_1:
	.byte		N08	, Bn3, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_3_2:
	.byte		N08	, Dn4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_3_3:
	.byte		N08	, Cs4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_3_4:
	.byte		N08	, An3, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0053_3_1
	.byte	PATT	
		.word	song_0053_3_2
	.byte	PATT	
		.word	song_0053_3_3
	.byte	PATT	
		.word	song_0053_3_4
	.byte		TIE	, Dn4, v127
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		TIE	, Cs4
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W48
	.byte		TIE	, Bn3
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		N96	, Cs4
	.byte	W96
song_0053_3_5:
	.byte		N48	, Cs4, v127
	.byte	W48
	.byte		N40	
	.byte	W48
	.byte	PEND
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W06
	.byte		N06	, Bn2
	.byte	W06
	.byte			Cs3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			Fs3
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte			An3
	.byte	W06
	.byte			Bn3
	.byte	W06
	.byte			Cs4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			An4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N96	, Bn4
	.byte	W96
	.byte			Dn5
	.byte	W96
	.byte		N06	
	.byte	W08
	.byte			Cs5
	.byte	W07
	.byte		N80	
	.byte	W80
	.byte	W01
	.byte		N48	, An4
	.byte	W48
	.byte			Fs4
	.byte	W48
	.byte		N96	, Bn4
	.byte	W96
	.byte			Fs5
	.byte	W96
	.byte		N06	
	.byte	W08
	.byte			En5
	.byte	W07
	.byte		N80	
	.byte	W80
	.byte	W01
	.byte		N48	, Cs5
	.byte	W48
	.byte			Dn5
	.byte	W48
	.byte		TIE	, Dn4
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		TIE	, Cs4
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W48
	.byte		TIE	, Bn3
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte		N96	, Cs4
	.byte	W96
	.byte	PATT	
		.word	song_0053_3_5
	.byte	PATT	
		.word	song_0053_3_2
song_0053_3_6:
	.byte		N08	, Fn4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_3_7:
	.byte		N08	, En4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
song_0053_3_8:
	.byte		N08	, Cn4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0053_3_2
	.byte	PATT	
		.word	song_0053_3_6
	.byte	PATT	
		.word	song_0053_3_7
	.byte	PATT	
		.word	song_0053_3_8
	.byte	PATT	
		.word	song_0053_3_2
	.byte	PATT	
		.word	song_0053_3_6
	.byte	PATT	
		.word	song_0053_3_7
	.byte	PATT	
		.word	song_0053_3_8
	.byte	PATT	
		.word	song_0053_3_2
	.byte	PATT	
		.word	song_0053_3_6
	.byte	PATT	
		.word	song_0053_3_7
	.byte	PATT	
		.word	song_0053_3_8
	.byte	GOTO	
		.word	song_0053_3_9
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0053_4
song_0053_4:	@ 0x087E2FD4
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v078
	.byte	PAN	, c_v
	.byte	W24
song_0053_4_7:
	.byte		N92	, Bn2, v127
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N92	
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0053_4_3:
	.byte		N06	, Cn1, v127
	.byte		N44	, Bn2
	.byte	W48
	.byte		N06	, Cn1
	.byte	W48
	.byte	PEND
song_0053_4_1:
	.byte		N06	, Cn1, v127
	.byte	W48
	.byte		N06	
	.byte	W48
	.byte	PEND
	.byte	PATT	
		.word	song_0053_4_1
song_0053_4_2:
	.byte		N06	, Cn1, v127
	.byte	W48
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte	PEND
	.byte		N06	
	.byte		N40	, Bn2
	.byte	W48
	.byte		N06	, Cn1
	.byte	W48
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte	PATT	
		.word	song_0053_4_3
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte		N06	, Cn1, v127
	.byte		N32	, Bn2
	.byte	W48
	.byte		N06	, Cn1
	.byte	W48
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte		N06	, Cn1, v127
	.byte		N42	, Bn2
	.byte	W48
	.byte		N06	, Cn1
	.byte	W48
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte	PATT	
		.word	song_0053_4_3
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte		N06	, Cn1, v127
	.byte	W72
	.byte		N08	
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte		N08	
	.byte	W08
	.byte		N06	
	.byte		N16	, Bn2
	.byte	W48
	.byte		N06	, Cn1
	.byte	W48
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte		N06	, Cn1, v127
	.byte		N22	, Bn2
	.byte	W48
	.byte		N06	, Cn1
	.byte	W48
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte	PATT	
		.word	song_0053_4_3
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte	PATT	
		.word	song_0053_4_3
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte	PATT	
		.word	song_0053_4_3
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte	PATT	
		.word	song_0053_4_3
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
song_0053_4_4:
	.byte		N06	, Cn1, v127
	.byte		N48	, Bn2
	.byte	W96
	.byte	PEND
	.byte	W96
	.byte		N06	, Cn1
	.byte	W96
song_0053_4_5:
	.byte	W48
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0053_4_4
	.byte	W96
	.byte		N06	, Cn1, v127
	.byte	W96
	.byte	PATT	
		.word	song_0053_4_5
song_0053_4_6:
	.byte		N06	, Cn1, v127
	.byte	W16
	.byte		N06	
	.byte	W16
	.byte		N06	
	.byte	W16
	.byte		N06	
	.byte	W16
	.byte		N06	
	.byte	W16
	.byte		N06	
	.byte	W16
	.byte	PEND
	.byte	PATT	
		.word	song_0053_4_6
	.byte	PATT	
		.word	song_0053_4_6
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte	PATT	
		.word	song_0053_4_3
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_1
	.byte	PATT	
		.word	song_0053_4_2
	.byte	GOTO	
		.word	song_0053_4_7
	.byte	FINE

	.align 2
	.global song_0053
song_0053:	@ 0x087E3168
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0053_1		@ track
	.word	song_0053_2		@ track
	.word	song_0053_3		@ track
	.word	song_0053_4		@ track
