	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0017_1
song_0017_1:	@ 0x087D8734
	.byte	KEYSH	, 0
	.byte	TEMPO	, 33
	.byte	VOICE	, 5
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
song_0017_1_1:
	.byte		N06	, Cs3, v127
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte	PEND
song_0017_1_2:
	.byte		N06	, Cs3, v127
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N24	, En3
	.byte		N24	, Ds4
	.byte	W12
	.byte	PEND
song_0017_1_3:
	.byte	W12
	.byte		N04	, Cs3, v127
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte	PEND
song_0017_1_4:
	.byte		N06	, Cs3, v127
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte	PEND
song_0017_1_5:
	.byte		N04	, Cs3, v127
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N06	, Cs3
	.byte		N06	, Cn4
	.byte	W12
	.byte	PEND
song_0017_1_6:
	.byte		N04	, Cs3, v127
	.byte		N04	, Cn4
	.byte	W12
	.byte		N16	, En3
	.byte		N16	, Ds4
	.byte	W24
	.byte		N06	, Cs3
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N08	, Cs3
	.byte		N08	, Cn4
	.byte	W12
	.byte		N04	, Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte	PEND
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W36
	.byte	PATT	
		.word	song_0017_1_1
	.byte	PATT	
		.word	song_0017_1_2
	.byte	PATT	
		.word	song_0017_1_3
	.byte	PATT	
		.word	song_0017_1_4
	.byte	PATT	
		.word	song_0017_1_5
	.byte	PATT	
		.word	song_0017_1_6
	.byte		N04	, Cs3, v127
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte			Cs3
	.byte		N04	, Cn4
	.byte	W12
	.byte		N16	, En3
	.byte		N16	, Ds4
	.byte	W24
	.byte			Fn3
	.byte		N16	, En4
	.byte	W36
	.byte	GOTO	
		.word	song_0017_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0017_2
song_0017_2:	@ 0x087D8865
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
song_0017_2_1:
	.byte		N06	, Fs3, v127
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N06	, Fs3
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte	PEND
song_0017_2_2:
	.byte		N06	, Fs3, v127
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N06	, Fs3
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N24	, An3
	.byte		N24	, An4
	.byte	W12
	.byte	PEND
song_0017_2_3:
	.byte	W12
	.byte		N04	, Fs3, v127
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte	PEND
song_0017_2_4:
	.byte		N06	, Fs3, v127
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N06	, Fs3
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N06	, Fs3
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte	PEND
song_0017_2_5:
	.byte		N04	, Fs3, v127
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N06	, Fs3
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N06	, Fs3
	.byte		N06	, Fs4
	.byte	W12
	.byte	PEND
song_0017_2_6:
	.byte		N04	, Fs3, v127
	.byte		N04	, Fs4
	.byte	W12
	.byte		N16	, An3
	.byte		N16	, An4
	.byte	W24
	.byte		N06	, Fs3
	.byte		N06	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N08	, Fs3
	.byte		N08	, Fs4
	.byte	W12
	.byte		N04	, Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte	PEND
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W36
	.byte	PATT	
		.word	song_0017_2_1
	.byte	PATT	
		.word	song_0017_2_2
	.byte	PATT	
		.word	song_0017_2_3
	.byte	PATT	
		.word	song_0017_2_4
	.byte	PATT	
		.word	song_0017_2_5
	.byte	PATT	
		.word	song_0017_2_6
	.byte		N04	, Fs3, v127
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte			Fs3
	.byte		N04	, Fs4
	.byte	W12
	.byte		N16	, An3
	.byte		N16	, An4
	.byte	W24
	.byte			As3
	.byte		N16	, As4
	.byte	W36
	.byte	GOTO	
		.word	song_0017_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0017_3
song_0017_3:	@ 0x087D8994
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
song_0017_3_1:
	.byte		N12	, Fn1, v127
	.byte	W24
	.byte		N12	
	.byte	W72
	.byte	PEND
	.byte	PATT	
		.word	song_0017_3_1
	.byte	W96
song_0017_3_2:
	.byte		N12	, Fn1, v127
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte	PEND
song_0017_3_3:
	.byte	W60
	.byte		N12	, Fn1, v127
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte	PEND
song_0017_3_4:
	.byte	W36
	.byte		N12	, Fn1, v127
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte	PEND
	.byte	W60
	.byte	PATT	
		.word	song_0017_3_1
	.byte	PATT	
		.word	song_0017_3_1
	.byte	W96
	.byte	PATT	
		.word	song_0017_3_2
	.byte	PATT	
		.word	song_0017_3_3
	.byte	PATT	
		.word	song_0017_3_4
	.byte	W36
	.byte		N16	, Gs1, v127
	.byte	W24
	.byte			An1
	.byte	W36
	.byte	GOTO	
		.word	song_0017_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0017_4
song_0017_4:	@ 0x087D89EB
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
song_0017_4_1:
	.byte		N24	, Fs3, v127
	.byte	W24
	.byte		N24	
	.byte		N24	, Cn5
	.byte	W72
	.byte	PEND
	.byte	PATT	
		.word	song_0017_4_1
	.byte	W96
song_0017_4_2:
	.byte		N36	, Fs3, v127
	.byte		N24	, Cn5
	.byte	W36
	.byte		N36	, Fs3
	.byte		N24	, Cn5
	.byte	W36
	.byte			Fs3
	.byte		N24	, Cn5
	.byte	W24
	.byte	PEND
song_0017_4_3:
	.byte	W60
	.byte		N12	, Fs3, v127
	.byte	W24
	.byte		N12	
	.byte		N12	, Cn5
	.byte	W12
	.byte	PEND
song_0017_4_4:
	.byte	W36
	.byte		N12	, Fs3, v127
	.byte	W36
	.byte		N12	
	.byte		N12	, Cn5
	.byte	W24
	.byte	PEND
	.byte	W60
	.byte	PATT	
		.word	song_0017_4_1
	.byte	PATT	
		.word	song_0017_4_1
	.byte	W96
	.byte	PATT	
		.word	song_0017_4_2
	.byte	PATT	
		.word	song_0017_4_3
	.byte	PATT	
		.word	song_0017_4_4
	.byte	W96
	.byte	GOTO	
		.word	song_0017_4_1
	.byte	FINE

	.align 2
	.global song_0017
song_0017:	@ 0x087D8A4C
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	188		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0017_1		@ track
	.word	song_0017_2		@ track
	.word	song_0017_3		@ track
	.word	song_0017_4		@ track
