	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0013_1
song_0013_1:	@ 0x087D6D20
	.byte	KEYSH	, 0
	.byte	TEMPO	, 61
	.byte	VOICE	, 10
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0013_1_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W72
	.byte		N04	, Gn4, v127
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N04	, An4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N02	, As4
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N04	, An4
	.byte	W06
	.byte		N02	, As4
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N04	, An4
	.byte	W06
	.byte		N02	, As4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N04	, An4
	.byte	W06
	.byte		N03	, As4
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N02	, Gs4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte		N03	
	.byte	W06
	.byte		N02	, Gn4
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	, Fn4
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	, En4
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N03	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N05	, Fn4
	.byte	W06
	.byte		N07	, Gn4
	.byte	W06
	.byte	W06
	.byte		N03	, En4
	.byte	W06
	.byte		N04	, Cn4
	.byte	W06
	.byte		N01	, As3
	.byte	W66
	.byte		N02	, Gn4
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte			An4
	.byte	W03
	.byte		N01	, Gn4
	.byte	W03
	.byte			As4
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N05	
	.byte	W06
	.byte		N04	
	.byte	W12
	.byte		N06	, An4
	.byte	W06
	.byte		N02	, As4
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N05	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N03	, An4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N04	, As4
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W06
	.byte		N02	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W06
	.byte		N01	, An4
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte			As4
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	, An4
	.byte	W03
	.byte			As4
	.byte	W03
	.byte		N03	, An4
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N03	, Gn4
	.byte	W06
	.byte		N03	
	.byte	W03
	.byte		N02	, Fn4
	.byte	W03
	.byte			Gn4
	.byte	W03
	.byte		N01	, Fn4
	.byte	W03
	.byte		N03	
	.byte	W06
	.byte			En4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N05	, Fn4
	.byte	W06
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte			Gn4
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N05	
	.byte	W06
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N01	
	.byte	W06
	.byte		N04	, En4
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N04	, Cn4
	.byte	W03
	.byte		N01	, Dn4
	.byte	W03
	.byte		N04	, Cn4
	.byte	W03
	.byte		N01	, Bn3
	.byte	W03
	.byte		N04	, As3
	.byte	W84
	.byte		N03	, As4
	.byte		N02	, Dn5
	.byte	W06
	.byte		N03	, As4
	.byte		N02	, Dn5
	.byte	W06
	.byte	W06
	.byte			An4
	.byte		N02	, Cn5
	.byte	W06
	.byte			An4
	.byte		N03	, Cn5
	.byte	W12
	.byte			Gn4
	.byte		N02	, As4
	.byte	W06
	.byte			Gn4
	.byte		N02	, As4
	.byte	W12
	.byte			Fn4
	.byte		N02	, An4
	.byte	W06
	.byte		N03	, Fn4
	.byte		N03	, An4
	.byte	W12
	.byte		N02	, Gn4
	.byte		N01	, As4
	.byte	W06
	.byte		N02	, Gn4
	.byte		N03	, As4
	.byte	W12
	.byte			Fn4
	.byte		N02	, An4
	.byte	W06
	.byte		N03	, Fn4
	.byte		N03	, An4
	.byte	W12
	.byte			En4
	.byte		N02	, Gn4
	.byte	W06
	.byte		N03	, En4
	.byte		N03	, Gn4
	.byte	W12
	.byte			Fn4
	.byte		N02	, An4
	.byte	W06
	.byte		N03	, Fn4
	.byte		N03	, An4
	.byte	W12
	.byte			Gn4
	.byte		N03	, As4
	.byte	W06
	.byte			Gn4
	.byte		N03	, As4
	.byte	W12
	.byte		N02	, An4
	.byte		N02	, Cn5
	.byte	W06
	.byte		N03	, An4
	.byte		N03	, Cn5
	.byte	W12
	.byte			As4
	.byte		N02	, Dn5
	.byte	W12
	.byte		N03	, An4
	.byte		N02	, Cn5
	.byte	W12
	.byte		N04	, Gn4
	.byte		N03	, As4
	.byte	W12
	.byte			An4
	.byte		N03	, Cn5
	.byte	W12
	.byte			Gn4
	.byte		N02	, As4
	.byte	W12
	.byte		N03	, Fn4
	.byte		N02	, An4
	.byte	W12
	.byte		N03	, Gn4
	.byte		N02	, As4
	.byte	W12
	.byte		N03	, Fn4
	.byte		N03	, An4
	.byte	W12
	.byte			En4
	.byte		N02	, Gn4
	.byte	W12
	.byte		N03	, Dn4
	.byte		N02	, Fn4
	.byte	W12
	.byte			Cn4
	.byte		N02	, En4
	.byte	W18
	.byte		N01	
	.byte		N02	, Gn4
	.byte	W66
	.byte			As4
	.byte		N02	, Dn5
	.byte	W06
	.byte		N03	, As4
	.byte		N03	, Dn5
	.byte	W06
	.byte	W06
	.byte		N02	, An4
	.byte		N02	, Cn5
	.byte	W06
	.byte		N03	, An4
	.byte		N03	, Cn5
	.byte	W12
	.byte			Gn4
	.byte		N02	, As4
	.byte	W06
	.byte		N03	, Gn4
	.byte		N03	, As4
	.byte	W12
	.byte			Fn4
	.byte		N02	, An4
	.byte	W06
	.byte		N04	, Fn4
	.byte		N03	, An4
	.byte	W12
	.byte			Gn4
	.byte		N02	, As4
	.byte	W06
	.byte		N03	, Gn4
	.byte		N03	, As4
	.byte	W12
	.byte			Fn4
	.byte		N02	, An4
	.byte	W06
	.byte		N03	, Fn4
	.byte		N03	, An4
	.byte	W12
	.byte			En4
	.byte		N02	, Gn4
	.byte	W12
	.byte		N03	, Fn4
	.byte		N02	, An4
	.byte	W12
	.byte		N03	, Gn4
	.byte		N01	, As4
	.byte	W06
	.byte			Gn4
	.byte		N02	, As4
	.byte	W06
	.byte		N03	, Fn4
	.byte		N03	, An4
	.byte	W12
	.byte		N02	, En4
	.byte		N02	, Gn4
	.byte	W12
	.byte		N03	, Dn4
	.byte		N02	, Fn4
	.byte	W12
	.byte		N03	, Cn4
	.byte		N02	, En4
	.byte	W12
	.byte		N03	, Dn4
	.byte		N02	, Fn4
	.byte	W12
	.byte			En4
	.byte		N02	, Gn4
	.byte	W18
	.byte			Cn4
	.byte		N02	, En4
	.byte	W78
	.byte	W48
	.byte			Gn3
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N08	
	.byte	W12
	.byte		N03	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W12
	.byte		N01	, As3
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N04	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N03	, An3
	.byte	W12
	.byte		N04	, As3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte		N05	, Fn3
	.byte	W12
	.byte		N03	, En3
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N05	, Fn3
	.byte	W12
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N10	
	.byte	W12
	.byte		N04	, An3
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N01	, As3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N05	, Cn4
	.byte	W12
	.byte		N02	, Dn4
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N06	, Cn4
	.byte	W12
	.byte		N04	, As3
	.byte	W06
	.byte		N03	
	.byte	W12
	.byte		N02	, Gn3
	.byte	W66
	.byte			Gn4
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte			An4
	.byte	W06
	.byte		N01	, Gn4
	.byte	W06
	.byte		N03	, As4
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			An4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N01	
	.byte	W03
	.byte		N02	, As4
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N03	, An4
	.byte	W06
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte			As4
	.byte	W03
	.byte		N11	
	.byte	W12
	.byte		N05	, An4
	.byte	W06
	.byte		N02	, Gn4
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte			Fn4
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N01	, En4
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N02	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte			Fn4
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte		N03	
	.byte	W06
	.byte		N01	, Gn4
	.byte	W03
	.byte		N02	
	.byte	W03
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	, En4
	.byte	W12
	.byte		N03	, Cn4
	.byte	W12
	.byte		N02	, As3
	.byte	W54
	.byte	W60
	.byte		N03	, Gn3
	.byte		N02	, Gn4
	.byte	W12
	.byte		N03	, Gn3
	.byte		N02	, Gn4
	.byte	W24
	.byte	W48
	.byte			Gn3
	.byte		N02	, Gn4
	.byte	W18
	.byte			As3
	.byte		N02	, As4
	.byte	W30
	.byte	W60
	.byte			Gn3
	.byte		N03	, Gn4
	.byte	W12
	.byte			Gn3
	.byte		N03	, Gn4
	.byte	W24
	.byte	W48
	.byte		N04	, Gn3
	.byte		N04	, Gn4
	.byte	W18
	.byte		N02	, As3
	.byte		N02	, As4
	.byte	W30
	.byte	W48
	.byte		N03	, Gn4
	.byte		N03	, Dn5
	.byte	W18
	.byte		N02	, Gn4
	.byte		N03	, Dn5
	.byte	W30
	.byte	W48
	.byte		N02	, As4
	.byte		N03	, Dn5
	.byte	W18
	.byte		N02	
	.byte		N01	, Fn5
	.byte	W30
	.byte	W48
	.byte		N02	, As4
	.byte		N03	, Dn5
	.byte	W18
	.byte		N03	
	.byte		N03	, Fn5
	.byte	W30
	.byte	W48
	.byte		N02	, As4
	.byte		N03	, Dn5
	.byte	W48
	.byte	GOTO	
		.word	song_0013_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0013_2
song_0013_2:	@ 0x087D70B6
	.byte	KEYSH	, 0
	.byte	VOICE	, 10
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0013_2_3:
	.byte	W96
	.byte	W96
song_0013_2_1:
	.byte		N03	, Cn3, v127
	.byte		N02	, En3
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W18
	.byte		N04	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W11
	.byte		N04	, As2
	.byte	W01
	.byte		N03	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0013_2_1
	.byte		N03	, Cn3, v127
	.byte		N02	, En3
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W18
	.byte		N04	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W11
	.byte		N04	, As2
	.byte	W01
	.byte		N03	, Dn3
	.byte	W23
	.byte			Cn3
	.byte	W01
	.byte			En3
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W17
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N04	, As2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Cn3
	.byte		N02	, En3
	.byte	W01
	.byte	W17
	.byte			Cn3
	.byte		N03	, En3
	.byte	W18
	.byte		N04	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N04	, As2
	.byte		N03	, Dn3
	.byte	W24
	.byte			Cn3
	.byte	W01
song_0013_2_2:
	.byte		N03	, En3, v127
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W17
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N04	, As2
	.byte		N03	, Dn3
	.byte	W24
	.byte			Cn3
	.byte	W01
	.byte	PEND
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte		N03	, En3, v127
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W17
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N04	, As2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N04	, Gn2
	.byte		N04	, Gn3
	.byte	W12
	.byte		N03	, Cn3
	.byte	W01
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte		N03	, En3, v127
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W17
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N04	, As2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N04	, En3
	.byte	W01
	.byte	W03
	.byte		N05	, Cn3
	.byte	W04
	.byte		N04	, En3
	.byte	W06
	.byte			Cn3
	.byte	W01
	.byte		N03	, En3
	.byte	W08
	.byte			Cn3
	.byte		N02	, En3
	.byte	W07
	.byte		N03	
	.byte	W01
	.byte			Cn3
	.byte	W06
	.byte			En3
	.byte	W01
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W01
	.byte			Cn3
	.byte	W06
	.byte		N04	, En3
	.byte	W02
	.byte		N03	, Cn3
	.byte	W06
	.byte			En3
	.byte	W02
	.byte		N04	, Cn3
	.byte	W06
	.byte			En3
	.byte	W03
	.byte			Cn3
	.byte	W06
	.byte			En3
	.byte	W03
	.byte			Cn3
	.byte	W05
	.byte			En3
	.byte	W04
	.byte			Cn3
	.byte	W04
	.byte			En3
	.byte	W04
	.byte	W01
	.byte		N05	, Cn3
	.byte	W03
	.byte		N03	, En3
	.byte	W07
	.byte		N04	, Cn3
	.byte	W01
	.byte		N03	, En3
	.byte	W08
	.byte		N05	
	.byte	W02
	.byte			Cn3
	.byte	W08
	.byte			En3
	.byte	W03
	.byte		N06	, Cn3
	.byte	W10
	.byte		N01	, En3
	.byte	W06
	.byte		N08	, As2
	.byte	W04
	.byte		N03	, Dn3
	.byte	W07
	.byte		N04	
	.byte	W01
	.byte		N05	, As2
	.byte	W07
	.byte		N04	, Dn3
	.byte	W03
	.byte			As2
	.byte	W05
	.byte			Dn3
	.byte	W03
	.byte		N02	, As2
	.byte	W04
	.byte		N03	, Dn3
	.byte	W02
	.byte		N04	, As2
	.byte	W06
	.byte			Dn3
	.byte	W02
	.byte		N03	, As2
	.byte	W03
	.byte		N04	, Fn3
	.byte	W03
	.byte		N03	, Cn3
	.byte	W01
	.byte		N06	, En3
	.byte	W05
	.byte		N04	, Cn3
	.byte	W06
	.byte			En3
	.byte	W03
	.byte			Cn3
	.byte	W05
	.byte			En3
	.byte	W04
	.byte		N03	, Cn3
	.byte	W04
	.byte		N04	, En3
	.byte	W03
	.byte			Cn3
	.byte	W06
	.byte			En3
	.byte	W02
	.byte		N03	, Cn3
	.byte	W06
	.byte		N04	, En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W01
	.byte			Cn3
	.byte	W08
	.byte		N05	, En3
	.byte	W01
	.byte		N04	, Cn3
	.byte	W08
	.byte			En3
	.byte	W01
	.byte		N05	, Cn3
	.byte	W08
	.byte			En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte		N04	, En3
	.byte	W03
	.byte			Cn3
	.byte	W06
	.byte			En3
	.byte	W03
	.byte		N05	, Cn3
	.byte	W06
	.byte		N04	, En3
	.byte	W03
	.byte		N05	, Cn3
	.byte	W05
	.byte			En3
	.byte	W05
	.byte			Cn3
	.byte	W05
	.byte		N03	, En3
	.byte	W06
	.byte		N09	, Cn3
	.byte	W01
	.byte		N04	, En3
	.byte	W08
	.byte		N05	, As2
	.byte	W01
	.byte			Dn3
	.byte	W08
	.byte		N04	
	.byte	W01
	.byte		N03	, As2
	.byte	W08
	.byte		N04	
	.byte		N03	, Dn3
	.byte	W07
	.byte			As2
	.byte	W01
	.byte			Dn3
	.byte	W07
	.byte		N04	, As2
	.byte		N03	, Dn3
	.byte	W06
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W05
	.byte		N04	, As2
	.byte	W04
	.byte	W01
	.byte		N06	, Cn3
	.byte		N04	, En3
	.byte	W10
	.byte		N04	
	.byte	W01
	.byte		N05	, Cn3
	.byte	W07
	.byte		N04	, En3
	.byte	W03
	.byte		N05	, Cn3
	.byte	W06
	.byte		N04	, En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W02
	.byte			Cn3
	.byte	W06
	.byte			En3
	.byte	W02
	.byte		N03	, Cn3
	.byte	W07
	.byte		N04	, En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W01
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W03
	.byte			Cn3
	.byte	W06
	.byte		N05	, En3
	.byte	W03
	.byte		N04	, Cn3
	.byte	W04
	.byte	W03
	.byte			En3
	.byte	W03
	.byte		N05	, Cn3
	.byte	W06
	.byte			En3
	.byte	W05
	.byte			Cn3
	.byte	W05
	.byte			En3
	.byte	W04
	.byte		N06	, Cn3
	.byte	W06
	.byte		N07	, En3
	.byte	W08
	.byte		N08	, Cn3
	.byte	W07
	.byte		N06	, Dn3
	.byte	W03
	.byte		N05	, As2
	.byte	W08
	.byte		N04	
	.byte		N05	, Dn3
	.byte	W09
	.byte		N04	, As2
	.byte		N04	, Dn3
	.byte	W09
	.byte		N07	, As2
	.byte	W04
	.byte		N06	, Dn3
	.byte	W09
	.byte		N04	, As2
	.byte	W07
	.byte			Cn3
	.byte		N04	, En3
	.byte	W09
	.byte		N05	
	.byte	W01
	.byte			Cn3
	.byte	W08
	.byte		N04	, En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W03
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte		N05	, En3
	.byte	W02
	.byte		N04	, Cn3
	.byte	W07
	.byte			En3
	.byte	W02
	.byte		N03	, Cn3
	.byte	W07
	.byte		N05	, En3
	.byte	W02
	.byte		N03	, Cn3
	.byte	W07
	.byte		N05	, En3
	.byte	W01
	.byte		N04	, Cn3
	.byte	W09
	.byte		N05	, En3
	.byte	W01
	.byte		N04	, Cn3
	.byte	W03
	.byte	W05
	.byte		N05	, En3
	.byte	W02
	.byte			Cn3
	.byte	W07
	.byte			En3
	.byte	W03
	.byte			Cn3
	.byte	W08
	.byte		N06	, En3
	.byte	W03
	.byte		N04	, Cn3
	.byte	W07
	.byte		N05	, En3
	.byte	W04
	.byte		N07	, Cn3
	.byte	W06
	.byte		N06	, As2
	.byte	W02
	.byte		N05	, Dn3
	.byte	W07
	.byte		N07	, As2
	.byte	W02
	.byte		N06	, Dn3
	.byte	W09
	.byte		N05	, As2
	.byte		N05	, Dn3
	.byte	W08
	.byte			As2
	.byte	W01
	.byte		N04	, Dn3
	.byte	W08
	.byte		N08	, As2
	.byte	W01
	.byte		N05	, Dn3
	.byte	W12
	.byte		N03	, Cn3
	.byte	W01
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte	PATT	
		.word	song_0013_2_2
	.byte		N03	, En3, v127
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W17
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N04	, As2
	.byte		N03	, Dn3
	.byte	W13
	.byte			As2
	.byte		N03	, Dn3
	.byte		N02	, Fn3
	.byte	W11
	.byte		N03	, Cn3
	.byte	W01
	.byte			En3
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W17
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte			As2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N04	, As2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N01	, Cn3
	.byte		N02	, En3
	.byte	W01
	.byte	W18
	.byte			Cn3
	.byte		N03	, En3
	.byte	W18
	.byte		N02	, Cn3
	.byte		N02	, En3
	.byte	W12
	.byte			Dn3
	.byte		N02	, Fn3
	.byte	W48
	.byte	GOTO	
		.word	song_0013_2_3
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0013_3
song_0013_3:	@ 0x087D73BF
	.byte	KEYSH	, 0
	.byte	VOICE	, 2
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W12
	.byte		N03	, Gn3, v127
	.byte	W12
song_0013_3_1:
	.byte	W02
	.byte		TIE	, Gn4, v127
	.byte	W92
	.byte	W02
	.byte	W96
	.byte	W96
	.byte	W44
	.byte	W01
	.byte		EOT	
	.byte	W48
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W30
	.byte	W01
	.byte		N03	, Fs4
	.byte	W04
	.byte		N11	, Gn4
	.byte	W18
	.byte		N04	, En4
	.byte	W05
	.byte		N05	, Cn4
	.byte	W07
	.byte		N08	, As3
	.byte	W30
	.byte	W01
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W36
	.byte		N04	, Ds4
	.byte	W02
	.byte		N08	, En4
	.byte	W07
	.byte		N02	, Cn4
	.byte	W06
	.byte		N09	, As3
	.byte	W44
	.byte	W01
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W42
	.byte	W01
	.byte		N05	, Dn4
	.byte	W02
	.byte			Ds4
	.byte	W04
	.byte		N08	, En4
	.byte	W17
	.byte		N07	, Gn4
	.byte	W30
	.byte	W96
	.byte	W96
	.byte	W44
	.byte	W02
	.byte		N02	, Fs4
	.byte	W03
	.byte		N06	, Gn4
	.byte	W17
	.byte		N04	, En4
	.byte	W15
	.byte		N05	, Cn4
	.byte	W14
	.byte		N08	, As3
	.byte	W01
	.byte	W18
	.byte		N06	, Gn3
	.byte	W54
	.byte		N05	
	.byte	W11
	.byte		N06	, An3
	.byte	W13
	.byte		N11	, As3
	.byte	W14
	.byte		N04	, An3
	.byte	W04
	.byte		N16	, As3
	.byte	W19
	.byte		N05	, An3
	.byte	W10
	.byte		N04	
	.byte	W02
	.byte		N08	, As3
	.byte	W11
	.byte		N05	, An3
	.byte	W13
	.byte			Gn3
	.byte	W11
	.byte		N04	, Fn3
	.byte	W12
	.byte		N13	, En3
	.byte	W18
	.byte		N15	
	.byte	W18
	.byte		N06	, Fn3
	.byte	W12
	.byte		N05	, Gn3
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W11
	.byte		N05	, An3
	.byte	W13
	.byte		N12	, As3
	.byte	W15
	.byte		N04	, An3
	.byte	W03
	.byte		N17	, As3
	.byte	W19
	.byte		N04	, An3
	.byte	W11
	.byte		N05	, As3
	.byte	W11
	.byte			Cn4
	.byte	W13
	.byte		N13	, Dn4
	.byte	W12
	.byte		N04	, Cn4
	.byte	W11
	.byte		N16	, As3
	.byte	W01
	.byte	W17
	.byte		N04	, Gn3
	.byte	W54
	.byte	W01
	.byte		N04	
	.byte	W11
	.byte			An3
	.byte	W12
	.byte		N15	, As3
	.byte	W01
	.byte	W18
	.byte		N14	
	.byte	W18
	.byte		N04	, An3
	.byte	W12
	.byte		N05	, As3
	.byte	W11
	.byte		N06	, An3
	.byte	W13
	.byte			Gn3
	.byte	W13
	.byte		N05	, Fn3
	.byte	W11
	.byte	W02
	.byte		N12	, Gn3
	.byte	W17
	.byte		N12	
	.byte	W17
	.byte		N05	, An3
	.byte	W09
	.byte		N02	
	.byte	W03
	.byte		N08	, As3
	.byte	W11
	.byte		N06	, Cn4
	.byte	W12
	.byte		N08	, Dn4
	.byte	W13
	.byte		N06	, Cn4
	.byte	W12
	.byte		N13	, As3
	.byte	W18
	.byte		N10	
	.byte	W16
	.byte		N05	, An3
	.byte	W12
	.byte		N06	, As3
	.byte	W12
	.byte		N07	, An3
	.byte	W14
	.byte		N05	, Gn3
	.byte	W10
	.byte		N06	, An3
	.byte	W10
	.byte		N02	
	.byte	W02
	.byte		N17	, As3
	.byte	W02
	.byte	W17
	.byte		N07	, Gn3
	.byte	W78
	.byte	W01
	.byte	W60
	.byte		N04	
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte	W48
	.byte		N06	
	.byte	W17
	.byte		N07	, As3
	.byte	W30
	.byte	W01
	.byte	W60
	.byte		N06	, Dn4
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte	W48
	.byte		N06	
	.byte	W18
	.byte			Fn4
	.byte	W30
	.byte	W48
	.byte		N05	, Dn4
	.byte	W18
	.byte		N05	
	.byte	W30
	.byte	W44
	.byte	W03
	.byte		N06	
	.byte	W19
	.byte		N05	, Fn4
	.byte	W30
	.byte	W44
	.byte	W03
	.byte		N06	, Gn4
	.byte	W18
	.byte		N06	
	.byte	W30
	.byte	W01
	.byte	W48
	.byte		N05	
	.byte	W36
	.byte		N03	, Gn3
	.byte	W12
	.byte	GOTO	
		.word	song_0013_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0013_4
song_0013_4:	@ 0x087D74FA
	.byte	KEYSH	, 0
	.byte	VOICE	, 19
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0013_4_1:
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte			Gn2
	.byte	W18
	.byte		N12	, En2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte	PEND
song_0013_4_2:
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte			Gn2
	.byte	W18
	.byte		N12	, En2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Dn2
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte	PATT	
		.word	song_0013_4_2
	.byte	PATT	
		.word	song_0013_4_1
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte			Gn2
	.byte	W18
	.byte		N12	, En2
	.byte	W12
	.byte			Dn2
	.byte	W48
	.byte	GOTO	
		.word	song_0013_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0013_5
song_0013_5:	@ 0x087D75DB
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0013_5_1:
	.byte		N06	, Cn1, v127
	.byte		N06	, En6
	.byte	W12
	.byte		N06	
	.byte		N06	, Gn6
	.byte	W06
	.byte			Dn6
	.byte		N06	, Gn6
	.byte	W18
	.byte			Ds6
	.byte		N06	, Gn6
	.byte	W06
	.byte			Ds6
	.byte	W06
	.byte			En6
	.byte	W06
	.byte			Dn6
	.byte		N06	, Gn6
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn6
	.byte	W06
	.byte			Gn6
	.byte	W06
	.byte			Ds6
	.byte	W06
	.byte			Cn1
	.byte		N06	, Ds6
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
song_0013_5_2:
	.byte		N06	, Cn1, v127
	.byte		N06	, En6
	.byte	W12
	.byte		N06	
	.byte		N06	, Gn6
	.byte	W06
	.byte			Dn6
	.byte		N06	, Gn6
	.byte	W18
	.byte			Ds6
	.byte		N06	, Gn6
	.byte	W06
	.byte			Ds6
	.byte	W06
	.byte		N03	, En6
	.byte	W03
	.byte		N06	
	.byte	W03
	.byte			Dn6
	.byte		N06	, Gn6
	.byte	W06
	.byte			Dn6
	.byte		N06	, Gn6
	.byte	W12
	.byte			Dn6
	.byte		N06	, Gn6
	.byte	W06
	.byte			En6
	.byte	W06
	.byte			Cn1
	.byte		N06	, Ds6
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte	PATT	
		.word	song_0013_5_2
	.byte	PATT	
		.word	song_0013_5_1
	.byte		N06	, Cn1, v127
	.byte		N06	, En6
	.byte	W12
	.byte		N06	
	.byte		N06	, Gn6
	.byte	W06
	.byte			Dn6
	.byte		N06	, Gn6
	.byte	W18
	.byte			Ds6
	.byte		N06	, Gn6
	.byte	W06
	.byte			Ds6
	.byte	W06
	.byte			Cn1
	.byte		N06	, Dn6
	.byte		N06	, En6
	.byte	W06
	.byte		N03	, Gn6
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Ds6
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	GOTO	
		.word	song_0013_5_1
	.byte	FINE

	.align 2
	.global song_0013
song_0013:	@ 0x087D7710
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0013_1		@ track
	.word	song_0013_2		@ track
	.word	song_0013_3		@ track
	.word	song_0013_4		@ track
	.word	song_0013_5		@ track
