	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0023_1
song_0023_1:	@ 0x087D9F1C
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 0
	.byte	VOL	, v056
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 45
	.byte	W12
	.byte		N28	, Bn3, v127
	.byte		N32	, Bn4
	.byte	W30
	.byte		N28	, An3
	.byte		N30	, An4
	.byte	W24
	.byte	W03
	.byte		N24	, Fs3
	.byte		N24	, Fs4
	.byte	W24
	.byte	W03
song_0023_1_1:
	.byte		N66	, Bn3, v127
	.byte		N66	, Dn4
	.byte		N66	, En4
	.byte		N66	, Gn4
	.byte	W68
	.byte	W01
	.byte		N84	, Dn4
	.byte		N84	, Fs4
	.byte	W01
	.byte			An3
	.byte	W24
	.byte	W02
	.byte	W66
	.byte		N76	
	.byte		N76	, Cn4
	.byte		N78	, Fs4
	.byte	W30
	.byte	W48
	.byte	W03
	.byte		N92	, Bn3
	.byte		N92	, Dn4
	.byte		N92	, Fs4
	.byte	W44
	.byte	W01
	.byte	W48
	.byte	W03
	.byte		N64	, En4
	.byte		N66	, Gn4
	.byte	W03
	.byte		N64	, Cn4
	.byte	W42
	.byte	W24
	.byte		N76	, An3
	.byte		N76	, Dn4
	.byte		N76	, Fs4
	.byte	W72
	.byte	W09
	.byte		N80	, Bn3
	.byte		N78	, Dn4
	.byte		N80	, Fs4
	.byte	W84
	.byte		N54	, Bn3
	.byte		N54	, En4
	.byte		TIE	, Fs4
	.byte	W03
	.byte	W54
	.byte		N48	, An3
	.byte		N48	, Ds4
	.byte	W42
	.byte	W07
	.byte		EOT	, Fs4
	.byte	W02
	.byte		N84	, Bn3
	.byte		N88	, En4
	.byte		N84	, Gn4
	.byte	W84
	.byte	W03
	.byte	W03
	.byte		N80	, An3
	.byte		N80	, Fs4
	.byte	W01
	.byte		N78	, Dn4
	.byte	W88
	.byte	W01
	.byte		N72	, An3
	.byte		N72	, Cn4
	.byte		TIE	, Fs4
	.byte	W03
	.byte	W78
	.byte		N88	, Bn3
	.byte		N88	, Dn4
	.byte	W18
	.byte	W68
	.byte	W03
	.byte		EOT	, Fs4
	.byte	W01
	.byte		N68	, Cn4
	.byte		N68	, En4
	.byte		N68	, Gn4
	.byte	W24
	.byte	W44
	.byte	W01
	.byte		N80	, An3
	.byte		N80	, Dn4
	.byte		N80	, Fs4
	.byte	W48
	.byte	W03
	.byte	W32
	.byte	W01
	.byte		N72	, En4
	.byte	W03
	.byte			Cn4
	.byte		N72	, Gn4
	.byte	W60
	.byte	W12
	.byte		N68	, Fs4
	.byte	W03
	.byte			An3
	.byte		N68	, Dn4
	.byte	W72
	.byte		N72	, Bn3
	.byte		N68	, Ds4
	.byte		N68	, Fs4
	.byte	W09
	.byte	W66
	.byte			Bn3
	.byte		N68	, En4
	.byte		N68	, Gn4
	.byte	W30
	.byte	W42
	.byte		N72	, Cn4
	.byte		N72	, En4
	.byte		N72	, Gn4
	.byte	W54
	.byte	W21
	.byte			Dn4
	.byte		N72	, Fs4
	.byte	W03
	.byte			Bn3
	.byte	W72
	.byte	W03
	.byte		N76	, An3
	.byte		N76	, Cn4
	.byte		N76	, En4
	.byte	W80
	.byte	W01
	.byte		TIE	, Bn3
	.byte		N80	, En4
	.byte		TIE	, Fs4
	.byte	W12
	.byte	W68
	.byte	W01
	.byte			Ds4
	.byte	W24
	.byte	W03
	.byte	W96
	.byte	W54
	.byte		EOT	, Bn3
	.byte			Ds4
	.byte			Fs4
	.byte	W42
	.byte	GOTO	
		.word	song_0023_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0023_2
song_0023_2:	@ 0x087DA010
	.byte	KEYSH	, 0
	.byte	VOICE	, 8
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W24
	.byte	W72
	.byte		N24	, Bn3, v127
	.byte	W24
song_0023_2_1:
	.byte		N04	, Bn3, v127
	.byte		N12	, Dn4
	.byte		N11	, En4
	.byte	W15
	.byte		N21	, Bn3
	.byte	W09
	.byte		N12	, Dn4
	.byte	W12
	.byte		N04	, En4
	.byte	W12
	.byte		N19	, Bn4
	.byte	W24
	.byte	W03
	.byte		N06	, Dn4
	.byte		N13	, Fs4
	.byte		N23	, Bn4
	.byte	W12
	.byte		N18	, Dn4
	.byte	W09
	.byte	W06
	.byte		N14	, Fs4
	.byte	W12
	.byte		N32	, Bn3
	.byte	W18
	.byte		N18	, Bn4
	.byte	W36
	.byte		N05	, An3
	.byte		N14	, Cn4
	.byte		N13	, Fs4
	.byte	W12
	.byte		N24	, An3
	.byte	W12
	.byte		N10	, Cn4
	.byte	W12
	.byte		N08	, Gn4
	.byte	W15
	.byte		N17	, An4
	.byte	W24
	.byte	W03
	.byte		N10	, Bn3
	.byte		N11	, Dn4
	.byte		N12	, Fs4
	.byte	W12
	.byte		N60	, Fs3
	.byte	W12
	.byte		N44	, An3
	.byte	W15
	.byte		N32	, Bn3
	.byte	W03
	.byte	W12
	.byte		N16	, Dn4
	.byte	W15
	.byte		N04	, Fs4
	.byte	W24
	.byte			Gn3
	.byte		N13	, Cn4
	.byte		N11	, En4
	.byte	W09
	.byte		N13	, Gn3
	.byte	W12
	.byte		N08	, Fs4
	.byte	W12
	.byte		N09	, Gn3
	.byte	W12
	.byte		N10	, Gn4
	.byte	W24
	.byte	W03
	.byte		N06	, Cn4
	.byte		N14	, Fs4
	.byte		N14	, An4
	.byte	W12
	.byte		N32	, Cn4
	.byte	W15
	.byte		N20	, Dn4
	.byte	W12
	.byte		N08	, Fs4
	.byte	W12
	.byte		N06	, Cn4
	.byte		N12	, Dn4
	.byte		N14	, Fs4
	.byte		N13	, An4
	.byte	W15
	.byte		N14	, Dn3
	.byte		N04	, Cn4
	.byte	W03
	.byte	W12
	.byte		N17	, Gn3
	.byte		N07	, Dn4
	.byte		N24	, Fs4
	.byte		N24	, Bn4
	.byte	W24
	.byte	W03
	.byte			Dn3
	.byte	W12
	.byte		N40	, Gn3
	.byte		N24	, Dn4
	.byte		N10	, Fs4
	.byte		N13	, An4
	.byte	W15
	.byte		N10	, Gn4
	.byte	W12
	.byte		N07	, An4
	.byte	W15
	.byte		N19	, En4
	.byte		N40	, Fs4
	.byte		N44	, Bn4
	.byte	W03
	.byte	W09
	.byte		N80	, Fs3
	.byte	W18
	.byte		N64	, Bn3
	.byte	W15
	.byte		N15	, En4
	.byte	W21
	.byte		N24	, Ds4
	.byte		N24	, Fs4
	.byte	W32
	.byte	W01
	.byte		N06	, Gn3
	.byte		N14	, Bn3
	.byte		N14	, Dn4
	.byte		N13	, En4
	.byte	W42
	.byte		N22	, Gn3
	.byte	W12
	.byte		N13	, Dn4
	.byte	W12
	.byte		N07	, En4
	.byte	W12
	.byte		N18	, Bn4
	.byte	W18
	.byte	W09
	.byte		N07	, Dn4
	.byte		N13	, Fs4
	.byte		N16	, Bn4
	.byte	W15
	.byte		N14	, Dn4
	.byte	W12
	.byte		N12	, Fs4
	.byte	W12
	.byte		N32	, Dn4
	.byte	W12
	.byte		N15	, An4
	.byte	W18
	.byte		N08	, Bn4
	.byte	W18
	.byte	W03
	.byte		N06	, An3
	.byte		N13	, Cn4
	.byte		N13	, Fs4
	.byte	W12
	.byte		N24	, An3
	.byte	W12
	.byte		N11	, Cn4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W12
	.byte		N17	, An4
	.byte	W24
	.byte	W03
	.byte		N04	, Bn3
	.byte		N14	, Dn4
	.byte		N15	, Fs4
	.byte	W12
	.byte		N16	, An3
	.byte	W06
	.byte	W09
	.byte		N13	, Bn3
	.byte	W12
	.byte		N04	, Dn4
	.byte	W15
	.byte		N12	, Fs4
	.byte	W18
	.byte		N04	, Dn4
	.byte	W15
	.byte		N05	, Gn3
	.byte		N12	, Cn4
	.byte		N10	, En4
	.byte	W12
	.byte		N13	, Gn3
	.byte	W12
	.byte		N09	, Fs4
	.byte	W03
	.byte	W09
	.byte		N08	, Gn3
	.byte	W12
	.byte		N16	, Gn4
	.byte	W12
	.byte		N05	, Gn3
	.byte	W15
	.byte		N06	, An3
	.byte		N14	, Dn4
	.byte		N15	, Fs4
	.byte	W15
	.byte		N09	, An3
	.byte	W12
	.byte		N17	
	.byte		N12	, En4
	.byte	W21
	.byte	W06
	.byte		N14	, An3
	.byte		N13	, Dn4
	.byte	W30
	.byte		N06	, Gn3
	.byte		N11	, Cn4
	.byte		N13	, Dn4
	.byte		N13	, En4
	.byte	W15
	.byte		N22	, Gn3
	.byte	W12
	.byte		N12	, Cn4
	.byte	W12
	.byte		N05	, En4
	.byte	W12
	.byte		N17	, Bn4
	.byte	W09
	.byte	W15
	.byte		N06	, Dn4
	.byte		N11	, Fs4
	.byte		N14	, Bn4
	.byte	W12
	.byte		N12	, Dn4
	.byte	W09
	.byte		N11	, Fs4
	.byte	W12
	.byte		N09	, Dn4
	.byte	W15
	.byte		N13	, Bn4
	.byte	W09
	.byte		N03	, Dn4
	.byte	W15
	.byte		N06	, Bn3
	.byte		N13	, Ds4
	.byte		N13	, Fs4
	.byte	W09
	.byte	W03
	.byte		N20	, Bn3
	.byte	W12
	.byte		N06	, Fs4
	.byte	W12
	.byte			Bn3
	.byte		N06	, Gn4
	.byte	W15
	.byte		N19	, Bn3
	.byte		N14	, An4
	.byte	W24
	.byte		N06	, Bn3
	.byte		N11	, En4
	.byte		N12	, Gn4
	.byte	W09
	.byte		N09	, Bn3
	.byte	W15
	.byte		N09	
	.byte		N10	, Fs4
	.byte	W06
	.byte	W06
	.byte		N05	, Bn3
	.byte	W12
	.byte		N04	
	.byte		N09	, En4
	.byte		N10	, Gn4
	.byte	W12
	.byte		N03	, Bn3
	.byte	W12
	.byte		N04	, Cn4
	.byte		N12	, En4
	.byte		N11	, Gn4
	.byte		N11	, Bn4
	.byte	W12
	.byte		N23	, Cn4
	.byte	W12
	.byte		N11	, En4
	.byte	W12
	.byte		N02	, Gn4
	.byte	W15
	.byte		N05	
	.byte		N11	, Bn4
	.byte		N12	, En5
	.byte	W03
	.byte	W09
	.byte		N02	, Gn4
	.byte	W15
	.byte		N07	, Fs4
	.byte		N13	, An4
	.byte		N13	, Bn4
	.byte		N16	, Dn5
	.byte	W12
	.byte		N44	, Fs3
	.byte	W12
	.byte		N36	, Bn3
	.byte	W12
	.byte		N28	, Dn4
	.byte	W12
	.byte		N09	, Fs4
	.byte	W12
	.byte		N05	, Bn4
	.byte	W12
	.byte	W03
	.byte		N04	, Cn4
	.byte		N13	, En4
	.byte		N14	, Gn4
	.byte		N16	, Bn4
	.byte	W12
	.byte		N19	, Cn4
	.byte	W15
	.byte		N10	, En4
	.byte		N12	, An4
	.byte	W12
	.byte		N08	, Cn4
	.byte	W12
	.byte		N06	
	.byte		N11	, En4
	.byte		N12	, Gn4
	.byte	W30
	.byte		N06	, En4
	.byte		N13	, Fs4
	.byte		N13	, An4
	.byte		N14	, Bn4
	.byte	W12
	.byte		N40	, En4
	.byte	W15
	.byte		N24	, Fs4
	.byte	W12
	.byte		N12	, An4
	.byte	W15
	.byte		N18	, Bn4
	.byte	W12
	.byte		N11	, En4
	.byte	W21
	.byte		TIE	, Ds4
	.byte		TIE	, Fs4
	.byte		TIE	, Bn4
	.byte	W21
	.byte	W96
	.byte	W54
	.byte		EOT	, Ds4
	.byte			Fs4
	.byte			Bn4
	.byte	W42
	.byte	GOTO	
		.word	song_0023_2_1
	.byte	FINE

	.align 2
	.global song_0023
song_0023:	@ 0x087DA234
	.byte	2		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	208		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0023_1		@ track
	.word	song_0023_2		@ track
