	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0021_1
song_0021_1:	@ 0x087D96E0
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0021_1_2:
	.byte	TEMPO	, 90
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		N08	, Gn4, v127
	.byte	W24
	.byte			Cn4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N13	, Fn4
	.byte	W12
	.byte		N14	, En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N11	, Cn4
	.byte	W12
	.byte		N40	, An3
	.byte	W36
	.byte		N15	, Bn3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte		N12	, En4
	.byte	W12
	.byte		N09	, Dn4
	.byte	W24
	.byte		N24	, En4
	.byte	W24
	.byte		N22	, Fn4
	.byte	W24
	.byte		N06	, Gn4
	.byte	W24
	.byte		N08	, Cn4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N12	, Fn4
	.byte	W12
	.byte		N14	, En4
	.byte	W12
	.byte		N13	, Dn4
	.byte	W12
	.byte		N12	, En4
	.byte	W12
	.byte		N09	, Fn4
	.byte	W24
	.byte		N24	, An3
	.byte	W24
	.byte			Cn4
	.byte	W24
	.byte		N12	, Dn4
	.byte	W24
	.byte		N28	, En4
	.byte	W24
	.byte		N24	, Fn4
	.byte	W24
	.byte		N68	, Gn4
	.byte	W66
	.byte		N09	, As4
	.byte	W06
song_0021_1_1:
	.byte		N44	, Bn4, v127
	.byte	W48
	.byte		N24	, An4
	.byte	W24
	.byte	PEND
	.byte		N80	, Fn4
	.byte	W72
	.byte	W24
	.byte		N15	
	.byte	W12
	.byte		N14	, En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N11	, En4
	.byte	W12
	.byte		N22	, Fn4
	.byte	W24
	.byte		N24	, Gn4
	.byte	W24
	.byte		N23	, An4
	.byte	W24
	.byte		N24	, Bn4
	.byte	W24
	.byte			Cn5
	.byte	W24
	.byte		N19	, Dn5
	.byte	W24
	.byte		N56	, En5
	.byte	W60
	.byte		N10	, Fn5
	.byte	W06
	.byte			En5
	.byte	W06
	.byte		N44	, Dn5
	.byte	W72
	.byte		N07	, Gn4
	.byte	W24
	.byte			Cn4
	.byte	W24
	.byte		N08	, An4
	.byte	W24
	.byte		N24	, Gn4
	.byte	W24
	.byte		N14	, Fn4
	.byte	W12
	.byte		N12	, En4
	.byte	W12
	.byte		N11	, Dn4
	.byte	W12
	.byte		N08	, Cn4
	.byte	W12
	.byte		N36	, An3
	.byte	W36
	.byte		N14	, Bn3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte		N16	, En4
	.byte	W12
	.byte		N13	, Dn4
	.byte	W24
	.byte		N24	, En4
	.byte	W24
	.byte			Fn4
	.byte	W24
	.byte		N09	, Gn4
	.byte	W24
	.byte		N06	, Cn4
	.byte	W24
	.byte		N08	, An4
	.byte	W24
	.byte		N10	, Gn4
	.byte	W24
	.byte		N14	, Fn4
	.byte	W12
	.byte		N12	, En4
	.byte	W12
	.byte		N15	, Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		N09	, Fn4
	.byte	W24
	.byte		N24	, An3
	.byte	W24
	.byte		N28	, Cn4
	.byte	W24
	.byte		N16	, Dn4
	.byte	W24
	.byte		N24	, En4
	.byte	W24
	.byte			Fn4
	.byte	W24
	.byte		N60	, Gn4
	.byte	W60
	.byte		N11	, An4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte	PATT	
		.word	song_0021_1_1
	.byte		N80	, Fn4, v127
	.byte	W72
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		N24	, Fn4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N23	, An4
	.byte	W24
	.byte		N22	
	.byte	W24
	.byte			Bn4
	.byte	W24
	.byte			Cn5
	.byte	W24
	.byte		N16	
	.byte	W36
	.byte		N11	, Bn4
	.byte	W12
	.byte		N24	, An4
	.byte	W24
	.byte		N68	, Gn4
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W24
	.byte		N06	, Fn5
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte		N06	
	.byte	W48
	.byte		N07	
	.byte	W24
	.byte	W72
	.byte	W72
	.byte	W24
	.byte		N05	, En5
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N05	
	.byte	W24
	.byte		N06	
	.byte	W48
	.byte		N07	
	.byte	W24
	.byte	W72
	.byte	W72
	.byte	W24
	.byte		N06	, Fn5
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W24
	.byte		N05	
	.byte	W24
	.byte		N12	, Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			An4
	.byte	W24
	.byte			Bn4
	.byte	W24
	.byte		N11	, Cn5
	.byte	W24
	.byte		N22	, Bn4
	.byte	W24
	.byte			Cn5
	.byte	W24
	.byte			Dn5
	.byte	W24
	.byte	GOTO	
		.word	song_0021_1_2
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0021_2
song_0021_2:	@ 0x087D985B
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0021_2_1:
	.byte	W24
	.byte		N04	, Gn2, v127
	.byte		N04	, En3
	.byte	W12
	.byte			Gn2
	.byte		N04	, En3
	.byte	W12
	.byte			Gn2
	.byte		N04	, En3
	.byte	W24
	.byte	PEND
song_0021_2_2:
	.byte		N04	, Gn2, v127
	.byte		N04	, En3
	.byte	W48
	.byte			Gn2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0021_2_1
	.byte	PATT	
		.word	song_0021_2_2
	.byte	PATT	
		.word	song_0021_2_1
song_0021_2_6:
	.byte		N04	, Gn2, v127
	.byte		N04	, En3
	.byte	W48
	.byte			Gn2
	.byte		N04	, Cn3
	.byte	W24
	.byte	PEND
song_0021_2_7:
	.byte	W24
	.byte		N04	, An2, v127
	.byte		N04	, Cn3
	.byte	W12
	.byte			An2
	.byte		N04	, Cn3
	.byte	W12
	.byte			An2
	.byte		N04	, Cn3
	.byte	W24
	.byte	PEND
song_0021_2_8:
	.byte		N04	, Gn2, v127
	.byte		N04	, Bn2
	.byte	W48
	.byte			Gn2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0021_2_1
song_0021_2_3:
	.byte		N04	, Gn2, v127
	.byte		N04	, En3
	.byte	W48
	.byte			Gn2
	.byte		N04	, En3
	.byte	W24
	.byte	PEND
song_0021_2_4:
	.byte	W24
	.byte		N04	, An2, v127
	.byte		N04	, Fn3
	.byte	W12
	.byte			An2
	.byte		N04	, Fn3
	.byte	W12
	.byte			An2
	.byte		N04	, Fn3
	.byte	W24
	.byte	PEND
song_0021_2_9:
	.byte		N04	, Gn2, v127
	.byte		N04	, Fn3
	.byte	W48
	.byte			Gn2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0021_2_1
	.byte	PATT	
		.word	song_0021_2_3
	.byte	PATT	
		.word	song_0021_2_4
song_0021_2_5:
	.byte		N04	, An2, v127
	.byte		N04	, Fn3
	.byte	W48
	.byte			An2
	.byte		N04	, Fn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0021_2_4
	.byte	PATT	
		.word	song_0021_2_5
song_0021_2_10:
	.byte	W24
	.byte		N04	, Gn2, v127
	.byte		N04	, En3
	.byte	W12
	.byte			Gn2
	.byte		N04	, Dn3
	.byte	W12
	.byte			Gn2
	.byte		N04	, Cn3
	.byte	W24
	.byte	PEND
song_0021_2_11:
	.byte		N04	, Gn2, v127
	.byte		N04	, Bn2
	.byte	W24
	.byte			Gn2
	.byte		N04	, Cn3
	.byte	W24
	.byte			Gn2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0021_2_1
	.byte	PATT	
		.word	song_0021_2_6
	.byte	PATT	
		.word	song_0021_2_7
	.byte	PATT	
		.word	song_0021_2_8
	.byte	PATT	
		.word	song_0021_2_1
	.byte	PATT	
		.word	song_0021_2_3
	.byte	PATT	
		.word	song_0021_2_4
	.byte	PATT	
		.word	song_0021_2_9
	.byte	PATT	
		.word	song_0021_2_1
	.byte	PATT	
		.word	song_0021_2_3
	.byte	PATT	
		.word	song_0021_2_4
	.byte	PATT	
		.word	song_0021_2_5
	.byte	PATT	
		.word	song_0021_2_4
	.byte	PATT	
		.word	song_0021_2_5
	.byte	PATT	
		.word	song_0021_2_10
	.byte	PATT	
		.word	song_0021_2_11
	.byte		N08	, En2, v127
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			As2
	.byte	W12
	.byte			An2
	.byte	W24
	.byte			Gn2
	.byte	W24
	.byte			En2
	.byte	W24
	.byte			Dn2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte	W24
	.byte		N08	
	.byte	W24
	.byte			Gn2
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			Dn2
	.byte	W12
song_0021_2_12:
	.byte	W24
	.byte		N04	, Gn2, v127
	.byte		N04	, Dn3
	.byte	W12
	.byte			Gn2
	.byte		N04	, Dn3
	.byte	W12
	.byte			Gn2
	.byte		N04	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0021_2_6
	.byte	PATT	
		.word	song_0021_2_12
	.byte		N04	, Gn2, v127
	.byte		N04	, Dn3
	.byte	W48
	.byte			Gn2
	.byte		N04	, Cn3
	.byte	W24
	.byte	PATT	
		.word	song_0021_2_12
	.byte	PATT	
		.word	song_0021_2_6
	.byte	W24
	.byte		N04	, Fn2, v127
	.byte		N04	, Cn3
	.byte	W12
	.byte			Fn2
	.byte		N04	, Cn3
	.byte	W12
	.byte			Fn2
	.byte		N04	, Cn3
	.byte	W24
	.byte			Fn2
	.byte		N04	, Bn2
	.byte	W24
	.byte			Fn2
	.byte		N04	, Cn3
	.byte	W24
	.byte			Fn2
	.byte		N04	, Dn3
	.byte	W24
	.byte	GOTO	
		.word	song_0021_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0021_3
song_0021_3:	@ 0x087D9A16
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0021_3_2:
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte		N68	, En3, v127
	.byte		N68	, As3
	.byte	W72
song_0021_3_1:
	.byte		N22	, En3, v127
	.byte		N22	, An3
	.byte	W48
	.byte			Cs4
	.byte		N22	, En4
	.byte	W24
	.byte	PEND
	.byte		TIE	, Dn4
	.byte		TIE	, Fn4
	.byte	W72
	.byte	W44
	.byte	W02
	.byte		EOT	, Dn4
	.byte			Fn4
	.byte	W24
	.byte	W02
	.byte		N68	, Dn3
	.byte		N68	, Gs3
	.byte	W72
	.byte		N22	, Dn3
	.byte		N22	, Gn3
	.byte	W48
	.byte			Bn3
	.byte		N22	, Dn4
	.byte	W24
	.byte		TIE	, Cn4
	.byte		TIE	, En4
	.byte	W72
	.byte	W44
	.byte	W02
	.byte		EOT	, Cn4
	.byte			En4
	.byte	W24
	.byte	W02
	.byte		N68	, En3
	.byte		N68	, As3
	.byte	W72
	.byte	PATT	
		.word	song_0021_3_1
	.byte		N92	, Dn4, v127
	.byte		N92	, Fn4
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	GOTO	
		.word	song_0021_3_2
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0021_4
song_0021_4:	@ 0x087D9A95
	.byte	KEYSH	, 0
	.byte	VOICE	, 19
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0021_4_9:
	.byte		N72	, Cn3, v127
	.byte	W72
song_0021_4_1:
	.byte	W24
	.byte		N24	, Gn3, v127
	.byte	W24
	.byte			Gn2
	.byte	W24
	.byte	PEND
	.byte		N72	, Cn3
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_1
	.byte		N72	, Cn3, v127
	.byte	W72
song_0021_4_2:
	.byte	W24
	.byte		N24	, Cn3, v127
	.byte	W24
	.byte			En2
	.byte	W24
	.byte	PEND
	.byte		N72	, Fn2
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_1
	.byte		N72	, Cn3, v127
	.byte	W72
song_0021_4_3:
	.byte	W24
	.byte		N24	, Cn3, v127
	.byte	W24
	.byte			Cs3
	.byte	W24
	.byte	PEND
	.byte		N72	, Dn3
	.byte	W72
song_0021_4_4:
	.byte	W24
	.byte		N24	, Gn2, v127
	.byte	W24
	.byte			Fn2
	.byte	W24
	.byte	PEND
	.byte		N72	, En2
	.byte	W72
song_0021_4_5:
	.byte	W24
	.byte		N24	, An3, v127
	.byte	W24
	.byte			An2
	.byte	W24
	.byte	PEND
	.byte		N72	, Dn3
	.byte	W72
song_0021_4_6:
	.byte	W24
	.byte		N24	, An2, v127
	.byte	W24
	.byte			Gn2
	.byte	W24
	.byte	PEND
	.byte		N72	, Fn2
	.byte	W72
song_0021_4_7:
	.byte	W24
	.byte		N24	, Fn3, v127
	.byte	W24
	.byte			Fn2
	.byte	W24
	.byte	PEND
	.byte		N72	, Gn2
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_1
	.byte		N72	, Cn3, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_2
	.byte		N72	, Fn2, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_1
	.byte		N72	, Cn3, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_3
	.byte		N72	, Dn3, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_4
	.byte		N72	, En2, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_5
	.byte		N72	, Dn3, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_6
	.byte		N72	, Fn2, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_7
	.byte		N72	, Gn2, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_4
	.byte		N68	, En2, v127
	.byte	W72
song_0021_4_8:
	.byte	W24
	.byte		N24	, An2, v127
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte	PEND
	.byte		N68	, Dn3
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_5
	.byte		N68	, Gn2, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_1
	.byte		N68	, Cn3, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_4
	.byte		N68	, En2, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_8
	.byte		N68	, Dn3, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_5
	.byte		N68	, Gn2, v127
	.byte	W72
	.byte	PATT	
		.word	song_0021_4_1
	.byte		N68	, Gn2, v127
	.byte	W72
	.byte		N24	
	.byte	W24
	.byte			An2
	.byte	W24
	.byte			Bn2
	.byte	W24
	.byte	GOTO	
		.word	song_0021_4_9
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0021_5
song_0021_5:	@ 0x087D9B9F
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0021_5_1:
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Cs8
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte	PEND
song_0021_5_2:
	.byte		N06	, Cs8, v127
	.byte	W24
	.byte		N48	, An7
	.byte	W48
	.byte	PEND
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	PATT	
		.word	song_0021_5_1
	.byte	PATT	
		.word	song_0021_5_2
	.byte	GOTO	
		.word	song_0021_5_1
	.byte	FINE

	.align 2
	.global song_0021
song_0021:	@ 0x087D9CC0
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0021_1		@ track
	.word	song_0021_2		@ track
	.word	song_0021_3		@ track
	.word	song_0021_4		@ track
	.word	song_0021_5		@ track
