	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0016_1
song_0016_1:	@ 0x087D7D98
	.byte	KEYSH	, 0
	.byte	TEMPO	, 61
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte	W96
	.byte	W96
song_0016_1_1:
	.byte	W48
	.byte		N14	, Gn4, v127
	.byte	W12
	.byte		N04	, Bn4
	.byte	W24
	.byte		N48	, An4
	.byte	W12
	.byte	W36
	.byte		N08	, Gn4
	.byte	W06
	.byte		N07	, Fs4
	.byte	W06
	.byte		N32	, En4
	.byte	W48
	.byte			Gn4
	.byte	W36
	.byte		N07	, Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N14	, Fs4
	.byte	W12
	.byte		N05	, Dn4
	.byte	W24
	.byte		N90	, Bn3
	.byte	W12
	.byte	W96
	.byte	W48
	.byte		N12	, Gn4
	.byte	W12
	.byte		N06	, Bn4
	.byte	W24
	.byte		N48	, An4
	.byte	W12
	.byte	W36
	.byte		N07	, Gn4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte		N32	, En4
	.byte	W48
	.byte		N36	, Gn4
	.byte	W36
	.byte		N08	, Fs4
	.byte	W06
	.byte		N07	, Gn4
	.byte	W06
	.byte		N13	, Fs4
	.byte	W12
	.byte		N02	, Dn4
	.byte	W12
	.byte		N13	, Bn3
	.byte	W12
	.byte		N84	, En4
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N13	, Bn4
	.byte	W24
	.byte		N09	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N08	, An4
	.byte	W18
	.byte		N15	, Bn4
	.byte	W36
	.byte		N13	
	.byte	W24
	.byte		N11	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N04	, An4
	.byte	W12
	.byte		N14	, Bn4
	.byte	W42
	.byte		N13	
	.byte	W24
	.byte		N12	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N08	, Fs4
	.byte	W18
	.byte		N08	
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte		N06	, An4
	.byte	W06
	.byte		N72	, Gn4
	.byte	W06
	.byte	W96
	.byte		N13	, Bn4
	.byte	W24
	.byte		N10	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N04	, An4
	.byte	W12
	.byte		N14	, Bn4
	.byte	W42
	.byte		N14	
	.byte	W24
	.byte		N10	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N05	, An4
	.byte	W12
	.byte		N13	, Bn4
	.byte	W42
	.byte		N15	
	.byte	W24
	.byte		N11	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N05	, Fs4
	.byte	W18
	.byte		N05	
	.byte	W12
	.byte		N07	, Gn4
	.byte	W12
	.byte		N05	, An4
	.byte	W06
	.byte		N66	, Gn4
	.byte	W06
	.byte	W84
	.byte		N05	, An4
	.byte	W12
	.byte		N14	, Bn4
	.byte	W24
	.byte		N10	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N04	, An4
	.byte	W12
	.byte		N07	, Bn4
	.byte	W24
	.byte		N05	, Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N06	, An4
	.byte	W06
	.byte		N15	, Bn4
	.byte	W24
	.byte		N09	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N04	, An4
	.byte	W12
	.byte			Bn4
	.byte	W42
	.byte		N16	
	.byte	W24
	.byte		N09	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N05	, Fs4
	.byte	W18
	.byte		N05	
	.byte	W12
	.byte		N06	, Gn4
	.byte	W12
	.byte			An4
	.byte	W06
	.byte		N56	, Gn4
	.byte	W06
	.byte	W54
	.byte		N06	, Bn3
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N15	, Bn4
	.byte	W24
	.byte		N09	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N03	, An4
	.byte	W12
	.byte		N06	, Bn4
	.byte	W24
	.byte			Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N16	, Bn4
	.byte	W24
	.byte		N12	, An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte		N05	, An4
	.byte	W12
	.byte		N16	, Bn4
	.byte	W42
	.byte		N16	
	.byte	W24
	.byte		N06	, An4
	.byte	W12
	.byte			Gn4
	.byte	W06
	.byte		N05	, Fs4
	.byte	W18
	.byte		N05	
	.byte	W12
	.byte		N06	, Gn4
	.byte	W12
	.byte			An4
	.byte	W06
	.byte		TIE	, Gn4
	.byte	W06
	.byte	W96
	.byte	W96
	.byte	W07
	.byte		EOT	
	.byte	W88
	.byte	W01
	.byte	W96
	.byte	GOTO	
		.word	song_0016_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0016_2
song_0016_2:	@ 0x087D7F0B
	.byte	KEYSH	, 0
	.byte	VOICE	, 9
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
	.byte	W96
	.byte	W96
song_0016_2_9:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	VOICE	, 8
	.byte	W54
	.byte		N06	, Bn3, v127
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			An4
	.byte	W06
song_0016_2_1:
	.byte		N36	, Bn4, v127
	.byte	W36
	.byte		N60	, En4
	.byte	W60
	.byte	PEND
song_0016_2_6:
	.byte	W24
	.byte		N24	, Gn4, v127
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte		N12	, Gn4
	.byte	W12
	.byte		N48	, Fs4
	.byte	W12
	.byte	PEND
song_0016_2_7:
	.byte	W36
	.byte		TIE	, Dn4, v127
	.byte	W60
	.byte	PEND
	.byte	W48
	.byte		EOT	
	.byte	W12
	.byte		N12	, Fs4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte	PATT	
		.word	song_0016_2_1
	.byte	W24
	.byte		N24	, Gn4, v127
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte		N12	, Gn4
	.byte	W12
	.byte		N84	, Fs4
	.byte	W12
	.byte	W84
	.byte		N12	
	.byte	W12
	.byte		N18	, An4
	.byte	W18
	.byte			Gn4
	.byte	W18
	.byte		N12	, Fs4
	.byte	W48
	.byte	VOICE	, 9
	.byte	W12
song_0016_2_2:
	.byte		N04	, En3, v072
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Bn3
	.byte	W06
	.byte			Gn3
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			Bn3
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_2_2
	.byte	PATT	
		.word	song_0016_2_2
	.byte		N04	, En3, v072
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			An3
	.byte	W06
	.byte			Bn2
	.byte	W06
	.byte			Bn3
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			Bn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			Fs3
	.byte	W06
	.byte			Bn3
	.byte	W06
	.byte			Bn2
	.byte	W06
	.byte			Bn3
	.byte	W06
song_0016_2_3:
	.byte		N04	, En3, v072
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Bn3
	.byte	W06
	.byte			Gn3
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			Bn3
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte	PEND
song_0016_2_4:
	.byte		N04	, En3, v072
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			An3
	.byte	W06
	.byte			En3
	.byte	W12
	.byte			Bn3
	.byte	W06
	.byte			An3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte	PEND
song_0016_2_5:
	.byte		N04	, En3, v072
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Bn3
	.byte	W06
	.byte			An3
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			Bn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_2_2
	.byte	PATT	
		.word	song_0016_2_3
	.byte	PATT	
		.word	song_0016_2_4
	.byte	PATT	
		.word	song_0016_2_5
	.byte		N04	, En3, v072
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Bn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte	VOICE	, 8
	.byte	W06
	.byte		N06	, Bn3, v127
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			An4
	.byte	W06
	.byte	PATT	
		.word	song_0016_2_1
	.byte	PATT	
		.word	song_0016_2_6
	.byte	PATT	
		.word	song_0016_2_7
	.byte	W48
	.byte		EOT	, Dn4
	.byte	W12
	.byte		N12	, Fs4, v127
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte	PATT	
		.word	song_0016_2_1
	.byte	W24
	.byte		N24	, Gn4, v127
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte		N12	, Gn4
	.byte	W12
	.byte		TIE	, Fs4
	.byte	W12
	.byte	W96
	.byte		EOT	
	.byte	W48
	.byte		N18	
	.byte	W18
	.byte			Dn4
	.byte	W18
	.byte		N12	, Bn3
	.byte	W12
	.byte		N96	, En4
	.byte	W96
	.byte	W72
	.byte	VOICE	, 9
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
song_0016_2_8:
	.byte		N04	, En3, v092
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Bn3
	.byte	W06
	.byte			Gn3
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			Bn3
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte	PEND
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT	
		.word	song_0016_2_8
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT	
		.word	song_0016_2_8
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0016_2_9
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0016_3
song_0016_3:	@ 0x087D8098
	.byte	KEYSH	, 0
	.byte	VOICE	, 3
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W06
song_0016_3_1:
	.byte		N04	, En4, v092
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Bn4
	.byte	W06
	.byte			Gn4
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			Bn4
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_3_1
song_0016_3_2:
	.byte		N04	, En4, v092
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Bn4
	.byte	W06
	.byte			Gn4
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			Bn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte	PEND
song_0016_3_3:
	.byte		N04	, En4, v092
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			An4
	.byte	W06
	.byte			En4
	.byte	W12
	.byte			Bn4
	.byte	W06
	.byte			An4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte	PEND
song_0016_3_4:
	.byte		N04	, En4, v092
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Bn4
	.byte	W06
	.byte			An4
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			Bn4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_3_1
	.byte	PATT	
		.word	song_0016_3_2
	.byte	PATT	
		.word	song_0016_3_3
	.byte	PATT	
		.word	song_0016_3_4
	.byte		N04	, En4, v092
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Bn4
	.byte	W06
	.byte			En4
	.byte	W54
song_0016_3_5:
	.byte		N04	, Bn5, v092
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			An5
	.byte	W12
	.byte			Bn5
	.byte	W12
	.byte			An5
	.byte	W06
	.byte			Bn5
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			An5
	.byte	W12
	.byte			Bn5
	.byte	W12
	.byte			An5
	.byte	W12
	.byte	PEND
song_0016_3_6:
	.byte		N04	, Bn5, v092
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			An5
	.byte	W12
	.byte			Bn5
	.byte	W12
	.byte			An5
	.byte	W06
	.byte			Bn5
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte			An5
	.byte	W12
	.byte			Bn5
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_3_5
	.byte	PATT	
		.word	song_0016_3_6
	.byte	PATT	
		.word	song_0016_3_5
	.byte	PATT	
		.word	song_0016_3_6
	.byte	PATT	
		.word	song_0016_3_5
	.byte		N12	, An5, v092
	.byte	W18
	.byte			Gn5
	.byte	W18
	.byte		N08	, Fs5
	.byte	W60
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W48
	.byte		N12	, Gn4, v127
	.byte	W12
	.byte		N08	, Bn4
	.byte	W24
	.byte		N48	, An4
	.byte	W12
	.byte	W36
	.byte		N07	, Gn4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte		N36	, En4
	.byte	W48
	.byte		N32	, Gn4
	.byte	W36
	.byte		N07	, Fs4
	.byte	W06
	.byte		N09	, Gn4
	.byte	W06
	.byte		N13	, Fs4
	.byte	W12
	.byte		N06	, Dn4
	.byte	W24
	.byte		TIE	, Bn3
	.byte	W12
	.byte	W84
	.byte		N02	, An3
	.byte	W01
	.byte		EOT	, Bn3
	.byte	W11
	.byte	W48
	.byte		N12	, Gn4
	.byte	W12
	.byte		N07	, Bn4
	.byte	W24
	.byte		N48	, An4
	.byte	W12
	.byte	W36
	.byte		N06	, Gn4
	.byte	W06
	.byte		N07	, Fs4
	.byte	W06
	.byte		N36	, En4
	.byte	W48
	.byte			Gn4
	.byte	W36
	.byte		N07	, Fs4
	.byte	W06
	.byte		N08	, Gn4
	.byte	W06
	.byte		N13	, Fs4
	.byte	W12
	.byte		N04	, Dn4
	.byte	W12
	.byte		N12	, Bn3
	.byte	W12
	.byte		N84	, En4
	.byte	W12
	.byte	W96
	.byte	PATT	
		.word	song_0016_3_5
	.byte	PATT	
		.word	song_0016_3_6
	.byte	PATT	
		.word	song_0016_3_5
	.byte	PATT	
		.word	song_0016_3_6
	.byte	PATT	
		.word	song_0016_3_5
	.byte	PATT	
		.word	song_0016_3_6
	.byte	PATT	
		.word	song_0016_3_5
	.byte	PATT	
		.word	song_0016_3_5
	.byte	PATT	
		.word	song_0016_3_5
	.byte		N04	, Bn5, v092
	.byte	W96
song_0016_3_7:
	.byte	W54
	.byte		N06	, En5, v092
	.byte	W06
	.byte			Fs5
	.byte	W12
	.byte			Gn5
	.byte	W06
	.byte			An5
	.byte	W06
	.byte			Bn5
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_3_7
	.byte	W96
song_0016_3_8:
	.byte	W42
	.byte		N06	, Dn6, v092
	.byte	W12
	.byte			En6
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N02	, Bn5
	.byte	W06
	.byte		N06	, An5
	.byte	W06
	.byte		N04	, Gn5
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0016_3_7
	.byte	PATT	
		.word	song_0016_3_7
	.byte	W96
	.byte	W48
	.byte		N06	, Dn5, v092
	.byte	W06
	.byte			En5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			En5
	.byte	W30
	.byte	PATT	
		.word	song_0016_3_7
	.byte	PATT	
		.word	song_0016_3_7
	.byte	W96
	.byte	PATT	
		.word	song_0016_3_8
	.byte	PATT	
		.word	song_0016_3_7
	.byte	PATT	
		.word	song_0016_3_7
	.byte	W96
	.byte	PATT	
		.word	song_0016_3_1
	.byte	PATT	
		.word	song_0016_3_1
	.byte	PATT	
		.word	song_0016_3_1
	.byte	PATT	
		.word	song_0016_3_1
	.byte	GOTO	
		.word	song_0016_3_2
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0016_4
song_0016_4:	@ 0x087D8267
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
	.byte	W96
	.byte	W84
	.byte		N12	, Bn1, v127
	.byte	W12
song_0016_4_1:
	.byte		N18	, En1, v127
	.byte	W18
	.byte		N06	, En2
	.byte	W18
	.byte		N12	, Bn1
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte	PEND
song_0016_4_2:
	.byte		N18	, En1, v127
	.byte	W18
	.byte		N06	, En2
	.byte	W18
	.byte		N12	
	.byte	W36
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte	PEND
song_0016_4_3:
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte		N06	, Gn1
	.byte	W18
	.byte		N12	, Cn2
	.byte	W24
	.byte		N06	, Dn2
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte	PEND
song_0016_4_4:
	.byte		N18	, En1, v127
	.byte	W18
	.byte		N06	, En2
	.byte	W18
	.byte		N12	, Bn1
	.byte	W18
	.byte		N06	, An1
	.byte	W06
	.byte			Bn1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An1
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0016_4_1
	.byte	PATT	
		.word	song_0016_4_2
	.byte	PATT	
		.word	song_0016_4_3
	.byte	PATT	
		.word	song_0016_4_4
song_0016_4_5:
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W24
	.byte			Gn2
	.byte	W24
	.byte		N12	, Gn1
	.byte	W12
	.byte	PEND
song_0016_4_6:
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W24
	.byte			Gn2
	.byte	W24
	.byte		N12	, Cn2
	.byte	W12
	.byte	PEND
song_0016_4_7:
	.byte		N18	, Bn1, v127
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W24
	.byte			Fs2
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte	PEND
song_0016_4_9:
	.byte		N18	, Bn1, v127
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte			An1
	.byte	W06
	.byte			Bn1
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			An1
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0016_4_5
	.byte	PATT	
		.word	song_0016_4_6
	.byte	PATT	
		.word	song_0016_4_7
song_0016_4_10:
	.byte		N18	, Bn1, v127
	.byte	W18
	.byte			Bn2
	.byte	W18
	.byte		N12	, Bn1
	.byte	W48
	.byte		N06	, An1
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte	PEND
song_0016_4_8:
	.byte		N18	, En1, v127
	.byte	W18
	.byte		N06	, En2
	.byte	W12
	.byte		N01	, Bn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte			An1
	.byte	W06
	.byte			Bn1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An1
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0016_4_8
	.byte	PATT	
		.word	song_0016_4_8
	.byte		N18	, En1, v127
	.byte	W18
	.byte		N06	, En2
	.byte	W12
	.byte		N01	, Bn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			En2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, An1
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte			En2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, An1
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte	PATT	
		.word	song_0016_4_1
	.byte	PATT	
		.word	song_0016_4_2
	.byte	PATT	
		.word	song_0016_4_3
	.byte	PATT	
		.word	song_0016_4_4
	.byte	PATT	
		.word	song_0016_4_1
	.byte	PATT	
		.word	song_0016_4_2
	.byte	PATT	
		.word	song_0016_4_3
	.byte	PATT	
		.word	song_0016_4_4
	.byte	PATT	
		.word	song_0016_4_5
	.byte	PATT	
		.word	song_0016_4_6
	.byte	PATT	
		.word	song_0016_4_7
	.byte	PATT	
		.word	song_0016_4_9
	.byte	PATT	
		.word	song_0016_4_5
	.byte	PATT	
		.word	song_0016_4_6
	.byte	PATT	
		.word	song_0016_4_7
	.byte	PATT	
		.word	song_0016_4_10
	.byte	PATT	
		.word	song_0016_4_1
	.byte		N18	, En2, v127
	.byte	W18
	.byte			En1
	.byte	W18
	.byte		N12	
	.byte	W60
song_0016_4_11:
	.byte		N18	, En1, v127
	.byte	W18
	.byte		N06	, En2
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte			Dn2
	.byte	W06
	.byte			En2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N12	, Bn1
	.byte	W12
	.byte	PEND
song_0016_4_12:
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte			Gn1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Gn1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte	PEND
song_0016_4_13:
	.byte		N18	, Dn2, v127
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte			An1
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, An1
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte	PEND
song_0016_4_14:
	.byte		N18	, En2, v127
	.byte	W18
	.byte		N06	, En1
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Fs1
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Gn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte		N12	, Bn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_4_11
	.byte	PATT	
		.word	song_0016_4_12
	.byte	PATT	
		.word	song_0016_4_13
	.byte	PATT	
		.word	song_0016_4_14
	.byte	PATT	
		.word	song_0016_4_11
	.byte	PATT	
		.word	song_0016_4_12
	.byte	PATT	
		.word	song_0016_4_13
	.byte	PATT	
		.word	song_0016_4_14
	.byte	PATT	
		.word	song_0016_4_11
	.byte	PATT	
		.word	song_0016_4_12
	.byte	PATT	
		.word	song_0016_4_13
	.byte		TIE	, En2, v127
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte	W84
	.byte		N12	, Bn1
	.byte	W12
	.byte	GOTO	
		.word	song_0016_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0016_5
song_0016_5:	@ 0x087D846E
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
song_0016_5_1:
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W36
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0016_5_8:
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W30
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W12
	.byte	PEND
song_0016_5_9:
	.byte		N06	, Cn1, v116
	.byte		N24	, Cs2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W18
	.byte		N06	
	.byte	W36
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte		N06	, Cn1, v116
	.byte		N23	, Cs2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W18
	.byte		N06	
	.byte	W36
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte		N06	, Cn1, v116
	.byte		N30	, An2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W18
	.byte		N06	
	.byte	W36
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_1
	.byte	PATT	
		.word	song_0016_5_1
	.byte		N06	, Cn2, v116
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W30
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W12
song_0016_5_3:
	.byte		N06	, Cn1, v116
	.byte		N24	, An2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0016_5_2:
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_5_2
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte		N32	, An2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W36
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_2
	.byte	PATT	
		.word	song_0016_5_2
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_3
	.byte	PATT	
		.word	song_0016_5_2
	.byte	PATT	
		.word	song_0016_5_2
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			Cn1
	.byte	W03
	.byte		N03	, An1
	.byte	W03
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W12
song_0016_5_4:
	.byte		N06	, Cn1, v116
	.byte		N24	, An2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W36
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_5_2
	.byte	PATT	
		.word	song_0016_5_2
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W18
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_4
	.byte	PATT	
		.word	song_0016_5_2
	.byte	PATT	
		.word	song_0016_5_2
	.byte	PATT	
		.word	song_0016_5_2
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Cn2
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W12
	.byte			Cn2
	.byte	W18
	.byte			An1
	.byte	W18
	.byte			Fn1
	.byte	W12
	.byte			Cn1
	.byte		N23	, Cs2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_2
song_0016_5_5:
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte		N06	, Dn1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
song_0016_5_6:
	.byte		N06	, Cn1, v116
	.byte		N28	, An2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_5_2
	.byte	PATT	
		.word	song_0016_5_5
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte		N24	, Cs2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_2
	.byte	PATT	
		.word	song_0016_5_5
	.byte		N06	, Cn1, v116
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W12
	.byte	PATT	
		.word	song_0016_5_6
	.byte	PATT	
		.word	song_0016_5_2
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Cn2
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			An1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Fn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte		N24	, An2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W18
	.byte		N06	
	.byte	W48
	.byte		N06	
	.byte	W12
song_0016_5_7:
	.byte		N06	, Cn1, v116
	.byte	W18
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W48
	.byte		N06	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0016_5_7
	.byte	PATT	
		.word	song_0016_5_8
	.byte	GOTO	
		.word	song_0016_5_9
	.byte	FINE

	.align 2
	.global song_0016
song_0016:	@ 0x087D8718
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0016_1		@ track
	.word	song_0016_2		@ track
	.word	song_0016_3		@ track
	.word	song_0016_4		@ track
	.word	song_0016_5		@ track
