	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0032_1
song_0032_1:	@ 0x087DC66C
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 8
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 40
	.byte		N06	, Fs5, v127
	.byte		N06	, An5
	.byte	W06
	.byte			An4
	.byte		N06	, Cs5
	.byte	W06
	.byte			An5
	.byte		N06	, Cs6
	.byte	W06
	.byte		N78	, Fs5
	.byte		N78	, An5
	.byte	W78
	.byte	W96
	.byte		N06	, Fs5
	.byte		N06	, Bn5
	.byte	W06
	.byte			Bn4
	.byte		N06	, Dn5
	.byte	W06
	.byte			Bn5
	.byte		N06	, Dn6
	.byte	W06
	.byte		N78	, Fs5
	.byte		N78	, Bn5
	.byte	W78
	.byte	W96
song_0032_1_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	VOICE	, 4
	.byte	W54
	.byte		N06	, Fs3, v127
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte			An3
	.byte	W06
	.byte			Bn3
	.byte	W06
	.byte			Cs4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte		N32	, Dn4
	.byte	W36
	.byte		N06	, En4
	.byte	W06
	.byte		N07	, Fs4
	.byte	W06
	.byte		N24	, En4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte			En4
	.byte	W24
	.byte		N48	, Dn4
	.byte	W48
	.byte	W12
	.byte		N14	
	.byte	W12
	.byte		N12	, En4
	.byte	W12
	.byte		N13	, Fs4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		N12	, Fs4
	.byte	W12
	.byte		N11	, Gn4
	.byte	W12
	.byte		N10	, An4
	.byte	W12
	.byte		N76	
	.byte	W96
	.byte		N24	
	.byte	W36
	.byte		N07	
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte		N12	, Cn5
	.byte	W12
	.byte		N08	, Bn4
	.byte	W12
	.byte		N13	
	.byte	W12
	.byte		N12	, An4
	.byte	W12
	.byte		N18	, Gn4
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	, Fn4
	.byte	W12
	.byte		N44	, En4
	.byte	W48
	.byte		N11	, Fn4
	.byte	W12
	.byte		N12	, Gn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte		N09	, Bn4
	.byte	W12
	.byte		N30	, Cn5
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N80	, Bn4
	.byte	W96
	.byte	W24
	.byte		N15	, En3
	.byte	W15
	.byte		N01	, Fs3
	.byte	W01
	.byte			Gs3
	.byte	W02
	.byte			An3
	.byte	W01
	.byte			Bn3
	.byte	W02
	.byte			Cs4
	.byte	W01
	.byte			Dn4
	.byte	W02
	.byte		N44	, En4
	.byte	W48
	.byte			Fs4
	.byte	W60
	.byte		N12	, Dn4
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte		N16	, Bn3
	.byte	W24
	.byte		N22	, En3
	.byte	W24
	.byte		N32	, En4
	.byte	W36
	.byte		N11	, Dn4
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N05	, Cs4
	.byte	W06
	.byte		N28	, En4
	.byte	W48
	.byte		N12	, En3
	.byte	W12
	.byte		N03	, Fs3
	.byte	W03
	.byte			Gs3
	.byte	W03
	.byte			An3
	.byte	W03
	.byte			Bn3
	.byte	W03
	.byte			Cs4
	.byte	W03
	.byte			Dn4
	.byte	W03
	.byte		N36	, En4
	.byte	W36
	.byte		N08	
	.byte	W12
	.byte		N14	
	.byte	W12
	.byte		N11	, Dn4
	.byte	W12
	.byte		N08	, Cs4
	.byte	W12
	.byte			As3
	.byte	W12
	.byte		N32	, Bn3
	.byte	W36
	.byte		N06	
	.byte	W06
	.byte		N08	, Cs4
	.byte	W06
	.byte		N36	, Dn4
	.byte	W48
	.byte		N19	, Cs4
	.byte	W18
	.byte		N18	, Bn3
	.byte	W18
	.byte		N13	, Cs4
	.byte	W12
	.byte		N36	, Dn4
	.byte	W36
	.byte		N12	, Bn3
	.byte	W12
	.byte		TIE	, Cs4
	.byte	W96
	.byte	W44
	.byte	W02
	.byte		EOT	
	.byte	W48
	.byte	W02
	.byte	GOTO	
		.word	song_0032_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0032_2
song_0032_2:	@ 0x087DC78C
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0032_2_1:
	.byte		N32	, An4, v127
	.byte	W36
	.byte		N12	
	.byte	W11
	.byte			Fs4
	.byte	W12
	.byte		N07	, Gn4
	.byte	W07
	.byte		N24	, An4
	.byte	W28
	.byte	W01
	.byte		N02	, Gs4
	.byte	W01
	.byte		N12	, An4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Fs4
	.byte	W11
	.byte		N07	, An4
	.byte	W07
	.byte		N56	, Gn4
	.byte	W54
	.byte	W24
	.byte		N12	, En4
	.byte	W11
	.byte			Fs4
	.byte	W13
	.byte		N13	, Gn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte		N12	, Bn4
	.byte	W12
	.byte		N24	, Cs5
	.byte	W12
	.byte	W12
	.byte		N68	, An4
	.byte	W84
	.byte	W01
	.byte		N10	, Fs4
	.byte	W11
	.byte		N07	, Gn4
	.byte	W06
	.byte		N12	, An4
	.byte	W12
	.byte		N17	, Bn4
	.byte	W17
	.byte		N40	, Gn4
	.byte	W48
	.byte	W01
	.byte	W01
	.byte		N12	
	.byte	W11
	.byte		N07	, Fs4
	.byte	W06
	.byte		N12	, Gn4
	.byte	W13
	.byte		N17	, An4
	.byte	W16
	.byte		N30	, Fs4
	.byte	W36
	.byte		N06	
	.byte	W13
	.byte	W01
	.byte		N12	
	.byte	W11
	.byte		N04	, Gn4
	.byte	W07
	.byte		N36	
	.byte	W42
	.byte		N12	
	.byte	W11
	.byte		N11	, Fs4
	.byte	W11
	.byte		N13	, Gn4
	.byte	W13
	.byte		N92	, En4
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N12	, Cs5
	.byte	W12
	.byte		N06	, Bn4
	.byte	W06
	.byte		N40	, Cs5
	.byte	W42
	.byte		N12	, An4
	.byte	W12
	.byte		N11	, Bn4
	.byte	W11
	.byte		N10	, Cs5
	.byte	W13
	.byte		N13	
	.byte	W12
	.byte		N06	, Dn5
	.byte	W06
	.byte		N66	, Bn4
	.byte	W78
	.byte		N10	, Cs5
	.byte	W12
	.byte		N06	, Dn5
	.byte	W06
	.byte		N36	, Bn4
	.byte	W40
	.byte	W01
	.byte		N11	, Gs4
	.byte	W11
	.byte		N13	, An4
	.byte	W13
	.byte		N09	, Bn4
	.byte	W13
	.byte		N11	
	.byte	W12
	.byte		N06	, An4
	.byte	W06
	.byte		N76	, Cs5
	.byte	W78
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		N17	
	.byte	W01
	.byte	W17
	.byte		N16	, Bn4
	.byte	W16
	.byte		N14	, Cs5
	.byte	W14
	.byte		N36	, Dn5
	.byte	W36
	.byte	W01
	.byte		N13	, Bn4
	.byte	W12
	.byte		TIE	, Cs5
	.byte	W96
	.byte	W68
	.byte	W03
	.byte		EOT	
	.byte	W24
	.byte	W01
	.byte	GOTO	
		.word	song_0032_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0032_3
song_0032_3:	@ 0x087DC860
	.byte	KEYSH	, 0
	.byte	VOICE	, 1
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W24
	.byte		N48	, Dn2, v127
	.byte	W01
	.byte			Cs3
	.byte	W02
	.byte			An3
	.byte	W44
	.byte	W01
	.byte		N12	, Dn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte		N92	, Cs4
	.byte		N92	, Fs4
	.byte	W12
	.byte	W96
	.byte		N48	, Gn1
	.byte	W01
	.byte			Dn3
	.byte	W02
	.byte			Bn3
	.byte	W44
	.byte	W01
	.byte		N12	, Gn1
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte		N80	, Dn4
	.byte		N80	, Fs4
	.byte	W12
	.byte	W96
song_0032_3_2:
	.byte		N12	, Dn2, v127
	.byte	W12
	.byte		N05	, An2
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte		N11	, An2
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte		N10	, An2
	.byte	W12
	.byte		N12	, Cs3
	.byte	W12
	.byte		N11	, An2
	.byte	W12
	.byte		N12	, En2
	.byte	W12
	.byte		N05	, Bn2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte		N11	, Bn2
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte		N10	, An1
	.byte	W12
	.byte		N11	, An2
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte		N10	, An2
	.byte	W12
	.byte		N11	, En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte		N12	, Dn2
	.byte	W12
	.byte		N11	, An2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte		N12	, Bn1
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte		N11	, Fs2
	.byte	W12
	.byte		N12	, En2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte		N11	, Gn3
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte		N22	, As1
	.byte		N22	, Gn3
	.byte	W24
	.byte		N11	, Dn3
	.byte		N11	, Fs3
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte		N12	, En1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte		N11	, Gn2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte		N12	, An1
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte		N11	, An2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte			An2
	.byte	W12
song_0032_3_1:
	.byte		N12	, Gn1, v127
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Bn2
	.byte		N12	, Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte		N12	, En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte	PEND
	.byte			Fs1
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte		N12	, En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Dn3
	.byte		N12	, Fs3
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte	PATT	
		.word	song_0032_3_1
	.byte		N12	, Dn2, v127
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte		N12	, Fs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte		N12	, Fs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte		N12	, Fn3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte		N12	, Fn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Bn2
	.byte		N12	, Dn3
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte		N12	, En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte		N12	, Fn3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte		N12	, Fn3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Dn3
	.byte		N12	, Gn3
	.byte	W12
	.byte			Bn2
	.byte	W15
	.byte		N44	, En3
	.byte	W44
	.byte	W01
	.byte		N11	, An1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An2
	.byte		N11	, Cs3
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An2
	.byte		N11	, Cs3
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Bn2
	.byte		N11	, Dn3
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Bn2
	.byte		N11	, Dn3
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			Bn2
	.byte		N11	, Dn3
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			Bn2
	.byte		N11	, Dn3
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An2
	.byte		N11	, Cs3
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Gs2
	.byte		N11	, Cs3
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Fs1
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			As2
	.byte		N11	, Cs3
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Fs1
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			As2
	.byte		N11	, Cs3
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Bn2
	.byte		N11	, Dn3
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			An2
	.byte		N11	, Dn3
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			An2
	.byte		N11	, Cs3
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Gs2
	.byte		N11	, Dn3
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte		N11	, Fs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte		N11	, Fs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte	W02
	.byte		N92	, Cs3
	.byte	W01
	.byte			Fs3
	.byte	W01
	.byte			An3
	.byte	W92
	.byte	GOTO	
		.word	song_0032_3_2
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0032_4
song_0032_4:	@ 0x087DCA6F
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		TIE	, Dn2, v127
	.byte	W96
	.byte	W72
	.byte		EOT	
	.byte		N24	, An1
	.byte	W24
	.byte		TIE	, Gn1
	.byte	W96
	.byte	W72
	.byte		EOT	
	.byte	W12
	.byte		N12	, An1
	.byte	W12
song_0032_4_1:
	.byte		N72	, Dn2, v127
	.byte	W84
	.byte		N12	
	.byte	W12
	.byte	PEND
	.byte		N72	, En2
	.byte	W84
	.byte		N06	, Bn1
	.byte	W06
	.byte			As1
	.byte	W06
song_0032_4_2:
	.byte		N72	, An1, v127
	.byte	W84
	.byte		N12	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0032_4_1
	.byte		N48	, Bn1, v127
	.byte	W48
	.byte			En2
	.byte	W48
	.byte		N24	, An1
	.byte	W24
	.byte			As1
	.byte	W24
	.byte		N48	, Bn1
	.byte	W48
	.byte		N72	, En1
	.byte	W84
	.byte		N12	
	.byte	W12
	.byte	PATT	
		.word	song_0032_4_2
song_0032_4_3:
	.byte		N48	, Gn1, v127
	.byte	W48
	.byte			An1
	.byte	W48
	.byte	PEND
	.byte			Fs1
	.byte	W48
	.byte		N24	, Bn1
	.byte	W24
	.byte			An1
	.byte	W24
	.byte	PATT	
		.word	song_0032_4_3
	.byte		N96	, Dn2, v127
	.byte	W96
	.byte		N48	
	.byte	W48
	.byte			Gn1
	.byte	W48
	.byte			En2
	.byte	W48
	.byte		N44	, An1
	.byte	W48
	.byte			Fn1
	.byte	W48
	.byte		N44	
	.byte	W48
	.byte		N48	, Gn1
	.byte	W48
	.byte		N22	, En1
	.byte	W24
	.byte			En2
	.byte	W24
	.byte		N32	, An1
	.byte	W36
	.byte		N01	
	.byte	W06
	.byte		N05	, En2
	.byte	W06
	.byte		N30	, An1
	.byte	W36
	.byte		N05	
	.byte	W06
	.byte			As1
	.byte	W06
	.byte		N32	, Bn1
	.byte	W36
	.byte		N01	
	.byte	W06
	.byte		N05	, Fs2
	.byte	W06
	.byte		N32	, Bn1
	.byte	W36
	.byte		N11	
	.byte	W12
	.byte		N32	, En2
	.byte	W36
	.byte		N01	, Bn1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N32	, En1
	.byte	W36
	.byte		N05	, Fs1
	.byte	W06
	.byte			Gs1
	.byte	W06
	.byte		N32	, An1
	.byte	W36
	.byte		N01	, En2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N18	, An2
	.byte	W18
	.byte			Gs2
	.byte	W18
	.byte		N12	, En2
	.byte	W12
	.byte		N32	, Fs2
	.byte	W36
	.byte		N01	
	.byte	W06
	.byte		N05	, Cs2
	.byte	W06
	.byte		N32	, Fs1
	.byte	W36
	.byte		N11	
	.byte	W12
	.byte		N48	, Bn1
	.byte	W48
	.byte			Fn2
	.byte	W48
	.byte		N32	, En2
	.byte	W36
	.byte		N01	
	.byte	W06
	.byte		N05	, Bn1
	.byte	W06
	.byte		N48	, En2
	.byte	W48
	.byte		N84	, Dn2
	.byte	W84
	.byte		N01	, An1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N96	, Dn2
	.byte	W96
	.byte	GOTO	
		.word	song_0032_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0032_5
song_0032_5:	@ 0x087DCB53
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0032_5_1:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Cs1
	.byte	W48
	.byte		N06	
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0032_5_1
	.byte	PATT	
		.word	song_0032_5_1
song_0032_5_2:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Cs1
	.byte	W48
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0032_5_6:
	.byte	PATT	
		.word	song_0032_5_2
	.byte	PATT	
		.word	song_0032_5_2
	.byte	PATT	
		.word	song_0032_5_2
	.byte	PATT	
		.word	song_0032_5_2
	.byte	PATT	
		.word	song_0032_5_2
	.byte	PATT	
		.word	song_0032_5_2
	.byte	PATT	
		.word	song_0032_5_2
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Cs1
	.byte	W24
	.byte			Cn1
	.byte	W18
	.byte			Cn2
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Fn1
	.byte	W12
song_0032_5_3:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Cs1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0032_5_3
	.byte	PATT	
		.word	song_0032_5_3
	.byte	PATT	
		.word	song_0032_5_3
	.byte	PATT	
		.word	song_0032_5_3
	.byte	PATT	
		.word	song_0032_5_3
	.byte	PATT	
		.word	song_0032_5_3
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Cs1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte		N06	, Cs2
	.byte	W06
	.byte			Cn2
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Cn1
	.byte		N06	, Fn1
	.byte	W06
	.byte		N06	
	.byte	W06
song_0032_5_5:
	.byte		N06	, Cn1, v127
	.byte		N06	, An2
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0032_5_4:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0032_5_4
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte		N03	, Cn2
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N06	, Cn1
	.byte		N06	, Cn2
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Cn1
	.byte		N06	, An1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0032_5_5
	.byte	PATT	
		.word	song_0032_5_4
	.byte	PATT	
		.word	song_0032_5_4
	.byte		N06	, Cn1, v127
	.byte		N06	, Cs2
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W84
	.byte		N06	
	.byte	W12
	.byte	GOTO	
		.word	song_0032_5_6
	.byte	FINE

	.align 2
	.global song_0032
song_0032:	@ 0x087DCC68
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0032_1		@ track
	.word	song_0032_2		@ track
	.word	song_0032_3		@ track
	.word	song_0032_4		@ track
	.word	song_0032_5		@ track
