	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0006_1
song_0006_1:	@ 0x087D387C
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v069
	.byte	PAN	, c_v
	.byte	W06
	.byte	TEMPO	, 54
	.byte	W24
song_0006_1_3:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N24	, Cn4, v127
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N36	
	.byte	W48
song_0006_1_1:
	.byte		N18	, Dn4, v127
	.byte	W18
	.byte			Ds4
	.byte	W18
	.byte		N12	, Fn4
	.byte	W12
	.byte		N36	, Dn4
	.byte	W48
	.byte	PEND
	.byte		N18	, Cn4
	.byte	W18
	.byte			Dn4
	.byte	W18
	.byte		N12	, Ds4
	.byte	W12
	.byte		N24	, Fn4
	.byte	W24
	.byte			Ds4
	.byte	W24
	.byte		N30	, Gn4
	.byte	W30
	.byte		N06	, Fn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N36	, Gn4
	.byte	W48
	.byte		N24	, Cn4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N40	
	.byte	W48
	.byte	PATT	
		.word	song_0006_1_1
	.byte		N18	, Cn4, v127
	.byte	W18
	.byte			Dn4
	.byte	W18
	.byte		N12	, Ds4
	.byte	W12
	.byte		N18	, Dn4
	.byte	W18
	.byte			Cn4
	.byte	W18
	.byte		N12	, Dn4
	.byte	W12
	.byte		N72	, Cn4
	.byte	W96
	.byte		N66	, Gn4
	.byte	W66
	.byte		N18	, Fn4
	.byte	W18
	.byte		N12	, Ds4
	.byte	W12
	.byte		N54	, Gn4
	.byte	W66
	.byte		N18	, Fn4
	.byte	W18
	.byte		N12	, Gn4
	.byte	W12
	.byte		N54	
	.byte	W66
	.byte		N18	, Cn5
	.byte	W18
	.byte		N12	, Dn5
	.byte	W12
	.byte		N72	, As4
	.byte	W96
	.byte		N30	, Cn5
	.byte	W30
	.byte		N06	, As4
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N12	, As4
	.byte	W18
	.byte		N18	, Fn4
	.byte	W18
	.byte		N12	, Gn4
	.byte	W12
	.byte		N30	, Gs4
	.byte	W30
	.byte		N06	, Gn4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N12	, Gn4
	.byte	W18
	.byte		N18	, Cn4
	.byte	W18
	.byte		N12	, Ds4
	.byte	W12
	.byte		N06	, Fn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N24	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N18	
	.byte	W18
	.byte			Fn4
	.byte	W18
	.byte		N12	, Gs4
	.byte	W12
	.byte		TIE	, Gn4
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W24
	.byte		N24	, Cn4
	.byte	W24
	.byte		N66	, Cn5
	.byte	W66
	.byte		N18	, Fn4
	.byte	W18
	.byte		N12	, Cn5
	.byte	W12
song_0006_1_2:
	.byte		N60	, Cn5, v127
	.byte	W60
	.byte		N24	, As4
	.byte	W24
	.byte		N06	, Gs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte	PEND
	.byte		N36	, Cn5
	.byte	W36
	.byte		N12	, As4
	.byte	W12
	.byte		N36	
	.byte	W36
	.byte		N12	, Cn5
	.byte	W12
	.byte		N40	, Gs4
	.byte	W48
	.byte		N18	, Fn4
	.byte	W18
	.byte			Gn4
	.byte	W18
	.byte		N06	, Gs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N60	, Cn5
	.byte	W60
	.byte		N24	, Fn4
	.byte	W24
	.byte		N12	, Cn5
	.byte	W12
	.byte	PATT	
		.word	song_0006_1_2
	.byte		N36	, Cn5, v127
	.byte	W36
	.byte		N30	, As4
	.byte	W30
	.byte		N18	, Ds5
	.byte	W18
	.byte		N12	, Gn4
	.byte	W12
	.byte		N72	, Gs4
	.byte	W96
	.byte		N18	, Fn4
	.byte	W18
	.byte			Gn4
	.byte	W18
	.byte		N12	, Gs4
	.byte	W12
	.byte		N40	, As4
	.byte	W48
	.byte		N18	, Gn4
	.byte	W18
	.byte			Fn4
	.byte	W18
	.byte		N12	, Gn4
	.byte	W12
	.byte		N40	, Gs4
	.byte	W48
	.byte		N18	
	.byte	W18
	.byte			Gn4
	.byte	W18
	.byte		N12	, Fn4
	.byte	W12
	.byte		N48	, Ds4
	.byte	W48
	.byte		N72	, Fn4
	.byte	W96
	.byte	GOTO	
		.word	song_0006_1_3
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0006_2
song_0006_2:	@ 0x087D39B0
	.byte	KEYSH	, 0
	.byte	VOICE	, 8
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W06
	.byte		N06	, Cn5, v100
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte			Fn5
	.byte	W06
song_0006_2_1:
	.byte		N12	, Gn5, v100
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N12	, Fn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N12	, Ds5
	.byte	W12
	.byte			Fn5
	.byte	W12
	.byte			Ds5
	.byte	W12
	.byte		N06	, Fn5
	.byte	W06
	.byte		N18	, Gn5
	.byte	W18
	.byte	PEND
	.byte	PATT	
		.word	song_0006_2_1
	.byte	PATT	
		.word	song_0006_2_1
	.byte		N48	, Ds5, v100
	.byte	W72
	.byte		N06	, Cn5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte	PATT	
		.word	song_0006_2_1
	.byte	PATT	
		.word	song_0006_2_1
	.byte		N48	, Cn5, v100
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W72
	.byte		N06	, Cn4, v127
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte	GOTO	
		.word	song_0006_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0006_3
song_0006_3:	@ 0x087D3A2D
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte	W24
song_0006_3_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N96	, Cn3, v127
	.byte	W96
	.byte			As2
	.byte	W96
	.byte			Gs2
	.byte	W96
	.byte			As2
	.byte	W96
	.byte		N48	, Cn3
	.byte	W48
	.byte			As2
	.byte	W48
	.byte			Gs2
	.byte	W48
	.byte			Gn2
	.byte	W48
	.byte		N96	, Cn3
	.byte	W96
	.byte		N06	, Gn3
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte			Gs3
	.byte	W06
	.byte			Cs4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N04	, Cn4
	.byte	W04
	.byte			Cs4
	.byte	W04
	.byte			Dn4
	.byte	W04
	.byte			En4
	.byte	W04
	.byte			Fn4
	.byte	W04
	.byte			Fs4
	.byte	W04
	.byte			Gn4
	.byte	W04
	.byte			Gs4
	.byte	W04
	.byte			An4
	.byte	W04
	.byte		N03	, As4
	.byte	W03
	.byte			Cn5
	.byte	W03
	.byte			Dn5
	.byte	W03
	.byte			En5
	.byte	W03
	.byte		TIE	, Fn5
	.byte	W96
	.byte	W18
	.byte		EOT	
	.byte		N18	, Ds5
	.byte	W18
	.byte		N12	, Cs5
	.byte	W12
	.byte		N48	, Fn5
	.byte	W48
	.byte		N44	, Ds5
	.byte	W48
	.byte		N48	, Gn4
	.byte	W48
	.byte		N92	, Gs4
	.byte	W96
	.byte		TIE	, Fn5
	.byte	W96
	.byte	W18
	.byte		EOT	
	.byte		N18	, Ds5
	.byte	W18
	.byte		N12	, Cs5
	.byte	W12
	.byte		N48	, Fn5
	.byte	W48
	.byte		N44	, Ds5
	.byte	W48
	.byte		N24	
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N48	, Gs4
	.byte	W48
	.byte		N06	, Fn5
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Gs3
	.byte	W06
	.byte	W96
	.byte	W96
	.byte		N18	, Cn4
	.byte	W18
	.byte			As3
	.byte	W18
	.byte		N12	, Gs3
	.byte	W12
	.byte		N48	, Gn3
	.byte	W48
	.byte		N90	, Gs3
	.byte	W96
	.byte	GOTO	
		.word	song_0006_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0006_4
song_0006_4:	@ 0x087D3AFE
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
	.byte	W24
song_0006_4_5:
	.byte		N18	, Gs1, v127
	.byte	W18
	.byte			Ds2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	, Ds2
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
song_0006_4_1:
	.byte		N18	, As1, v127
	.byte	W18
	.byte			Fn2
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
	.byte			As1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	, Fn2
	.byte	W18
	.byte		N12	, As1
	.byte	W12
	.byte	PEND
	.byte		N18	, Cn2
	.byte	W18
	.byte			Gn1
	.byte	W18
	.byte		N12	, As1
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	, Gn2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte		N18	, Cn2
	.byte	W18
	.byte			Gn1
	.byte	W18
	.byte		N12	, As1
	.byte	W12
	.byte		N06	, Cn2
	.byte	W06
	.byte			Dn2
	.byte	W12
	.byte			Ds2
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte		N06	, Gn1
	.byte	W06
	.byte		N18	, Gs1
	.byte	W18
	.byte			Ds2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte		N06	, Gs1
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N18	
	.byte	W18
	.byte		N06	, Gs1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte	PATT	
		.word	song_0006_4_1
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W42
	.byte		N06	, Gn1, v127
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			Dn2
	.byte	W12
	.byte			Ds2
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			Gn1
	.byte	W06
	.byte		N36	, Gs1
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N18	
	.byte	W18
	.byte			Ds2
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
	.byte		N36	, Gn1
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N18	
	.byte	W18
	.byte			Dn2
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte		N36	, Fn1
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N18	
	.byte	W18
	.byte			Cn2
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte		N36	, Ds2
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N18	
	.byte	W18
	.byte			As1
	.byte	W18
	.byte		N12	, Ds2
	.byte	W12
	.byte		N18	, Fn1
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, Gn1
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, Cs2
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, Cn2
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, Gs1
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N36	
	.byte	W36
	.byte		N12	, Fn1
	.byte	W12
	.byte		N18	, Gn1
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte			Gn2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N18	, Cn2
	.byte	W48
song_0006_4_2:
	.byte		N18	, Cs2, v127
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
	.byte			Cs2
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
	.byte	PEND
song_0006_4_3:
	.byte		N18	, Cs2, v127
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	, Gs1
	.byte	W12
	.byte			Cs2
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v+63
	.byte		N12	
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte	PEND
song_0006_4_4:
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	, Gn1
	.byte	W12
	.byte		N18	, Cn2
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N06	, As1
	.byte	W06
	.byte			Gn1
	.byte	W06
	.byte	PEND
	.byte		N18	, Fn1
	.byte	W18
	.byte			Fn2
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte		N06	, Ds1
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte	PATT	
		.word	song_0006_4_2
	.byte	PATT	
		.word	song_0006_4_3
	.byte	PATT	
		.word	song_0006_4_4
	.byte		N18	, Fn1, v127
	.byte	W18
	.byte			Fn2
	.byte	W18
	.byte		N12	, Fn1
	.byte	W12
	.byte			Ds2
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N18	
	.byte	W18
	.byte		N12	, Cn2
	.byte	W12
	.byte		N18	, As1
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, Cs2
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, Cn2
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, Fn1
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, As1
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte		N18	, Cn2
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N12	
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N54	, Fn1
	.byte	W78
	.byte	GOTO	
		.word	song_0006_4_5
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0006_5
song_0006_5:	@ 0x087D3CA6
	.byte	KEYSH	, 0
	.byte	VOICE	, 19
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte	W24
song_0006_5_2:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte			Ds3
	.byte	W18
	.byte		N12	, Cn4
	.byte		N12	, Ds4
	.byte	W12
	.byte			As1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte		N24	, Ds3
	.byte	W12
	.byte		N12	, Gn0
	.byte	W12
song_0006_5_1:
	.byte		N18	, Gs1, v127
	.byte	W18
	.byte			Ds3
	.byte	W18
	.byte		N12	, Cn4
	.byte		N12	, Ds4
	.byte	W12
	.byte			As1
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte		N24	, Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0006_5_1
	.byte		N18	, Ds1, v127
	.byte	W18
	.byte			Ds3
	.byte	W18
	.byte		N12	, As3
	.byte		N12	, Ds4
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte		N24	, Bn2
	.byte	W24
	.byte		N18	, Cn2
	.byte	W18
	.byte			Ds3
	.byte	W18
	.byte		N12	, Cn4
	.byte		N12	, Ds4
	.byte	W12
	.byte			As1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte		N24	, Ds3
	.byte	W24
	.byte	PATT	
		.word	song_0006_5_1
	.byte	PATT	
		.word	song_0006_5_1
	.byte		N18	, Cn2, v127
	.byte	W18
	.byte			Ds3
	.byte	W18
	.byte		N12	, Cn4
	.byte		N12	, Ds4
	.byte	W60
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0006_5_2
	.byte	FINE

	@********************** Track  6 **********************@

	.global song_0006_6
song_0006_6:	@ 0x087D3D36
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte	W24
song_0006_6_4:
	.byte		N06	, Cn1, v127
	.byte		N42	, Cs2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
song_0006_6_1:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0006_6_1
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W18
	.byte		N03	, Dn1
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N05	, An1
	.byte	W06
	.byte		N06	, Cn1
	.byte		N06	, Dn1
	.byte	W06
	.byte			Cn1
	.byte		N17	, An2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W15
	.byte		N03	, Cn2
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N07	
	.byte	W09
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte			Cn1
	.byte		N28	, Cs2
	.byte	W36
	.byte		N06	, Cn1
	.byte	W12
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
song_0006_6_2:
	.byte		N06	, Cn1, v127
	.byte	W36
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte		N06	, Cn1, v127
	.byte	W42
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte		N28	, An2
	.byte	W36
	.byte		N06	, Cn1
	.byte	W12
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte	PATT	
		.word	song_0006_6_2
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte		N03	, Dn1
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N06	, Cn1
	.byte		N06	, Dn1
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W48
	.byte			Cn1
	.byte		N21	, An2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
song_0006_6_3:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0006_6_3
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte			Cn1
	.byte		N20	, An2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0006_6_3
	.byte	PATT	
		.word	song_0006_6_3
	.byte	PATT	
		.word	song_0006_6_3
	.byte		N06	, Cn1, v127
	.byte		N20	, Cs2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0006_6_3
	.byte	PATT	
		.word	song_0006_6_3
	.byte		N06	, Cn1, v127
	.byte	W18
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte		N03	, Dn1
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	GOTO	
		.word	song_0006_6_4
	.byte	FINE

	.align 2
	.global song_0006
song_0006:	@ 0x087D3ED0
	.byte	6		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0006_1		@ track
	.word	song_0006_2		@ track
	.word	song_0006_3		@ track
	.word	song_0006_4		@ track
	.word	song_0006_5		@ track
	.word	song_0006_6		@ track
