	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0043_1
song_0043_1:	@ 0x087DFAF8
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
	.byte	TEMPO	, 78
	.byte	W48
	.byte	W96
	.byte	W72
song_0043_1_1:
	.byte		N05	, Cn5, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	PEND
song_0043_1_2:
	.byte		N05	, An5, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	PEND
song_0043_1_3:
	.byte		N05	, Cn5, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	PEND
song_0043_1_4:
	.byte		N05	, Dn5, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	PEND
song_0043_1_5:
	.byte		N05	, Fn5, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N08	, Cn5
	.byte	W24
	.byte	PEND
song_0043_1_6:
	.byte	W48
	.byte		N05	, Cn5, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	PEND
song_0043_1_7:
	.byte		N05	, Fn5, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N08	, Cn5
	.byte	W60
	.byte	PEND
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N08	, As5
	.byte	W36
	.byte	W96
	.byte	W72
	.byte	PATT	
		.word	song_0043_1_1
	.byte	PATT	
		.word	song_0043_1_2
	.byte	PATT	
		.word	song_0043_1_3
	.byte	PATT	
		.word	song_0043_1_4
	.byte	PATT	
		.word	song_0043_1_5
	.byte	PATT	
		.word	song_0043_1_6
	.byte	PATT	
		.word	song_0043_1_7
	.byte		N05	, Cn5, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N08	, As5
	.byte	W12
	.byte		TIE	, Cn3
	.byte	W96
	.byte	W72
	.byte		EOT	
	.byte		TIE	, Dn3
	.byte	W96
	.byte	W72
	.byte		EOT	
	.byte		TIE	, Ds3
	.byte	W96
	.byte	W72
	.byte		EOT	
	.byte		TIE	, Fn3
	.byte	W96
	.byte	W42
	.byte	W01
	.byte		EOT	
	.byte	W05
	.byte		N22	, Gn3
	.byte	W24
	.byte		TIE	, Gn4
	.byte	W96
	.byte	W72
	.byte		EOT	
	.byte		N72	, Fn4
	.byte	W72
	.byte			Dn4
	.byte	W24
	.byte	W48
	.byte		N06	, Ds4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N48	, Gn4
	.byte	W48
	.byte			Cn5
	.byte	W48
	.byte		N24	, Dn5
	.byte	W24
	.byte			Ds5
	.byte	W24
	.byte			Cn5
	.byte	W24
	.byte		N96	, As4
	.byte	W72
	.byte	W24
	.byte		N72	, Dn5
	.byte	W48
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W96
	.byte	W72
	.byte	PATT	
		.word	song_0043_1_1
	.byte	PATT	
		.word	song_0043_1_2
	.byte	PATT	
		.word	song_0043_1_1
	.byte	PATT	
		.word	song_0043_1_2
	.byte	GOTO	
		.word	song_0043_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0043_2
song_0043_2:	@ 0x087DFC68
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
	.byte		N11	, Gn3, v127
	.byte		N11	, Gn4
	.byte	W24
	.byte	W12
	.byte			Gn3
	.byte		N11	, Gn4
	.byte	W48
	.byte		TIE	, Gn2
	.byte		TIE	, Gn3
	.byte	W36
	.byte	W68
	.byte	W03
	.byte		EOT	, Gn2
	.byte			Gn3
	.byte	W01
song_0043_2_7:
	.byte	W96
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W48
song_0043_2_1:
	.byte		N05	, As3, v127
	.byte		N05	, Fn4
	.byte	W24
	.byte			As3
	.byte		N05	, Fn4
	.byte	W48
	.byte	PEND
song_0043_2_2:
	.byte	W48
	.byte		N05	, As3, v127
	.byte		N05	, Fn4
	.byte	W24
	.byte			As3
	.byte		N05	, Fn4
	.byte	W24
	.byte	PEND
	.byte	W72
	.byte		N68	, Bn2
	.byte		N68	, As3
	.byte	W24
	.byte	W48
	.byte		N96	, Gn3
	.byte		N96	, Gn4
	.byte	W48
	.byte	W60
	.byte		N06	, Gn3
	.byte		N06	, Gn4
	.byte	W12
	.byte		N16	, Cn4
	.byte		N16	, Cn5
	.byte	W96
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W48
	.byte	PATT	
		.word	song_0043_2_1
	.byte	PATT	
		.word	song_0043_2_2
	.byte	W72
song_0043_2_4:
	.byte	W12
	.byte		N04	, Cn4, v127
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N08	
	.byte	W36
	.byte	PEND
	.byte	W72
song_0043_2_3:
	.byte	W12
	.byte		N04	, Dn4, v127
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N08	
	.byte	W36
	.byte	PEND
	.byte	W72
song_0043_2_5:
	.byte	W12
	.byte		N04	, Ds4, v127
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N08	
	.byte	W36
	.byte	PEND
	.byte	W72
	.byte	PATT	
		.word	song_0043_2_3
	.byte	W72
	.byte	PATT	
		.word	song_0043_2_4
	.byte	W72
	.byte	PATT	
		.word	song_0043_2_3
	.byte	W72
	.byte	PATT	
		.word	song_0043_2_5
	.byte	W72
	.byte	W12
	.byte		N04	, Dn4, v127
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N08	
	.byte	W12
	.byte	W72
	.byte	W24
	.byte		N84	, Cn4
	.byte	W48
	.byte	W48
	.byte		N22	, Dn4
	.byte	W24
	.byte			Ds4
	.byte	W24
	.byte		TIE	, Dn4
	.byte	W48
	.byte	W72
	.byte	W24
	.byte		EOT	
	.byte		N84	, Cn4
	.byte	W48
	.byte	W48
	.byte		N22	, Dn4
	.byte	W24
	.byte			Ds4
	.byte	W24
	.byte		TIE	, Fn4
	.byte	W48
	.byte	W72
	.byte	W24
	.byte		EOT	
	.byte		N04	, Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W24
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W12
song_0043_2_6:
	.byte	W12
	.byte		N04	, Ds3, v127
	.byte		N04	, Gn3
	.byte	W12
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W24
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte	PEND
	.byte	W12
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W24
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W24
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W24
	.byte			Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte	PATT	
		.word	song_0043_2_6
	.byte	W12
	.byte		N04	, Ds3, v127
	.byte		N04	, Gn3
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W24
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W24
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W24
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W24
	.byte			Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte	W96
	.byte	W72
	.byte	W24
	.byte		N16	, Gn3
	.byte		N16	, Fn4
	.byte	W48
	.byte			Gn3
	.byte		N16	, Fn4
	.byte	W24
	.byte	W24
	.byte			Gn3
	.byte		N16	, Fn4
	.byte	W48
	.byte	GOTO	
		.word	song_0043_2_7
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0043_3
song_0043_3:	@ 0x087DFDF3
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
	.byte		N03	, Cn4, v127
	.byte	W04
	.byte			Dn4
	.byte	W04
	.byte			Ds4
	.byte	W04
	.byte			Fn4
	.byte	W04
	.byte			Gn4
	.byte	W04
	.byte			Gs4
	.byte	W04
	.byte		N11	, Dn4
	.byte		N11	, As4
	.byte	W24
	.byte	W12
	.byte			Dn4
	.byte		N11	, As4
	.byte	W48
	.byte			Dn4
	.byte		N11	, Bn4
	.byte	W36
	.byte	W72
song_0043_3_6:
	.byte		N05	, Cn2, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N23	, Cn2
	.byte	W24
	.byte		N06	, As4
	.byte	W24
	.byte		N05	, Dn5
	.byte	W24
	.byte			Cn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N12	, Cn2
	.byte	W12
	.byte		N05	, Dn5
	.byte	W24
	.byte		N05	
	.byte	W24
	.byte			Cn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds2
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N14	, As2
	.byte	W36
	.byte	W24
	.byte		N10	, Fn3
	.byte	W10
	.byte		N06	, Gn3
	.byte	W07
	.byte		N05	, Fn3
	.byte	W05
	.byte		N04	, Gn3
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte		N03	, Gn3
	.byte	W04
	.byte			Fn3
	.byte	W03
	.byte		N02	, Gn3
	.byte	W02
	.byte			Fn3
	.byte	W03
	.byte			Gn3
	.byte	W02
	.byte			Fn3
	.byte	W02
	.byte			Gn3
	.byte	W02
	.byte		N12	, As3
	.byte	W10
	.byte		N07	, Cn4
	.byte	W07
	.byte		N06	, As3
	.byte	W07
	.byte		N04	, Fn4
	.byte	W04
	.byte			Gn4
	.byte	W04
	.byte		N03	, Fn4
	.byte	W04
	.byte			Gn4
	.byte	W03
	.byte			Fn4
	.byte	W02
	.byte			Gn4
	.byte	W03
	.byte			Fn4
	.byte	W04
	.byte		N04	, Dn5
	.byte	W04
	.byte			Ds5
	.byte	W04
	.byte			Dn5
	.byte	W03
	.byte			Ds5
	.byte	W03
	.byte		N03	, Dn5
	.byte	W02
	.byte			Ds5
	.byte	W03
	.byte			Dn5
	.byte	W02
	.byte			Ds5
	.byte	W03
	.byte		N10	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N05	, Cn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			As3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N12	, Cn3
	.byte	W24
	.byte		N06	, As4
	.byte	W24
	.byte		N05	, Dn5
	.byte	W24
	.byte			Cn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N12	, Cn3
	.byte	W12
	.byte		N05	, Dn5
	.byte	W24
	.byte		N05	
	.byte	W24
	.byte			Cn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N12	, As2
	.byte	W12
song_0043_3_1:
	.byte	W12
	.byte		N04	, Ds3, v127
	.byte		N04	, Gn3
	.byte	W12
	.byte		N08	, Ds3
	.byte		N08	, Gn3
	.byte	W24
	.byte		N04	, Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte		N08	, Ds3
	.byte		N08	, Gn3
	.byte	W24
	.byte		N04	, Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte	PEND
song_0043_3_2:
	.byte		N08	, Ds3, v127
	.byte		N08	, Gn3
	.byte	W24
	.byte		N04	, Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte		N08	, Ds3
	.byte		N08	, Gn3
	.byte	W24
	.byte		N04	, Ds3
	.byte		N04	, Gn3
	.byte	W12
	.byte	PEND
song_0043_3_3:
	.byte	W12
	.byte		N04	, Dn3, v127
	.byte		N04	, Fn3
	.byte	W12
	.byte		N08	, Dn3
	.byte		N08	, Fn3
	.byte	W24
	.byte		N04	, Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte		N08	, Dn3
	.byte		N08	, Fn3
	.byte	W24
	.byte		N04	, Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte	PEND
song_0043_3_4:
	.byte		N08	, Dn3, v127
	.byte		N08	, Fn3
	.byte	W24
	.byte		N04	, Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte		N08	, Dn3
	.byte		N08	, Fn3
	.byte	W24
	.byte		N04	, Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0043_3_1
	.byte	PATT	
		.word	song_0043_3_2
	.byte	PATT	
		.word	song_0043_3_3
	.byte	PATT	
		.word	song_0043_3_4
	.byte	PATT	
		.word	song_0043_3_1
	.byte	PATT	
		.word	song_0043_3_2
	.byte	PATT	
		.word	song_0043_3_3
	.byte	PATT	
		.word	song_0043_3_4
	.byte	PATT	
		.word	song_0043_3_1
	.byte	PATT	
		.word	song_0043_3_2
song_0043_3_5:
	.byte	W12
	.byte		N04	, Dn3, v127
	.byte		N04	, Fn3
	.byte	W12
	.byte		N08	, Dn3
	.byte		N08	, Fn3
	.byte	W24
	.byte		N04	, Dn3
	.byte		N04	, Fn3
	.byte	W12
	.byte		N08	, Dn3
	.byte		N08	, Fn3
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0043_3_5
	.byte	W12
	.byte		N04	, Dn3, v127
	.byte		N04	, Fn3
	.byte	W60
	.byte	W24
	.byte		N68	, Ds3
	.byte	W48
	.byte	W24
	.byte			Fn3
	.byte	W48
	.byte	W24
	.byte			Dn3
	.byte	W48
	.byte	W72
	.byte	W24
	.byte			Cn3
	.byte	W48
	.byte	W24
	.byte			Dn3
	.byte	W48
	.byte	W24
	.byte			Fn3
	.byte	W48
	.byte	W24
	.byte		N11	, Cn4
	.byte	W12
	.byte		N05	, Bn3
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte		N11	, Dn4
	.byte	W12
	.byte		N05	, Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N11	, Ds4
	.byte	W12
	.byte		N05	, Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N11	, Fn4
	.byte	W12
	.byte		N05	, Ds4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N11	, Gn4
	.byte	W12
	.byte		N05	, Fn4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N11	, Ds4
	.byte	W12
	.byte		N05	, Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte		N11	, Fn4
	.byte	W12
	.byte		N05	, Ds4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N11	, Gn4
	.byte	W12
	.byte		N05	, Fn4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte		N11	, As4
	.byte	W12
	.byte		N05	, Gs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N11	, Cn5
	.byte	W12
	.byte		N05	, As4
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte			As5
	.byte	W06
	.byte			Gs5
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N12	, Gn3
	.byte	W24
	.byte			Gn5
	.byte	W72
	.byte	W72
	.byte	W24
	.byte		N16	, Bn3
	.byte		N16	, Gn4
	.byte	W48
	.byte			Bn3
	.byte		N16	, Gn4
	.byte	W24
	.byte	W24
	.byte			Bn3
	.byte		N16	, Gn4
	.byte	W48
	.byte	GOTO	
		.word	song_0043_3_6
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0043_4
song_0043_4:	@ 0x087E016D
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W48
	.byte		N11	, Bn2, v127
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte		N05	, Gn4
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N11	, Gn3
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N36	, Bn2
	.byte		N11	, Gn3
	.byte	W36
	.byte	W48
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	, Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
song_0043_4_8:
	.byte		N13	, Cn4, v127
	.byte		N06	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
song_0043_4_1:
	.byte		N06	, Dn5, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N12	, Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte		N12	, Cn4
	.byte		N06	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
song_0043_4_2:
	.byte		N06	, Dn5, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte		N06	
	.byte	W12
	.byte		N12	, Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	, Cn4
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
song_0043_4_3:
	.byte		N06	, Dn5, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N12	, Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N23	, Cn4
	.byte		N06	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
song_0043_4_4:
	.byte		N06	, Dn5, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte			Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte	PEND
	.byte		N14	, Cn4
	.byte		N06	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	, Gn3
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte		N06	, Dn5
	.byte	W06
	.byte			Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte			Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte			Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte		N24	, Bn2
	.byte		N12	, Cn4
	.byte		N06	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0043_4_1
	.byte		N23	, Cn4, v127
	.byte		N06	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0043_4_2
	.byte		N06	, Dn5, v127
	.byte	W12
	.byte		N12	, Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N24	, Cn4
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0043_4_3
	.byte	PATT	
		.word	song_0043_4_4
	.byte		N24	, Cn4, v127
	.byte		N06	, Dn5
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N30	, Bn2
	.byte		N22	, Cn5
	.byte		N06	, Dn5
	.byte	W96
	.byte	W72
	.byte	W96
	.byte	W72
	.byte	W96
	.byte	W72
	.byte	W96
	.byte	W48
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
song_0043_4_5:
	.byte		N06	, Dn5, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0043_4_2
	.byte	PATT	
		.word	song_0043_4_5
	.byte	PATT	
		.word	song_0043_4_2
	.byte	PATT	
		.word	song_0043_4_5
	.byte	PATT	
		.word	song_0043_4_2
	.byte	PATT	
		.word	song_0043_4_2
	.byte	PATT	
		.word	song_0043_4_2
	.byte		N06	, Dn5, v127
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N23	, Bn2
	.byte		N01	, Cn4
	.byte	W01
	.byte		N23	
	.byte	W23
	.byte		N01	
	.byte	W01
	.byte		N23	
	.byte	W23
song_0043_4_6:
	.byte		N01	, Cn4, v127
	.byte	W01
	.byte		N23	
	.byte	W23
	.byte		N01	
	.byte	W01
	.byte		N23	
	.byte	W23
	.byte		N01	
	.byte	W01
	.byte		N23	
	.byte	W23
	.byte	PEND
	.byte	PATT	
		.word	song_0043_4_6
	.byte	PATT	
		.word	song_0043_4_6
	.byte		N01	, Cn4, v127
	.byte	W01
	.byte		N23	
	.byte	W23
	.byte		N24	, Bn2
	.byte		N01	, Cn4
	.byte	W01
	.byte		N23	
	.byte	W23
	.byte		N01	
	.byte	W01
	.byte		N23	
	.byte	W23
	.byte	PATT	
		.word	song_0043_4_6
	.byte	PATT	
		.word	song_0043_4_6
	.byte		N01	, Cn4, v127
	.byte	W01
	.byte		N23	
	.byte	W23
	.byte		N11	, Gn3
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N11	
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N24	, Cn4
	.byte	W01
	.byte		N06	, Dn5
	.byte	W11
	.byte		N06	
	.byte	W24
	.byte		N06	
	.byte	W12
song_0043_4_7:
	.byte	W12
	.byte		N06	, Dn5, v127
	.byte	W13
	.byte		N06	
	.byte	W11
	.byte		N06	
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0043_4_7
	.byte	PATT	
		.word	song_0043_4_7
	.byte	PATT	
		.word	song_0043_4_7
	.byte	PATT	
		.word	song_0043_4_7
	.byte	W12
	.byte		N06	, Dn5, v127
	.byte	W13
	.byte		N06	
	.byte	W11
	.byte		N06	
	.byte	W24
	.byte		N06	
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N11	, Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N23	, Bn2
	.byte		N24	, Gn3
	.byte	W96
	.byte		N24	
	.byte	W72
	.byte		N21	, Bn2
	.byte	W24
	.byte		N16	, Gn3
	.byte	W24
	.byte		N22	, Bn2
	.byte	W24
	.byte		N16	, Gn3
	.byte	W24
	.byte		N22	, Bn2
	.byte	W24
	.byte		N16	, Gn3
	.byte	W24
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N11	, Gn3
	.byte		N06	, Dn5
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	GOTO	
		.word	song_0043_4_8
	.byte	FINE

	.align 2
	.global song_0043
song_0043:	@ 0x087E043C
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0043_1		@ track
	.word	song_0043_2		@ track
	.word	song_0043_3		@ track
	.word	song_0043_4		@ track
