	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0024_1
song_0024_1:	@ 0x087DA244
	.byte	KEYSH	, 0
	.byte	TEMPO	, 93
	.byte	VOICE	, 3
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W48
	.byte	TEMPO	, 39
	.byte	W24
	.byte	W48
	.byte	TEMPO	, 14
	.byte	W11
	.byte		N15	, Gn3, v127
	.byte	W01
	.byte	TEMPO	, 40
	.byte	W12
song_0024_1_1:
	.byte		N54	, En4, v127
	.byte	W60
	.byte		N12	
	.byte	W11
	.byte		N13	, Fn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		N48	, Dn4
	.byte	W01
	.byte	W60
	.byte		N12	
	.byte	W11
	.byte		N14	, En4
	.byte	W13
	.byte		N10	, Dn4
	.byte	W12
	.byte		N13	
	.byte	W12
	.byte		N20	, Cn4
	.byte	W20
	.byte		N09	, Bn3
	.byte	W08
	.byte		N08	, Cn4
	.byte	W07
	.byte		N30	, An4
	.byte	W36
	.byte	W01
	.byte		N10	, Cn4
	.byte	W11
	.byte		N48	
	.byte	W01
	.byte	W44
	.byte	W03
	.byte		N32	, Bn3
	.byte	W48
	.byte	W01
	.byte		N23	, Cn4
	.byte	W23
	.byte		N32	, An4
	.byte	W32
	.byte	W02
	.byte		N04	, Gs4
	.byte	W03
	.byte		N11	, An4
	.byte	W10
	.byte		N12	, Gn4
	.byte	W12
	.byte		N09	, Fn4
	.byte	W12
	.byte		N11	
	.byte	W02
	.byte	W07
	.byte			En4
	.byte	W11
	.byte		N48	, Gn4
	.byte	W64
	.byte	W01
	.byte		N13	, Cn4
	.byte	W12
	.byte		N44	, Dn4
	.byte	W01
	.byte	W44
	.byte	W03
	.byte		N13	
	.byte	W12
	.byte		N14	, En4
	.byte	W13
	.byte		N24	, Dn4
	.byte	W23
	.byte		N48	, En4
	.byte	W01
	.byte	W44
	.byte	W03
	.byte		N36	, Dn4
	.byte	W48
	.byte	W01
	.byte		N54	, En4
	.byte	W56
	.byte		N03	, Ds4
	.byte	W03
	.byte		N12	, En4
	.byte	W11
	.byte			Fn4
	.byte	W12
	.byte		N14	, En4
	.byte	W13
	.byte		N56	, Dn4
	.byte	W01
	.byte	W60
	.byte		N13	
	.byte	W12
	.byte			En4
	.byte	W11
	.byte		N10	, Dn4
	.byte	W13
	.byte		N14	
	.byte	W12
	.byte		N20	, Cn4
	.byte	W20
	.byte		N09	, Bn3
	.byte	W08
	.byte		N07	, Cn4
	.byte	W08
	.byte		N32	, An4
	.byte	W32
	.byte	W03
	.byte		N09	, Cn4
	.byte	W11
	.byte		N48	
	.byte	W02
	.byte	W44
	.byte	W02
	.byte		N36	, Bn3
	.byte	W48
	.byte	W02
	.byte		N23	, Cn4
	.byte	W22
	.byte		N32	, An4
	.byte	W36
	.byte		N11	
	.byte	W11
	.byte		N03	, As4
	.byte	W02
	.byte		N11	, Bn4
	.byte	W12
	.byte		N09	, An4
	.byte	W12
	.byte		N10	
	.byte	W01
	.byte	W08
	.byte		N06	, Gn4
	.byte	W09
	.byte		N36	
	.byte	W40
	.byte		N04	, Fs4
	.byte	W02
	.byte		N21	, Gn4
	.byte	W21
	.byte		N09	, Fn4
	.byte	W08
	.byte		N08	, En4
	.byte	W07
	.byte		N07	, Fn4
	.byte	W01
	.byte	W05
	.byte		N06	, En4
	.byte	W06
	.byte		N36	, Fn4
	.byte	W48
	.byte		N13	, Dn4
	.byte	W11
	.byte			En4
	.byte	W13
	.byte		N14	, Fn4
	.byte	W12
	.byte		N48	, En4
	.byte	W01
	.byte	W48
	.byte		N36	, Dn4
	.byte	W36
	.byte		N08	, Cn4
	.byte	W11
	.byte		N15	
	.byte	W01
	.byte	W18
	.byte		N04	, Gs4
	.byte	W03
	.byte		N32	, An4
	.byte	W36
	.byte	W02
	.byte		N12	
	.byte	W12
	.byte		N11	, Bn4
	.byte	W11
	.byte		N12	, Cn5
	.byte	W12
	.byte		N02	, Bn4
	.byte	W02
	.byte	W01
	.byte		N03	, Cn5
	.byte	W04
	.byte		N24	, Bn4
	.byte	W28
	.byte	W01
	.byte		N08	, Gn4
	.byte	W10
	.byte		N03	, Gs4
	.byte	W04
	.byte		N14	, An4
	.byte	W23
	.byte		N07	, En4
	.byte	W08
	.byte			Fn4
	.byte	W07
	.byte		N04	, Gn4
	.byte	W08
	.byte		N10	
	.byte	W02
	.byte	W06
	.byte		N06	, Fn4
	.byte	W06
	.byte		N04	, En4
	.byte	W04
	.byte		N48	, Fn4
	.byte	W54
	.byte	W01
	.byte		N09	, Cn4
	.byte	W11
	.byte		N13	, Dn4
	.byte	W13
	.byte		N42	, En4
	.byte	W01
	.byte	W48
	.byte		N08	, Dn4
	.byte	W08
	.byte		N05	, En4
	.byte	W04
	.byte		N03	, Dn4
	.byte	W04
	.byte		N02	, En4
	.byte	W03
	.byte			Dn4
	.byte	W04
	.byte		N02	
	.byte	W03
	.byte			En4
	.byte	W02
	.byte			Dn4
	.byte	W02
	.byte		N03	, En4
	.byte	W03
	.byte		N01	, Dn4
	.byte	W03
	.byte		N04	
	.byte	W03
	.byte		N07	, Cn4
	.byte	W09
	.byte		TIE	
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W36
	.byte	W01
	.byte		EOT	
	.byte	W03
	.byte		N02	, Dn4
	.byte	W03
	.byte		N04	, En4
	.byte	W03
	.byte		N13	, Fn4
	.byte	W11
	.byte		N14	, En4
	.byte	W13
	.byte			Dn4
	.byte	W12
	.byte		N09	, Fn4
	.byte	W07
	.byte		N84	, En4
	.byte	W07
	.byte	W84
	.byte		N11	, Cn4
	.byte	W12
	.byte		N19	, An3
	.byte	W23
	.byte		N23	, Cn4
	.byte	W24
	.byte		N24	, Fn4
	.byte	W24
	.byte	W02
	.byte		N19	, An4
	.byte	W19
	.byte		N03	, Fs4
	.byte	W04
	.byte		TIE	, Gn4
	.byte	W96
	.byte	W44
	.byte	W03
	.byte		EOT	
	.byte	W48
	.byte	W01
	.byte	GOTO	
		.word	song_0024_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0024_2
song_0024_2:	@ 0x087DA3DE
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W24
	.byte		N68	, Gn3, v127
	.byte		N68	, As3
	.byte	W24
	.byte	W48
	.byte		N44	, Fn3
	.byte		N44	, As3
	.byte	W24
	.byte	W24
	.byte		N22	, Gn3
	.byte		N22	, Dn4
	.byte	W24
	.byte		TIE	, Ds4
	.byte		TIE	, Gn4
	.byte	W24
	.byte	W72
	.byte	W72
	.byte	W48
	.byte		EOT	, Ds4
	.byte			Gn4
	.byte	W24
song_0024_2_3:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W12
	.byte		N12	, Gn2, v127
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N48	, En3
	.byte	W48
	.byte	W12
	.byte		N12	, Gn2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte		N40	, Dn3
	.byte	W48
	.byte		N24	, An2
	.byte	W24
	.byte			Gn2
	.byte	W24
	.byte		N48	, Fn2
	.byte	W48
	.byte	W08
	.byte		N08	, Gn2
	.byte	W08
	.byte			An2
	.byte	W08
	.byte			En3
	.byte	W08
	.byte			Dn3
	.byte	W08
	.byte			Cn3
	.byte	W08
	.byte		N36	, Bn2
	.byte	W48
	.byte		N16	, An2
	.byte	W24
	.byte		N32	, Fn4
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte		N07	
	.byte	W08
	.byte			En4
	.byte	W08
	.byte		N30	
	.byte	W80
	.byte		N07	, Dn4
	.byte	W07
	.byte			Cs4
	.byte	W07
	.byte		N40	, Dn4
	.byte	W44
	.byte	W02
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			An3
	.byte	W12
	.byte		N84	, Gn3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0024_2_1:
	.byte		N05	, Cn3, v127
	.byte		N05	, En3
	.byte	W06
	.byte			Dn3
	.byte		N05	, Fn3
	.byte	W06
	.byte		N16	, En3
	.byte		N16	, Gn3
	.byte	W24
	.byte		N60	, En3
	.byte		N60	, Gn3
	.byte	W60
	.byte	PEND
song_0024_2_2:
	.byte		N68	, Fn3, v127
	.byte		N68	, An3
	.byte	W72
	.byte		N22	, Dn3
	.byte		N22	, Fn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0024_2_1
	.byte	PATT	
		.word	song_0024_2_2
	.byte	PATT	
		.word	song_0024_2_1
	.byte	PATT	
		.word	song_0024_2_2
	.byte	PATT	
		.word	song_0024_2_1
	.byte	PATT	
		.word	song_0024_2_2
	.byte	GOTO	
		.word	song_0024_2_3
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0024_3
song_0024_3:	@ 0x087DA4A8
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		N68	, Ds4, v127
	.byte	W24
	.byte	W48
	.byte		N22	, Dn4
	.byte	W24
	.byte			Ds4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		TIE	, Cn5
	.byte	W24
	.byte	W72
	.byte	W72
	.byte	W44
	.byte	W03
	.byte		EOT	
	.byte	W24
	.byte	W01
song_0024_3_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W48
	.byte		N44	, Gn3, v127
	.byte	W48
	.byte		N12	, An3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte		N22	, Cn4
	.byte	W24
	.byte		N44	, Dn4
	.byte	W48
	.byte		N22	, Bn3
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte		N44	, Cs4
	.byte	W48
	.byte		N92	, An3
	.byte	W96
	.byte		N44	, Gn3
	.byte	W48
	.byte		N44	
	.byte	W48
	.byte		N92	
	.byte	W96
	.byte			An3
	.byte	W96
	.byte			Gn3
	.byte	W96
	.byte			An3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0024_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0024_4
song_0024_4:	@ 0x087DA508
	.byte	KEYSH	, 0
	.byte	VOICE	, 19
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
	.byte	W72
	.byte	W48
	.byte		N11	, Gs1, v127
	.byte		N11	, Ds2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Cn5
	.byte		N11	, Ds5
	.byte	W12
	.byte			Gs4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Ds4
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			Gs3
	.byte	W12
	.byte		N06	, Ds4
	.byte		N06	, Gn4
	.byte	W04
	.byte			Cn4
	.byte	W04
	.byte			Gs3
	.byte	W04
	.byte			Gn3
	.byte	W04
	.byte			Ds3
	.byte	W04
	.byte			Cn3
	.byte	W04
	.byte			Gs2
	.byte	W04
	.byte			Gn2
	.byte	W04
	.byte			Ds2
	.byte	W04
	.byte		N04	, Gs3
	.byte		N04	, Cn4
	.byte	W04
	.byte			Gn3
	.byte	W04
	.byte			Ds3
	.byte	W04
	.byte			Cn3
	.byte	W04
	.byte			Gs2
	.byte	W04
	.byte			Gn2
	.byte	W04
	.byte		N12	, Gs1
	.byte	W36
song_0024_4_4:
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gn3
	.byte	W24
	.byte			Gn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Gn3
	.byte	W24
	.byte			Gn2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Gs2
	.byte	W12
song_0024_4_1:
	.byte		N12	, An1, v127
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte	PEND
	.byte			Dn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte		N06	
	.byte		N06	, Bn2
	.byte	W06
	.byte			An2
	.byte		N06	, Cn3
	.byte	W06
	.byte		N12	, Bn2
	.byte		N12	, Dn3
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gn3
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn3
	.byte	W24
	.byte			Bn1
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte	PATT	
		.word	song_0024_4_1
	.byte		N12	, Dn2, v127
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			As2
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			An3
	.byte	W24
	.byte			Dn2
	.byte		N12	, An2
	.byte	W12
	.byte			Cn3
	.byte		N12	, Fn3
	.byte	W12
	.byte			An2
	.byte		N12	, Dn3
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Cn3
	.byte	W24
	.byte			An2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			An2
	.byte		N12	, Cs3
	.byte	W12
	.byte			Bn2
	.byte		N12	, Dn3
	.byte	W12
	.byte			Cs3
	.byte		N12	, En3
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Fn3
	.byte	W24
	.byte			Dn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			En3
	.byte	W48
	.byte			Dn3
	.byte	W48
	.byte			Cn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gn3
	.byte	W36
	.byte			Gn2
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Fn3
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte			An2
	.byte	W24
song_0024_4_2:
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gn3
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte			Cn3
	.byte	W24
	.byte	PEND
song_0024_4_3:
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Fn3
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte			Dn3
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0024_4_2
	.byte	PATT	
		.word	song_0024_4_3
	.byte	PATT	
		.word	song_0024_4_2
	.byte	PATT	
		.word	song_0024_4_3
	.byte	GOTO	
		.word	song_0024_4_4
	.byte	FINE

	.align 2
	.global song_0024
song_0024:	@ 0x087DA6E0
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0024_1		@ track
	.word	song_0024_2		@ track
	.word	song_0024_3		@ track
	.word	song_0024_4		@ track
