	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0037_1
song_0037_1:	@ 0x087DE418
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 36
	.byte		N12	, An3, v112
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Fs4
	.byte	W12
song_0037_1_3:
	.byte		N96	, Bn3, v112
	.byte	W96
song_0037_1_1:
	.byte	W12
	.byte		N12	, Bn3, v112
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte	PEND
	.byte		TIE	, Fs4
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W12
	.byte		N12	, An3
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte		N96	, Bn3
	.byte	W96
	.byte	PATT	
		.word	song_0037_1_1
	.byte		N96	, An4, v112
	.byte	W96
	.byte	W24
	.byte		N24	
	.byte	W24
	.byte			Bn4
	.byte	W24
	.byte			Cn5
	.byte	W24
	.byte	W01
	.byte		N48	, Bn4
	.byte	W48
	.byte			Fs5
	.byte	W44
	.byte	W03
	.byte		N60	, En5
	.byte	W60
	.byte		N12	, Dn5
	.byte	W12
	.byte			Cs5
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte		N48	, An4
	.byte	W48
	.byte			En5
	.byte	W48
	.byte		N60	, Dn5
	.byte	W60
	.byte		N12	, Cs5
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N08	, Bn4
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N06	, En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte		N08	, Gn4
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N06	
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N08	, Bn4
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N04	, Bn3, v068
	.byte	W04
	.byte			Cs4
	.byte	W04
	.byte			Dn4
	.byte	W04
	.byte			En4
	.byte	W04
	.byte			Fs4
	.byte	W04
	.byte			Gn4
	.byte	W04
	.byte			Bn4
	.byte	W04
	.byte			Cs5
	.byte	W04
	.byte			Dn5
	.byte	W04
	.byte			En5
	.byte	W04
	.byte			Fs5
	.byte	W04
	.byte			Gn5
	.byte	W04
	.byte		N07	, An5
	.byte	W06
	.byte		N06	, Bn5
	.byte	W05
	.byte		N05	, An5
	.byte	W04
	.byte		N04	, Bn5
	.byte	W04
	.byte		N02	, An5
	.byte	W04
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte			An5
	.byte	W02
	.byte			Bn5
	.byte	W03
	.byte		N72	, An5
	.byte	W96
song_0037_1_2:
	.byte	W48
	.byte		N03	, Dn6, v076
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Bn5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Gn5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Dn5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Bn5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Gn5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Dn5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte	PEND
	.byte	W96
	.byte	W48
	.byte			Dn6
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			An5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Fs5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Dn5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			An5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Fs5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Dn5
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			An4
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte			Fs4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Cn5
	.byte	W03
	.byte			Fs5
	.byte	W03
	.byte		N04	, An5
	.byte	W84
	.byte	PATT	
		.word	song_0037_1_2
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		N24	, Fs4, v080
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte		N30	, Bn4
	.byte	W36
	.byte		N06	
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte		N12	, Dn5
	.byte	W12
	.byte		N20	, En5
	.byte	W20
	.byte		N08	, Fs5
	.byte	W08
	.byte			Gn5
	.byte	W08
	.byte		N36	, An5
	.byte	W36
	.byte		N12	, Gn5
	.byte	W12
	.byte		N40	, Fs5
	.byte	W48
	.byte		N08	, Gn5
	.byte	W08
	.byte			Fs5
	.byte	W08
	.byte			Gn5
	.byte	W08
	.byte		TIE	, En5
	.byte	W72
	.byte	W40
	.byte		EOT	
	.byte	W08
	.byte		N23	, Dn5
	.byte	W24
	.byte		N24	, Cs5
	.byte	W24
	.byte		TIE	, Dn5
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W12
	.byte		N12	, An3
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte	GOTO	
		.word	song_0037_1_3
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0037_2
song_0037_2:	@ 0x087DE5A8
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
	.byte	W36
song_0037_2_3:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0037_2_1:
	.byte	W60
	.byte		N12	, An3, v112
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte	PEND
	.byte		N96	, Bn3
	.byte	W96
song_0037_2_2:
	.byte	W12
	.byte		N12	, Bn3, v112
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		N20	, Dn4
	.byte	W20
	.byte		N08	, Cs4
	.byte	W08
	.byte			Dn4
	.byte	W08
	.byte	PEND
	.byte		N96	, Fs4
	.byte	W96
	.byte	PATT	
		.word	song_0037_2_1
	.byte		N96	, Bn3, v112
	.byte	W96
	.byte	PATT	
		.word	song_0037_2_2
	.byte		N96	, An4, v112
	.byte	W96
	.byte	W24
	.byte		N24	, Fs3, v127
	.byte	W24
	.byte			Gn3
	.byte	W24
	.byte			An3
	.byte	W24
	.byte		N30	, Bn3
	.byte	W36
	.byte		N06	
	.byte	W06
	.byte			Cs4
	.byte	W06
	.byte		N12	, Dn4
	.byte	W12
	.byte		N20	, En4
	.byte	W20
	.byte		N08	, Fs4
	.byte	W08
	.byte			Gn4
	.byte	W08
	.byte		N36	, An4
	.byte	W36
	.byte		N12	, Gn4
	.byte	W12
	.byte		N40	, Fs4
	.byte	W48
	.byte	W24
	.byte		N08	, Dn3
	.byte	W08
	.byte			Cs3
	.byte	W08
	.byte			Dn3
	.byte	W08
	.byte		N48	, Bn2
	.byte	W48
	.byte	W48
	.byte		N23	, Bn4, v100
	.byte	W24
	.byte		N24	, Gn4
	.byte	W24
	.byte		TIE	, Fs4
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W48
	.byte	GOTO	
		.word	song_0037_2_3
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0037_3
song_0037_3:	@ 0x087DE63A
	.byte	KEYSH	, 0
	.byte	VOICE	, 14
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
	.byte	W36
song_0037_3_3:
	.byte		N11	, Bn2, v127
	.byte		N12	, Dn3
	.byte	W12
	.byte		N11	, Gn2
	.byte	W12
	.byte		N10	, Bn2
	.byte		N10	, Dn3
	.byte	W12
	.byte		N09	, Gn2
	.byte	W12
	.byte		N11	, Bn2
	.byte		N11	, Dn3
	.byte	W12
	.byte		N09	, Gn2
	.byte	W12
	.byte		N08	, Bn2
	.byte		N07	, Gn3
	.byte	W12
	.byte			Bn2
	.byte		N10	, Fs3
	.byte	W12
	.byte		N12	, Cs3
	.byte		N11	, En3
	.byte	W12
	.byte		N08	, An2
	.byte	W12
	.byte		N11	, Cs3
	.byte		N11	, En3
	.byte	W12
	.byte		N06	, An2
	.byte	W12
	.byte		N10	, Cs3
	.byte		N11	, En3
	.byte	W12
	.byte		N06	, An2
	.byte	W12
	.byte		N09	, Cs3
	.byte		N10	, En3
	.byte	W24
song_0037_3_2:
	.byte		N12	, Dn3, v127
	.byte		N11	, Fs3
	.byte	W12
	.byte		N07	, An2
	.byte	W12
	.byte		N11	, Dn3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N07	, An2
	.byte	W12
	.byte		N10	, Dn3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N05	, An2
	.byte	W12
	.byte		N13	, Dn3
	.byte		N12	, Fs3
	.byte	W24
	.byte	PEND
	.byte			Cn3
	.byte		N11	, Fs3
	.byte	W12
	.byte		N09	, An2
	.byte	W12
	.byte		N10	, Cn3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N08	, An2
	.byte	W12
	.byte		N11	, Cn3
	.byte		N12	, Fs3
	.byte	W24
	.byte		N10	, Cn3
	.byte		N10	, Fs3
	.byte	W24
	.byte		N11	, Dn3
	.byte		N11	, Gn3
	.byte	W12
	.byte		N07	, Bn2
	.byte	W12
	.byte		N11	, Dn3
	.byte		N10	, Gn3
	.byte	W12
	.byte		N05	, Bn2
	.byte	W12
	.byte		N10	, Dn3
	.byte		N10	, Gn3
	.byte	W12
	.byte		N09	, Bn2
	.byte	W12
	.byte		N08	, Dn3
	.byte		N09	, Gn3
	.byte	W12
	.byte		N04	, Dn3
	.byte		N05	, Fs3
	.byte	W12
song_0037_3_1:
	.byte		N10	, Cs3, v127
	.byte		N11	, En3
	.byte	W12
	.byte		N07	, An2
	.byte	W12
	.byte		N10	, Cs3
	.byte		N11	, En3
	.byte	W12
	.byte		N05	, An2
	.byte	W12
	.byte		N09	, Cs3
	.byte		N10	, En3
	.byte	W12
	.byte		N05	, An2
	.byte	W12
	.byte		N10	, Cs3
	.byte		N11	, En3
	.byte	W24
	.byte	PEND
	.byte			Cs3
	.byte		N12	, Fs3
	.byte	W12
	.byte		N10	, An2
	.byte	W12
	.byte		N12	, Cs3
	.byte		N12	, Fs3
	.byte	W12
	.byte		N10	, Fs2
	.byte	W12
	.byte		N11	, Fs3
	.byte		N12	, An3
	.byte	W12
	.byte		N13	, Fs2
	.byte	W12
	.byte		N11	, Gn3
	.byte	W12
	.byte		N12	, Fs2
	.byte	W12
	.byte		N11	, Ds3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N08	, An2
	.byte	W12
	.byte		N11	, Ds3
	.byte		N09	, Fs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Ds3
	.byte		N09	, Fs3
	.byte	W24
	.byte		N13	, Ds3
	.byte		N13	, Fs3
	.byte	W12
	.byte		N10	, An2
	.byte	W12
	.byte		N12	, Bn2
	.byte		N11	, Dn3
	.byte	W12
	.byte		N07	, Gn2
	.byte	W12
	.byte		N11	, Bn2
	.byte		N11	, Dn3
	.byte	W24
	.byte		N10	
	.byte		N11	, Fs3
	.byte	W12
	.byte		N09	, Bn2
	.byte	W12
	.byte		N10	
	.byte		N13	, Fs3
	.byte	W24
	.byte		N11	, Cs3
	.byte		N12	, En3
	.byte	W12
	.byte		N07	, An2
	.byte	W12
	.byte		N11	, Cs3
	.byte		N11	, En3
	.byte	W12
	.byte		N06	, An2
	.byte	W12
	.byte		N12	, Cs3
	.byte		N14	, En3
	.byte	W24
	.byte		N12	, Cs3
	.byte		N12	, En3
	.byte	W24
	.byte		N10	, Cs3
	.byte		N11	, Fs3
	.byte	W12
	.byte		N08	, An2
	.byte	W12
	.byte		N10	, Cs3
	.byte		N11	, Fs3
	.byte	W12
	.byte		N04	, An2
	.byte	W12
	.byte		N10	, Cs3
	.byte		N12	, Fs3
	.byte	W12
	.byte		N04	, An2
	.byte	W12
	.byte		N10	, Cs3
	.byte		N11	, Fs3
	.byte	W24
	.byte		N10	, Dn3
	.byte		N11	, Fs3
	.byte	W12
	.byte		N06	, An2
	.byte	W12
	.byte		N11	, Dn3
	.byte		N11	, Fs3
	.byte	W12
	.byte		N06	, An2
	.byte	W12
	.byte		N12	, Dn3
	.byte		N12	, Fs3
	.byte	W24
	.byte		N10	, Dn3
	.byte		N09	, Fs3
	.byte	W24
	.byte			Dn3
	.byte		N09	, Gn3
	.byte	W12
	.byte		N06	, Bn2
	.byte	W12
	.byte		N14	, Dn3
	.byte		N14	, Gn3
	.byte	W24
	.byte		N09	, Dn3
	.byte		N10	, Gn3
	.byte	W12
	.byte		N05	, Bn2
	.byte	W12
	.byte		N14	, Dn3
	.byte		N15	, Gn3
	.byte	W24
	.byte		N11	, Dn3
	.byte		N11	, Gn3
	.byte	W12
	.byte		N07	, Bn2
	.byte	W12
	.byte		N15	, Dn3
	.byte		N15	, Gn3
	.byte	W24
	.byte		N10	, Dn3
	.byte		N11	, Gn3
	.byte	W12
	.byte		N04	, Bn2
	.byte	W12
	.byte		N08	, Dn3
	.byte		N08	, Gn3
	.byte	W24
	.byte		N07	
	.byte		N09	, Dn4
	.byte	W12
	.byte		N05	, En3
	.byte	W12
	.byte		N10	, Gn3
	.byte		N12	, Dn4
	.byte	W12
	.byte		N07	, En3
	.byte	W12
	.byte		N11	, Gn3
	.byte		N12	, Dn4
	.byte	W12
	.byte		N06	, En3
	.byte	W12
	.byte		N10	, Gn3
	.byte		N11	, Dn4
	.byte	W12
	.byte		N05	, En3
	.byte	W12
	.byte		N92	, An3
	.byte		N92	, Cs4
	.byte	W96
	.byte		N11	, Bn2
	.byte		N10	, Dn3
	.byte	W12
	.byte		N11	, Gn2
	.byte	W12
	.byte			Bn2
	.byte		N10	, Dn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte		N11	, Bn2
	.byte		N11	, Dn3
	.byte	W12
	.byte		N09	, Gn2
	.byte	W12
	.byte		N08	, Bn2
	.byte		N07	, Gn3
	.byte	W12
	.byte			Bn2
	.byte		N10	, Fs3
	.byte	W12
	.byte			Cs3
	.byte		N11	, En3
	.byte	W12
	.byte		N08	, An2
	.byte	W12
	.byte		N11	, Cs3
	.byte		N11	, En3
	.byte	W12
	.byte		N10	, An2
	.byte	W12
	.byte			Cs3
	.byte		N11	, En3
	.byte	W12
	.byte		N09	, An2
	.byte	W12
	.byte		N11	, Cs3
	.byte		N10	, En3
	.byte	W24
	.byte		N11	, Dn3
	.byte		N11	, Fs3
	.byte	W12
	.byte		N07	, An2
	.byte	W12
	.byte		N11	, Dn3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N08	, An2
	.byte	W12
	.byte		N10	, Dn3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N09	, An2
	.byte	W12
	.byte		N13	, Dn3
	.byte		N12	, Fs3
	.byte	W24
	.byte			Cn3
	.byte		N11	, Fs3
	.byte	W12
	.byte		N09	, An2
	.byte	W12
	.byte		N10	, Cn3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N08	, An2
	.byte	W12
	.byte		N11	, Cn3
	.byte		N12	, Fs3
	.byte	W12
	.byte		N14	, Dn2
	.byte	W12
	.byte		N10	, Cn3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N13	, Dn2
	.byte	W12
	.byte		N12	, Dn3
	.byte		N11	, Gn3
	.byte	W12
	.byte		N09	, Bn2
	.byte	W12
	.byte		N11	, Dn3
	.byte		N10	, Gn3
	.byte	W12
	.byte		N11	, Bn2
	.byte	W12
	.byte		N10	, Dn3
	.byte		N10	, Gn3
	.byte	W12
	.byte		N09	, Bn2
	.byte	W12
	.byte		N08	, Dn3
	.byte		N09	, Gn3
	.byte	W12
	.byte		N04	, Dn3
	.byte		N05	, Fs3
	.byte	W12
	.byte	PATT	
		.word	song_0037_3_1
	.byte		N11	, Cs3, v127
	.byte		N12	, Fs3
	.byte	W12
	.byte		N10	, An2
	.byte	W12
	.byte		N12	, Cs3
	.byte		N12	, Fs3
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte		N11	, Fs3
	.byte		N12	, An3
	.byte	W12
	.byte		N11	, Fs2
	.byte	W12
	.byte			Cs3
	.byte		N11	, Gn3
	.byte	W12
	.byte		N12	, Fs2
	.byte	W12
	.byte		N11	, Ds3
	.byte		N10	, Fs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte		N11	, Ds3
	.byte		N09	, Fs3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Ds3
	.byte		N09	, Fs3
	.byte	W24
	.byte		N23	, Cn3
	.byte		N23	, Fs3
	.byte	W24
	.byte		N10	, Dn3
	.byte		N10	, Gn3
	.byte	W12
	.byte		N06	, Bn2
	.byte	W12
	.byte		N10	, Dn3
	.byte		N10	, Gn3
	.byte	W24
	.byte		N11	, Dn3
	.byte		N13	, Gn3
	.byte	W24
	.byte		N09	, Dn3
	.byte		N09	, Gn3
	.byte	W24
	.byte		N10	, Cs3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N09	, Fs2
	.byte	W12
	.byte		N12	, Cs3
	.byte		N12	, En3
	.byte	W12
	.byte		N09	, Fs2
	.byte	W12
	.byte		N12	, Ds3
	.byte		N12	, Fs3
	.byte	W12
	.byte		N09	, An2
	.byte	W12
	.byte		N16	, Ds3
	.byte		N16	, Fs3
	.byte	W24
	.byte		N09	, Dn3
	.byte		N09	, Gn3
	.byte	W12
	.byte		N11	, Bn2
	.byte	W12
	.byte		N14	, Dn3
	.byte		N14	, Gn3
	.byte	W24
	.byte		N09	, Dn3
	.byte		N10	, Gn3
	.byte	W12
	.byte		N11	, Bn2
	.byte	W12
	.byte		N14	, Dn3
	.byte		N15	, Gn3
	.byte	W24
	.byte		N48	, En3
	.byte		N48	, An3
	.byte	W96
	.byte	PATT	
		.word	song_0037_3_2
	.byte		N12	, Dn3, v127
	.byte		N11	, Fs3
	.byte	W12
	.byte		N09	, An2
	.byte	W12
	.byte		N11	, Dn3
	.byte		N10	, Fs3
	.byte	W12
	.byte		N08	, An2
	.byte	W12
	.byte		N12	, Cn3
	.byte		N12	, Fs3
	.byte	W12
	.byte		N11	, Dn2
	.byte	W12
	.byte		N10	, Cn3
	.byte		N10	, Fs3
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte	GOTO	
		.word	song_0037_3_3
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0037_4
song_0037_4:	@ 0x087DE945
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
	.byte	W36
song_0037_4_4:
	.byte		N56	, Gn1, v127
	.byte	W66
	.byte		N21	
	.byte	W24
	.byte		N80	
	.byte	W06
	.byte	W84
	.byte		N12	
	.byte	W12
	.byte		N80	, Dn2
	.byte	W84
	.byte		N64	
	.byte	W12
	.byte	W60
	.byte		N12	
	.byte	W24
	.byte		N13	
	.byte	W12
	.byte		N48	, Gn1
	.byte	W60
	.byte		N18	
	.byte	W24
	.byte		N09	
	.byte	W12
	.byte		N72	
	.byte	W84
	.byte		N10	
	.byte	W12
	.byte		N36	, Fs1
	.byte	W48
	.byte		N48	
	.byte	W48
	.byte		N54	, Bn1
	.byte	W60
	.byte		N06	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte			Gn1
	.byte	W36
	.byte		N03	
	.byte	W06
	.byte		N16	
	.byte	W24
	.byte		N13	
	.byte	W18
	.byte		N66	
	.byte	W12
	.byte	W60
	.byte		N16	
	.byte	W24
	.byte		N11	
	.byte	W12
	.byte		N72	, Fs1
	.byte	W84
	.byte		N13	
	.byte	W12
	.byte		N48	, Bn1
	.byte	W60
	.byte		N14	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N32	, En2
	.byte	W48
	.byte		N24	
	.byte	W36
	.byte		N07	, En1
	.byte	W12
	.byte		N24	
	.byte	W36
	.byte		N05	
	.byte	W12
	.byte		N28	
	.byte	W36
	.byte		N02	
	.byte	W12
	.byte		N44	, An1
	.byte	W48
	.byte		N32	
	.byte	W48
	.byte		N92	
	.byte	W96
song_0037_4_1:
	.byte		N06	, Gn1, v116
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0037_4_1
song_0037_4_2:
	.byte		N06	, Dn2, v116
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0037_4_2
	.byte	PATT	
		.word	song_0037_4_1
	.byte	PATT	
		.word	song_0037_4_1
	.byte		N06	, Fs2, v116
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Bn2
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
song_0037_4_3:
	.byte		N06	, En2, v116
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte			Fs2
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Bn2
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0037_4_3
	.byte		N48	, An1, v127
	.byte	W96
	.byte		N80	, Dn2
	.byte	W84
	.byte		N11	
	.byte	W12
	.byte		N56	, Dn1
	.byte	W72
	.byte		N10	
	.byte	W24
	.byte	GOTO	
		.word	song_0037_4_4
	.byte	FINE

	.align 2
	.global song_0037
song_0037:	@ 0x087DEA78
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0037_1		@ track
	.word	song_0037_2		@ track
	.word	song_0037_3		@ track
	.word	song_0037_4		@ track
