	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0030_1
song_0030_1:	@ 0x087DBD5C
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 5
	.byte	VOL	, v100
	.byte	PAN	, c_v
	.byte	W24
song_0030_1_5:
	.byte	TEMPO	, 40
	.byte		N04	, As2, v120
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
song_0030_1_1:
	.byte		N04	, As2, v120
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0030_1_1
	.byte	PATT	
		.word	song_0030_1_1
	.byte	PATT	
		.word	song_0030_1_1
	.byte	PATT	
		.word	song_0030_1_1
song_0030_1_2:
	.byte		N04	, Cn3, v120
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0030_1_1
	.byte	PATT	
		.word	song_0030_1_2
	.byte		N04	, As2, v120
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W24
	.byte		N06	, Dn3
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte			As2
	.byte	W06
	.byte			An2
	.byte	W06
song_0030_1_3:
	.byte		N04	, Gn3, v120
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0030_1_3
	.byte	PATT	
		.word	song_0030_1_3
	.byte	PATT	
		.word	song_0030_1_3
song_0030_1_4:
	.byte		N04	, Gs3, v120
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0030_1_3
	.byte	PATT	
		.word	song_0030_1_4
	.byte		N04	, Gn3, v120
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W12
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N02	
	.byte	W04
	.byte		N04	
	.byte	W48
	.byte	PATT	
		.word	song_0030_1_3
	.byte	PATT	
		.word	song_0030_1_3
	.byte	PATT	
		.word	song_0030_1_3
	.byte	PATT	
		.word	song_0030_1_3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W72
	.byte		N06	, Dn4, v120
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			As3
	.byte	W06
	.byte			An3
	.byte	W06
	.byte	GOTO	
		.word	song_0030_1_5
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0030_2
song_0030_2:	@ 0x087DBEA7
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v094
	.byte	PAN	, c_v
	.byte	W24
song_0030_2_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N44	, Ds3, v120
	.byte	W48
	.byte			Gs3
	.byte	W44
	.byte		N02	, As3
	.byte	W02
	.byte			Cn4
	.byte	W02
	.byte		N06	, Dn4
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte		N52	, As3
	.byte	W60
	.byte		N24	, Gn3
	.byte	W24
	.byte		N96	, Gs3
	.byte	W96
	.byte		N48	, Gn3
	.byte	W96
	.byte	GOTO	
		.word	song_0030_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0030_3
song_0030_3:	@ 0x087DBEE8
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	MOD	, 0
	.byte	VOL	, v100
	.byte	PAN	, c_v
	.byte	W24
song_0030_3_8:
	.byte	W96
	.byte	W92
	.byte	W01
	.byte		N01	, Dn3, v112
	.byte	W01
	.byte			Gn3
	.byte	W02
song_0030_3_2:
	.byte		N48	, As3, v112
	.byte	W48
	.byte		N24	, An3
	.byte	W24
	.byte			Fn3
	.byte	W24
	.byte	PEND
song_0030_3_3:
	.byte		N04	, Gn3, v112
	.byte	W24
	.byte		N48	, Dn3
	.byte	W48
	.byte		N06	, Cn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte			Ds3
	.byte	W06
	.byte	PEND
song_0030_3_4:
	.byte		N06	, Dn3, v112
	.byte	W18
	.byte		N02	, Ds3
	.byte	W02
	.byte			Fn3
	.byte	W02
	.byte			Ds3
	.byte	W02
	.byte		N12	, Dn3
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte		N04	, Dn3
	.byte	W18
	.byte			Gn3
	.byte	W06
	.byte			As3
	.byte	W18
	.byte			Ds4
	.byte	W06
	.byte	PEND
song_0030_3_5:
	.byte		N72	, Dn4, v112
	.byte	W78
	.byte		N06	
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte	PEND
song_0030_3_1:
	.byte		N06	, Ds4, v112
	.byte	W18
	.byte		N03	, Gs3
	.byte	W03
	.byte			Gn3
	.byte	W03
	.byte		N40	, Gs3
	.byte	W48
	.byte		N18	, Cn4
	.byte	W18
	.byte		N03	, As3
	.byte	W03
	.byte			Cn4
	.byte	W03
	.byte	PEND
song_0030_3_6:
	.byte		N06	, As3, v112
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N60	, Gn3
	.byte	W66
	.byte		N06	, Dn4
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0030_3_1
	.byte		N06	, As3, v112
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N36	, Gn4
	.byte	W60
	.byte		N06	, Dn3
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte			As2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte	PATT	
		.word	song_0030_3_2
	.byte	PATT	
		.word	song_0030_3_3
	.byte	PATT	
		.word	song_0030_3_4
	.byte	PATT	
		.word	song_0030_3_5
	.byte	PATT	
		.word	song_0030_3_1
	.byte	PATT	
		.word	song_0030_3_6
	.byte	PATT	
		.word	song_0030_3_1
	.byte		N06	, As3, v112
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N36	, Gn4
	.byte	W80
	.byte	W01
	.byte		N01	, Dn4
	.byte	W01
	.byte			Gn4
	.byte	W02
	.byte		N48	, As4
	.byte	W48
	.byte		N24	, An4
	.byte	W24
	.byte			Fn4
	.byte	W24
	.byte		N04	, Gn4
	.byte	W24
	.byte		N48	, Dn4
	.byte	W48
	.byte		N06	, Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Dn4
	.byte	W18
	.byte		N02	, Ds4
	.byte	W02
	.byte			Fn4
	.byte	W02
	.byte			Ds4
	.byte	W02
	.byte		N12	, Dn4
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N04	, Dn4
	.byte	W18
	.byte			Gn4
	.byte	W06
	.byte			As4
	.byte	W18
	.byte			Ds5
	.byte	W06
	.byte		N72	, Dn5
	.byte	W78
	.byte		N06	
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			Dn5
	.byte	W06
song_0030_3_7:
	.byte		N06	, Ds5, v112
	.byte	W18
	.byte		N03	, Gs4
	.byte	W03
	.byte			Gn4
	.byte	W03
	.byte		N40	, Gs4
	.byte	W48
	.byte		N18	, Cn5
	.byte	W18
	.byte		N03	, As4
	.byte	W03
	.byte			Cn5
	.byte	W03
	.byte	PEND
	.byte		N06	, As4
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N60	, Gn4
	.byte	W66
	.byte		N06	, Dn5
	.byte	W06
	.byte			Cn5
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte	PATT	
		.word	song_0030_3_7
	.byte		N06	, As4, v112
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N36	, Gn5
	.byte	W84
	.byte	GOTO	
		.word	song_0030_3_8
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0030_4
song_0030_4:	@ 0x087DC01A
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v100
	.byte	PAN	, c_v
	.byte	W24
song_0030_4_1:
	.byte		N48	, Gn1, v127
	.byte	W84
	.byte		N12	, Dn2
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
song_0030_4_2:
	.byte		N48	, Gs1, v127
	.byte	W84
	.byte		N12	, Ds2
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_2
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_2
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_2
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_2
	.byte	PATT	
		.word	song_0030_4_1
	.byte	PATT	
		.word	song_0030_4_2
	.byte	PATT	
		.word	song_0030_4_1
	.byte	GOTO	
		.word	song_0030_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0030_5
song_0030_5:	@ 0x087DC0B1
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v078
	.byte	PAN	, c_v
	.byte	W24
song_0030_5_1:
	.byte		N12	, Dn1, v112
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte		N12	, Dn1, v112
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W24
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte	PATT	
		.word	song_0030_5_1
	.byte		N12	, Dn1, v112
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W24
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte		N12	, Dn4, v127
	.byte	W06
	.byte		N06	, Dn1, v112
	.byte	W06
song_0030_5_2:
	.byte		N12	, Dn1, v112
	.byte		N12	, Gn3, v127
	.byte	W12
	.byte		N04	, Dn1, v112
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte		N12	, Dn4, v127
	.byte	W06
	.byte		N06	, Dn1, v112
	.byte	W06
	.byte	PEND
song_0030_5_3:
	.byte		N12	, Dn1, v112
	.byte		N14	, Gn3, v127
	.byte	W12
	.byte		N04	, Dn1, v112
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte		N12	, Dn4, v127
	.byte	W06
	.byte		N06	, Dn1, v112
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0030_5_2
	.byte	PATT	
		.word	song_0030_5_3
	.byte		N12	, Dn1, v112
	.byte		N14	, Gs3, v127
	.byte	W12
	.byte		N04	, Dn1, v112
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte		N12	, Ds4, v127
	.byte	W06
	.byte		N06	, Dn1, v112
	.byte	W06
	.byte		N12	
	.byte		N17	, Gn3, v127
	.byte	W12
	.byte		N04	, Dn1, v112
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte		N12	, Dn4, v127
	.byte	W06
	.byte		N06	, Dn1, v112
	.byte	W06
	.byte		N12	
	.byte		N17	, Gs3, v127
	.byte	W12
	.byte		N04	, Dn1, v112
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte		N12	, Ds4, v127
	.byte	W06
	.byte		N06	, Dn1, v112
	.byte	W06
	.byte		N12	
	.byte		N19	, Gn3, v127
	.byte	W12
	.byte		N04	, Dn1, v112
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte		N12	
	.byte	W24
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	GOTO	
		.word	song_0030_5_1
	.byte	FINE

	.align 2
	.global song_0030
song_0030:	@ 0x087DC270
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0030_1		@ track
	.word	song_0030_2		@ track
	.word	song_0030_3		@ track
	.word	song_0030_4		@ track
	.word	song_0030_5		@ track
