	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0020_1
song_0020_1:	@ 0x087D93F0
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 12
	.byte	VOL	, v100
	.byte	PAN	, c_v
	.byte	W24
song_0020_1_1:
	.byte	TEMPO	, 35
	.byte		N68	, Fn3, v116
	.byte		N68	, An3
	.byte	W72
	.byte		N66	, Gn3
	.byte		N66	, As3
	.byte	W24
	.byte	W48
	.byte		N92	, En3
	.byte		N92	, Gn3
	.byte	W48
	.byte	W48
	.byte		N44	, Cs3
	.byte		N44	, An3
	.byte	W48
	.byte		N88	, Dn3
	.byte		N90	, Fn3
	.byte	W96
	.byte		N90	
	.byte		N90	, Dn4
	.byte	W96
	.byte		N42	, Gn3
	.byte		N44	, Cn4
	.byte	W48
	.byte			Gn3
	.byte		N44	, As3
	.byte	W48
	.byte		N92	, En3
	.byte		N92	, An3
	.byte	W96
	.byte			En3
	.byte		N92	, An3
	.byte	W96
	.byte	W24
	.byte		N21	, Fn3
	.byte		N21	, An3
	.byte	W24
	.byte		N44	, Gn3
	.byte		N44	, As3
	.byte	W48
	.byte		N42	, En3
	.byte		N42	, Gn3
	.byte	W48
	.byte		N44	, Dn3
	.byte		N48	, Fn3
	.byte	W48
	.byte		N24	, En3
	.byte		N24	, Gn3
	.byte	W24
	.byte			En3
	.byte		N24	, An3
	.byte	W24
	.byte			Cn3
	.byte		N24	, Fn3
	.byte	W24
	.byte			An3
	.byte		N24	, Cn4
	.byte	W24
	.byte		N48	, An3
	.byte		N48	, Bn3
	.byte	W48
	.byte		N24	, Gs3
	.byte		N24	, Bn3
	.byte	W24
	.byte			Gs3
	.byte		N24	, Dn4
	.byte	W24
	.byte		N96	, An3
	.byte		N96	, Cn4
	.byte	W96
	.byte			Gn3
	.byte		N96	, Cs4
	.byte	W96
	.byte	W48
	.byte		N06	, Dn2
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte		N06	, An3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Gn3
	.byte		N06	, As3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			En3
	.byte		N06	, Gn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte		N06	, An3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N06	
	.byte		N06	, Fn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			En3
	.byte		N06	, Gn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Cs3
	.byte		N06	, En3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte		N06	, An3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Gn3
	.byte		N06	, As3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			En3
	.byte		N06	, Gn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte		N06	, An3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N06	
	.byte		N06	, Fn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			En3
	.byte		N06	, Gn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Cn3
	.byte		N06	, En3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			As2
	.byte		N06	, Dn3
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			Fn3
	.byte		N06	, An3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			As3
	.byte		N06	, Dn4
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			An3
	.byte		N06	, Cn4
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Gn3
	.byte		N06	, As3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte		N06	, An3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			En3
	.byte		N06	, Gn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte		N06	, An3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Gn3
	.byte		N06	, As3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			En3
	.byte		N06	, Gn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte		N06	, An3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Gn3
	.byte		N06	, As3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Cs3
	.byte		N06	, An3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Cs3
	.byte		N06	, Gn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Cs3
	.byte		N06	, Fn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Cs3
	.byte		N06	, En3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte		N06	
	.byte		N06	, Dn3
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte			As2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Cs3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			Cs3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			Cs3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			As2
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Cs3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte		N04	
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			Dn3
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			Cs3
	.byte	W04
	.byte			En3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			Dn3
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			Cs3
	.byte	W04
	.byte			En3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			Dn3
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			En3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			Cs3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			En3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			Cs3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			Dn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			Cs3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			An2
	.byte	W04
	.byte			Dn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte			Dn4
	.byte	W04
	.byte			Ds4
	.byte	W04
	.byte			Dn4
	.byte	W04
	.byte			Cn4
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte			As3
	.byte	W04
	.byte			An3
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte			Gn3
	.byte	W04
	.byte			Fs3
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte			Ds3
	.byte	W04
	.byte			Dn3
	.byte	W04
	.byte			Cn3
	.byte	W04
	.byte			As2
	.byte	W04
	.byte			An2
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte			Gn2
	.byte	W04
	.byte			Fs2
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte			Ds2
	.byte	W04
	.byte			Dn2
	.byte	W04
	.byte		N04	
	.byte	W04
	.byte			As1
	.byte	W04
	.byte			An1
	.byte	W04
	.byte		N96	, Gn2
	.byte	W96
	.byte	W48
	.byte	GOTO	
		.word	song_0020_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0020_2
song_0020_2:	@ 0x087D9605
	.byte	KEYSH	, 0
	.byte	VOICE	, 3
	.byte	VOL	, v100
	.byte	PAN	, c_v
	.byte	W24
song_0020_2_1:
	.byte		N92	, Dn2, v127
	.byte	W96
	.byte		N96	, En2
	.byte	W96
	.byte			An1
	.byte	W96
	.byte		N44	, Dn2
	.byte	W48
	.byte		N52	, Cn2
	.byte	W48
	.byte		N96	, As1
	.byte	W96
	.byte		N44	, An1
	.byte	W48
	.byte			Gn1
	.byte	W48
	.byte		TIE	, An1
	.byte	W96
	.byte	W92
	.byte	W03
	.byte		EOT	
	.byte	W01
	.byte		N68	, Dn2
	.byte	W72
	.byte		N44	, En2
	.byte	W24
	.byte	W24
	.byte		N24	, An1
	.byte	W24
	.byte		N48	, Bn1
	.byte	W48
	.byte		N24	, Cn2
	.byte	W24
	.byte			Cs2
	.byte	W24
	.byte			Dn2
	.byte	W24
	.byte			Ds2
	.byte	W24
	.byte		N48	, En2
	.byte	W48
	.byte		N24	
	.byte	W24
	.byte			En1
	.byte	W24
	.byte		N96	, Fn1
	.byte	W96
	.byte			An1
	.byte		N96	, En2
	.byte		N96	, An2
	.byte	W96
	.byte	W48
	.byte	W96
	.byte		N72	, Dn2
	.byte	W72
	.byte		N24	, Cn2
	.byte	W24
	.byte		N96	, As1
	.byte	W96
	.byte		N48	, Gn1
	.byte	W48
	.byte			An1
	.byte	W48
	.byte		N06	, Dn2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			As2
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			En2
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte			En2
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			As2
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Bn2
	.byte	W06
	.byte			Cs3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			Fn2
	.byte	W06
	.byte			Gn2
	.byte	W06
	.byte			En3
	.byte	W06
	.byte			An2
	.byte	W06
	.byte			En3
	.byte	W06
	.byte		N04	, Dn3
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Cs2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte	W96
	.byte		N96	, Gn1
	.byte	W96
	.byte	W48
	.byte	GOTO	
		.word	song_0020_2_1
	.byte	FINE

	.align 2
	.global song_0020
song_0020:	@ 0x087D96D0
	.byte	2		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	188		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0020_1		@ track
	.word	song_0020_2		@ track
