	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0010_1
song_0010_1:	@ 0x087D53E0
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 14
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W24
song_0010_1_3:
	.byte	TEMPO	, 65
	.byte		N13	, Gn1, v127
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Cn3
	.byte		N02	, En3
	.byte	W24
	.byte		N03	, Cn3
	.byte		N03	, En3
	.byte	W12
	.byte		N13	, Gn1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte		N03	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte		N01	, Cn3
	.byte		N01	, En3
	.byte	W24
	.byte		N03	, Cn3
	.byte		N03	, En3
	.byte	W12
	.byte		N14	, Gn1
	.byte	W12
	.byte		N03	, Bn2
	.byte		N04	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N13	, Cn2
	.byte	W12
	.byte		N03	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Cn3
	.byte		N02	, En3
	.byte	W24
	.byte			Cn3
	.byte		N03	, En3
	.byte	W12
	.byte		N13	, Dn2
	.byte	W12
	.byte		N03	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N13	, Dn2
	.byte	W12
	.byte		N02	, An2
	.byte		N02	, Dn3
	.byte	W24
	.byte		N03	, An2
	.byte		N02	, Dn3
	.byte	W24
	.byte			An2
	.byte		N02	, Dn3
	.byte	W12
	.byte		N14	, Gn1
	.byte	W12
	.byte		N03	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N02	, Dn3
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte		N03	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W12
	.byte		N14	, Gn1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N02	, Dn3
	.byte	W24
	.byte			Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N11	, Cn2
	.byte	W12
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte		N01	, Cn3
	.byte		N01	, En3
	.byte	W24
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W12
	.byte		N13	, Gn1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N13	, Cn2
	.byte	W12
	.byte		N02	, Cn3
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Cn3
	.byte		N02	, En3
	.byte	W24
	.byte		N03	, Cn3
	.byte		N03	, En3
	.byte	W12
	.byte		N13	, Dn2
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N11	, Dn2
	.byte	W12
	.byte		N03	, An2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N12	, Gn1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, Dn3
	.byte	W12
	.byte		N10	, En1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W24
	.byte		N03	, Bn2
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W12
	.byte	W12
	.byte			Bn2
	.byte		N02	, En3
	.byte	W12
	.byte		N11	, En1
	.byte	W12
	.byte		N01	, Bn2
	.byte		N02	, En3
	.byte	W24
	.byte			Bn2
	.byte		N03	, En3
	.byte	W12
	.byte	W12
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W24
	.byte			Bn2
	.byte		N03	, En3
	.byte	W12
	.byte		N11	, En1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, En3
	.byte	W12
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, En3
	.byte	W24
	.byte			Bn2
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W12
	.byte		N10	, En1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N03	, En3
	.byte	W12
	.byte	W12
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W12
	.byte		N13	, En1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, En3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N03	, En3
	.byte	W12
	.byte	W12
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N02	, En3
	.byte	W12
	.byte		N12	, En1
	.byte	W12
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W12
	.byte	W12
	.byte			Bn2
	.byte		N02	, En3
	.byte	W24
	.byte			Bn2
	.byte		N02	, En3
	.byte	W24
	.byte			Bn2
	.byte		N02	, En3
	.byte	W12
	.byte		N14	, An1
	.byte	W12
	.byte		N03	, Cs3
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Cs3
	.byte		N02	, En3
	.byte	W12
	.byte	W12
	.byte		N03	, Cs3
	.byte		N02	, En3
	.byte	W24
	.byte		N03	, Cs3
	.byte		N02	, En3
	.byte	W12
	.byte		N13	, An1
	.byte	W12
	.byte		N03	, Cs3
	.byte		N03	, En3
	.byte	W24
	.byte			Cs3
	.byte		N02	, En3
	.byte	W12
	.byte	W12
	.byte			Cs3
	.byte		N02	, En3
	.byte	W24
	.byte			Cs3
	.byte		N02	, En3
	.byte	W12
song_0010_1_1:
	.byte		N13	, En1, v127
	.byte	W12
	.byte		N02	, Bn2
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W12
	.byte	PEND
	.byte	W12
	.byte			Bn2
	.byte		N03	, En3
	.byte	W24
	.byte		N02	, Bn2
	.byte		N02	, En3
	.byte	W12
	.byte	PATT	
		.word	song_0010_1_1
song_0010_1_2:
	.byte	W12
	.byte		N02	, Bn2, v127
	.byte		N03	, En3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N02	, En3
	.byte	W12
	.byte	PEND
	.byte		N13	, Fs1
	.byte	W12
	.byte		N02	, Cs3
	.byte		N03	, Fs3
	.byte	W24
	.byte		N02	, Cs3
	.byte		N03	, Fs3
	.byte	W12
	.byte	W12
	.byte		N02	, Cs3
	.byte		N03	, Fs3
	.byte	W24
	.byte		N02	, Cs3
	.byte		N02	, Fs3
	.byte	W12
	.byte		N36	, Cn3
	.byte		N36	, En3
	.byte	W48
	.byte		N44	, Dn3
	.byte		N44	, Fs3
	.byte	W48
	.byte		N10	, En1
	.byte	W12
	.byte		N01	, Bn2
	.byte		N02	, En3
	.byte	W24
	.byte		N01	, Bn2
	.byte		N03	, En3
	.byte	W12
	.byte	PATT	
		.word	song_0010_1_2
	.byte		N02	, Bn2, v127
	.byte		N02	, En3
	.byte	W24
	.byte		N68	, Dn3
	.byte		N68	, Fs3
	.byte	W24
	.byte	W48
	.byte	GOTO	
		.word	song_0010_1_3
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0010_2
song_0010_2:	@ 0x087D5635
	.byte	KEYSH	, 0
	.byte	VOICE	, 13
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0010_2_1:
	.byte		N04	, Dn4, v127
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N04	
	.byte	W24
	.byte	PEND
	.byte			En4
	.byte	W72
	.byte	PATT	
		.word	song_0010_2_1
	.byte		N04	, En4, v127
	.byte	W72
	.byte	PATT	
		.word	song_0010_2_1
song_0010_2_2:
	.byte		N04	, En4, v127
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte	PEND
	.byte			Bn4
	.byte	W48
	.byte			Dn4
	.byte	W24
	.byte			An4
	.byte	W72
	.byte	PATT	
		.word	song_0010_2_1
	.byte		N04	, En4, v127
	.byte	W72
	.byte	PATT	
		.word	song_0010_2_1
	.byte		N04	, En4, v127
	.byte	W72
	.byte	PATT	
		.word	song_0010_2_1
	.byte	PATT	
		.word	song_0010_2_2
	.byte		N04	, Bn4, v127
	.byte	W48
	.byte			An4
	.byte	W24
	.byte			Gn4
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W24
	.byte			Gs4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte		N17	, Dn4
	.byte	W18
	.byte		N05	, En4
	.byte	W18
	.byte		N04	, Bn3
	.byte	W12
	.byte			Gs4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte		N18	, Dn4
	.byte	W18
	.byte		N05	, En4
	.byte	W30
song_0010_2_3:
	.byte	W12
	.byte		N04	, Cs4, v127
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte	PEND
song_0010_2_4:
	.byte		N04	, Gn4, v127
	.byte	W12
	.byte		N05	, Fs4
	.byte	W06
	.byte			En4
	.byte	W30
	.byte	PEND
	.byte	PATT	
		.word	song_0010_2_3
	.byte	PATT	
		.word	song_0010_2_4
song_0010_2_5:
	.byte		N04	, Gs4, v127
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte	PEND
	.byte		N17	, Dn4
	.byte	W18
	.byte		N05	, En4
	.byte	W18
	.byte		N04	, Bn3
	.byte	W12
	.byte	PATT	
		.word	song_0010_2_5
	.byte		N18	, Dn4, v127
	.byte	W18
	.byte		N05	, En4
	.byte	W30
	.byte		N04	, An4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte			Gs4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte		N44	, Gn4
	.byte	W48
	.byte			Fs4
	.byte	W48
	.byte		N92	, En4
	.byte	W48
	.byte	W48
	.byte	W48
	.byte	W48
	.byte	GOTO	
		.word	song_0010_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0010_3
song_0010_3:	@ 0x087D570F
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0010_3_10:
	.byte	W72
song_0010_3_1:
	.byte	W12
	.byte		N06	, Cn3, v127
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N04	, En3
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte	PEND
	.byte			Bn3
	.byte	W72
	.byte	PATT	
		.word	song_0010_3_1
	.byte		N04	, Bn3, v127
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W12
	.byte		N06	, Fs3
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N04	, Fs3
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Bn2
	.byte	W72
	.byte	PATT	
		.word	song_0010_3_1
	.byte		N04	, Bn3, v127
	.byte	W72
	.byte	PATT	
		.word	song_0010_3_1
	.byte		N04	, Bn3, v127
	.byte	W72
	.byte	W72
	.byte	W72
	.byte	W72
song_0010_3_2:
	.byte		N05	, En2, v127
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			An2
	.byte	W06
	.byte	PEND
song_0010_3_3:
	.byte	W06
	.byte		N05	, En2, v127
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte	PEND
song_0010_3_4:
	.byte		N05	, Bn2, v127
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte	PEND
song_0010_3_5:
	.byte		N05	, En2, v127
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0010_3_2
	.byte	PATT	
		.word	song_0010_3_3
	.byte	PATT	
		.word	song_0010_3_4
	.byte	PATT	
		.word	song_0010_3_5
song_0010_3_6:
	.byte		N05	, An2, v127
	.byte	W12
	.byte			Cs3
	.byte	W12
	.byte			An2
	.byte	W06
	.byte			Dn3
	.byte	W12
	.byte			An2
	.byte	W06
	.byte	PEND
song_0010_3_7:
	.byte		N05	, En3, v127
	.byte	W12
	.byte			An2
	.byte	W06
	.byte			Dn3
	.byte	W12
	.byte			An2
	.byte	W06
	.byte			Cs3
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0010_3_6
	.byte	PATT	
		.word	song_0010_3_7
song_0010_3_8:
	.byte		N05	, En2, v127
	.byte	W12
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte	PEND
song_0010_3_9:
	.byte		N05	, Bn2, v127
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0010_3_8
	.byte	PATT	
		.word	song_0010_3_9
	.byte		N05	, Fs2, v127
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			Fs2
	.byte	W06
	.byte			Cs3
	.byte	W12
	.byte			Fs2
	.byte	W06
	.byte			Fs3
	.byte	W12
	.byte			Fs2
	.byte	W06
	.byte			Cs3
	.byte	W12
	.byte			Fs2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte		N44	, En3
	.byte	W48
	.byte			Dn3
	.byte	W48
	.byte	PATT	
		.word	song_0010_3_8
	.byte	PATT	
		.word	song_0010_3_9
	.byte		N16	, En2, v127
	.byte	W24
	.byte		N68	, Fs2
	.byte	W24
	.byte	W48
	.byte	GOTO	
		.word	song_0010_3_10
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0010_4
song_0010_4:	@ 0x087D5835
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0010_4_1:
	.byte		N12	, Gn1, v127
	.byte	W12
	.byte		N04	, Gn2
	.byte	W24
	.byte			Fs2
	.byte	W12
	.byte		N12	, Gn2
	.byte	W12
	.byte		N04	, Dn2
	.byte	W12
	.byte	PEND
song_0010_4_2:
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte		N04	, Gn2
	.byte	W24
	.byte			Fs2
	.byte	W12
	.byte		N06	, Gn2
	.byte	W06
	.byte			En2
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0010_4_1
song_0010_4_3:
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte		N04	, Gn2
	.byte	W24
	.byte			An2
	.byte	W12
	.byte		N06	, Gn2
	.byte	W06
	.byte			En2
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0010_4_1
song_0010_4_4:
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte		N04	, Gn2
	.byte	W24
	.byte			Fs2
	.byte	W12
	.byte		N12	, Gn2
	.byte	W12
	.byte		N04	, Cn2
	.byte	W12
	.byte	PEND
	.byte		N12	, Dn2
	.byte	W12
	.byte		N04	, Gn2
	.byte	W24
	.byte			Fs2
	.byte	W12
	.byte		N12	, Gn2
	.byte	W12
	.byte		N04	, Bn1
	.byte	W12
	.byte		N12	, Dn2
	.byte	W12
	.byte		N04	, En2
	.byte	W12
	.byte			Fs2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte		N12	, An2
	.byte	W12
	.byte		N04	, Dn2
	.byte	W12
	.byte	PATT	
		.word	song_0010_4_1
	.byte	PATT	
		.word	song_0010_4_2
	.byte	PATT	
		.word	song_0010_4_1
	.byte	PATT	
		.word	song_0010_4_3
	.byte	PATT	
		.word	song_0010_4_1
	.byte	PATT	
		.word	song_0010_4_4
	.byte		N12	, Dn2, v127
	.byte	W12
	.byte		N04	, Gn2
	.byte	W24
	.byte			Dn2
	.byte	W12
	.byte		N12	, An1
	.byte	W12
	.byte		N04	, Dn2
	.byte	W12
	.byte		N12	, Gn1
	.byte	W12
	.byte		N04	, An1
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			An1
	.byte	W12
	.byte		N12	, Gn1
	.byte	W12
	.byte		N04	, Fs1
	.byte	W12
	.byte			En1
	.byte	W72
song_0010_4_5:
	.byte	W12
	.byte		N06	, Dn2, v127
	.byte	W06
	.byte		N05	, En2
	.byte	W06
	.byte		N04	, En1
	.byte	W48
	.byte	PEND
song_0010_4_6:
	.byte	W36
	.byte		N06	, Dn2, v127
	.byte	W06
	.byte		N05	, En2
	.byte	W06
	.byte		N04	, En1
	.byte	W24
	.byte	PEND
song_0010_4_7:
	.byte	W60
	.byte		N06	, Dn2, v127
	.byte	W06
	.byte		N05	, En2
	.byte	W06
	.byte	PEND
	.byte		N04	, En1
	.byte	W72
	.byte	PATT	
		.word	song_0010_4_5
	.byte	PATT	
		.word	song_0010_4_6
	.byte	PATT	
		.word	song_0010_4_7
	.byte		N04	, An1, v127
	.byte	W48
	.byte	W36
	.byte		N06	, En1
	.byte	W06
	.byte		N05	, Gn1
	.byte	W06
	.byte		N04	, An1
	.byte	W48
song_0010_4_8:
	.byte	W36
	.byte		N06	, Dn2, v127
	.byte	W06
	.byte		N05	, En2
	.byte	W06
	.byte	PEND
	.byte		N04	, En1
	.byte	W48
	.byte	PATT	
		.word	song_0010_4_8
	.byte		N04	, En1, v127
	.byte	W48
	.byte	PATT	
		.word	song_0010_4_8
	.byte		N04	, Fs1, v127
	.byte	W48
	.byte	W36
	.byte		N06	, An1
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte		N44	, Cn2
	.byte	W48
	.byte			Dn2
	.byte	W48
	.byte		N04	, En1
	.byte	W48
	.byte	PATT	
		.word	song_0010_4_8
	.byte		N08	, En1, v127
	.byte	W24
	.byte		N68	, Dn1
	.byte	W24
	.byte	W48
	.byte	GOTO	
		.word	song_0010_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0010_5
song_0010_5:	@ 0x087D596B
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0010_5_1:
	.byte		N01	, Dn6, v127
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, En6
	.byte		N02	, Cs7
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
song_0010_5_2:
	.byte		N01	, Dn6, v127
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0010_5_1
	.byte	PATT	
		.word	song_0010_5_2
	.byte	PATT	
		.word	song_0010_5_1
	.byte	PATT	
		.word	song_0010_5_2
	.byte	PATT	
		.word	song_0010_5_1
	.byte	PATT	
		.word	song_0010_5_2
	.byte	PATT	
		.word	song_0010_5_1
	.byte	PATT	
		.word	song_0010_5_2
	.byte	PATT	
		.word	song_0010_5_1
	.byte	PATT	
		.word	song_0010_5_2
	.byte	PATT	
		.word	song_0010_5_1
	.byte	PATT	
		.word	song_0010_5_2
	.byte	PATT	
		.word	song_0010_5_1
	.byte		N01	, Dn6, v127
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N05	, En6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N05	, Ds6
	.byte	W06
	.byte			Dn6
	.byte		N05	, Cs7
	.byte	W06
	.byte			Cn6
	.byte		N05	, Cs7
	.byte	W06
song_0010_5_3:
	.byte		N01	, Dn6, v127
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Dn6
	.byte		N02	, Cs7
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Dn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Dn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Dn6
	.byte		N02	, Cs7
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Dn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte	PATT	
		.word	song_0010_5_3
	.byte		N01	, En6, v127
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Dn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Dn6
	.byte		N02	, Cs7
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Dn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Dn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
song_0010_5_6:
	.byte		N01	, Dn6, v127
	.byte		N02	, Cs7
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
song_0010_5_7:
	.byte		N01	, Dn6, v127
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte	PEND
song_0010_5_4:
	.byte		N01	, Dn6, v127
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte	PEND
song_0010_5_5:
	.byte		N01	, Dn6, v127
	.byte		N02	, Cs7
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N02	
	.byte	W02
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0010_5_4
	.byte	PATT	
		.word	song_0010_5_5
	.byte		N01	, Dn6, v127
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N01	, Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Dn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte	PATT	
		.word	song_0010_5_6
	.byte	PATT	
		.word	song_0010_5_7
	.byte	PATT	
		.word	song_0010_5_4
	.byte	PATT	
		.word	song_0010_5_5
	.byte	PATT	
		.word	song_0010_5_4
	.byte	PATT	
		.word	song_0010_5_5
	.byte		N01	, Dn6, v127
	.byte		N06	, Cs7
	.byte	W18
	.byte		N01	
	.byte	W03
	.byte		N01	
	.byte	W03
	.byte			Ds6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Dn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, En6
	.byte		N06	, Cs7
	.byte	W12
	.byte		N01	, Cn6
	.byte		N06	, Cs7
	.byte	W12
	.byte	GOTO	
		.word	song_0010_5_1
	.byte	FINE

	.align 2
	.global song_0010
song_0010:	@ 0x087D5C44
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0010_1		@ track
	.word	song_0010_2		@ track
	.word	song_0010_3		@ track
	.word	song_0010_4		@ track
	.word	song_0010_5		@ track
