	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0283_1
song_0283_1:	@ 0x087E7A6C
	.byte	KEYSH	, 0
	.byte	TEMPO	, 60
	.byte	MOD	, 0
	.byte	BEND	, c_v
	.byte	W01
	.byte	VOICE	, 6
	.byte	VOL	, v086
	.byte	W01
	.byte	PAN	, c_v
	.byte	W04
song_0283_1_1:
	.byte	TEMPO	, 80
	.byte		N14	, Cn2, v100
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			En5
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte			Gn2
	.byte		N14	, Bn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			Dn2
	.byte		N14	, En4
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte			En1
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte		N42	, Gn5
	.byte	W48
	.byte	GOTO	
		.word	song_0283_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0283_2
song_0283_2:	@ 0x087E7B16
	.byte	KEYSH	, 0
	.byte	MOD	, 0
	.byte	BEND	, c_v
	.byte	W01
	.byte	VOICE	, 8
	.byte	VOL	, v086
	.byte	W01
	.byte	PAN	, c_v
	.byte	W04
song_0283_2_1:
	.byte		N14	, Cn3, v100
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			En5
	.byte	W12
	.byte			Gn5
	.byte	W12
	.byte			Bn5
	.byte	W12
	.byte			En6
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte			Gn5
	.byte	W12
	.byte			Bn5
	.byte	W12
	.byte			Dn6
	.byte	W12
	.byte			An2
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte			En5
	.byte	W12
	.byte			An5
	.byte	W12
	.byte			Cn6
	.byte	W12
	.byte			Gn3
	.byte		N14	, Bn5
	.byte	W12
	.byte			Gn5
	.byte	W12
	.byte			En5
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			Dn3
	.byte		N14	, En5
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Fn5
	.byte	W12
	.byte			An5
	.byte	W12
	.byte			Cn6
	.byte	W12
	.byte			En2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte			Gn5
	.byte	W12
	.byte			Bn5
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte			Fn5
	.byte	W12
	.byte			An5
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte			Gn5
	.byte	W12
	.byte			Cn6
	.byte	W12
	.byte			Dn6
	.byte	W12
	.byte		N42	, Gn6
	.byte	W48
	.byte	GOTO	
		.word	song_0283_2_1
	.byte	FINE

	.align 2
	.global song_0283
song_0283:	@ 0x087E7BBC
	.byte	2		@ trackCount
	.byte	0		@ blockCount
	.byte	255		@ priority
	.byte	188		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0283_1		@ track
	.word	song_0283_2		@ track
