	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0000_1
song_0000_1:	@ 0x087D10CC
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W01
	.byte	MOD	, 0
	.byte	BEND	, c_v
	.byte	W23
	.byte	TEMPO	, 73
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0000_1_1:
	.byte		N30	, Cn4, v127
	.byte	W36
	.byte		N32	, Dn4
	.byte	W36
	.byte		N24	, Ds4
	.byte	W24
	.byte		N19	, Dn4
	.byte	W24
	.byte		N22	, As3
	.byte	W24
	.byte		N15	
	.byte	W24
	.byte		N05	
	.byte	W12
	.byte		N68	, Cn4
	.byte	W12
	.byte	W60
	.byte		N14	, Gn4
	.byte	W12
	.byte		N11	, Fn4
	.byte	W12
	.byte		N10	, Ds4
	.byte	W12
	.byte		N19	, Dn4
	.byte	W24
	.byte		N12	, Ds4
	.byte	W24
	.byte			Fn4
	.byte	W12
	.byte		N08	, As4
	.byte	W12
	.byte		N09	, Gn4
	.byte	W12
	.byte		TIE	, Cn5
	.byte	W12
	.byte	W90
	.byte		EOT	
	.byte	W06
	.byte	W96
	.byte		N36	, Cn3
	.byte	W36
	.byte		N09	, Dn3
	.byte	W12
	.byte		N13	, Ds3
	.byte	W12
	.byte		N04	, Cn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte		N32	, Fn3
	.byte	W12
	.byte	W24
	.byte		N23	, Ds3
	.byte	W24
	.byte		N14	, Dn3
	.byte	W12
	.byte		N13	, Ds3
	.byte	W12
	.byte		N08	, Fn3
	.byte	W12
	.byte		N48	, As3
	.byte	W12
	.byte	W36
	.byte		N05	, Gs3
	.byte	W12
	.byte		N11	, Gn3
	.byte	W12
	.byte		N08	, Fn3
	.byte	W24
	.byte		N05	, Ds3
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N68	, Gn3
	.byte	W84
	.byte		N05	
	.byte	W12
	.byte		N15	, Gs3
	.byte	W12
	.byte		N11	, Gn3
	.byte	W12
	.byte		N12	, Fn3
	.byte	W12
	.byte		N14	, Dn3
	.byte	W24
	.byte		N12	, As3
	.byte	W24
	.byte		N06	, Ds3
	.byte	W06
	.byte			Fn3
	.byte	W06
	.byte		N13	, Gn3
	.byte	W12
	.byte		N14	, Fn3
	.byte	W12
	.byte		N11	, Ds3
	.byte	W12
	.byte		N17	, Cn3
	.byte	W24
	.byte		N21	, Cn4
	.byte	W24
	.byte		N09	, Ds3
	.byte	W12
	.byte		N28	, Fn3
	.byte	W36
	.byte		N04	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N12	, Gn3
	.byte	W12
	.byte			Gs3
	.byte	W12
	.byte		N80	, Gn3
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W84
	.byte		N48	, Cn3
	.byte	W12
	.byte	W36
	.byte		N12	, Dn3
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte		N48	, Fn3
	.byte	W12
	.byte	W84
	.byte			Ds3
	.byte	W12
	.byte	W36
	.byte		N12	, Fn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte		N48	, Fn3
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N04	, Gn3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N06	, As3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte		N08	, Fn3
	.byte	W12
	.byte		N06	, Gn3
	.byte	W36
	.byte		N11	, Cn4
	.byte	W24
	.byte		N10	, Dn4
	.byte	W12
	.byte		N08	, Ds4
	.byte	W24
	.byte			Cn4
	.byte	W12
	.byte		N10	, Gn4
	.byte	W12
	.byte		N07	, Fn4
	.byte	W12
	.byte	W12
	.byte			Ds4
	.byte	W24
	.byte		N09	, Dn4
	.byte	W24
	.byte		N12	, Ds4
	.byte	W12
	.byte			Fn4
	.byte	W12
	.byte		N11	, As4
	.byte	W12
	.byte		N17	, Cn4
	.byte	W24
	.byte		N12	, Dn4
	.byte	W12
	.byte		N09	, Ds4
	.byte	W24
	.byte		N11	, Cn4
	.byte	W12
	.byte		N13	, Gn4
	.byte	W12
	.byte		N11	, Fn4
	.byte	W12
	.byte	W12
	.byte		N09	, Ds4
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte		N04	, Ds4
	.byte	W12
	.byte		N10	, Fn4
	.byte	W12
	.byte		N03	, As3
	.byte	W12
	.byte		N24	, Ds4
	.byte	W24
	.byte		N13	, Fn4
	.byte	W12
	.byte		N09	, Gn4
	.byte	W24
	.byte		N04	, Ds4
	.byte	W12
	.byte		N13	, As4
	.byte	W12
	.byte		N11	, Gs4
	.byte	W12
	.byte	W12
	.byte		N10	, Gn4
	.byte	W24
	.byte		N24	, Fn4
	.byte	W24
	.byte		N04	, Gn4
	.byte	W12
	.byte		N13	, Gs4
	.byte	W12
	.byte		N04	, Dn4
	.byte	W12
	.byte		N24	, Ds4
	.byte	W24
	.byte		N12	, Fn4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W24
	.byte		N03	, Ds4
	.byte	W12
	.byte		N14	, As4
	.byte	W12
	.byte		N10	, Gs4
	.byte	W12
	.byte	W12
	.byte		N15	, Gn4
	.byte	W24
	.byte		N18	, Fn4
	.byte	W24
	.byte		N08	, Gn4
	.byte	W12
	.byte		N14	, Gs4
	.byte	W12
	.byte		N05	, Dn5
	.byte	W12
	.byte	GOTO	
		.word	song_0000_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0000_2
song_0000_2:	@ 0x087D124D
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W01
	.byte	MOD	, 0
	.byte	BEND	, c_v
	.byte	W23
	.byte	W24
song_0000_2_1:
	.byte		N10	, Gn1, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0000_2_1
	.byte		N10	, Gn1, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N04	
	.byte	W06
	.byte		N10	
	.byte	W06
	.byte	W96
song_0000_2_10:
	.byte		N10	, Gs1, v127
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte			Ds2
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte		N22	, As1
	.byte	W12
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	, Fn2
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	, Dn2
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	, As1
	.byte	W12
	.byte		N22	, Gs1
	.byte	W12
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N12	
	.byte	W04
	.byte	BEND	, c_v+63
	.byte	W04
	.byte		c_v
	.byte	W04
	.byte		N10	, Gn1
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte		N22	, As1
	.byte	W12
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N22	, Gs1
	.byte	W12
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	, Gs2
	.byte	W12
	.byte		N05	, Gs1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N12	, Gn1
	.byte	W48
	.byte		N12	
	.byte	W12
song_0000_2_2:
	.byte		N10	, Cn2, v127
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N11	
	.byte	W12
	.byte		N10	, Gn2
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte		N22	, As1
	.byte	W12
	.byte	PEND
song_0000_2_3:
	.byte	W12
	.byte		N05	, As1, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N11	
	.byte	W12
	.byte		N10	, Fn2
	.byte	W12
	.byte			As1
	.byte	W12
	.byte		N22	, Gs1
	.byte	W12
	.byte	PEND
song_0000_2_4:
	.byte	W12
	.byte		N05	, Gs1, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N22	, Gn1
	.byte	W12
	.byte	PEND
song_0000_2_5:
	.byte	W12
	.byte		N05	, Gn1, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte	PEND
song_0000_2_6:
	.byte		N10	, Fn1, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N22	, As1
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte		N22	, Gn1
	.byte	W12
	.byte	PEND
song_0000_2_7:
	.byte	W12
	.byte		N10	, Gn1, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N22	, Cn2
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte			As1
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte	PEND
	.byte			Gs1
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte			Ds2
	.byte	W12
	.byte			Gs1
	.byte	W12
	.byte		N22	, Gn1
	.byte	W12
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N10	, Gn2
	.byte	W12
	.byte		N04	, Gn1
	.byte	W06
	.byte		N10	, Dn2
	.byte	W12
	.byte		N05	, Gn1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	PATT	
		.word	song_0000_2_2
	.byte	PATT	
		.word	song_0000_2_3
	.byte	PATT	
		.word	song_0000_2_4
	.byte	PATT	
		.word	song_0000_2_5
	.byte	PATT	
		.word	song_0000_2_6
	.byte	PATT	
		.word	song_0000_2_7
	.byte		N10	, Fn1, v127
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte		N22	, Gn1
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N22	, Gs1
	.byte	W12
song_0000_2_8:
	.byte	W12
	.byte		N10	, Gs1, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N22	, As1
	.byte	W12
	.byte	PEND
song_0000_2_9:
	.byte	W12
	.byte		N10	, As1, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N22	, Gs1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0000_2_8
	.byte	PATT	
		.word	song_0000_2_9
	.byte	W12
	.byte		N10	, Gs1, v127
	.byte	W12
	.byte		N22	, As1
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte		N22	, Gs1
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte		N22	, As1
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte		N22	, Gs1
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte		N07	, Gn1
	.byte	W08
	.byte			Bn1
	.byte	W08
	.byte			Cn2
	.byte	W08
	.byte		N10	, Dn2
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N10	
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte			An1
	.byte	W06
	.byte		N04	, Gn1
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N08	, As1
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte		N12	, Gn1
	.byte	W36
	.byte		N11	, Cn2
	.byte	W24
	.byte		N10	, Dn2
	.byte	W12
	.byte		N08	, Ds2
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte		N10	, Gn2
	.byte	W12
	.byte		N07	, Fn2
	.byte	W12
	.byte	W12
	.byte			Ds2
	.byte	W24
	.byte		N09	, Dn2
	.byte	W24
	.byte		N12	, Ds2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte		N11	, As1
	.byte	W12
	.byte		N17	, Cn2
	.byte	W24
	.byte		N12	, Dn2
	.byte	W12
	.byte		N09	, Ds2
	.byte	W24
	.byte		N11	, Cn2
	.byte	W12
	.byte		N13	, Gn2
	.byte	W12
	.byte		N11	, Fn2
	.byte	W12
	.byte	W12
	.byte		N09	, Ds2
	.byte	W24
	.byte			Dn2
	.byte	W24
	.byte		N04	, Ds2
	.byte	W12
	.byte		N10	, Fn2
	.byte	W12
	.byte		N03	, As1
	.byte	W12
	.byte		N24	, Cn2
	.byte	W24
	.byte		N13	, Dn2
	.byte	W12
	.byte		N09	, Ds2
	.byte	W24
	.byte		N04	, Cn2
	.byte	W12
	.byte		N13	, Gn2
	.byte	W12
	.byte		N11	, Fn2
	.byte	W12
	.byte	W12
	.byte		N10	, Ds2
	.byte	W24
	.byte		N24	, Dn2
	.byte	W24
	.byte		N04	, Ds2
	.byte	W12
	.byte		N13	, Fn2
	.byte	W12
	.byte		N04	, As1
	.byte	W12
	.byte		N24	, Cn2
	.byte	W24
	.byte		N12	, Dn2
	.byte	W12
	.byte		N06	, Ds2
	.byte	W24
	.byte		N03	, Cn2
	.byte	W12
	.byte		N14	, Gn2
	.byte	W12
	.byte		N10	, Fn2
	.byte	W12
	.byte	W12
	.byte		N15	, Ds2
	.byte	W24
	.byte		N18	, Dn2
	.byte	W24
	.byte		N08	, Ds2
	.byte	W12
	.byte		N14	, Fn2
	.byte	W12
	.byte		N05	, As2
	.byte	W12
	.byte	GOTO	
		.word	song_0000_2_10
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0000_3
song_0000_3:	@ 0x087D14F3
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0000_3_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N72	, Gs3, v127
	.byte	W84
	.byte		N54	, Gn3
	.byte	W12
	.byte	W96
	.byte		N32	, Cn4
	.byte	W36
	.byte		N13	, Dn4
	.byte	W12
	.byte		N14	, Ds4
	.byte	W12
	.byte		N12	, Cn4
	.byte	W12
	.byte		N14	, Gn4
	.byte	W12
	.byte		N32	, Fn4
	.byte	W12
	.byte	W24
	.byte		N22	, Ds4
	.byte	W24
	.byte		N15	, Dn4
	.byte	W12
	.byte		N13	, Ds4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte		N44	, As4
	.byte	W12
	.byte	W36
	.byte		N10	, Gs4
	.byte	W12
	.byte		N14	, Gn4
	.byte	W12
	.byte		N07	, Fn4
	.byte	W24
	.byte		N06	, Ds4
	.byte	W06
	.byte		N08	, Fn4
	.byte	W06
	.byte		N72	, Gn4
	.byte	W84
	.byte		N12	
	.byte	W12
	.byte		N14	, Gs4
	.byte	W12
	.byte		N13	, Gn4
	.byte	W12
	.byte		N14	, Fn4
	.byte	W12
	.byte			Dn4
	.byte	W24
	.byte		N11	, As4
	.byte	W24
	.byte		N06	, Ds4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte		N13	, Gn4
	.byte	W12
	.byte		N14	, Fn4
	.byte	W12
	.byte		N12	, Ds4
	.byte	W12
	.byte		N13	, Cn4
	.byte	W24
	.byte		N12	, Cn5
	.byte	W24
	.byte		N10	, Ds4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte		N10	, Gn4
	.byte	W12
	.byte		N12	, Gs4
	.byte	W12
	.byte		N23	, Gn4
	.byte	W24
	.byte		N13	, As4
	.byte	W12
	.byte		N10	, Gn4
	.byte	W12
	.byte		N72	, Cn5
	.byte	W12
	.byte	W84
	.byte		N40	, Dn4
	.byte	W12
	.byte	W36
	.byte		N14	, Ds4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte		N16	, Dn4
	.byte	W12
	.byte		N13	, As4
	.byte	W12
	.byte		N48	, Gn4
	.byte	W12
	.byte	W84
	.byte		N44	, As4
	.byte	W12
	.byte	W36
	.byte		N11	, Cn5
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte		N07	, As4
	.byte	W12
	.byte		N10	, Fn5
	.byte	W12
	.byte		N12	, Gn5
	.byte	W12
	.byte		N15	, Fn5
	.byte	W12
	.byte		N11	, Ds5
	.byte	W12
	.byte			Fn5
	.byte	W12
	.byte			Ds5
	.byte	W12
	.byte		N12	, Dn5
	.byte	W12
	.byte			Ds5
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte		N11	, Cn5
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte		N12	, Cn5
	.byte	W12
	.byte		N13	, As4
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte			As4
	.byte	W12
	.byte			Cn5
	.byte	W12
	.byte		N08	, As4
	.byte	W08
	.byte			Gs4
	.byte	W08
	.byte		N06	, Gn4
	.byte	W08
	.byte		N48	, Fs4
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0000_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0000_4
song_0000_4:	@ 0x087D15E9
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v075
	.byte	PAN	, c_v+20
	.byte	W24
	.byte	W24
song_0000_4_1:
	.byte	W06
	.byte		N04	, As4, v127
	.byte	W18
	.byte		N08	, Fn4
	.byte	W24
	.byte		N04	
	.byte	W18
	.byte		N18	
	.byte	W18
	.byte		N04	, Gn4
	.byte	W12
	.byte	PEND
	.byte		N02	, Gn5
	.byte	W04
	.byte			Fn5
	.byte	W04
	.byte			Dn5
	.byte	W04
	.byte			Cn5
	.byte	W04
	.byte			As4
	.byte	W04
	.byte			Gn4
	.byte	W04
	.byte			Dn5
	.byte	W04
	.byte			Cn5
	.byte	W04
	.byte			As4
	.byte	W04
	.byte			Gn4
	.byte	W04
	.byte			Fn4
	.byte	W04
	.byte			Dn4
	.byte	W04
	.byte			Fn4
	.byte	W04
	.byte			Dn4
	.byte	W04
	.byte			Cn4
	.byte	W04
	.byte			As3
	.byte	W04
	.byte			Gn3
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			Gn3
	.byte	W04
	.byte			Fn3
	.byte	W04
	.byte			Dn3
	.byte	W04
	.byte			Cn3
	.byte	W04
	.byte			As2
	.byte	W04
	.byte			Gn2
	.byte	W04
	.byte	PATT	
		.word	song_0000_4_1
	.byte	BEND	, c_v
	.byte		N90	, Gn5, v127
	.byte	W24
	.byte	BEND	, c_v-1
	.byte	W28
	.byte		c_v-5
	.byte	W10
	.byte		c_v-9
	.byte	W11
	.byte		c_v-17
	.byte	W06
	.byte		c_v-25
	.byte	W05
	.byte		c_v-33
	.byte	W04
	.byte		c_v-42
	.byte	W02
	.byte		c_v
	.byte	W06
song_0000_4_3:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W12
	.byte		N04	, Cn4, v127
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N03	, Cn5
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N06	, Bn4
	.byte	W60
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0000_4_2:
	.byte		N32	, Fn3, v127
	.byte	W36
	.byte		N44	, As2
	.byte	W48
	.byte			Gn3
	.byte	W12
	.byte	PEND
	.byte	W36
	.byte		N56	, Cn3
	.byte	W60
	.byte	W96
	.byte	W54
	.byte		N06	, Gn4
	.byte	W18
	.byte		N06	
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	PATT	
		.word	song_0000_4_2
	.byte	W36
	.byte		N56	, Cn3, v127
	.byte	W60
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W84
	.byte		N32	, Gs2
	.byte	W12
	.byte	W24
	.byte			As2
	.byte	W36
	.byte			Gs2
	.byte	W36
	.byte			As2
	.byte	W36
	.byte			Gs2
	.byte	W36
	.byte		N08	, Gn2
	.byte	W08
	.byte			Bn2
	.byte	W08
	.byte			Cn3
	.byte	W08
	.byte		N12	, Dn3
	.byte	W60
	.byte		N04	, Fs3
	.byte	W06
	.byte			An3
	.byte	W06
	.byte			Cn4
	.byte	W06
	.byte			Ds4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			An4
	.byte	W06
	.byte		N03	, Gn4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N02	
	.byte	W06
	.byte		N06	, As4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte		N08	, Fn4
	.byte	W12
	.byte		N06	, Gn4
	.byte	W36
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0000_4_3
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0000_5
song_0000_5:	@ 0x087D16F0
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		N05	, Dn1, v127
	.byte	W18
	.byte			Cn1
	.byte	W06
song_0000_5_6:
	.byte		N05	, Cn1, v127
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte	PEND
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N05	
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte		N05	
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn1
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N05	
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	W48
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
song_0000_5_3:
	.byte		N05	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0000_5_1:
	.byte	W12
	.byte		N05	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
song_0000_5_2:
	.byte	W12
	.byte		N05	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0000_5_1
	.byte	PATT	
		.word	song_0000_5_2
	.byte		N05	, Dn1, v127
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W32
	.byte	W03
	.byte		N01	
	.byte	W01
	.byte		N05	
	.byte	W24
	.byte	PATT	
		.word	song_0000_5_3
	.byte	PATT	
		.word	song_0000_5_1
	.byte	PATT	
		.word	song_0000_5_2
	.byte	W12
	.byte		N05	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte		N12	, Fn1
	.byte	W12
song_0000_5_4:
	.byte		N05	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N05	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PEND
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N05	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0000_5_3
	.byte	W06
	.byte		N05	, Cn1, v127
	.byte	W06
	.byte		N05	
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	PATT	
		.word	song_0000_5_3
	.byte	PATT	
		.word	song_0000_5_1
	.byte	PATT	
		.word	song_0000_5_2
	.byte	W12
	.byte		N05	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W12
	.byte	PATT	
		.word	song_0000_5_4
	.byte	W12
	.byte		N05	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W30
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	PATT	
		.word	song_0000_5_2
	.byte	PATT	
		.word	song_0000_5_2
	.byte	PATT	
		.word	song_0000_5_2
	.byte	W12
	.byte		N05	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte		N08	, Cn2
	.byte	W08
	.byte			An1
	.byte	W08
	.byte		N07	, Fn1
	.byte	W08
	.byte		N05	, Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W36
	.byte			Cn1
	.byte	W12
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
song_0000_5_5:
	.byte		N05	, Cn1, v127
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0000_5_5
	.byte	PATT	
		.word	song_0000_5_5
	.byte	PATT	
		.word	song_0000_5_5
	.byte	PATT	
		.word	song_0000_5_6
	.byte		N05	, Cn1, v127
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte	PATT	
		.word	song_0000_5_6
	.byte		N05	, Cn1, v127
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W18
	.byte		N05	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte		N05	
	.byte	W06
	.byte	GOTO	
		.word	song_0000_5_3
	.byte	FINE

	.align 2
	.global song_0000
song_0000:	@ 0x087D18D8
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0000_1		@ track
	.word	song_0000_2		@ track
	.word	song_0000_3		@ track
	.word	song_0000_4		@ track
	.word	song_0000_5		@ track
