	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0058_1
song_0058_1:	@ 0x087E5324
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 4
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	TEMPO	, 74
	.byte	W24
song_0058_1_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N12	, Bn3, v127
	.byte	W12
	.byte		N07	, En4
	.byte	W36
	.byte		N11	, Bn3
	.byte	W12
	.byte		N07	, En4
	.byte	W36
	.byte		N12	, Dn4
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte		N06	, Dn4
	.byte	W12
	.byte		N44	, Bn3
	.byte	W60
	.byte		N19	, En3
	.byte	W24
	.byte		N12	, Gn3
	.byte	W12
	.byte		N09	, En3
	.byte	W12
	.byte		N07	, Gn3
	.byte	W12
	.byte		N24	, An3
	.byte	W24
	.byte		N12	, Cn4
	.byte	W12
	.byte		N22	, Bn3
	.byte	W96
	.byte		N11	
	.byte	W12
	.byte		N08	, En4
	.byte	W36
	.byte		N11	, Bn3
	.byte	W12
	.byte		N06	, En4
	.byte	W36
	.byte		N12	, Dn4
	.byte	W12
	.byte		N05	, Bn3
	.byte	W12
	.byte		N13	, Dn4
	.byte	W12
	.byte		N42	, En4
	.byte	W60
	.byte		N05	, Fs4
	.byte	W12
	.byte		N16	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N24	, Dn4
	.byte	W24
	.byte		N22	, Bn3
	.byte	W24
	.byte		N11	, Fs4
	.byte	W12
	.byte		N10	, En4
	.byte	W60
	.byte		N12	, Gn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte		N36	, Bn3
	.byte	W36
	.byte		N11	, Cn4
	.byte	W12
	.byte		N23	, Bn3
	.byte	W24
	.byte		N24	, En4
	.byte	W24
	.byte		N48	, Dn4
	.byte	W48
	.byte		N36	, Bn3
	.byte	W48
	.byte		N24	, En3
	.byte	W24
	.byte		N20	, Fs3
	.byte	W24
	.byte		N24	, Gn3
	.byte	W24
	.byte			Cn4
	.byte	W24
	.byte		N44	, Bn3
	.byte	W72
	.byte		N16	, Gn3
	.byte	W12
	.byte		N12	, An3
	.byte	W12
	.byte		N32	, Bn3
	.byte	W36
	.byte		N15	, Cn4
	.byte	W12
	.byte		N28	, Bn3
	.byte	W24
	.byte		N24	, En4
	.byte	W24
	.byte		N42	, Dn4
	.byte	W48
	.byte		N28	, Bn3
	.byte	W48
	.byte		N13	, An3
	.byte	W12
	.byte		N14	, Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte		N13	, Gn3
	.byte	W12
	.byte		N05	, Fs3
	.byte	W12
	.byte		N23	
	.byte	W24
	.byte		N12	, Gn3
	.byte	W12
	.byte		N78	, En3
	.byte	W96
	.byte		N03	, Fs3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N08	, En3
	.byte	W12
	.byte		N10	, Fs3
	.byte	W12
	.byte		N07	, Gn3
	.byte	W24
	.byte		N05	, An3
	.byte	W12
	.byte		N12	, Bn3
	.byte	W12
	.byte		N08	, An3
	.byte	W12
	.byte		N07	, Gn3
	.byte	W12
	.byte		N42	, Bn3
	.byte	W60
	.byte		N03	, Cn4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N05	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte		N12	, An3
	.byte	W12
	.byte		N24	, Dn4
	.byte	W24
	.byte		N12	, Cn4
	.byte	W12
	.byte		N44	, Bn3
	.byte	W72
	.byte		N23	
	.byte	W24
	.byte		N30	, En4
	.byte	W36
	.byte		N14	
	.byte	W12
	.byte		N22	, Fs4
	.byte	W24
	.byte		N24	, En4
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte			Cn4
	.byte	W24
	.byte		N36	, Bn3
	.byte	W48
	.byte		N07	, Cn4
	.byte	W12
	.byte		N07	
	.byte	W12
	.byte		N15	
	.byte	W12
	.byte		N13	, Bn3
	.byte	W12
	.byte		N22	, An3
	.byte	W24
	.byte			Gn3
	.byte	W24
	.byte		N44	, Bn3
	.byte	W72
	.byte		N16	, Gn3
	.byte	W12
	.byte		N11	, Fs3
	.byte	W12
	.byte		N68	, En3
	.byte	W72
	.byte		N15	, Cn4
	.byte	W12
	.byte		N12	, Bn3
	.byte	W12
	.byte		N68	, An3
	.byte	W96
	.byte		N05	, Bn3
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N12	, Fs4
	.byte	W12
	.byte			En4
	.byte	W84
	.byte	GOTO	
		.word	song_0058_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0058_2
song_0058_2:	@ 0x087E546C
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
song_0058_2_2:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W12
	.byte		N08	, Bn4, v127
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte		N08	
	.byte	W12
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		N24	, Bn3
	.byte	W24
	.byte		N05	, Bn4
	.byte	W12
	.byte		N36	, Fs4
	.byte	W36
	.byte	W96
	.byte	W96
	.byte		N04	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N04	, Bn3
	.byte	W12
	.byte		N48	
	.byte	W48
song_0058_2_1:
	.byte		N12	, Fs5, v127
	.byte	W12
	.byte			En5
	.byte	W84
	.byte	PEND
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte			An3
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte		N04	, Fs3
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte		N12	, Gn3
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte			Bn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte		N04	, Gn3
	.byte	W12
	.byte		N30	, En3
	.byte	W36
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		N24	, Gn2
	.byte	W24
	.byte			Cn3
	.byte	W24
	.byte			En3
	.byte	W24
	.byte		N48	, Fs3
	.byte	W48
	.byte			Dn3
	.byte	W48
	.byte			En3
	.byte	W60
	.byte		N12	, Cn3
	.byte	W12
	.byte			En3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte		N24	, Fs3
	.byte	W36
	.byte		N60	, Bn3
	.byte	W60
	.byte	W36
	.byte		N24	, En5
	.byte	W60
	.byte	W36
	.byte		N24	
	.byte	W60
	.byte		N05	, Bn4
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte	PATT	
		.word	song_0058_2_1
	.byte	GOTO	
		.word	song_0058_2_2
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0058_3
song_0058_3:	@ 0x087E5510
	.byte	KEYSH	, 0
	.byte	VOICE	, 6
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
song_0058_3_1:
	.byte		TIE	, Dn3, v127
	.byte		TIE	, Fs3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		EOT	, Dn3
	.byte			Fs3
	.byte		N08	, En3
	.byte		N08	, Gn3
	.byte	W96
	.byte		N92	
	.byte	W96
	.byte		N66	, Fs3
	.byte	W72
	.byte		N22	
	.byte	W24
	.byte		N68	, En3
	.byte	W72
	.byte		N18	
	.byte	W24
	.byte		N48	, Ds3
	.byte	W60
	.byte		N30	
	.byte	W36
	.byte		N48	, En3
	.byte	W60
	.byte		N32	, Gn3
	.byte	W36
	.byte		N30	, Fs3
	.byte	W36
	.byte		N54	, Gn3
	.byte	W60
	.byte		N66	, Fs3
	.byte	W72
	.byte		N17	
	.byte	W24
	.byte		N07	
	.byte	W12
	.byte		N09	, Gn3
	.byte	W84
	.byte		N92	
	.byte	W96
	.byte			Fs3
	.byte	W96
	.byte		N80	, En3
	.byte	W96
	.byte		N66	, Ds3
	.byte	W72
	.byte		N18	
	.byte	W24
	.byte		N90	, Gn3
	.byte	W96
	.byte			Fs3
	.byte	W96
	.byte		N40	, En3
	.byte	W48
	.byte			Ds3
	.byte	W48
	.byte		N64	, En3
	.byte	W72
	.byte		N17	
	.byte	W24
	.byte		N90	, Fs3
	.byte	W96
	.byte		N84	, Gn3
	.byte	W96
	.byte		N68	, En3
	.byte	W72
	.byte		N18	, Gn3
	.byte	W24
	.byte		N54	, Fs3
	.byte	W60
	.byte		N05	
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N66	, En3
	.byte	W72
	.byte		N20	
	.byte	W24
	.byte		N64	, Dn3
	.byte	W72
	.byte		N21	
	.byte	W24
	.byte		N68	, En3
	.byte	W72
	.byte		N19	, Gn3
	.byte	W24
	.byte		N24	, Fs3
	.byte	W36
	.byte		N28	
	.byte	W36
	.byte		N18	
	.byte	W24
	.byte		N17	, Gn3
	.byte	W36
	.byte		N54	
	.byte	W60
	.byte		N20	, En3
	.byte	W36
	.byte		N54	
	.byte	W60
	.byte		N64	, Fs3
	.byte	W72
	.byte		N18	
	.byte	W24
	.byte		N08	
	.byte	W12
	.byte		N12	, Gn3
	.byte	W84
	.byte	GOTO	
		.word	song_0058_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0058_4
song_0058_4:	@ 0x087E55B2
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W24
	.byte	W24
song_0058_4_1:
	.byte		N12	, En1, v127
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte		N06	, Bn1
	.byte	W06
	.byte		N08	, En1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N12	, Bn1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0058_4_1
	.byte	PATT	
		.word	song_0058_4_1
	.byte		N08	, En1, v127
	.byte	W12
	.byte		N10	, Bn1
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte			En1
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
song_0058_4_3:
	.byte		N10	, Dn2, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte	PEND
song_0058_4_4:
	.byte		N10	, Cn2, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte	PEND
	.byte			Bn1
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N22	
	.byte	W24
	.byte		N06	, An1
	.byte	W06
	.byte			Bn1
	.byte	W06
song_0058_4_2:
	.byte		N10	, En2, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte	PEND
	.byte			Dn2
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte			En2
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
song_0058_4_5:
	.byte		N10	, Bn1, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte	PEND
	.byte			En2
	.byte	W12
	.byte			En1
	.byte	W36
	.byte		N01	, En2
	.byte	W12
	.byte		N10	, Bn1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte	PATT	
		.word	song_0058_4_2
	.byte	PATT	
		.word	song_0058_4_3
	.byte	PATT	
		.word	song_0058_4_4
	.byte	PATT	
		.word	song_0058_4_5
	.byte	PATT	
		.word	song_0058_4_2
	.byte	PATT	
		.word	song_0058_4_3
	.byte		N10	, Cn2, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte	PATT	
		.word	song_0058_4_2
	.byte	PATT	
		.word	song_0058_4_5
	.byte	PATT	
		.word	song_0058_4_2
song_0058_4_6:
	.byte		N10	, An1, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0058_4_5
	.byte	PATT	
		.word	song_0058_4_4
	.byte	PATT	
		.word	song_0058_4_5
	.byte	PATT	
		.word	song_0058_4_6
	.byte	PATT	
		.word	song_0058_4_5
	.byte		N10	, En2, v127
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N22	, En1
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte			Bn1
	.byte	W12
	.byte			An1
	.byte	W12
	.byte		N10	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N22	
	.byte	W24
	.byte		N10	
	.byte	W12
	.byte			Cn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte	PATT	
		.word	song_0058_4_5
	.byte		N10	, En1, v127
	.byte	W12
	.byte		N10	
	.byte	W84
	.byte	GOTO	
		.word	song_0058_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0058_5
song_0058_5:	@ 0x087E5719
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
	.byte		N06	, Dn1, v127
	.byte	W18
	.byte		N06	
	.byte	W06
song_0058_5_1:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0058_5_1
	.byte	PATT	
		.word	song_0058_5_1
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte		N21	, Cs2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
song_0058_5_2:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Cn2
	.byte	W12
	.byte			An1
	.byte	W12
	.byte			Fn1
	.byte	W12
	.byte			Cn1
	.byte		N22	, An2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_2
	.byte	PATT	
		.word	song_0058_5_1
	.byte	PATT	
		.word	song_0058_5_1
	.byte	PATT	
		.word	song_0058_5_1
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W18
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte		N23	, An2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte	PATT	
		.word	song_0058_5_1
	.byte	PATT	
		.word	song_0058_5_1
	.byte	PATT	
		.word	song_0058_5_1
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte		N24	, Cs2
	.byte	W24
	.byte		N06	, Cn1
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte		N21	, An2
	.byte	W24
	.byte		N06	, Cn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W24
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W36
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W06
	.byte	GOTO	
		.word	song_0058_5_1
	.byte	FINE

	.align 2
	.global song_0058
song_0058:	@ 0x087E584C
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0058_1		@ track
	.word	song_0058_2		@ track
	.word	song_0058_3		@ track
	.word	song_0058_4		@ track
	.word	song_0058_5		@ track
