	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0004_1
song_0004_1:	@ 0x087D2AF0
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 4
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W06
	.byte	TEMPO	, 72
	.byte	W12
	.byte	W24
song_0004_1_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W24
	.byte		N09	, En3, v127
	.byte	W19
	.byte		N04	
	.byte	W05
	.byte		N48	, Bn3
	.byte	W48
	.byte		N24	, An3
	.byte	W24
	.byte			Gs3
	.byte	W24
	.byte			Fs3
	.byte	W24
	.byte			An3
	.byte	W24
	.byte		N12	, Gs3
	.byte	W24
	.byte		N09	, En3
	.byte	W19
	.byte		N04	
	.byte	W05
	.byte		N48	, Bn3
	.byte	W48
	.byte	W96
	.byte	W96
	.byte		N96	, Dn3
	.byte	W96
	.byte		N84	, Cn3
	.byte	W84
	.byte		N06	, Bn2
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte		N36	, Bn2
	.byte	W36
	.byte		N06	, Cs3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N24	, Fs3
	.byte	W24
	.byte		N12	, An2
	.byte	W12
	.byte			Bn2
	.byte	W12
	.byte		N84	, Cn3
	.byte	W84
	.byte		N06	, Dn3
	.byte	W06
	.byte			En3
	.byte	W06
	.byte		N84	, Fs3
	.byte	W84
	.byte		N06	, En3
	.byte	W06
	.byte			Fs3
	.byte	W06
	.byte		N84	, Gn3
	.byte	W84
	.byte		N06	, Fs3
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N16	, Fs3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N66	, Gn3
	.byte	W72
	.byte		N72	, Dn4
	.byte	W24
	.byte	W48
	.byte		N16	
	.byte	W16
	.byte			Cn4
	.byte	W16
	.byte			As3
	.byte	W16
	.byte		N96	, An3
	.byte	W96
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			As3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Fn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N72	, Gn3
	.byte	W72
	.byte		N24	, Dn4
	.byte	W24
	.byte		N16	, Gn4
	.byte	W16
	.byte			Fn4
	.byte	W16
	.byte			Ds4
	.byte	W16
	.byte		N16	
	.byte	W16
	.byte			Dn4
	.byte	W16
	.byte			Cn4
	.byte	W16
	.byte		N36	, Dn4
	.byte	W36
	.byte		N60	, An3
	.byte	W60
	.byte		N24	
	.byte	W24
	.byte			As3
	.byte	W24
	.byte			Cn4
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0004_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0004_2
song_0004_2:	@ 0x087D2BC3
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte	W12
	.byte	W24
song_0004_2_1:
	.byte		N04	, Bn3, v127
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N08	
	.byte	W60
	.byte		N04	, Dn4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N08	
	.byte	W12
	.byte	PEND
	.byte		N04	, Cs4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N08	
	.byte	W36
	.byte		N04	, An3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N36	
	.byte	W36
	.byte	PATT	
		.word	song_0004_2_1
	.byte		N04	, Cs4, v127
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N08	
	.byte	W36
	.byte		N04	, An3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte		N20	
	.byte	W36
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W48
	.byte		N04	, Dn4
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N12	, En4
	.byte	W96
	.byte	W48
	.byte		N04	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N18	
	.byte	W30
	.byte	W96
	.byte	W48
	.byte		N04	, Bn3
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N18	
	.byte	W30
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0004_2_2:
	.byte		N12	, Dn4, v127
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte	PEND
song_0004_2_3:
	.byte	W12
	.byte		N12	, Dn4, v127
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0004_2_2
	.byte	PATT	
		.word	song_0004_2_3
	.byte	PATT	
		.word	song_0004_2_2
	.byte	PATT	
		.word	song_0004_2_3
	.byte	PATT	
		.word	song_0004_2_2
	.byte	W12
	.byte		N12	, Dn4, v127
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W36
	.byte		N96	, As2
	.byte	W96
	.byte			Cn3
	.byte	W96
	.byte			Dn3
	.byte	W96
	.byte		N24	, Gn2
	.byte	W24
	.byte			An2
	.byte	W24
	.byte			As2
	.byte	W24
	.byte			Gn3
	.byte	W24
	.byte		N96	, As2
	.byte	W96
	.byte			Cn3
	.byte	W96
	.byte			Dn3
	.byte	W96
	.byte	W12
	.byte		N24	, As3
	.byte	W24
	.byte		N06	, An3
	.byte	W06
	.byte			Gn3
	.byte	W06
	.byte		N12	, Fn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			As2
	.byte	W12
	.byte		N96	, Fn2
	.byte	W96
	.byte	W96
song_0004_2_4:
	.byte	W24
	.byte		N08	, Fn2, v127
	.byte	W19
	.byte		N04	
	.byte	W05
	.byte		N48	, Fn3
	.byte	W48
	.byte	PEND
	.byte	PATT	
		.word	song_0004_2_4
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N36	, Cn3, v127
	.byte	W36
	.byte			Fn3
	.byte	W36
	.byte		N24	, Gs3
	.byte	W24
	.byte			Gn3
	.byte	W24
	.byte			Fn3
	.byte	W24
	.byte			Ds3
	.byte	W24
	.byte			Gn3
	.byte	W24
	.byte		TIE	, Fn3
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte	GOTO	
		.word	song_0004_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0004_3
song_0004_3:	@ 0x087D2CC8
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v080
	.byte	PAN	, c_v
	.byte	W06
	.byte	W12
	.byte	W24
song_0004_3_1:
	.byte		N12	, En1, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, En2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, En1
	.byte	W06
	.byte	PEND
song_0004_3_2:
	.byte		N12	, En1, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte	BEND	, c_v-64
	.byte		N12	, En2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N12	, Fn1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0004_3_1
	.byte	PATT	
		.word	song_0004_3_2
song_0004_3_3:
	.byte		N06	, Cn2, v127
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte		N12	, Cn2
	.byte	W60
	.byte		N06	
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte		N12	, Cn2
	.byte	W12
	.byte	PEND
song_0004_3_4:
	.byte		N06	, Dn2, v127
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N12	, Dn2
	.byte	W36
	.byte		N01	, Cn2
	.byte	W12
	.byte		N36	, Dn2
	.byte	W36
	.byte	PEND
	.byte	PATT	
		.word	song_0004_3_3
	.byte	PATT	
		.word	song_0004_3_4
	.byte	PATT	
		.word	song_0004_3_3
	.byte	PATT	
		.word	song_0004_3_4
	.byte	PATT	
		.word	song_0004_3_3
	.byte	PATT	
		.word	song_0004_3_4
	.byte	PATT	
		.word	song_0004_3_1
	.byte	PATT	
		.word	song_0004_3_1
	.byte	PATT	
		.word	song_0004_3_1
	.byte		N06	, En1, v127
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Bn1
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N06	, En1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			En2
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N01	, En1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, En2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N12	, Bn1
	.byte	W12
	.byte		N96	, En1
	.byte	W96
	.byte			Dn1
	.byte	W96
	.byte			Cn2
	.byte	W96
	.byte		N48	, Dn2
	.byte	W48
	.byte			Bn1
	.byte	W48
song_0004_3_5:
	.byte	W24
	.byte		N24	, Cn2, v127
	.byte	W24
	.byte			En2
	.byte	W24
	.byte			Gn2
	.byte	W24
	.byte	PEND
	.byte		N48	, Fs2
	.byte	W48
	.byte			Dn2
	.byte	W48
	.byte	PATT	
		.word	song_0004_3_5
	.byte		N16	, Dn2, v127
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Dn3
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N06	, Dn2
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Bn1
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N12	, Fs1
	.byte	W12
song_0004_3_6:
	.byte		N12	, En1, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, En2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	, En1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, En2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, En1
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0004_3_6
	.byte	PATT	
		.word	song_0004_3_6
song_0004_3_7:
	.byte		N12	, Bn1, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Bn2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	, Bn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Bn2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Bn1
	.byte	W06
	.byte	PEND
	.byte		N12	, An1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, An2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	, An1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, An2
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, An1
	.byte	W06
	.byte	PATT	
		.word	song_0004_3_7
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Cn3
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	, Cn2
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Cn3
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Cn2
	.byte	W06
	.byte		N12	, Dn2
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Dn3
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	, Dn2
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	BEND	, c_v-64
	.byte		N12	, Dn3
	.byte	W06
	.byte	BEND	, c_v
	.byte	W06
	.byte		N01	
	.byte	W06
	.byte		N06	, Dn2
	.byte	W06
song_0004_3_8:
	.byte		N12	, Ds2, v127
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte	PEND
song_0004_3_9:
	.byte	W12
	.byte		N12	, Ds2, v127
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte	PEND
song_0004_3_10:
	.byte		N12	, Dn2, v127
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W24
	.byte	PEND
	.byte	W12
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte	PATT	
		.word	song_0004_3_8
	.byte	PATT	
		.word	song_0004_3_9
	.byte	PATT	
		.word	song_0004_3_10
	.byte	W12
	.byte		N12	, Dn2, v127
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
song_0004_3_11:
	.byte		N12	, Ds2, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
song_0004_3_12:
	.byte		N12	, Fn2, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	, Fn1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
song_0004_3_13:
	.byte		N12	, Gn1, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte		N12	, Fn1
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	, Fn2
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0004_3_11
	.byte	PATT	
		.word	song_0004_3_12
	.byte	PATT	
		.word	song_0004_3_13
	.byte	PATT	
		.word	song_0004_3_13
song_0004_3_15:
	.byte		N12	, Cs2, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0004_3_11
song_0004_3_14:
	.byte		N12	, Fn1, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0004_3_14
	.byte	PATT	
		.word	song_0004_3_15
	.byte	PATT	
		.word	song_0004_3_11
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0004_3_14
	.byte	PATT	
		.word	song_0004_3_15
	.byte	PATT	
		.word	song_0004_3_11
	.byte	PATT	
		.word	song_0004_3_14
	.byte	PATT	
		.word	song_0004_3_14
	.byte	GOTO	
		.word	song_0004_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0004_4
song_0004_4:	@ 0x087D2FEB
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte	W12
	.byte	W24
song_0004_4_8:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N30	, Gn4, v127
	.byte	W36
	.byte		N24	, En4
	.byte	W24
	.byte		N12	, Fs4
	.byte	W12
	.byte		N24	, Gn4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte		N30	, En4
	.byte	W36
	.byte		N24	, Bn4
	.byte	W24
	.byte		N12	, An4
	.byte	W12
	.byte		N24	, Gn4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte		N30	, Gn4
	.byte	W36
	.byte		N24	, En5
	.byte	W24
	.byte		N12	, Fs5
	.byte	W12
	.byte		N24	, Gn5
	.byte	W24
	.byte			Fs5
	.byte	W24
	.byte			En5
	.byte	W24
	.byte			Dn5
	.byte	W24
	.byte			En5
	.byte	W24
	.byte		N30	
	.byte	W36
	.byte		N24	, Bn5
	.byte	W24
	.byte		N12	, An5
	.byte	W12
	.byte		N24	, Gn5
	.byte	W24
	.byte			Fs5
	.byte	W24
	.byte			Gn5
	.byte	W24
	.byte			An5
	.byte	W24
	.byte			Fs5
	.byte	W24
	.byte		TIE	, En5
	.byte	W96
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W06
	.byte		N06	, En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte			An4
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			Ds5
	.byte	W06
	.byte			En5
	.byte	W96
	.byte		N72	, Gn3
	.byte	W72
	.byte		N84	, Bn3
	.byte	W24
song_0004_4_1:
	.byte	W60
	.byte		N12	, En4, v127
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte	PEND
song_0004_4_2:
	.byte		N24	, An4, v127
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte	PEND
song_0004_4_3:
	.byte		N48	, Fs4, v127
	.byte	W48
	.byte			Dn4
	.byte	W48
	.byte	PEND
	.byte		N36	, En4
	.byte	W36
	.byte		N24	, Bn4
	.byte	W24
	.byte		N12	, An4
	.byte	W12
	.byte		N24	, Gn4
	.byte	W24
song_0004_4_4:
	.byte		N48	, Fs4, v127
	.byte	W48
	.byte			An4
	.byte	W48
	.byte	PEND
	.byte		N36	, Gn4
	.byte	W36
	.byte		N24	, Bn4
	.byte	W24
	.byte		N12	, An4
	.byte	W12
	.byte		N24	, Gn4
	.byte	W24
	.byte		N20	, Fs4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte			An4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte		N72	, En4
	.byte	W72
	.byte			Bn4
	.byte	W24
	.byte	PATT	
		.word	song_0004_4_1
	.byte	PATT	
		.word	song_0004_4_2
	.byte	PATT	
		.word	song_0004_4_3
	.byte		N48	, En4, v127
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte	PATT	
		.word	song_0004_4_4
	.byte		N48	, Gn4, v127
	.byte	W48
	.byte		N23	, En4
	.byte	W24
	.byte		N12	, Fs4
	.byte	W12
	.byte			Gn4
	.byte	W12
	.byte		N48	, An4
	.byte	W48
	.byte			Dn5
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0004_4_5:
	.byte		N36	, Dn5, v127
	.byte	W36
	.byte			Cn5
	.byte	W36
	.byte		N24	, Fn5
	.byte	W24
	.byte	PEND
song_0004_4_6:
	.byte		N36	, Dn5, v127
	.byte	W36
	.byte		N24	, Cn5
	.byte	W24
	.byte		N12	, As4
	.byte	W12
	.byte		N24	, Cn5
	.byte	W24
	.byte	PEND
	.byte		TIE	, Dn5
	.byte	W96
	.byte	W48
	.byte		EOT	
	.byte	W48
	.byte	PATT	
		.word	song_0004_4_5
	.byte	PATT	
		.word	song_0004_4_6
	.byte		TIE	, Dn5, v127
	.byte	W96
	.byte	W96
	.byte		EOT	
song_0004_4_7:
	.byte		N36	, Fn4, v127
	.byte	W36
	.byte			Ds4
	.byte	W36
	.byte		N24	, Gs4
	.byte	W24
	.byte	PEND
	.byte		N36	, Fn4
	.byte	W36
	.byte		N24	, Ds4
	.byte	W24
	.byte		N12	, Cs4
	.byte	W12
	.byte		N24	, Ds4
	.byte	W24
	.byte		TIE	, Fn4
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte	PATT	
		.word	song_0004_4_7
	.byte		N36	, Fn4, v127
	.byte	W36
	.byte		N60	, Ds4
	.byte	W60
	.byte		N36	, En4
	.byte	W36
	.byte			Cn4
	.byte	W36
	.byte		N24	, Gn4
	.byte	W24
	.byte			Gs4
	.byte	W24
	.byte		N12	, Gn4
	.byte	W12
	.byte		N28	, Fn4
	.byte	W36
	.byte		N06	
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Gs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte		N36	, Cn5
	.byte	W36
	.byte			Fn5
	.byte	W36
	.byte		N24	, Gs5
	.byte	W24
	.byte			Gn5
	.byte	W24
	.byte			Fn5
	.byte	W24
	.byte			Ds5
	.byte	W24
	.byte			Gn5
	.byte	W24
	.byte		TIE	, Fn5
	.byte	W96
	.byte	W96
	.byte		EOT	
	.byte	GOTO	
		.word	song_0004_4_8
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0004_5
song_0004_5:	@ 0x087D3172
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
	.byte		N03	, Dn1, v127
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N15	, En2
	.byte	W18
	.byte		N06	, Cn1
	.byte	W06
song_0004_5_1:
	.byte		N06	, Cn1, v127
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte	PEND
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte	PATT	
		.word	song_0004_5_1
	.byte		N06	, Cn1, v127
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
song_0004_5_2:
	.byte		N06	, Dn1, v127
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte	PEND
song_0004_5_3:
	.byte		N06	, Dn1, v127
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W36
	.byte	PEND
	.byte	PATT	
		.word	song_0004_5_2
	.byte	PATT	
		.word	song_0004_5_3
	.byte	PATT	
		.word	song_0004_5_2
	.byte	PATT	
		.word	song_0004_5_3
	.byte		N06	, Cn1, v127
	.byte		N06	, Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W24
	.byte		N06	
	.byte		N06	, Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte		N06	, Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W36
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
song_0004_5_5:
	.byte		N06	, Cn1, v127
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W18
	.byte			Cn1
	.byte	W06
	.byte		N06	
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte		N06	
	.byte	W48
	.byte			Cn1
	.byte	W18
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Fn1
	.byte	W06
song_0004_5_4:
	.byte		N06	, Cn1, v127
	.byte	W48
	.byte		N06	
	.byte	W48
	.byte	PEND
	.byte	PATT	
		.word	song_0004_5_4
	.byte	PATT	
		.word	song_0004_5_4
	.byte	PATT	
		.word	song_0004_5_4
	.byte	PATT	
		.word	song_0004_5_4
	.byte	PATT	
		.word	song_0004_5_4
	.byte		N06	, Cn1, v127
	.byte	W48
	.byte		N06	
	.byte	W30
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W24
	.byte		N06	
	.byte	W44
	.byte	W03
	.byte		N01	
	.byte	W01
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_5
song_0004_5_6:
	.byte		N06	, Cn1, v127
	.byte	W84
	.byte		N06	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0004_5_6
	.byte	PATT	
		.word	song_0004_5_6
	.byte	PATT	
		.word	song_0004_5_6
	.byte	PATT	
		.word	song_0004_5_6
	.byte	PATT	
		.word	song_0004_5_6
	.byte	PATT	
		.word	song_0004_5_6
	.byte		N06	, Cn1, v127
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W06
	.byte			Cn2
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte			An1
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			Fn1
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte	PATT	
		.word	song_0004_5_1
	.byte		N06	, Cn2, v127
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte			An1
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte	W06
	.byte		N03	, Fn1
	.byte	W03
	.byte		N03	
	.byte	W03
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Dn1
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	GOTO	
		.word	song_0004_5_1
	.byte	FINE

	.align 2
	.global song_0004
song_0004:	@ 0x087D337C
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0004_1		@ track
	.word	song_0004_2		@ track
	.word	song_0004_3		@ track
	.word	song_0004_4		@ track
	.word	song_0004_5		@ track
