	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0057_1
song_0057_1:	@ 0x087E362C
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 13
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W24
song_0057_1_1:
	.byte	TEMPO	, 65
	.byte	BEND	, c_v-46
	.byte		N04	, Dn4, v112
	.byte	W01
	.byte	BEND	, c_v-48
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-62
	.byte	W01
	.byte		c_v-63
	.byte	W01
	.byte		c_v-64
	.byte	W16
	.byte		N04	, Gn4
	.byte	W08
	.byte	BEND	, c_v-57
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v-2
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N04	
	.byte	W24
	.byte			En4
	.byte	W04
	.byte	BEND	, c_v
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v+10
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+19
	.byte	W02
	.byte		c_v+25
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+40
	.byte	W01
	.byte		c_v+41
	.byte	W02
	.byte		c_v+45
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+47
	.byte	W01
	.byte		c_v+49
	.byte	W01
	.byte		c_v+50
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+54
	.byte	W01
	.byte		c_v+56
	.byte	W02
	.byte		c_v+57
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+63
	.byte	W36
	.byte	W02
	.byte		c_v+58
	.byte	W01
	.byte		c_v+54
	.byte	W01
	.byte		c_v+51
	.byte		N04	, Dn4
	.byte	W01
	.byte	BEND	, c_v+47
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+28
	.byte	W01
	.byte		c_v+23
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v
	.byte	W14
	.byte		N04	, Gn4
	.byte	W24
	.byte	BEND	, c_v-2
	.byte		N04	
	.byte	W01
	.byte	BEND	, c_v-5
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-39
	.byte	W02
	.byte		c_v-41
	.byte	W04
	.byte		c_v-40
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-37
	.byte		N04	, En4
	.byte	W01
	.byte	BEND	, c_v-32
	.byte	W01
	.byte		c_v-31
	.byte	W02
	.byte		c_v-26
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W12
	.byte	W30
	.byte		c_v+1
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v+7
	.byte	W01
	.byte		c_v+12
	.byte	W02
	.byte		c_v+16
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+20
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+28
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+31
	.byte	W02
	.byte		c_v+35
	.byte	W01
	.byte		c_v+37
	.byte		N04	, Dn4
	.byte	W01
	.byte	BEND	, c_v+39
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+46
	.byte	W02
	.byte		c_v+49
	.byte	W02
	.byte		c_v+51
	.byte	W02
	.byte		c_v+53
	.byte	W01
	.byte		c_v+54
	.byte	W02
	.byte		c_v+56
	.byte	W01
	.byte		c_v+58
	.byte	W05
	.byte		c_v+60
	.byte	W05
	.byte		N04	, Gn4
	.byte	W03
	.byte	BEND	, c_v+63
	.byte	W13
	.byte		c_v+60
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+11
	.byte	W01
	.byte		c_v+8
	.byte		N04	
	.byte	W01
	.byte	BEND	, c_v+3
	.byte	W01
	.byte		c_v+1
	.byte	W01
	.byte		c_v
	.byte	W21
	.byte		N04	, En4
	.byte	W19
	.byte	BEND	, c_v-1
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v-5
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v-10
	.byte		N04	, Fs4
	.byte	W02
	.byte	BEND	, c_v-14
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-25
	.byte	W02
	.byte		c_v-27
	.byte	W02
	.byte		c_v-28
	.byte	W02
	.byte		c_v-29
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-38
	.byte	W05
	.byte		c_v-39
	.byte	W02
	.byte		N04	, Gn4
	.byte	W02
	.byte	BEND	, c_v-38
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-35
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-1
	.byte	W01
	.byte		c_v
	.byte	W11
	.byte		N04	, Bn4
	.byte	W20
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+3
	.byte	W02
	.byte		c_v+9
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+28
	.byte	W01
	.byte		c_v+30
	.byte	W02
	.byte		c_v+32
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+39
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+42
	.byte	W02
	.byte		c_v+43
	.byte	W02
	.byte		c_v+45
	.byte	W01
	.byte		c_v+46
	.byte	W03
	.byte		c_v+50
	.byte	W01
	.byte		c_v+51
	.byte		N04	, Dn4
	.byte	W01
	.byte	BEND	, c_v+53
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+58
	.byte	W02
	.byte		c_v+59
	.byte	W02
	.byte		c_v+61
	.byte	W02
	.byte		c_v+63
	.byte	W14
	.byte		N04	, An4
	.byte	W03
	.byte	BEND	, c_v+60
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+25
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+6
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W09
	.byte	W36
	.byte	W03
	.byte		c_v-1
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-24
	.byte		N04	, Dn4
	.byte	W01
	.byte	BEND	, c_v-25
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-28
	.byte	W02
	.byte		c_v-30
	.byte	W01
	.byte		c_v-32
	.byte	W02
	.byte		c_v-34
	.byte	W01
	.byte		c_v-35
	.byte	W01
	.byte		c_v-37
	.byte	W02
	.byte		c_v-39
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-43
	.byte	W02
	.byte		c_v-44
	.byte	W02
	.byte		c_v-43
	.byte	W02
	.byte		c_v-42
	.byte	W01
	.byte		c_v-41
	.byte	W02
	.byte		c_v-39
	.byte		N04	, Gn4
	.byte	W01
	.byte	BEND	, c_v-38
	.byte	W02
	.byte		c_v-35
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-2
	.byte	W15
	.byte		N04	
	.byte	W20
	.byte	BEND	, c_v+6
	.byte	W01
	.byte		c_v+10
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+16
	.byte	W01
	.byte		N04	, En4
	.byte	W01
	.byte	BEND	, c_v+20
	.byte	W01
	.byte		c_v+23
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+33
	.byte	W02
	.byte		c_v+36
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+49
	.byte	W01
	.byte		c_v+50
	.byte	W01
	.byte		c_v+53
	.byte	W03
	.byte		c_v+55
	.byte	W01
	.byte		c_v+56
	.byte	W02
	.byte		c_v+59
	.byte	W02
	.byte		c_v+61
	.byte	W01
	.byte		c_v+63
	.byte	W36
	.byte	W02
	.byte		c_v+1
	.byte	W01
	.byte		c_v
	.byte	W10
	.byte		N04	, Dn4
	.byte	W24
	.byte			Gn4
	.byte	W07
	.byte	BEND	, c_v-3
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-11
	.byte	W02
	.byte		c_v-14
	.byte	W02
	.byte		c_v-15
	.byte	W02
	.byte		c_v-16
	.byte	W02
	.byte		c_v-18
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-26
	.byte		N04	
	.byte	W02
	.byte	BEND	, c_v-28
	.byte	W02
	.byte		c_v-29
	.byte	W09
	.byte		c_v-29
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-18
	.byte	W02
	.byte		c_v-15
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-1
	.byte		N04	, En4
	.byte	W01
	.byte	BEND	, c_v
	.byte	W23
	.byte	W36
	.byte	W03
	.byte		c_v+63
	.byte	W09
	.byte		N04	, Dn4
	.byte	W20
	.byte	BEND	, c_v+58
	.byte	W01
	.byte		c_v+50
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+33
	.byte		N04	, Gn4
	.byte	W01
	.byte	BEND	, c_v+29
	.byte	W01
	.byte		c_v+20
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+11
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W16
	.byte		N04	
	.byte	W24
	.byte			En4
	.byte	W02
	.byte	BEND	, c_v-3
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-17
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-31
	.byte	W02
	.byte		c_v-32
	.byte	W02
	.byte		c_v-34
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-40
	.byte	W04
	.byte		N04	, Fs4
	.byte	W08
	.byte	BEND	, c_v-33
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v
	.byte	W10
	.byte		N04	, Gn4
	.byte	W19
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v+8
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		N04	, Bn4
	.byte	W01
	.byte	BEND	, c_v+20
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+47
	.byte	W01
	.byte		c_v+49
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+52
	.byte	W02
	.byte		c_v+55
	.byte	W01
	.byte		c_v+56
	.byte	W02
	.byte		c_v+61
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte	W13
	.byte		c_v+36
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v
	.byte	W11
	.byte		N04	, An4
	.byte	W24
	.byte			Gn4
	.byte	W03
	.byte	BEND	, c_v-3
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-27
	.byte	W02
	.byte		c_v-29
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-36
	.byte	W02
	.byte		c_v-40
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-49
	.byte	W02
	.byte		c_v-50
	.byte	W01
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W48
	.byte		N04	, Gs4
	.byte	W12
	.byte	BEND	, c_v-1
	.byte		N04	
	.byte	W01
	.byte	BEND	, c_v-6
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-15
	.byte	W03
	.byte		c_v-25
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-35
	.byte	W01
	.byte		c_v-37
	.byte		N04	
	.byte	W03
	.byte	BEND	, c_v-41
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-50
	.byte	W02
	.byte		c_v-52
	.byte	W01
	.byte		c_v-54
	.byte	W02
	.byte		N04	, Bn3
	.byte	W02
	.byte	BEND	, c_v-53
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-2
	.byte	W01
	.byte		c_v
	.byte		N17	, Dn4
	.byte	W18
	.byte		N05	, En4
	.byte	W14
	.byte	BEND	, c_v+2
	.byte	W01
	.byte		c_v+7
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+28
	.byte		N04	, Bn3
	.byte	W01
	.byte	BEND	, c_v+32
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+42
	.byte	W02
	.byte		c_v+49
	.byte	W01
	.byte		c_v+53
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+61
	.byte	W01
	.byte		c_v+63
	.byte	W02
	.byte		N04	, Gs4
	.byte	W12
	.byte		N04	
	.byte	W04
	.byte	BEND	, c_v+62
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+32
	.byte	W03
	.byte		c_v+3
	.byte		N04	
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte		N04	, Bn3
	.byte	W12
	.byte		N18	, Dn4
	.byte	W18
	.byte		N05	, En4
	.byte	W04
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-19
	.byte	W02
	.byte		c_v-27
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-32
	.byte	W03
	.byte		c_v-36
	.byte	W01
	.byte		c_v-37
	.byte	W02
	.byte		c_v-39
	.byte	W01
	.byte		c_v-40
	.byte	W02
	.byte		c_v-42
	.byte	W05
	.byte		c_v-44
	.byte	W02
	.byte		c_v-43
	.byte	W02
	.byte		c_v-41
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N04	, Cs4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Cs4
	.byte	W06
	.byte	BEND	, c_v
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v+10
	.byte	W01
	.byte		c_v+16
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+34
	.byte		N04	, Gn4
	.byte	W03
	.byte	BEND	, c_v+47
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+62
	.byte	W01
	.byte		c_v+63
	.byte	W04
	.byte		N05	, Fs4
	.byte	W06
	.byte			En4
	.byte	W14
	.byte	BEND	, c_v+41
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+1
	.byte	W01
	.byte		c_v
	.byte	W24
	.byte		N04	, Cs4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Cs4
	.byte	W06
	.byte	BEND	, c_v-8
	.byte	W03
	.byte		c_v-16
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-28
	.byte		N04	, Gn4
	.byte	W01
	.byte	BEND	, c_v-30
	.byte	W03
	.byte		c_v-37
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-40
	.byte	W03
	.byte		c_v-43
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-47
	.byte		N05	, Fs4
	.byte	W01
	.byte	BEND	, c_v-49
	.byte	W01
	.byte		c_v-50
	.byte	W04
	.byte		N05	, En4
	.byte	W05
	.byte	BEND	, c_v-48
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-17
	.byte	W01
	.byte		c_v-9
	.byte	W19
	.byte		N04	, Gs4
	.byte	W12
	.byte		N04	
	.byte	W05
	.byte	BEND	, c_v+4
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+42
	.byte		N04	
	.byte	W01
	.byte	BEND	, c_v+46
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+54
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+59
	.byte	W07
	.byte		N04	, Bn3
	.byte	W12
	.byte		N17	, Dn4
	.byte	W06
	.byte	BEND	, c_v+59
	.byte	W01
	.byte		c_v+53
	.byte	W01
	.byte		c_v+49
	.byte	W01
	.byte		c_v+43
	.byte	W02
	.byte		c_v+21
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v+5
	.byte	W03
	.byte		N05	, En4
	.byte	W18
	.byte		N04	, Bn3
	.byte	W12
	.byte			Gs4
	.byte	W09
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-20
	.byte		N04	
	.byte	W01
	.byte	BEND	, c_v-26
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-35
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-61
	.byte	W01
	.byte		c_v-64
	.byte		N04	
	.byte	W12
	.byte			Bn3
	.byte	W06
	.byte	BEND	, c_v-62
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-12
	.byte		N18	, Dn4
	.byte	W01
	.byte	BEND	, c_v-5
	.byte	W01
	.byte		c_v
	.byte	W16
	.byte		N05	, En4
	.byte	W19
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v+10
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+29
	.byte	W03
	.byte		c_v+40
	.byte	W01
	.byte		c_v+47
	.byte	W01
	.byte		c_v+49
	.byte		N04	, An4
	.byte	W01
	.byte	BEND	, c_v+52
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+60
	.byte	W07
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W03
	.byte	BEND	, c_v+57
	.byte	W01
	.byte		c_v+46
	.byte	W04
	.byte		c_v+5
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte			Gs4
	.byte	W04
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-11
	.byte	W02
	.byte		c_v-16
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-27
	.byte		N04	, An4
	.byte	W01
	.byte	BEND	, c_v-29
	.byte	W01
	.byte		c_v-31
	.byte	W03
	.byte		c_v-39
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-54
	.byte		N04	, Bn4
	.byte	W01
	.byte	BEND	, c_v-55
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-61
	.byte	W01
	.byte		c_v-63
	.byte	W01
	.byte		c_v-64
	.byte	W07
	.byte		N44	, Gn4
	.byte	W07
	.byte	BEND	, c_v-63
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-40
	.byte	W03
	.byte		c_v-24
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v
	.byte	W32
	.byte	W01
	.byte		N44	, Fs4
	.byte	W05
	.byte	BEND	, c_v
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v+8
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+44
	.byte	W01
	.byte		c_v+48
	.byte	W03
	.byte		c_v+55
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+62
	.byte	W01
	.byte		c_v+63
	.byte	W21
	.byte		c_v+50
	.byte	W01
	.byte		c_v+40
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+19
	.byte		N92	, En4
	.byte	W01
	.byte	BEND	, c_v+12
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v
	.byte	W44
	.byte	W01
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-17
	.byte	W02
	.byte		c_v-25
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-32
	.byte	W02
	.byte		c_v-43
	.byte	W02
	.byte		c_v-49
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-60
	.byte	W01
	.byte		c_v-63
	.byte	W01
	.byte		c_v-64
	.byte	W18
	.byte		c_v-52
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte	W48
	.byte	W48
	.byte	GOTO	
		.word	song_0057_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0057_2
song_0057_2:	@ 0x087E3C54
	.byte	KEYSH	, 0
	.byte	VOICE	, 3
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W24
song_0057_2_1:
	.byte	W48
	.byte	W36
	.byte		N06	, Cn3, v112
	.byte	W06
	.byte			Dn3
	.byte	W05
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+19
	.byte		N04	, En3
	.byte	W01
	.byte	BEND	, c_v+26
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+57
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+63
	.byte	W04
	.byte		N04	, Fs3
	.byte	W10
	.byte	BEND	, c_v+46
	.byte	W01
	.byte		c_v+39
	.byte	W01
	.byte		c_v+31
	.byte		N04	, Gn3
	.byte	W01
	.byte	BEND	, c_v+25
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v
	.byte	W09
	.byte		N04	, An3
	.byte	W12
	.byte			Bn3
	.byte	W05
	.byte	BEND	, c_v-8
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-43
	.byte	W04
	.byte		c_v-38
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v
	.byte	W64
	.byte		N06	, Cn3
	.byte	W06
	.byte			Dn3
	.byte	W02
	.byte	BEND	, c_v-6
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-28
	.byte		N04	, En3
	.byte	W01
	.byte	BEND	, c_v-31
	.byte	W01
	.byte		c_v-35
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-50
	.byte	W02
	.byte		c_v-49
	.byte	W01
	.byte		c_v-46
	.byte		N04	, Fs3
	.byte	W01
	.byte	BEND	, c_v-40
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-2
	.byte	W01
	.byte		c_v
	.byte	W07
	.byte		N04	, Gn3
	.byte	W12
	.byte			An3
	.byte	W05
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+8
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+23
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+60
	.byte		N04	, Bn3
	.byte	W01
	.byte	BEND	, c_v+63
	.byte	W16
	.byte		c_v+57
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+33
	.byte	W02
	.byte		c_v+20
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W24
	.byte	W96
	.byte	W80
	.byte		c_v+55
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+1
	.byte		N06	, Fs3
	.byte	W01
	.byte	BEND	, c_v
	.byte	W05
	.byte		N06	, Gn3
	.byte	W06
	.byte		N04	, Fs3
	.byte	W12
	.byte			En3
	.byte	W05
	.byte	BEND	, c_v-9
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-53
	.byte		N04	, Dn3
	.byte	W01
	.byte	BEND	, c_v-60
	.byte	W01
	.byte		c_v-64
	.byte	W06
	.byte		c_v-63
	.byte	W01
	.byte		c_v-61
	.byte	W01
	.byte		c_v-56
	.byte	W02
	.byte		c_v-44
	.byte		N04	, Cn3
	.byte	W01
	.byte	BEND	, c_v-27
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v
	.byte	W09
	.byte		N04	, Bn2
	.byte	W48
	.byte	W24
	.byte	W03
	.byte	BEND	, c_v-7
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-60
	.byte	W01
	.byte		c_v-64
	.byte	W01
	.byte		c_v-64
	.byte	W02
	.byte		N06	, Cn3
	.byte	W02
	.byte	BEND	, c_v-64
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		N06	, Dn3
	.byte	W01
	.byte	BEND	, c_v-24
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-1
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N04	, En3
	.byte	W12
	.byte			Fs3
	.byte	W07
	.byte	BEND	, c_v
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+20
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+41
	.byte		N04	, Gn3
	.byte	W01
	.byte	BEND	, c_v+48
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte	W09
	.byte		N04	, An3
	.byte	W03
	.byte	BEND	, c_v+53
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W06
	.byte		N04	, Bn3
	.byte	W78
	.byte	BEND	, c_v+55
	.byte	W02
	.byte		c_v+16
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N06	, Cn3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N04	, En3
	.byte	W12
	.byte	BEND	, c_v-9
	.byte		N04	, Fs3
	.byte	W01
	.byte	BEND	, c_v-16
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-54
	.byte	W02
	.byte		c_v-54
	.byte		N04	, Gn3
	.byte	W01
	.byte	BEND	, c_v-51
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W06
	.byte		N04	, An3
	.byte	W12
	.byte			Bn3
	.byte	W07
	.byte	BEND	, c_v+2
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+63
	.byte	W32
	.byte	W03
	.byte	W96
	.byte	W96
	.byte	W44
	.byte	W02
	.byte		c_v+16
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+39
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v+49
	.byte	W01
	.byte		c_v+63
	.byte	W10
	.byte		N05	, Gs2
	.byte	W04
	.byte	BEND	, c_v+59
	.byte	W01
	.byte		c_v+42
	.byte	W02
	.byte		c_v
	.byte	W05
	.byte		N05	, En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte	BEND	, c_v-7
	.byte		N05	, Bn2
	.byte	W01
	.byte	BEND	, c_v-16
	.byte	W02
	.byte		c_v-42
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-59
	.byte	W01
	.byte		c_v-64
	.byte	W01
	.byte		c_v-64
	.byte	W05
	.byte		N05	, En2
	.byte	W03
	.byte	BEND	, c_v-60
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-23
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-6
	.byte	W01
	.byte		c_v
	.byte	W10
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W03
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+47
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+63
	.byte	W04
	.byte		N05	, Gs2
	.byte	W08
	.byte	BEND	, c_v+61
	.byte	W02
	.byte		c_v+27
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v
	.byte		N05	, En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W04
	.byte	BEND	, c_v-10
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-63
	.byte	W01
	.byte		c_v-64
	.byte		N05	, En2
	.byte	W03
	.byte	BEND	, c_v-64
	.byte	W01
	.byte		c_v-63
	.byte	W01
	.byte		c_v-59
	.byte	W01
	.byte		c_v-52
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-46
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W03
	.byte	BEND	, c_v+8
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+47
	.byte	W01
	.byte		c_v+63
	.byte	W05
	.byte		N05	, Gs2
	.byte	W07
	.byte	BEND	, c_v+60
	.byte	W01
	.byte		c_v+45
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N05	, En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W05
	.byte	BEND	, c_v-4
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-36
	.byte	W03
	.byte		c_v-51
	.byte	W01
	.byte		c_v-55
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v-57
	.byte	W03
	.byte		c_v-56
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-51
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-47
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v
	.byte	W07
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W01
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+20
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+39
	.byte	W01
	.byte		c_v+47
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+61
	.byte	W01
	.byte		c_v+63
	.byte	W04
	.byte		N05	, Gs2
	.byte	W08
	.byte	BEND	, c_v+59
	.byte	W01
	.byte		c_v+53
	.byte	W02
	.byte		c_v+12
	.byte	W01
	.byte		c_v
	.byte		N05	, En2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W03
	.byte	BEND	, c_v-12
	.byte	W01
	.byte		c_v-17
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-64
	.byte	W02
	.byte		N05	, En2
	.byte	W06
	.byte	BEND	, c_v-63
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-57
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-5
	.byte	W01
	.byte		c_v
	.byte	W05
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W01
	.byte	BEND	, c_v+2
	.byte	W01
	.byte		c_v+7
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+61
	.byte	W01
	.byte		c_v+63
	.byte	W03
	.byte		N05	, Gs2
	.byte	W10
	.byte	BEND	, c_v+18
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+4
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v+2
	.byte	W01
	.byte		c_v
	.byte	W04
	.byte		N05	, An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W05
	.byte	BEND	, c_v-23
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-61
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v-63
	.byte	W04
	.byte		c_v-62
	.byte	W01
	.byte		c_v-59
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-57
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v
	.byte	W04
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte	BEND	, c_v+14
	.byte	W01
	.byte		c_v+25
	.byte	W01
	.byte		c_v+36
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		N05	, Gs2
	.byte	W12
	.byte			En2
	.byte	W01
	.byte	BEND	, c_v+51
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N05	, An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W03
	.byte	BEND	, c_v-5
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-28
	.byte	W02
	.byte		c_v-44
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-62
	.byte	W01
	.byte		c_v-64
	.byte		N05	, En2
	.byte	W06
	.byte			An2
	.byte	W04
	.byte	BEND	, c_v-54
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			An2
	.byte	W06
	.byte	BEND	, c_v+6
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+54
	.byte		N05	, Cs3
	.byte	W01
	.byte	BEND	, c_v+58
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte	W09
	.byte		c_v+63
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v+50
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N05	, Dn3
	.byte	W12
	.byte			An2
	.byte	W06
	.byte			En3
	.byte	W03
	.byte	BEND	, c_v-8
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-17
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-28
	.byte	W03
	.byte		c_v-44
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-51
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-54
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-61
	.byte	W01
	.byte		c_v-63
	.byte	W01
	.byte		c_v-64
	.byte	W01
	.byte		N05	, Dn3
	.byte	W04
	.byte	BEND	, c_v-64
	.byte	W01
	.byte		c_v-61
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N05	, An2
	.byte	W06
	.byte			Cs3
	.byte	W12
	.byte			An2
	.byte	W02
	.byte	BEND	, c_v+8
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+23
	.byte	W01
	.byte		c_v+28
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+53
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte		N05	, Cs3
	.byte	W12
	.byte			An2
	.byte	W01
	.byte	BEND	, c_v+51
	.byte	W01
	.byte		c_v+36
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v+5
	.byte		N05	, Dn3
	.byte	W01
	.byte	BEND	, c_v
	.byte	W01
	.byte		c_v
	.byte	W10
	.byte		N05	, An2
	.byte	W06
	.byte			En3
	.byte	W10
	.byte	BEND	, c_v-8
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-38
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-45
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-60
	.byte	W02
	.byte		c_v-64
	.byte		N05	, Dn3
	.byte	W01
	.byte	BEND	, c_v-64
	.byte	W05
	.byte		c_v-63
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-1
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v
	.byte	W05
	.byte		N05	, Cs3
	.byte	W12
	.byte	BEND	, c_v+3
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v+7
	.byte	W01
	.byte		c_v+11
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+20
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		N05	, Gs2
	.byte	W12
	.byte	BEND	, c_v+54
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v+40
	.byte	W01
	.byte		c_v+28
	.byte	W01
	.byte		c_v+10
	.byte	W01
	.byte		c_v+2
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		N05	, An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W04
	.byte	BEND	, c_v-4
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-28
	.byte	W03
	.byte		c_v-47
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v-54
	.byte	W01
	.byte		c_v-64
	.byte	W04
	.byte		N05	, An2
	.byte	W05
	.byte	BEND	, c_v-62
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-10
	.byte	W02
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			En2
	.byte	W01
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+17
	.byte	W03
	.byte		c_v+33
	.byte	W01
	.byte		c_v+39
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+63
	.byte	W02
	.byte		N05	, Gs2
	.byte	W10
	.byte	BEND	, c_v+34
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+15
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v+6
	.byte	W01
	.byte		c_v
	.byte	W04
	.byte		N05	, An2
	.byte	W12
	.byte			En2
	.byte	W06
	.byte			Bn2
	.byte	W11
	.byte	BEND	, c_v-3
	.byte	W01
	.byte		c_v-11
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v-19
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-44
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-45
	.byte	W02
	.byte		c_v-44
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v
	.byte	W04
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte			Fs2
	.byte	W07
	.byte	BEND	, c_v+11
	.byte	W01
	.byte		c_v+23
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+49
	.byte	W02
	.byte		N05	, An2
	.byte	W12
	.byte			Fs2
	.byte	W02
	.byte	BEND	, c_v+43
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v+5
	.byte		N05	, Cs3
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte		N05	, Fs2
	.byte	W06
	.byte			Fs3
	.byte	W08
	.byte	BEND	, c_v-5
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-43
	.byte		N05	, Fs2
	.byte	W01
	.byte	BEND	, c_v-50
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-62
	.byte	W01
	.byte		c_v-64
	.byte	W02
	.byte		N05	, Cs3
	.byte	W02
	.byte	BEND	, c_v-62
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-5
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N05	, Fs2
	.byte	W06
	.byte			An2
	.byte	W12
	.byte		N44	, En3
	.byte	W09
	.byte	BEND	, c_v+5
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+57
	.byte	W01
	.byte		c_v+63
	.byte	W11
	.byte		c_v+55
	.byte	W01
	.byte		c_v+44
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v
	.byte	W19
	.byte		N44	, Dn3
	.byte	W14
	.byte	BEND	, c_v-14
	.byte	W02
	.byte		c_v-43
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-60
	.byte	W01
	.byte		c_v-63
	.byte	W02
	.byte		c_v-64
	.byte	W02
	.byte		c_v-63
	.byte	W01
	.byte		c_v-62
	.byte	W01
	.byte		c_v-60
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-45
	.byte	W03
	.byte		c_v-10
	.byte	W01
	.byte		c_v
	.byte	W16
	.byte		N05	, En2
	.byte	W12
	.byte			Gs2
	.byte	W01
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+26
	.byte	W03
	.byte		c_v+50
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+62
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		N05	, En2
	.byte	W06
	.byte			An2
	.byte	W01
	.byte	BEND	, c_v+44
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+10
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N05	, En2
	.byte	W06
	.byte			Bn2
	.byte	W12
	.byte	BEND	, c_v-9
	.byte		N05	, En2
	.byte	W03
	.byte	BEND	, c_v-32
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-47
	.byte		N05	, An2
	.byte	W01
	.byte	BEND	, c_v-49
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v
	.byte		N05	, En2
	.byte	W06
	.byte			Gs2
	.byte	W12
	.byte		N16	, En2
	.byte	W10
	.byte	BEND	, c_v+12
	.byte	W01
	.byte		c_v+25
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+63
	.byte	W09
	.byte		c_v+61
	.byte	W01
	.byte		c_v+55
	.byte		N68	, Fs2
	.byte	W02
	.byte	BEND	, c_v+18
	.byte	W01
	.byte		c_v+7
	.byte	W01
	.byte		c_v
	.byte	W20
	.byte	W07
	.byte		c_v-2
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-35
	.byte	W02
	.byte		c_v-60
	.byte	W01
	.byte		c_v-63
	.byte	W01
	.byte		c_v-64
	.byte	W05
	.byte		c_v-62
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v
	.byte	W23
	.byte	GOTO	
		.word	song_0057_2_1
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0057_3
song_0057_3:	@ 0x087E4281
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v062
	.byte	PAN	, c_v
	.byte	W24
song_0057_3_1:
	.byte	BEND	, c_v-44
	.byte		N12	, Gn1, v112
	.byte	W01
	.byte	BEND	, c_v-48
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-50
	.byte	W02
	.byte		c_v-47
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N04	, Gn2
	.byte	W23
	.byte	BEND	, c_v+57
	.byte	W01
	.byte		c_v+46
	.byte		N04	, Fs2
	.byte	W01
	.byte	BEND	, c_v+34
	.byte	W01
	.byte		c_v+23
	.byte	W01
	.byte		c_v+1
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N12	, Gn2
	.byte	W06
	.byte	BEND	, c_v-13
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		N04	, Dn2
	.byte	W01
	.byte	BEND	, c_v-51
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v
	.byte	W06
	.byte		N12	, Cn2
	.byte	W11
	.byte	BEND	, c_v+9
	.byte	W01
	.byte		c_v+26
	.byte		N04	, Gn2
	.byte	W01
	.byte	BEND	, c_v+44
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+63
	.byte	W08
	.byte		c_v+31
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W10
	.byte		N04	, Fs2
	.byte	W03
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-17
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-54
	.byte	W03
	.byte		c_v-50
	.byte		N06	, Gn2
	.byte	W01
	.byte	BEND	, c_v-43
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N06	, En2
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte	BEND	, c_v+12
	.byte		N06	, Cn2
	.byte	W01
	.byte	BEND	, c_v+27
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+63
	.byte	W03
	.byte		N12	, Gn1
	.byte	W03
	.byte	BEND	, c_v+60
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v
	.byte	W06
	.byte		N04	, Gn2
	.byte	W07
	.byte	BEND	, c_v-13
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-60
	.byte	W01
	.byte		c_v-63
	.byte	W03
	.byte		c_v-55
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v
	.byte	W03
	.byte		N04	, Fs2
	.byte	W10
	.byte	BEND	, c_v+8
	.byte	W01
	.byte		c_v+20
	.byte	W01
	.byte		c_v+31
	.byte		N12	, Gn2
	.byte	W01
	.byte	BEND	, c_v+45
	.byte	W01
	.byte		c_v+63
	.byte	W06
	.byte		c_v+54
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+1
	.byte		N04	, Dn2
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte		N12	, Cn2
	.byte	W01
	.byte	BEND	, c_v-6
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-37
	.byte		N04	, Gn2
	.byte	W01
	.byte	BEND	, c_v-28
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v
	.byte	W09
	.byte	W05
	.byte		c_v+3
	.byte	W01
	.byte		c_v+16
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+38
	.byte	W02
	.byte		c_v+63
	.byte	W02
	.byte		N04	, An2
	.byte	W06
	.byte	BEND	, c_v+49
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+16
	.byte	W01
	.byte		c_v+4
	.byte	W03
	.byte		N06	, Gn2
	.byte	W06
	.byte			En2
	.byte	W05
	.byte	BEND	, c_v-12
	.byte	W01
	.byte		c_v-24
	.byte		N06	, Dn2
	.byte	W01
	.byte	BEND	, c_v-33
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		N06	, Cn2
	.byte	W03
	.byte	BEND	, c_v-48
	.byte	W02
	.byte		c_v-27
	.byte	W01
	.byte		c_v-8
	.byte		N12	, Gn1
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte		N04	, Gn2
	.byte	W02
	.byte	BEND	, c_v+2
	.byte	W01
	.byte		c_v+16
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+63
	.byte	W07
	.byte		c_v+61
	.byte	W01
	.byte		c_v+45
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v
	.byte	W07
	.byte		N04	, Fs2
	.byte	W12
	.byte	BEND	, c_v-11
	.byte		N12	, Gn2
	.byte	W01
	.byte	BEND	, c_v-28
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-59
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		N04	, Dn2
	.byte	W12
	.byte		N12	, Cn2
	.byte	W03
	.byte	BEND	, c_v+13
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+63
	.byte	W06
	.byte		N04	, Gn2
	.byte	W01
	.byte	BEND	, c_v+60
	.byte	W01
	.byte		c_v+39
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v
	.byte	W16
	.byte		c_v-11
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-49
	.byte		N04	, Fs2
	.byte	W01
	.byte	BEND	, c_v-52
	.byte	W01
	.byte		c_v-59
	.byte	W03
	.byte		c_v-55
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N12	, Gn2
	.byte	W12
	.byte		N04	, Cn2
	.byte	W04
	.byte	BEND	, c_v+5
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+54
	.byte	W01
	.byte		c_v+63
	.byte	W04
	.byte		N12	, Dn2
	.byte	W03
	.byte	BEND	, c_v+63
	.byte	W01
	.byte		c_v+45
	.byte	W01
	.byte		c_v+25
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v
	.byte	W05
	.byte		N04	, Gn2
	.byte	W13
	.byte	BEND	, c_v-9
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-55
	.byte	W03
	.byte		c_v-53
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-22
	.byte		N04	, Fs2
	.byte	W01
	.byte	BEND	, c_v-7
	.byte	W01
	.byte		c_v
	.byte	W10
	.byte		N12	, Gn2
	.byte	W08
	.byte	BEND	, c_v+6
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+57
	.byte	W01
	.byte		c_v+63
	.byte		N04	, Bn1
	.byte	W08
	.byte	BEND	, c_v+62
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		N12	, Dn2
	.byte	W12
	.byte		N04	, En2
	.byte	W04
	.byte	BEND	, c_v-11
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-55
	.byte	W03
	.byte		N04	, Fs2
	.byte	W01
	.byte	BEND	, c_v-49
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-3
	.byte	W01
	.byte		c_v
	.byte	W06
	.byte		N04	, Gn2
	.byte	W12
	.byte		N12	, An2
	.byte	W01
	.byte	BEND	, c_v+17
	.byte	W01
	.byte		c_v+39
	.byte	W01
	.byte		c_v+57
	.byte	W01
	.byte		c_v+63
	.byte	W06
	.byte		c_v+61
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+31
	.byte		N04	, Dn2
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte		N12	, Gn1
	.byte	W08
	.byte	BEND	, c_v-13
	.byte	W02
	.byte		c_v-35
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-58
	.byte		N04	, Gn2
	.byte	W01
	.byte	BEND	, c_v-62
	.byte	W01
	.byte		c_v-64
	.byte	W04
	.byte		c_v-59
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W13
	.byte		N04	, Fs2
	.byte	W02
	.byte	BEND	, c_v+38
	.byte	W01
	.byte		c_v+57
	.byte	W09
	.byte		N12	, Gn2
	.byte	W01
	.byte	BEND	, c_v+57
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N04	, Dn2
	.byte	W10
	.byte	BEND	, c_v-12
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-33
	.byte		N12	, Cn2
	.byte	W01
	.byte	BEND	, c_v-41
	.byte	W01
	.byte		c_v-50
	.byte	W02
	.byte		c_v-49
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v
	.byte	W04
	.byte		N04	, Gn2
	.byte	W11
	.byte	BEND	, c_v+7
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+63
	.byte	W07
	.byte		c_v+56
	.byte	W01
	.byte		c_v+39
	.byte	W01
	.byte		c_v+19
	.byte		N04	, Fs2
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte		N06	, Gn2
	.byte	W06
	.byte	BEND	, c_v-8
	.byte		N06	, En2
	.byte	W01
	.byte	BEND	, c_v-19
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-60
	.byte		N06	, Dn2
	.byte	W01
	.byte	BEND	, c_v-62
	.byte	W03
	.byte		c_v-53
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-30
	.byte		N06	, Cn2
	.byte	W01
	.byte	BEND	, c_v-10
	.byte	W01
	.byte		c_v
	.byte	W04
	.byte		N12	, Gn1
	.byte	W11
	.byte	BEND	, c_v+8
	.byte	W01
	.byte		c_v+24
	.byte		N04	, Gn2
	.byte	W01
	.byte	BEND	, c_v+41
	.byte	W01
	.byte		c_v+63
	.byte	W08
	.byte		c_v+45
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+2
	.byte	W01
	.byte		c_v
	.byte	W11
	.byte		N04	, Fs2
	.byte	W06
	.byte	BEND	, c_v-7
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-61
	.byte	W01
	.byte		N12	, Gn2
	.byte	W01
	.byte	BEND	, c_v-64
	.byte	W02
	.byte		c_v-61
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v
	.byte	W04
	.byte		N04	, Dn2
	.byte	W11
	.byte	BEND	, c_v+14
	.byte	W01
	.byte		c_v+29
	.byte		N12	, Cn2
	.byte	W01
	.byte	BEND	, c_v+47
	.byte	W01
	.byte		c_v+61
	.byte	W01
	.byte		c_v+63
	.byte	W08
	.byte		c_v+23
	.byte	W01
	.byte		c_v+11
	.byte		N04	, Gn2
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte	W02
	.byte		c_v-17
	.byte	W01
	.byte		c_v-30
	.byte	W02
	.byte		c_v-43
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-55
	.byte	W02
	.byte		c_v-51
	.byte	W01
	.byte		c_v-42
	.byte		N04	, An2
	.byte	W01
	.byte	BEND	, c_v-33
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-8
	.byte	W09
	.byte		N06	, Gn2
	.byte	W03
	.byte	BEND	, c_v+8
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+63
	.byte		N06	, En2
	.byte	W06
	.byte			Dn2
	.byte	W04
	.byte	BEND	, c_v+48
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+6
	.byte		N06	, Cn2
	.byte	W01
	.byte	BEND	, c_v
	.byte	W05
	.byte		N12	, Gn1
	.byte	W10
	.byte	BEND	, c_v-14
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-32
	.byte		N04	, Gn2
	.byte	W01
	.byte	BEND	, c_v-39
	.byte	W01
	.byte		c_v-46
	.byte	W02
	.byte		c_v-57
	.byte	W01
	.byte		c_v-64
	.byte	W04
	.byte		c_v-58
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W11
	.byte		N04	, Fs2
	.byte	W03
	.byte	BEND	, c_v+10
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+49
	.byte	W01
	.byte		c_v+63
	.byte	W06
	.byte		N12	, Gn2
	.byte	W03
	.byte	BEND	, c_v+28
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N04	, Dn2
	.byte	W10
	.byte	BEND	, c_v-9
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-34
	.byte		N12	, Cn2
	.byte	W01
	.byte	BEND	, c_v-53
	.byte	W01
	.byte		c_v-61
	.byte	W01
	.byte		c_v-64
	.byte	W05
	.byte		c_v-63
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-45
	.byte	W02
	.byte		c_v-13
	.byte		N04	, Gn2
	.byte	W01
	.byte	BEND	, c_v
	.byte	W18
	.byte		c_v+3
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		N04	, Fs2
	.byte	W08
	.byte	BEND	, c_v+44
	.byte	W02
	.byte		c_v+4
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		N12	, Gn2
	.byte	W12
	.byte		N04	, Cn2
	.byte	W01
	.byte	BEND	, c_v-7
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-64
	.byte	W01
	.byte		c_v-64
	.byte	W05
	.byte		N12	, Dn2
	.byte	W02
	.byte	BEND	, c_v-62
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v
	.byte	W05
	.byte		N04	, Gn2
	.byte	W10
	.byte	BEND	, c_v+4
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+28
	.byte	W01
	.byte		c_v+36
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+63
	.byte	W08
	.byte		c_v+53
	.byte		N04	, Dn2
	.byte	W01
	.byte	BEND	, c_v+34
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v
	.byte	W09
	.byte		N12	, An1
	.byte	W07
	.byte	BEND	, c_v-12
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-55
	.byte		N04	, Dn2
	.byte	W01
	.byte	BEND	, c_v-60
	.byte	W02
	.byte		c_v-64
	.byte	W04
	.byte		c_v-64
	.byte	W01
	.byte		c_v-61
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v-11
	.byte		N12	, Gn1
	.byte	W01
	.byte	BEND	, c_v
	.byte	W11
	.byte		N04	, An1
	.byte	W12
	.byte	BEND	, c_v+6
	.byte		N04	, Bn1
	.byte	W01
	.byte	BEND	, c_v+33
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+63
	.byte	W08
	.byte		N04	, An1
	.byte	W01
	.byte	BEND	, c_v+63
	.byte	W02
	.byte		c_v+27
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N12	, Gn1
	.byte	W07
	.byte	BEND	, c_v-10
	.byte	W03
	.byte		c_v-36
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-50
	.byte		N04	, Fs1
	.byte	W03
	.byte	BEND	, c_v-63
	.byte	W01
	.byte		c_v-64
	.byte	W03
	.byte		c_v-64
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v
	.byte		N04	, En1
	.byte	W48
	.byte	W32
	.byte	W03
	.byte	BEND	, c_v+4
	.byte	W01
	.byte		c_v+16
	.byte		N06	, Dn2
	.byte	W01
	.byte	BEND	, c_v+28
	.byte	W01
	.byte		c_v+49
	.byte	W02
	.byte		c_v+60
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		N05	, En2
	.byte	W06
	.byte		N04	, En1
	.byte	W01
	.byte	BEND	, c_v+56
	.byte	W01
	.byte		c_v+34
	.byte	W02
	.byte		c_v
	.byte	W18
	.byte		c_v-2
	.byte	W01
	.byte		c_v-15
	.byte	W02
	.byte		c_v-39
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-58
	.byte	W03
	.byte		c_v-49
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v
	.byte	W11
	.byte	W04
	.byte		c_v+5
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte	W09
	.byte		c_v+56
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+7
	.byte	W15
	.byte		N06	, Dn2
	.byte	W04
	.byte	BEND	, c_v-12
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-26
	.byte		N05	, En2
	.byte	W01
	.byte	BEND	, c_v-30
	.byte	W01
	.byte		c_v-32
	.byte	W04
	.byte		c_v-25
	.byte		N04	, En1
	.byte	W01
	.byte	BEND	, c_v-16
	.byte	W01
	.byte		c_v-5
	.byte	W44
	.byte	W02
	.byte	W32
	.byte	W01
	.byte		c_v+6
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+29
	.byte		N06	, Dn2
	.byte	W01
	.byte	BEND	, c_v+47
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte	W02
	.byte		N05	, En2
	.byte	W06
	.byte		N04	, En1
	.byte	W03
	.byte	BEND	, c_v+51
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v
	.byte	W42
	.byte	W36
	.byte		N06	, Dn2
	.byte	W03
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-24
	.byte		N05	, En2
	.byte	W02
	.byte	BEND	, c_v-40
	.byte	W01
	.byte		c_v-47
	.byte	W02
	.byte		c_v-46
	.byte	W01
	.byte		c_v-41
	.byte		N04	, En1
	.byte	W01
	.byte	BEND	, c_v-34
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v
	.byte	W44
	.byte	W24
	.byte	W02
	.byte		c_v
	.byte	W01
	.byte		c_v+24
	.byte	W03
	.byte		c_v+52
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+63
	.byte	W04
	.byte		N06	, Dn2
	.byte	W06
	.byte		N05	, En2
	.byte	W04
	.byte	BEND	, c_v+60
	.byte	W01
	.byte		c_v+23
	.byte	W01
	.byte		c_v+4
	.byte		N04	, En1
	.byte	W01
	.byte	BEND	, c_v
	.byte	W44
	.byte	W03
	.byte	W22
	.byte		c_v-2
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-43
	.byte	W02
	.byte		c_v-48
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v
	.byte		N06	, Dn2
	.byte	W06
	.byte		N05	, En2
	.byte	W05
	.byte	BEND	, c_v+3
	.byte	W01
	.byte		c_v+12
	.byte		N04	, An1
	.byte	W01
	.byte	BEND	, c_v+24
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+42
	.byte	W44
	.byte	W01
	.byte	W36
	.byte		N06	, En1
	.byte	W06
	.byte		N05	, Gn1
	.byte	W02
	.byte	BEND	, c_v-1
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-49
	.byte		N04	, An1
	.byte	W02
	.byte	BEND	, c_v-50
	.byte	W04
	.byte		c_v-37
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v
	.byte	W36
	.byte	W02
	.byte	W28
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+44
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+63
	.byte		N06	, Dn2
	.byte	W06
	.byte		N05	, En2
	.byte	W06
	.byte		N04	, En1
	.byte	W01
	.byte	BEND	, c_v+45
	.byte	W01
	.byte		c_v+23
	.byte	W01
	.byte		c_v
	.byte	W44
	.byte	W01
	.byte	W28
	.byte		c_v-32
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-60
	.byte		N06	, Dn2
	.byte	W04
	.byte	BEND	, c_v-33
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v
	.byte		N05	, En2
	.byte	W06
	.byte		N04	, En1
	.byte	W07
	.byte	BEND	, c_v+8
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+49
	.byte	W01
	.byte		c_v+63
	.byte	W36
	.byte	W02
	.byte	W30
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N06	, Dn2
	.byte	W06
	.byte		N05	, En2
	.byte	W06
	.byte		N04	, Fs1
	.byte	W04
	.byte	BEND	, c_v-9
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-59
	.byte	W03
	.byte		c_v-52
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v
	.byte	W30
	.byte	W01
	.byte	W36
	.byte		N06	, An1
	.byte	W05
	.byte	BEND	, c_v+8
	.byte	W01
	.byte		c_v+25
	.byte		N06	, Bn1
	.byte	W01
	.byte	BEND	, c_v+43
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+63
	.byte	W03
	.byte		N44	, Cn2
	.byte	W10
	.byte	BEND	, c_v+43
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v
	.byte	W15
	.byte		c_v-13
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-59
	.byte	W02
	.byte		c_v-56
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v
	.byte	W07
	.byte		N44	, Dn2
	.byte	W08
	.byte	BEND	, c_v+4
	.byte	W01
	.byte		c_v+20
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+63
	.byte	W11
	.byte		c_v+54
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v
	.byte	W15
	.byte		c_v-33
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-49
	.byte	W04
	.byte		N04	, En1
	.byte	W02
	.byte	BEND	, c_v-11
	.byte	W01
	.byte		c_v
	.byte	W14
	.byte		c_v
	.byte	W01
	.byte		c_v+8
	.byte	W30
	.byte	W32
	.byte		c_v+1
	.byte	W01
	.byte		c_v+11
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+41
	.byte		N06	, Dn2
	.byte	W01
	.byte	BEND	, c_v+61
	.byte	W01
	.byte		c_v+63
	.byte	W04
	.byte		N05	, En2
	.byte	W06
	.byte		N08	, En1
	.byte	W05
	.byte	BEND	, c_v+13
	.byte	W01
	.byte		c_v
	.byte	W13
	.byte		c_v-1
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-49
	.byte		N68	, Dn1
	.byte	W01
	.byte	BEND	, c_v-51
	.byte	W01
	.byte		c_v-52
	.byte	W02
	.byte		c_v-48
	.byte	W01
	.byte		c_v-40
	.byte	W03
	.byte		c_v
	.byte	W16
	.byte	W01
	.byte		c_v+7
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+63
	.byte	W15
	.byte		c_v+13
	.byte	W01
	.byte		c_v
	.byte	W14
	.byte		c_v-7
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-38
	.byte	W02
	.byte		c_v-37
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte	GOTO	
		.word	song_0057_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0057_4
song_0057_4:	@ 0x087E4955
	.byte	KEYSH	, 0
	.byte	VOICE	, 125
	.byte	VOL	, v069
	.byte	PAN	, c_v
	.byte	W24
song_0057_4_1:
	.byte		N10	, Cn1, v112
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Ds3
	.byte	W03
	.byte	BEND	, c_v+63
	.byte	W01
	.byte		c_v+61
	.byte	W02
	.byte		c_v+60
	.byte	W02
	.byte		c_v+58
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+53
	.byte	W01
	.byte		c_v+52
	.byte		N01	, Cn3
	.byte	W02
	.byte	BEND	, c_v+51
	.byte	W01
	.byte		c_v+49
	.byte	W02
	.byte		c_v+47
	.byte	W03
	.byte		c_v+46
	.byte	W01
	.byte		c_v+45
	.byte	W01
	.byte		c_v+43
	.byte	W02
	.byte		c_v+41
	.byte	W01
	.byte		c_v+39
	.byte	W02
	.byte		c_v+37
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+33
	.byte	W02
	.byte		c_v+32
	.byte	W02
	.byte		c_v+30
	.byte	W02
	.byte		c_v+28
	.byte	W01
	.byte		c_v+27
	.byte		N01	
	.byte	W01
	.byte	BEND	, c_v+24
	.byte	W01
	.byte		c_v+22
	.byte	W02
	.byte		c_v+20
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v+17
	.byte	W02
	.byte		c_v+14
	.byte	W01
	.byte		c_v+12
	.byte	W02
	.byte		c_v+10
	.byte	W01
	.byte		c_v+7
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+5
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N01	, Cn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Cn3
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v+6
	.byte	W01
	.byte		c_v+7
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+15
	.byte	W02
	.byte		c_v+18
	.byte	W01
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+20
	.byte	W02
	.byte		c_v+21
	.byte	W02
	.byte		c_v+23
	.byte	W03
	.byte		c_v+25
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+28
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+31
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W02
	.byte	BEND	, c_v+32
	.byte	W02
	.byte		c_v+34
	.byte	W02
	.byte		c_v+36
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+40
	.byte	W01
	.byte		c_v+42
	.byte	W02
	.byte		c_v+43
	.byte		N01	, Cn3
	.byte	W03
	.byte	BEND	, c_v+44
	.byte	W05
	.byte		c_v+49
	.byte	W03
	.byte		c_v+52
	.byte	W04
	.byte		c_v+54
	.byte	W01
	.byte		c_v+55
	.byte	W02
	.byte		c_v+56
	.byte	W02
	.byte		c_v+57
	.byte	W02
	.byte		c_v+58
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+62
	.byte		N01	
	.byte	W01
	.byte	BEND	, c_v+63
	.byte	W11
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Cn3
	.byte	W20
	.byte	BEND	, c_v+60
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+54
	.byte	W01
	.byte		c_v+52
	.byte		N01	
	.byte	W01
	.byte	BEND	, c_v+51
	.byte	W01
	.byte		c_v+50
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+45
	.byte	W02
	.byte		c_v+43
	.byte	W02
	.byte		c_v+41
	.byte	W01
	.byte		c_v+40
	.byte	W01
	.byte		c_v+36
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+33
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+30
	.byte	W02
	.byte		c_v+26
	.byte	W02
	.byte		c_v+25
	.byte	W01
	.byte		c_v+23
	.byte	W02
	.byte		c_v+20
	.byte	W01
	.byte		c_v+19
	.byte	W01
	.byte		c_v+17
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+15
	.byte	W02
	.byte		c_v+13
	.byte	W02
	.byte		c_v+11
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+6
	.byte	W01
	.byte		c_v+4
	.byte	W03
	.byte		c_v+3
	.byte	W01
	.byte		c_v+1
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W02
	.byte	BEND	, c_v
	.byte	W10
	.byte		N01	, Cn3
	.byte	W12
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v
	.byte	W01
	.byte		c_v+1
	.byte	W02
	.byte		c_v+3
	.byte	W02
	.byte		c_v+5
	.byte	W02
	.byte		c_v+9
	.byte	W01
	.byte		c_v+10
	.byte	W02
	.byte		c_v+12
	.byte	W01
	.byte		N01	, Cn3
	.byte	W02
	.byte	BEND	, c_v+17
	.byte	W01
	.byte		c_v+18
	.byte	W02
	.byte		c_v+19
	.byte	W02
	.byte		c_v+22
	.byte	W02
	.byte		c_v+23
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+28
	.byte	W02
	.byte		c_v+31
	.byte	W01
	.byte		c_v+32
	.byte	W02
	.byte		c_v+34
	.byte	W02
	.byte		c_v+35
	.byte	W02
	.byte		c_v+38
	.byte	W02
	.byte		c_v+41
	.byte	W01
	.byte		c_v+43
	.byte		N01	
	.byte	W02
	.byte	BEND	, c_v+44
	.byte	W02
	.byte		c_v+45
	.byte	W02
	.byte		c_v+47
	.byte	W01
	.byte		c_v+50
	.byte	W02
	.byte		c_v+51
	.byte	W01
	.byte		c_v+53
	.byte	W02
	.byte		c_v+55
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+56
	.byte	W01
	.byte		c_v+59
	.byte	W03
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte	W06
	.byte		N01	, Cn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Cn3
	.byte	W22
	.byte	BEND	, c_v+59
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+55
	.byte		N01	
	.byte	W01
	.byte	BEND	, c_v+50
	.byte	W01
	.byte		c_v+44
	.byte	W01
	.byte		c_v+40
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+17
	.byte	W02
	.byte		c_v+3
	.byte	W01
	.byte		c_v+1
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Cn3
	.byte	W24
	.byte		N01	
	.byte	W11
	.byte	BEND	, c_v-1
	.byte	W01
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-17
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-20
	.byte	W02
	.byte		c_v-21
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-28
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-30
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-35
	.byte	W03
	.byte		c_v-37
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-54
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v-60
	.byte	W01
	.byte		c_v-62
	.byte	W06
	.byte		c_v-64
	.byte	W01
	.byte		c_v-64
	.byte	W03
	.byte		N01	, Cn3
	.byte	W12
	.byte	W12
	.byte	BEND	, c_v-63
	.byte		N01	
	.byte	W01
	.byte	BEND	, c_v-58
	.byte	W01
	.byte		c_v-56
	.byte	W02
	.byte		c_v-52
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-35
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-32
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v-4
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-1
	.byte	W01
	.byte		c_v
	.byte	W10
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Cn3
	.byte	W24
	.byte		N01	
	.byte	W09
	.byte	BEND	, c_v
	.byte	W01
	.byte		c_v+1
	.byte	W02
	.byte		c_v+3
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+4
	.byte	W03
	.byte		c_v+7
	.byte	W01
	.byte		c_v+8
	.byte	W01
	.byte		c_v+10
	.byte	W01
	.byte		c_v+12
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+16
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+18
	.byte	W01
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+19
	.byte	W01
	.byte		c_v+20
	.byte	W02
	.byte		c_v+25
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+35
	.byte	W02
	.byte		c_v+38
	.byte	W01
	.byte		c_v+40
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v+41
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+44
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+50
	.byte	W03
	.byte		c_v+52
	.byte	W01
	.byte		c_v+54
	.byte	W01
	.byte		c_v+55
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+58
	.byte	W02
	.byte		c_v+60
	.byte	W02
	.byte		c_v+63
	.byte	W19
	.byte		N01	
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W04
	.byte	BEND	, c_v+60
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+31
	.byte	W01
	.byte		c_v+28
	.byte	W02
	.byte		c_v+24
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+20
	.byte	W01
	.byte		c_v+18
	.byte	W02
	.byte		c_v+16
	.byte	W01
	.byte		c_v+14
	.byte	W02
	.byte		c_v+12
	.byte	W01
	.byte		c_v+11
	.byte	W01
	.byte		c_v+6
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v+2
	.byte	W02
	.byte		c_v
	.byte	W09
	.byte		N01	, Cn3
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W04
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v-6
	.byte	W02
	.byte		c_v-7
	.byte	W02
	.byte		c_v-9
	.byte	W02
	.byte		c_v-12
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-14
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-32
	.byte	W02
	.byte		c_v-35
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v-36
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-40
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-58
	.byte		N01	, Cn3
	.byte	W02
	.byte	BEND	, c_v-59
	.byte	W01
	.byte		c_v-61
	.byte	W02
	.byte		c_v-64
	.byte	W01
	.byte		c_v-64
	.byte	W06
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-64
	.byte	W01
	.byte		c_v-62
	.byte	W01
	.byte		c_v-56
	.byte	W02
	.byte		c_v-51
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-37
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-34
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-6
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Cn3
	.byte	W24
	.byte	BEND	, c_v+1
	.byte		N01	
	.byte	W01
	.byte	BEND	, c_v+3
	.byte	W02
	.byte		c_v+9
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+18
	.byte	W02
	.byte		c_v+21
	.byte	W02
	.byte		c_v+23
	.byte	W02
	.byte		c_v+26
	.byte	W01
	.byte		c_v+31
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+33
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+40
	.byte	W01
	.byte		c_v+42
	.byte	W02
	.byte		c_v+43
	.byte	W01
	.byte		c_v+45
	.byte	W01
	.byte		c_v+47
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+52
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+53
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+58
	.byte	W03
	.byte		c_v+59
	.byte	W03
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Cn3
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W06
	.byte	BEND	, c_v+60
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+56
	.byte	W03
	.byte		c_v+50
	.byte	W01
	.byte		c_v+46
	.byte		N01	, Cn3
	.byte	W02
	.byte	BEND	, c_v+44
	.byte	W02
	.byte		c_v+40
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+32
	.byte	W02
	.byte		c_v+30
	.byte	W02
	.byte		c_v+28
	.byte	W01
	.byte		c_v+26
	.byte		N01	, Gs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v+23
	.byte	W02
	.byte		c_v+19
	.byte	W01
	.byte		c_v+16
	.byte	W01
	.byte		c_v+14
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v+2
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		N01	, Cn3
	.byte	W18
	.byte		N05	, Ds3
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte			Cn3
	.byte	W06
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W07
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-3
	.byte	W01
	.byte		c_v-5
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-10
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v-12
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-28
	.byte	W02
	.byte		c_v-32
	.byte	W01
	.byte		c_v-34
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-36
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-50
	.byte	W02
	.byte		c_v-52
	.byte	W02
	.byte		c_v-54
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-55
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-60
	.byte	W01
	.byte		c_v-64
	.byte	W01
	.byte		c_v-64
	.byte	W06
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W23
	.byte	BEND	, c_v-64
	.byte	W01
	.byte		c_v-63
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-61
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-57
	.byte	W01
	.byte		c_v-52
	.byte	W02
	.byte		c_v-48
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-39
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-29
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-28
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v-2
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W07
	.byte	BEND	, c_v
	.byte	W01
	.byte		c_v+1
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v+5
	.byte	W02
	.byte		c_v+13
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+14
	.byte	W01
	.byte		c_v+16
	.byte	W02
	.byte		c_v+18
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+37
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W02
	.byte	BEND	, c_v+41
	.byte	W01
	.byte		c_v+42
	.byte	W02
	.byte		c_v+45
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+46
	.byte	W02
	.byte		c_v+50
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+53
	.byte	W01
	.byte		c_v+55
	.byte	W02
	.byte		c_v+56
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+62
	.byte	W01
	.byte		c_v+63
	.byte	W05
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte			Ds3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W05
	.byte	BEND	, c_v+61
	.byte	W01
	.byte		c_v+60
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+54
	.byte	W01
	.byte		c_v+53
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+50
	.byte	W01
	.byte		c_v+47
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+45
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+29
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+21
	.byte	W02
	.byte		c_v+14
	.byte	W01
	.byte		c_v+13
	.byte	W02
	.byte		c_v+9
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+5
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v+2
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W19
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W06
	.byte	BEND	, c_v-3
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v-6
	.byte	W02
	.byte		c_v-9
	.byte	W02
	.byte		c_v-10
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v-11
	.byte	W02
	.byte		c_v-13
	.byte	W01
	.byte		c_v-14
	.byte	W01
	.byte		c_v-15
	.byte	W02
	.byte		c_v-17
	.byte	W01
	.byte		c_v-21
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-24
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-28
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-33
	.byte	W02
	.byte		c_v-34
	.byte	W02
	.byte		c_v-36
	.byte	W01
	.byte		c_v-37
	.byte	W03
	.byte		c_v-40
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-41
	.byte	W01
	.byte		c_v-42
	.byte	W01
	.byte		c_v-43
	.byte	W02
	.byte		c_v-48
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-56
	.byte	W02
	.byte		c_v-57
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-59
	.byte	W02
	.byte		c_v-60
	.byte	W03
	.byte		c_v-61
	.byte	W01
	.byte		c_v-62
	.byte	W01
	.byte		c_v-64
	.byte	W01
	.byte		c_v-64
	.byte	W15
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W07
	.byte	BEND	, c_v-60
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-52
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-39
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-34
	.byte	W02
	.byte		c_v-26
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-20
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-13
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte		N01	, Ds3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte			Dn3
	.byte	W07
	.byte	BEND	, c_v+2
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v+7
	.byte	W02
	.byte		c_v+11
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W02
	.byte	BEND	, c_v+13
	.byte	W01
	.byte		c_v+14
	.byte	W02
	.byte		c_v+17
	.byte	W02
	.byte		c_v+19
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+25
	.byte	W02
	.byte		c_v+26
	.byte	W02
	.byte		c_v+28
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+37
	.byte	W01
	.byte		c_v+39
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+43
	.byte	W02
	.byte		c_v+49
	.byte	W01
	.byte		c_v+50
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+51
	.byte	W01
	.byte		c_v+52
	.byte	W02
	.byte		c_v+54
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+57
	.byte	W01
	.byte		c_v+59
	.byte	W02
	.byte		c_v+61
	.byte	W02
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W05
	.byte	BEND	, c_v+62
	.byte	W01
	.byte		c_v+58
	.byte	W01
	.byte		c_v+55
	.byte	W02
	.byte		c_v+51
	.byte	W02
	.byte		c_v+49
	.byte	W01
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+46
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+40
	.byte	W02
	.byte		c_v+38
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+25
	.byte	W02
	.byte		c_v+19
	.byte	W01
	.byte		c_v+17
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+16
	.byte	W01
	.byte		c_v+15
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+7
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v+1
	.byte	W01
	.byte		c_v
	.byte	W17
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W05
	.byte	BEND	, c_v-1
	.byte	W01
	.byte		c_v-4
	.byte	W03
	.byte		c_v-8
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-13
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-15
	.byte	W01
	.byte		c_v-16
	.byte	W02
	.byte		c_v-22
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-34
	.byte	W01
	.byte		c_v-36
	.byte	W01
	.byte		c_v-40
	.byte		N01	, Ds3
	.byte	W02
	.byte	BEND	, c_v-43
	.byte	W01
	.byte		c_v-44
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-48
	.byte	W01
	.byte		c_v-49
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-53
	.byte	W02
	.byte		c_v-54
	.byte	W01
	.byte		c_v-56
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-59
	.byte	W02
	.byte		c_v-62
	.byte	W01
	.byte		c_v-63
	.byte	W02
	.byte		c_v-64
	.byte	W06
	.byte		N01	, Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W16
	.byte	BEND	, c_v-63
	.byte	W03
	.byte		c_v-46
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-22
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-16
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v
	.byte	W08
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W04
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+15
	.byte	W02
	.byte		c_v+21
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+31
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v+34
	.byte	W01
	.byte		c_v+35
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+43
	.byte	W01
	.byte		c_v+44
	.byte	W01
	.byte		c_v+46
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+50
	.byte	W01
	.byte		c_v+51
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+58
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W02
	.byte	BEND	, c_v+62
	.byte	W01
	.byte		c_v+63
	.byte	W09
	.byte		N01	, Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W24
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W09
	.byte	BEND	, c_v+62
	.byte	W01
	.byte		c_v+59
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+54
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+50
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte		c_v+45
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+41
	.byte	W01
	.byte		c_v+38
	.byte	W01
	.byte		c_v+33
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+27
	.byte	W01
	.byte		c_v+25
	.byte	W01
	.byte		c_v+22
	.byte	W01
	.byte		c_v+20
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+18
	.byte	W01
	.byte		c_v+13
	.byte	W02
	.byte		c_v+6
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v+1
	.byte	W01
	.byte		c_v
	.byte	W05
	.byte		N01	, Ds3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W03
	.byte	BEND	, c_v-4
	.byte	W01
	.byte		c_v-7
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v-11
	.byte	W02
	.byte		c_v-14
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-19
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-30
	.byte	W01
	.byte		c_v-33
	.byte	W01
	.byte		c_v-34
	.byte	W02
	.byte		c_v-41
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-47
	.byte	W02
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-54
	.byte	W01
	.byte		c_v-55
	.byte	W02
	.byte		c_v-57
	.byte	W02
	.byte		c_v-58
	.byte	W01
	.byte		c_v-59
	.byte	W03
	.byte		c_v-63
	.byte	W01
	.byte		c_v-64
	.byte	W01
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-64
	.byte	W11
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W03
	.byte	BEND	, c_v-60
	.byte	W01
	.byte		c_v-54
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-43
	.byte	W01
	.byte		c_v-41
	.byte	W01
	.byte		c_v-36
	.byte	W02
	.byte		c_v-32
	.byte	W01
	.byte		c_v-30
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-28
	.byte	W01
	.byte		c_v-26
	.byte	W01
	.byte		c_v-23
	.byte	W01
	.byte		c_v-18
	.byte	W01
	.byte		c_v-15
	.byte	W01
	.byte		c_v-12
	.byte	W01
	.byte		c_v-10
	.byte	W01
	.byte		c_v-8
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W24
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W05
	.byte	BEND	, c_v+5
	.byte	W01
	.byte		c_v+7
	.byte	W01
	.byte		c_v+9
	.byte	W01
	.byte		c_v+12
	.byte	W04
	.byte		c_v+17
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+19
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+24
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+32
	.byte	W01
	.byte		c_v+34
	.byte	W03
	.byte		c_v+41
	.byte	W01
	.byte		c_v+42
	.byte	W01
	.byte		c_v+45
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+46
	.byte	W02
	.byte		c_v+49
	.byte	W01
	.byte		c_v+50
	.byte	W01
	.byte		c_v+52
	.byte	W01
	.byte		c_v+53
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+58
	.byte	W02
	.byte		c_v+61
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte		N01	, Ds3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W24
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W06
	.byte	BEND	, c_v+58
	.byte	W01
	.byte		c_v+56
	.byte	W01
	.byte		c_v+54
	.byte	W03
	.byte		c_v+44
	.byte	W01
	.byte		c_v+41
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v+32
	.byte	W01
	.byte		c_v+30
	.byte	W01
	.byte		c_v+26
	.byte	W01
	.byte		c_v+21
	.byte	W01
	.byte		c_v+17
	.byte	W01
	.byte		c_v+13
	.byte	W01
	.byte		c_v+5
	.byte	W01
	.byte		c_v+3
	.byte	W01
	.byte		c_v
	.byte	W01
	.byte		c_v
	.byte	W02
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Ds3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W10
	.byte	BEND	, c_v-2
	.byte	W01
	.byte		c_v-4
	.byte	W01
	.byte		c_v-6
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-8
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-13
	.byte	W03
	.byte		c_v-20
	.byte	W01
	.byte		c_v-22
	.byte	W01
	.byte		c_v-25
	.byte	W01
	.byte		c_v-27
	.byte	W01
	.byte		c_v-28
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W02
	.byte	BEND	, c_v-34
	.byte	W01
	.byte		c_v-38
	.byte	W01
	.byte		c_v-40
	.byte	W02
	.byte		c_v-43
	.byte	W01
	.byte		c_v-45
	.byte	W01
	.byte		c_v-46
	.byte	W01
	.byte		c_v-47
	.byte	W01
	.byte		c_v-50
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-53
	.byte	W01
	.byte		c_v-55
	.byte	W01
	.byte		c_v-56
	.byte	W01
	.byte		c_v-58
	.byte	W01
	.byte		c_v-60
	.byte	W01
	.byte		c_v-62
	.byte	W01
	.byte		c_v-64
	.byte	W01
	.byte		c_v-64
	.byte	W05
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W12
	.byte			Ds3
	.byte	W07
	.byte	BEND	, c_v-63
	.byte	W03
	.byte		c_v-54
	.byte	W01
	.byte		c_v-51
	.byte	W01
	.byte		c_v-47
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v-43
	.byte	W01
	.byte		c_v-37
	.byte	W01
	.byte		c_v-35
	.byte	W01
	.byte		c_v-32
	.byte	W01
	.byte		c_v-31
	.byte	W01
	.byte		c_v-29
	.byte	W01
	.byte		c_v-27
	.byte	W02
	.byte		c_v-20
	.byte	W01
	.byte		c_v-17
	.byte	W01
	.byte		c_v-16
	.byte	W01
	.byte		c_v-14
	.byte		N01	, Dn3
	.byte	W01
	.byte	BEND	, c_v-12
	.byte	W01
	.byte		c_v-11
	.byte	W01
	.byte		c_v-9
	.byte	W01
	.byte		c_v-3
	.byte	W01
	.byte		c_v
	.byte	W07
	.byte		N01	, Gs2
	.byte		N01	, Cn3
	.byte	W24
	.byte			Gs2
	.byte		N01	, Cn3
	.byte	W09
	.byte	BEND	, c_v+1
	.byte	W01
	.byte		c_v+4
	.byte	W01
	.byte		c_v+6
	.byte	W01
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Gs2
	.byte		N01	, Dn3
	.byte	W02
	.byte	BEND	, c_v+12
	.byte	W02
	.byte		c_v+14
	.byte	W01
	.byte		c_v+16
	.byte	W04
	.byte		c_v+20
	.byte	W01
	.byte		c_v+21
	.byte	W02
	.byte		c_v+24
	.byte	W01
	.byte		c_v+25
	.byte	W02
	.byte		c_v+26
	.byte	W04
	.byte		c_v+31
	.byte	W03
	.byte		c_v+32
	.byte	W01
	.byte		c_v+34
	.byte	W01
	.byte		c_v+35
	.byte		N10	, Cn1
	.byte		N10	, Fs2
	.byte		N01	, Ds3
	.byte	W01
	.byte	BEND	, c_v+39
	.byte	W01
	.byte		c_v+41
	.byte	W02
	.byte		c_v+43
	.byte	W04
	.byte		c_v+45
	.byte	W01
	.byte		c_v+48
	.byte	W03
	.byte		c_v+51
	.byte		N01	, Cn3
	.byte	W01
	.byte	BEND	, c_v+52
	.byte	W01
	.byte		c_v+54
	.byte	W01
	.byte		c_v+55
	.byte	W01
	.byte		c_v+58
	.byte	W03
	.byte		c_v+62
	.byte	W01
	.byte		c_v+63
	.byte	W01
	.byte		c_v+63
	.byte	W03
	.byte		N01	, Gs2
	.byte		N01	, Dn3
	.byte	W12
	.byte			Cn3
	.byte	W24
	.byte		N01	
	.byte	W10
	.byte	BEND	, c_v+56
	.byte	W01
	.byte		c_v+48
	.byte	W01
	.byte	GOTO	
		.word	song_0057_4_1
	.byte	FINE

	.align 2
	.global song_0057
song_0057:	@ 0x087E530C
	.byte	4		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0057_1		@ track
	.word	song_0057_2		@ track
	.word	song_0057_3		@ track
	.word	song_0057_4		@ track
