	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0008_1
song_0008_1:	@ 0x087D4678
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
song_0008_1_1:
	.byte	TEMPO	, 66
	.byte	W72
	.byte		N24	, En4, v127
	.byte	W24
	.byte		N90	, Fn4
	.byte	W96
	.byte	W72
	.byte		N24	, Gn4
	.byte	W24
	.byte		N90	, Fn4
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W72
	.byte		N06	, Cn4
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Gn4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N20	
	.byte	W24
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N16	
	.byte	W24
	.byte		N15	, Fn4
	.byte	W24
	.byte		N05	, En4
	.byte	W12
	.byte		N24	, Fn4
	.byte	W36
	.byte		N05	, Gn4
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N17	
	.byte	W24
	.byte		N05	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			An4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte		N19	, Cn5
	.byte	W24
	.byte		N17	, En4
	.byte	W24
	.byte		N05	
	.byte	W12
	.byte		N36	
	.byte	W36
	.byte		N06	, Fn4
	.byte	W12
	.byte		N88	
	.byte	W48
	.byte	W84
	.byte		N03	
	.byte	W12
	.byte		N16	, En4
	.byte	W24
	.byte		N11	, Fn4
	.byte	W12
	.byte		N54	, Dn4
	.byte	W60
	.byte	W96
	.byte		N16	, Bn4
	.byte	W24
	.byte		N04	, En4
	.byte	W12
	.byte		N60	
	.byte	W60
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N15	, Gn4
	.byte	W24
	.byte		N18	, Bn4
	.byte	W24
	.byte		N16	
	.byte	W24
	.byte		N04	, An4
	.byte	W12
	.byte		N84	
	.byte	W60
	.byte	W60
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N04	, Bn4
	.byte	W12
	.byte		N13	, Cn5
	.byte	W24
	.byte		N05	, An4
	.byte	W12
	.byte		N68	
	.byte	W60
	.byte	W24
	.byte		N13	
	.byte	W24
	.byte			Bn4
	.byte	W24
	.byte		N15	, Cn5
	.byte	W24
	.byte		TIE	, Dn5
	.byte	W96
	.byte	W05
	.byte		EOT	
	.byte	W90
	.byte	W01
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W84
	.byte		N44	, An4
	.byte	W12
	.byte	W36
	.byte		N42	, Bn4
	.byte	W48
	.byte			Cn5
	.byte	W12
	.byte	W36
	.byte		N48	, Dn5
	.byte	W60
	.byte		N17	, Cn5
	.byte	W24
	.byte		N12	, Dn5
	.byte	W12
	.byte		N05	, Cn5
	.byte	W12
	.byte		N12	, Dn5
	.byte	W12
	.byte		N06	, Cn5
	.byte	W12
	.byte		N07	, Dn5
	.byte	W12
	.byte		N11	, En5
	.byte	W12
	.byte	W12
	.byte		N06	, Gn4
	.byte	W24
	.byte		N44	
	.byte	W60
	.byte		N16	, Cn5
	.byte	W24
	.byte		N12	, Dn5
	.byte	W12
	.byte		N06	, Cn5
	.byte	W12
	.byte		N11	, Dn5
	.byte	W12
	.byte		N06	, Cn5
	.byte	W12
	.byte		N12	, Dn5
	.byte	W12
	.byte		N13	, En5
	.byte	W12
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N11	, Dn5
	.byte	W12
	.byte		N14	, Cn5
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N11	, As4
	.byte	W12
	.byte		N36	, An4
	.byte	W12
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N11	, Bn4
	.byte	W12
	.byte		N36	, Cn5
	.byte	W36
	.byte		N20	, Gn4
	.byte	W24
	.byte		N23	, Dn5
	.byte	W24
	.byte			Cn5
	.byte	W24
	.byte		N09	, Bn4
	.byte	W12
	.byte		TIE	, Cn5
	.byte	W12
	.byte	W92
	.byte	W03
	.byte		EOT	
	.byte	W01
	.byte	W96
	.byte	W96
	.byte	W12
	.byte		N04	, Gn4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N07	, Dn5
	.byte	W12
	.byte		N08	, Bn4
	.byte	W12
	.byte		N12	, Cn5
	.byte	W12
	.byte	GOTO	
		.word	song_0008_1_1
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0008_2
song_0008_2:	@ 0x087D47B0
	.byte	KEYSH	, 0
	.byte	VOICE	, 1
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
song_0008_2_2:
	.byte		N12	, En3, v127
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte	PEND
song_0008_2_1:
	.byte		N12	, Fn3, v127
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte	PEND
song_0008_2_3:
	.byte		N12	, Gn3, v127
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0008_2_1
	.byte	PATT	
		.word	song_0008_2_2
	.byte	PATT	
		.word	song_0008_2_1
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
song_0008_2_4:
	.byte		N12	, En3, v127
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	, Fn3
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte	PEND
song_0008_2_5:
	.byte		N12	, Gn3, v127
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	, Fn3
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0008_2_4
	.byte	PATT	
		.word	song_0008_2_1
	.byte	PATT	
		.word	song_0008_2_2
	.byte	PATT	
		.word	song_0008_2_1
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_4
	.byte	PATT	
		.word	song_0008_2_5
	.byte	PATT	
		.word	song_0008_2_4
	.byte	PATT	
		.word	song_0008_2_1
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_1
	.byte	PATT	
		.word	song_0008_2_1
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_1
song_0008_2_6:
	.byte		N12	, Gn3, v127
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N36	, Fn3
	.byte	W12
	.byte	PEND
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N36	, Gn3
	.byte	W36
	.byte		N01	
	.byte	W12
	.byte		N36	, An3
	.byte	W12
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N24	, Fn3
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_3
	.byte	PATT	
		.word	song_0008_2_1
	.byte	PATT	
		.word	song_0008_2_6
	.byte	W24
	.byte		N01	, Fn3, v127
	.byte	W12
	.byte		N36	, Gn3
	.byte	W36
	.byte		N01	
	.byte	W12
	.byte		N36	, Fn3
	.byte	W12
	.byte	W24
	.byte		N01	
	.byte	W12
	.byte		N36	, En3
	.byte	W36
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N16	
	.byte	W96
	.byte	GOTO	
		.word	song_0008_2_2
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0008_3
song_0008_3:	@ 0x087D491C
	.byte	KEYSH	, 0
	.byte	VOICE	, 22
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
song_0008_3_1:
	.byte		N12	, Cn2, v127
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			Gn3
	.byte	W12
	.byte			Cn4
	.byte	W60
	.byte	PEND
song_0008_3_2:
	.byte		N12	, Cn2, v127
	.byte	W24
	.byte			Fn3
	.byte	W12
	.byte			Cn2
	.byte	W24
	.byte			Fn3
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0008_3_1
	.byte	PATT	
		.word	song_0008_3_2
	.byte	PATT	
		.word	song_0008_3_1
	.byte	PATT	
		.word	song_0008_3_2
	.byte	PATT	
		.word	song_0008_3_1
	.byte		N12	, En2, v127
	.byte	W24
	.byte			Dn3
	.byte	W12
	.byte			An1
	.byte	W24
	.byte			En3
	.byte	W12
	.byte		N10	, An2
	.byte	W12
	.byte		N12	, An1
	.byte	W12
song_0008_3_3:
	.byte		N12	, Dn2, v127
	.byte	W12
	.byte			Dn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Dn4
	.byte	W60
	.byte	PEND
song_0008_3_4:
	.byte		N12	, Dn2, v127
	.byte	W24
	.byte			Dn3
	.byte	W12
	.byte			Dn2
	.byte	W24
	.byte			Dn3
	.byte	W12
	.byte		N24	, Dn2
	.byte	W24
	.byte	PEND
song_0008_3_5:
	.byte		N12	, Gn1, v127
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Cn4
	.byte	W60
	.byte	PEND
	.byte			Gn1
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Cn4
	.byte	W36
	.byte		N08	, Gn3
	.byte	W12
	.byte		N12	, Gn1
	.byte	W12
	.byte	PATT	
		.word	song_0008_3_1
	.byte	PATT	
		.word	song_0008_3_2
	.byte	PATT	
		.word	song_0008_3_1
	.byte		N12	, En2, v127
	.byte	W24
	.byte			Dn3
	.byte	W12
	.byte			An1
	.byte	W24
	.byte			En3
	.byte	W12
	.byte		N09	, An2
	.byte	W12
	.byte		N12	, An1
	.byte	W12
	.byte	PATT	
		.word	song_0008_3_3
	.byte	PATT	
		.word	song_0008_3_4
	.byte	PATT	
		.word	song_0008_3_5
	.byte		N12	, Gn1, v127
	.byte	W12
	.byte			Cn3
	.byte	W12
	.byte			An3
	.byte	W12
	.byte			Cn4
	.byte	W36
	.byte		N09	, Gn3
	.byte	W12
	.byte		N12	, Gn1
	.byte	W12
song_0008_3_6:
	.byte		N12	, En2, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
	.byte	PATT	
		.word	song_0008_3_6
song_0008_3_7:
	.byte		N12	, An1, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
	.byte	PATT	
		.word	song_0008_3_7
song_0008_3_8:
	.byte		N12	, Dn2, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
	.byte	PATT	
		.word	song_0008_3_8
	.byte		N12	, Gs1, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte			Gn1
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N12	
	.byte	W12
song_0008_3_9:
	.byte		N12	, Cn2, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
song_0008_3_10:
	.byte		N12	, En2, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte			En1
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0008_3_7
song_0008_3_11:
	.byte		N12	, Cn2, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte			En1
	.byte	W12
	.byte	PEND
song_0008_3_12:
	.byte		N12	, Fn1, v127
	.byte	W36
	.byte		N12	
	.byte	W60
	.byte	PEND
	.byte			En1
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N24	, Dn2
	.byte	W12
	.byte	W12
	.byte		N12	, An1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte		N24	, En2
	.byte	W24
	.byte		N12	, Bn1
	.byte	W12
	.byte			En1
	.byte	W12
	.byte		N24	, Fn1
	.byte	W12
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte		N24	, Gn1
	.byte	W24
	.byte		N12	, Dn2
	.byte	W12
	.byte			Gn2
	.byte	W12
	.byte			Gn1
	.byte	W12
	.byte	PATT	
		.word	song_0008_3_9
	.byte	PATT	
		.word	song_0008_3_10
	.byte	PATT	
		.word	song_0008_3_7
	.byte	PATT	
		.word	song_0008_3_11
	.byte	PATT	
		.word	song_0008_3_12
	.byte		N12	, En1, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N24	, Fn1
	.byte	W12
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte			Fn2
	.byte	W12
	.byte		N24	, En2
	.byte	W24
	.byte		N12	, Cn2
	.byte	W12
	.byte			En2
	.byte	W12
	.byte		N24	, Dn2
	.byte	W12
	.byte	W12
	.byte		N12	, An1
	.byte	W12
	.byte			Dn2
	.byte	W12
	.byte		N24	, Cn2
	.byte	W24
	.byte		N12	, Gn1
	.byte	W12
	.byte		N01	
	.byte	W12
	.byte		N12	, Cn2
	.byte	W12
	.byte			As1
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte		N24	, Gn1
	.byte	W96
	.byte	GOTO	
		.word	song_0008_3_1
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0008_4
song_0008_4:	@ 0x087D4AA8
	.byte	KEYSH	, 0
	.byte	VOICE	, 4
	.byte	VOL	, v050
	.byte	PAN	, c_v
	.byte	W06
song_0008_4_1:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N05	, Gn4, v127
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N18	
	.byte	W24
	.byte		N05	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N14	
	.byte	W24
	.byte		N15	, Fn4
	.byte	W24
	.byte		N06	, En4
	.byte	W12
	.byte		N28	, Fn4
	.byte	W36
	.byte		N05	, Gn4
	.byte	W12
	.byte		N05	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N17	
	.byte	W24
	.byte		N05	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N14	
	.byte	W12
	.byte		N13	, An4
	.byte	W12
	.byte		N15	, Bn4
	.byte	W12
	.byte		N18	, Cn5
	.byte	W24
	.byte		N15	, En4
	.byte	W24
	.byte		N04	
	.byte	W12
	.byte		N36	
	.byte	W36
	.byte		N05	, Fn4
	.byte	W12
	.byte		TIE	
	.byte	W48
	.byte	W72
	.byte		EOT	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N14	, Gn4
	.byte	W12
	.byte		N12	, Fn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte		N56	, Fn4
	.byte	W60
	.byte	W24
	.byte		N10	, En4
	.byte	W24
	.byte		N11	, Cn4
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W12
	.byte		N05	, Gn4
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N04	
	.byte	W12
	.byte		N05	, An4
	.byte	W12
	.byte		N06	, Bn4
	.byte	W12
	.byte		N05	, Cn5
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte		N15	, Cn5
	.byte	W24
	.byte		N14	, Dn5
	.byte	W12
	.byte		N05	, Cn5
	.byte	W12
	.byte		N11	, Dn5
	.byte	W12
	.byte		N08	, Cn5
	.byte	W12
	.byte		N06	, Dn5
	.byte	W12
	.byte		N12	, En5
	.byte	W12
	.byte	W12
	.byte		N07	, Gn4
	.byte	W24
	.byte		N44	
	.byte	W60
	.byte		N14	, Cn5
	.byte	W24
	.byte		N13	, Dn5
	.byte	W12
	.byte		N11	, Cn5
	.byte	W12
	.byte		N15	, Dn5
	.byte	W12
	.byte		N14	, Cn5
	.byte	W12
	.byte		N08	, Dn5
	.byte	W12
	.byte		N15	, En5
	.byte	W12
	.byte	W12
	.byte		N15	
	.byte	W12
	.byte		N14	, Dn5
	.byte	W12
	.byte		N16	, Cn5
	.byte	W24
	.byte		N15	
	.byte	W12
	.byte		N12	, As4
	.byte	W12
	.byte		N42	, An4
	.byte	W12
	.byte	W36
	.byte		N13	
	.byte	W12
	.byte		N14	, Bn4
	.byte	W12
	.byte		N36	, Cn5
	.byte	W36
	.byte		N20	, Bn4
	.byte	W24
	.byte		N21	, Cn5
	.byte	W24
	.byte		N20	, Bn4
	.byte	W24
	.byte		N09	, Gn4
	.byte	W12
	.byte		N44	, Fn4
	.byte	W12
	.byte	W36
	.byte		N42	, Gn4
	.byte	W48
	.byte			An4
	.byte	W12
	.byte	W36
	.byte		N36	
	.byte	W36
	.byte		N24	, Fn4
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W84
	.byte			An3
	.byte	W12
	.byte	W12
	.byte		N12	, Bn3
	.byte	W12
	.byte		N06	, Cn4
	.byte	W12
	.byte		N24	, Gn3
	.byte	W24
	.byte		N12	, Bn3
	.byte	W12
	.byte		N06	, Cn4
	.byte	W12
	.byte		N24	, Fn3
	.byte	W12
	.byte	W12
	.byte		N12	, Bn3
	.byte	W12
	.byte		N06	, Cn4
	.byte	W12
	.byte		N24	, En3
	.byte	W24
	.byte		N12	, Bn3
	.byte	W12
	.byte			Cn4
	.byte	W12
	.byte			En3
	.byte	W12
	.byte		N64	, Dn3
	.byte	W72
	.byte		N06	, Dn4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fn4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte		N07	, Gn4
	.byte	W96
	.byte	GOTO	
		.word	song_0008_4_1
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0008_5
song_0008_5:	@ 0x087D4BD5
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W06
song_0008_5_1:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Cs1
	.byte	W12
	.byte			Cn1
	.byte	W36
	.byte			Cs1
	.byte	W24
	.byte	PEND
song_0008_5_2:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Cs1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			As4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N06	, Cs1
	.byte		N12	, As4
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte	PATT	
		.word	song_0008_5_2
	.byte	PATT	
		.word	song_0008_5_1
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			As4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Cn1
	.byte		N12	, As4
	.byte	W06
	.byte		N06	, Dn1
	.byte	W06
	.byte		N06	
	.byte		N12	, As4
	.byte	W06
	.byte		N06	, An1
	.byte	W06
	.byte			Fn1
	.byte	W12
	.byte			Cn1
	.byte		N18	, An2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte			Ds1
	.byte	W12
	.byte			Dn1
	.byte	W24
song_0008_5_3:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			As4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Ds1
	.byte		N12	, As4
	.byte	W12
	.byte		N06	, Dn1
	.byte		N12	, As4
	.byte	W24
	.byte	PEND
song_0008_5_4:
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte			Ds1
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0008_5_3
	.byte	PATT	
		.word	song_0008_5_4
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W24
	.byte			As4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Ds1
	.byte		N12	, As4
	.byte	W12
	.byte		N06	, Dn1
	.byte	W12
	.byte			Cn1
	.byte		N30	, Cs2
	.byte	W12
	.byte	W24
	.byte		N06	, Dn1
	.byte	W12
	.byte			Cn1
	.byte		N20	, An2
	.byte	W24
	.byte		N06	, Ds1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte		N23	, Cs2
	.byte	W12
	.byte	W12
	.byte		N06	, Cn1
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte		N19	, An2
	.byte	W24
	.byte		N06	, Ds1
	.byte	W12
	.byte			Dn1
	.byte		N12	, As4
	.byte	W12
	.byte		N06	, Dn1
	.byte	W12
	.byte			Cn1
	.byte		N21	, Cs2
	.byte	W24
	.byte		N06	, Dn1
	.byte	W12
	.byte			Cn1
	.byte	W24
	.byte			Ds1
	.byte	W12
	.byte			Dn1
	.byte	W24
	.byte	PATT	
		.word	song_0008_5_3
	.byte	PATT	
		.word	song_0008_5_4
	.byte	PATT	
		.word	song_0008_5_3
	.byte	PATT	
		.word	song_0008_5_4
	.byte		N06	, Cn1, v127
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			As4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte			Ds1
	.byte		N12	, As4
	.byte	W12
	.byte		N06	, Dn1
	.byte		N12	, As4
	.byte	W12
	.byte		N06	, Cn1
	.byte	W12
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W36
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte	W12
	.byte		N06	
	.byte	W12
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W12
	.byte			As4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N06	, Dn1
	.byte		N12	, As4
	.byte	W12
	.byte		N06	, Cn1
	.byte	W12
	.byte		N06	
	.byte	W24
	.byte			Dn1
	.byte	W12
	.byte			Cn1
	.byte	W36
	.byte			Dn1
	.byte	W24
	.byte		N06	
	.byte	W48
	.byte			As4
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte	GOTO	
		.word	song_0008_5_1
	.byte	FINE

	.align 2
	.global song_0008
song_0008:	@ 0x087D4D7C
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0008_1		@ track
	.word	song_0008_2		@ track
	.word	song_0008_3		@ track
	.word	song_0008_4		@ track
	.word	song_0008_5		@ track
