	.include "MPlayDef.s"

	.section .rodata

	@********************** Track  1 **********************@

	.align 2
	.global song_0003_1
song_0003_1:	@ 0x087D2610
	.byte	KEYSH	, 0
	.byte	TEMPO	, 125
	.byte	VOICE	, 3
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0003_1_3:
	.byte	TEMPO	, 72
	.byte	W96
	.byte	W54
	.byte		N04	, Cs4, v112
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			En5
	.byte	W06
	.byte			Gn5
	.byte	W06
	.byte		N16	, Fs5
	.byte	W96
	.byte	W96
	.byte		N04	, Fs4, v092
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			Gn4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			Fs3
	.byte	W06
	.byte			As3
	.byte	W06
	.byte			Cs4
	.byte	W06
	.byte			En4
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte		N16	, Bn4
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N12	, Fs5, v127
	.byte	W36
	.byte		N12	
	.byte	W48
	.byte		N12	
	.byte	W12
	.byte			Bn4
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W48
	.byte		N06	, Fs4, v112
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte			Fs5
	.byte	W24
	.byte	W96
	.byte	W48
	.byte		N04	, Fs4
	.byte	W06
	.byte			As4
	.byte	W06
	.byte			Cs5
	.byte	W06
	.byte			Fn5
	.byte	W06
	.byte			Fs5
	.byte	W24
	.byte	W72
	.byte		N02	, Bn4, v127
	.byte	W04
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W02
song_0003_1_1:
	.byte	W01
	.byte		N02	, Bn4, v080
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W02
	.byte			Cs5
	.byte	W03
	.byte		N08	, Bn4
	.byte	W48
	.byte	PEND
song_0003_1_2:
	.byte	W72
	.byte		N02	, An4, v080
	.byte	W05
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W01
	.byte	PEND
	.byte	W02
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W02
	.byte		N08	, An4
	.byte	W44
	.byte	W03
	.byte	W72
	.byte		N02	, Bn4
	.byte	W04
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			Cs5
	.byte	W02
	.byte	PATT	
		.word	song_0003_1_1
	.byte	PATT	
		.word	song_0003_1_2
	.byte	W02
	.byte		N02	, An4, v080
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W03
	.byte			An4
	.byte	W03
	.byte			Bn4
	.byte	W04
	.byte			An4
	.byte	W04
	.byte			Bn4
	.byte	W02
	.byte			An4
	.byte	W03
	.byte		N08	, Dn5, v127
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0003_1_3
	.byte	FINE

	@********************** Track  2 **********************@

	.global song_0003_2
song_0003_2:	@ 0x087D278A
	.byte	KEYSH	, 0
	.byte	VOICE	, 5
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0003_2_6:
	.byte		N44	, Fs3, v127
	.byte	W48
	.byte			En3
	.byte	W48
	.byte		N92	, Gn3
	.byte	W96
	.byte		N24	, Fs3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0003_2_1:
	.byte	W24
	.byte		N24	, Fs4, v127
	.byte	W24
	.byte			En4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte	PEND
song_0003_2_2:
	.byte		N72	, En4, v127
	.byte	W72
	.byte		N24	, Fs4
	.byte	W24
	.byte	PEND
song_0003_2_3:
	.byte		N48	, An4, v127
	.byte	W48
	.byte		N44	, Gn4
	.byte	W48
	.byte	PEND
	.byte	W24
	.byte		N24	, En4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte			Gn4
	.byte	W24
	.byte		N72	, Cs4
	.byte	W72
	.byte		N24	, Dn4
	.byte	W24
	.byte			En4
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte			Dn4
	.byte	W24
	.byte			En4
	.byte	W24
	.byte		TIE	, Fs4
	.byte	W96
	.byte	W68
	.byte	W03
	.byte		EOT	
	.byte	W24
	.byte	W01
	.byte	PATT	
		.word	song_0003_2_1
	.byte	PATT	
		.word	song_0003_2_2
	.byte	PATT	
		.word	song_0003_2_3
	.byte	W24
	.byte		N22	, En4, v127
	.byte	W24
	.byte			Fs4
	.byte	W24
	.byte			Gn4
	.byte	W24
song_0003_2_4:
	.byte		N68	, Bn4, v127
	.byte	W72
	.byte		N22	, As4
	.byte	W24
	.byte	PEND
song_0003_2_5:
	.byte		N44	, Dn5, v127
	.byte	W48
	.byte			Cs5
	.byte	W48
	.byte	PEND
	.byte	PATT	
		.word	song_0003_2_4
	.byte	PATT	
		.word	song_0003_2_5
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte		N72	, En3, v127
	.byte		TIE	, Gn3
	.byte		TIE	, An3
	.byte	W72
	.byte			Gn2
	.byte	W24
	.byte	W24
	.byte		EOT	, An3
	.byte		N72	, An4
	.byte	W72
	.byte		EOT	, Gn2
	.byte			Gn3
	.byte		N12	, Bn4
	.byte	W12
	.byte		N24	, Bn2
	.byte		N24	, Bn3
	.byte	W84
	.byte	GOTO	
		.word	song_0003_2_6
	.byte	FINE

	@********************** Track  3 **********************@

	.global song_0003_3
song_0003_3:	@ 0x087D283C
	.byte	KEYSH	, 0
	.byte	VOICE	, 19
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0003_3_2:
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0003_3_1:
	.byte	W24
	.byte		N12	, Gn2, v127
	.byte	W24
	.byte			Dn2
	.byte	W24
	.byte			Gn1
	.byte	W24
	.byte	PEND
	.byte			Fs1
	.byte	W96
	.byte	W24
	.byte			Fs2
	.byte	W24
	.byte			Cs2
	.byte	W24
	.byte			Fs1
	.byte	W24
	.byte			Gn1
	.byte	W96
	.byte	PATT	
		.word	song_0003_3_1
	.byte		N12	, An1, v127
	.byte	W96
	.byte	W24
	.byte			An2
	.byte	W24
	.byte			En2
	.byte	W24
	.byte			An1
	.byte	W24
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W48
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	GOTO	
		.word	song_0003_3_2
	.byte	FINE

	@********************** Track  4 **********************@

	.global song_0003_4
song_0003_4:	@ 0x087D2892
	.byte	KEYSH	, 0
	.byte	VOICE	, 0
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0003_4_3:
	.byte		N44	, Bn3, v127
	.byte	W48
	.byte		N44	
	.byte	W48
	.byte		N11	, Cs4
	.byte	W12
	.byte		N22	
	.byte	W24
	.byte		N22	
	.byte	W24
	.byte		N22	
	.byte	W24
	.byte		N11	
	.byte	W12
song_0003_4_1:
	.byte		N03	, Fs3, v127
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte		N03	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0003_4_1
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N72	, Fs4, v127
	.byte	W84
	.byte		N24	, Bn3
	.byte	W12
	.byte	W12
	.byte		N12	, Cs4
	.byte	W12
	.byte			Dn4
	.byte	W12
	.byte			En4
	.byte	W12
	.byte			Fs4
	.byte	W12
	.byte			Bn4
	.byte	W12
	.byte			Cs5
	.byte	W12
	.byte			Dn5
	.byte	W12
	.byte		N24	, En5
	.byte	W24
	.byte			Cs5
	.byte	W24
	.byte			An4
	.byte	W24
	.byte		N12	, Fs4
	.byte	W12
	.byte		N84	, An4
	.byte	W12
	.byte	W96
	.byte		N48	, Fs4
	.byte	W48
	.byte			Bn4
	.byte	W48
	.byte		N24	, Cs5
	.byte	W24
	.byte			Dn5
	.byte	W24
	.byte			En5
	.byte	W24
	.byte			Fs5
	.byte	W24
	.byte		N84	, En5
	.byte	W84
	.byte		TIE	, An5
	.byte	W12
	.byte	W96
	.byte		EOT	
	.byte		N04	, Bn1
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			En2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			En2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Bn1
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			En2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			An2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs2
	.byte	W06
	.byte		N04	
	.byte	W06
song_0003_4_2:
	.byte		N04	, Bn2, v127
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			En3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			En3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Bn2
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			En3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			An3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs3
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0003_4_2
	.byte		N04	, Bn3, v127
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			En4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Bn4
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Dn5
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			Fs5
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte			An5
	.byte	W06
	.byte		N04	
	.byte	W06
	.byte	W96
	.byte	W96
	.byte		N12	, Bn5
	.byte	W12
	.byte		N04	, Bn1
	.byte	W84
	.byte	GOTO	
		.word	song_0003_4_3
	.byte	FINE

	@********************** Track  5 **********************@

	.global song_0003_5
song_0003_5:	@ 0x087D29CA
	.byte	KEYSH	, 0
	.byte	VOICE	, 126
	.byte	VOL	, v075
	.byte	PAN	, c_v
	.byte	W24
song_0003_5_6:
	.byte	W96
	.byte	W84
	.byte		N11	, Cs4, v127
	.byte	W12
	.byte		N12	, Fs3
	.byte	W96
	.byte	W96
	.byte		N11	
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte		N12	, Bn3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
	.byte		N11	, Fs3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte			Cs4
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte		N11	
	.byte	W12
	.byte			Fs3
	.byte	W12
	.byte		N12	, Bn3
	.byte	W96
	.byte	W96
	.byte	W96
	.byte	W96
song_0003_5_1:
	.byte	W24
	.byte		N24	, Fs3, v127
	.byte	W48
	.byte		N24	
	.byte	W24
	.byte	PEND
song_0003_5_2:
	.byte	W24
	.byte		N24	, Fs3, v127
	.byte	W36
	.byte		N12	
	.byte	W12
	.byte		N24	
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song_0003_5_1
	.byte	PATT	
		.word	song_0003_5_2
song_0003_5_3:
	.byte		N06	, Dn1, v080
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte	PEND
song_0003_5_4:
	.byte		N06	, Dn1, v080
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W12
	.byte	PEND
	.byte	PATT	
		.word	song_0003_5_3
	.byte	PATT	
		.word	song_0003_5_4
	.byte	PATT	
		.word	song_0003_5_3
	.byte	PATT	
		.word	song_0003_5_4
	.byte	PATT	
		.word	song_0003_5_3
	.byte	PATT	
		.word	song_0003_5_4
song_0003_5_5:
	.byte		N12	, Bn3, v127
	.byte	W96
	.byte	W36
	.byte		N06	, Fs3
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	PEND
	.byte	PATT	
		.word	song_0003_5_5
	.byte		N12	, Bn3, v127
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W12
	.byte		N06	, Fs3
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte		N12	, Bn3
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte	W96
	.byte	W96
	.byte	W12
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N12	
	.byte	W24
	.byte		N06	
	.byte	W06
	.byte		N06	
	.byte	W06
	.byte	GOTO	
		.word	song_0003_5_6
	.byte	FINE

	.align 2
	.global song_0003
song_0003:	@ 0x087D2AD4
	.byte	5		@ trackCount
	.byte	0		@ blockCount
	.byte	10		@ priority
	.byte	168		@ reverb

	.word	voicegroup000		@ voicegroup/tone

	.word	song_0003_1		@ track
	.word	song_0003_2		@ track
	.word	song_0003_3		@ track
	.word	song_0003_4		@ track
	.word	song_0003_5		@ track
